### ISSUE TITLE
Selecting sibling nodes does not extend selection in visual mode

### ISSUE THREAD

**Issue by lykahb** [helix-editor/helix#3675] opened 2022-09-03 23:10 UTC
### Summary

Alt-n and Alt-p behave the same in the select mode, as in the normal mode. They move selection instead of expanding it.

### Reproduction Steps

I tried this:

1. Open a file with a language supported by tree-sitter. Select a syntax node with Alt-O.
2. Enter select mode with "v".
3. Move selection to siblings with Alt-n, Alt-p.

I expected this to happen:
The selection expands to include the newly selected nodes.

Instead, this happened:
The selection moves to the newly selected node. The node selected before loses the selection. In other words, Alt-n and Alt-p behave the same in the select mode, as in the normal mode.

https://asciinema.org/a/FNyUuzPGy8n9A19esl2ZFQGtR

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Gnome Terminal

### Helix Version

helix 22.08.1 (e917a8e0)

**Comment by the-mikedavis** [comment] 2022-09-03 23:42
Duplicate of https://github.com/helix-editor/helix/issues/1999

**Closed by the-mikedavis** 2022-09-03 23:42 UTC
Labels: C-bug
