### ISSUE TITLE
Highlight matching parenthesis before the cursor

### ISSUE THREAD

**Issue by ArthaTi** [helix-editor/helix#11333] opened 2024-07-26 15:06 UTC
Consider a scenario where I'm closing a number of consecutive parentheses. While typing, it is most handy to have the opening parenthesis highlighted to match the one I have just closed — this way I can easily figure out how many parentheses remain to insert. For example, here, I have just inserted a closing paren that matches the opening paren to `call` on line 8. I would expect it to be highlighted.

![Screenshot-20240726-045925](https://github.com/user-attachments/assets/ab84d17d-15ee-48d2-b3cd-29d7bfd1eea1)

This can be seen in action in other editors, for example, in Vim:

![image](https://github.com/user-attachments/assets/6ec6fad6-40d8-457c-88d4-3d180bdc79bc)

Helix already has a paren-matching feature, but it happens to only highlight parentheses that exactly match the current selection cursor position, and so, is useless in this case. It would be very helpful to include the previous character. Note that Vim uses the previous character only if there is no match on the current position, which I believe is the best behavior.

**Comment by TheZoq2** [comment] 2024-08-08 12:12
I requested a similar feature a while back https://github.com/helix-editor/helix/issues/8547

**Comment by the-mikedavis** [comment] 2024-08-08 17:02
Yeah this is a duplicate of https://github.com/helix-editor/helix/discussions/8548

**Closed by the-mikedavis** 2024-08-08 17:02 UTC
Labels: C-enhancement

**Comment by TheZoq2** [comment] 2024-08-10 10:24
Would it be possible to reconsider this? While I see the point of "semantically this is strange", I don't think it'd cause confusion and now that I'm back on helix I'm still noticing that I have a harder time closing matching braces correctly.

As @jba suggested in #8548 it could even be a config flag for those of us who really like this behaviour

**Comment by jba** [comment] 2024-08-11 21:37
@TheZoq2 I have a commit that does this. I've been running off of my local build for months. I could share it with you if this doesn't go forward.
