### ISSUE TITLE
fuzzy search for autocomplete

### ISSUE THREAD

**Issue by rgasper** [helix-editor/helix#3084] opened 2022-07-15 19:51 UTC
#### Describe your feature request

Adding a fuzzy-find capability to autocomplete would be awesome! It's probably my favorite feature from VSCode that I miss in Helix. In particular, the VSCode autocomplete provides the following types of suggestions that I'm missing:
- will show suggestions where the currently typed stub is in the middle
  - so if I've typed `back`, the autocomplete will suggest options like `my_data_backup`
- will show suggestions where letters in the currently typed stub show up spaced out throughout the suggestion in order
  - so if I've typed `bgvn`, the autocomplete will suggest options like `_big_global_variable_name`
- autocomplete can be configured via settings to be case-insensitive

**Comment by kirawi** [comment] 2022-07-15 21:17
Duplicate of #1015

**Comment by archseer** [comment] 2022-07-16 13:15
Not a duplicate.

**Comment by archseer** [comment] 2022-07-16 13:16
However this should already work out of the box? We fuzzy filter the completion.

**Comment by sudormrfbin** [comment] 2022-07-16 13:36
> * will show suggestions where the currently typed stub is in the middle
>   
>   * so if I've typed `back`, the autocomplete will suggest options like `my_data_backup`

Suggestions in the middle don't seem to work (or they work but randomly in at least rust-analyzer).

> * will show suggestions where letters in the currently typed stub show up spaced out throughout the suggestion in order
>   
>   * so if I've typed `bgvn`, the autocomplete will suggest options like `_big_global_variable_name`

This seems to work with rust-analyzer.

> * autocomplete can be configured via settings to be case-insensitive

Case insensitive autocomplete doesn't work (tested with rust-analyzer and the Dart LSP).

Maybe there's LSP specific settings that have to be modified?

**Comment by sudormrfbin** [comment] 2022-07-16 13:51
So this seems to be due to filtering the completion results and removing completions that don't _start_ with the current word:

https://github.com/helix-editor/helix/blob/fb625697854e3a9d99aa4cfe952f2050b7e82ce0/helix-term/src/commands.rs#L3712-L3722

**Comment by ChrHorn** [comment] 2022-08-01 08:15
After https://github.com/helix-editor/helix/pull/3215 gets merged we could try to simply remove the prefix filerting to get full fuzzy matching. This would also fix https://github.com/helix-editor/helix/issues/1807.

**Closed** 2022-11-17 01:16 UTC
Labels: C-bug, A-helix-term
