### ISSUE TITLE
autocompletion puts the cursor in the wrong place

### ISSUE THREAD

**Issue by eulerdisk** [helix-editor/helix#6232] opened 2023-03-09 14:42 UTC
### Summary

I think the new snippet based autocompletion has problems.
It put the cursor in the wrong place.
It seems to me it puts the cursor at the selection starting point. Is that the desired behavior?

See the asccinema.

### Reproduction Steps

https://asciinema.org/a/RKvDTNf8i22Ufz2MBZlawshzI

### Platform

WSL

### Terminal Emulator

Windows Terminal

### Helix Version

helix 22.12 (39d5fb0e)

**Comment by archseer** [comment] 2023-03-09 14:54
Fix is included in https://github.com/helix-editor/helix/pull/5728 I think

**Comment by eulerdisk** [comment] 2023-03-09 15:02
> Fix is included in #5728 I think

👍

**Comment by pascalkuthe** [comment] 2023-03-09 18:22
This is indeed fixed by #5728, I can't reproduce the problem you mentinoed but I have some local fixes so it might be related to that

**Closed** 2023-03-10 07:54 UTC
Labels: C-bug, A-language-server, A-helix-term

**Comment by eulerdisk** [comment] 2023-03-10 14:38
> This is indeed fixed by #5728, I can't reproduce the problem you mentinoned but I have some local fixes so it might be related to that

Nope. Cursor position is still going places randomly.
It's hard to reproduce though.

**Comment by pascalkuthe** [comment] 2023-03-10 14:44
> > This is indeed fixed by #5728, I can't reproduce the problem you mentinoned but I have some local fixes so it might be related to that
> 
> Nope. Cursor position is still going places randomly. It's hard to reproduce though and it's a different problem than before.

I tried the reproduction case you showed above and it works just fine now. I have spent a lot of time debugging this and I am fairly certain the cursor positioning should be correct now. Did you use the final version of that PR after it was merged (or in other words latest master)? I did a lot of additional work on that PR yesterday so it's possible you got an old version of that PR.

If you have found a different bug please open a new separate bug report.
