### ISSUE TITLE
J - Join lines - ignoring number command (i.e 3J, 6J) and always joins only next line

### ISSUE THREAD

**Issue by Hessesian** [helix-editor/helix#3875] opened 2022-09-17 14:28 UTC
### Summary

As per instructions in hx --tutor, joining multiple lines with command like 3J results in only joining the next line

### Reproduction Steps

 

I tried this:

1. `hx`
2. Enter 3J

I expected this to happen: joins 3 lines

Instead, this happened: joins 1 line

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

22.08.1

**Comment by the-mikedavis** [comment] 2022-09-17 14:43
Duplicate of https://github.com/helix-editor/helix/issues/2679

Are you sure you are running on 22.08.1? This was fixed before the 22.08 release. You may need to remove `~/.config/helix/runtime/tutor.txt` or ~/.config/helix/runtime/tutor` and [re-link your runtime directory](https://github.com/helix-editor/helix/blob/a73e83ef4df18e2b70bf9b409928f5eb2fc26a99/README.md?plain=1#L48-L55) if you built from source.

**Closed by the-mikedavis** 2022-09-17 14:43 UTC
Labels: C-bug
