### ISSUE TITLE
LSP related crash (C#) (OmniSharp)

### ISSUE THREAD

**Issue by ZuixAlias** [helix-editor/helix#2430] opened 2022-05-08 14:28 UTC
### Summary

Crashes at random when using C#'s LSP (Omnisharp). This was the msg :

![crash_msg](https://user-images.githubusercontent.com/96847142/167300293-d7055ed6-68c5-4c99-b6d4-3794795f698b.png)

### Reproduction Steps

I am using `Ctrl + S` to save in edit/ normal mode...once the timing of the crash happened to be same as when using this key bind or a little after (not sure)...
Second time i guess it was without using it...again, not sure (but most probably it's not related to the key bind)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-05-08T19:00:50.682 helix_view::editor [ERROR] Failed to initialize the LSP for `source.csharp` { cannot find binary path }
2022-05-08T19:05:54.313 helix_view::editor [ERROR] Failed to initialize the LSP for `source.csharp` { cannot find binary path }
2022-05-08T19:06:43.981 helix_view::editor [ERROR] Failed to initialize the LSP for `source.csharp` { cannot find binary path }
2022-05-08T19:24:11.209 helix_lsp [ERROR] unhandled LSP notification: o#/msbuildprojectdiagnostics
2022-05-08T19:24:11.212 helix_lsp [ERROR] unhandled LSP notification: o#/projectconfiguration
2022-05-08T19:24:11.212 helix_lsp [ERROR] unhandled LSP notification: o#/projectadded
2022-05-08T19:24:11.213 helix_lsp [ERROR] unhandled LSP notification: o#/projectchanged
2022-05-08T19:24:52.991 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 0, character: 0 }, end: Position { line: 0, character: 3 } }, severity: Some(Error), code: Some(String("CS0116")), code_description: None, source: Some("csharp"), message: "A namespace cannot directly contain members such as fields, methods or statements", related_information: None, tags: Some([]), data: None }
2022-05-08T19:26:19.006 helix_lsp [ERROR] unhandled LSP notification: o#/msbuildprojectdiagnostics
2022-05-08T19:26:19.007 helix_lsp [ERROR] unhandled LSP notification: o#/projectconfiguration
2022-05-08T19:26:19.007 helix_lsp [ERROR] unhandled LSP notification: o#/projectadded
2022-05-08T19:26:19.007 helix_lsp [ERROR] unhandled LSP notification: o#/projectchanged
```

</details>

### Platform

Windows

### Terminal Emulator

Window Terminal 1.12.10983.0

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by sudormrfbin** [comment] 2022-05-09 17:23
An LSP should never be able to crash the editor by sending invalid responses; at best it should show a warning to the user about the malformed response. This would require a larger refactoring of the language server handling code though to be as defensive as possible (some servers do not conform to the protocol and send responses that are subtly invalid) and handle all errors.

**Comment by archseer** [comment] 2022-06-01 00:54
@CptPotato I'm interested in fixing these issues (I have a fix for the first one) but I'd like to understand the underlying cause a bit better. Can you reproduce these crashes with `hx -v` and give me a copy of the log file? I'd recommend testing with a very small file so there's less output for the formatting. 

For jumping to symbols there seems to be an issue with both builtins and jumping out of the current workspace? Can you get me a trace for both?

**Comment by archseer** [comment] 2022-06-02 02:20
Looks like the formatting ranges returned are not sorted / are actually in reverse order. We expect it to be sorted: https://github.com/helix-editor/helix/blob/99e08f50bdfeb24abe6afff8082ee160a7cadb6f/helix-core/src/transaction.rs#L483=

**Comment by archseer** [comment] 2022-06-02 02:20
For the goto symbol, it's returning a really weird URI that looks like it escaped all the slashes `file:///%24metadata%24%5CProject%5CFoo%5CAssembly%5CSystem%5CRuntime%5CSymbol%5CSystem%5CInt32.cs`

**Comment by archseer** [comment] 2022-06-02 05:09
@CptPotato can you test again? I pushed https://github.com/helix-editor/helix/commit/3d91c99c3e64460d292e0393e89d723feefe10aa, https://github.com/helix-editor/helix/commit/6de6a3edbbdb1b9c87051d535e2b55635aa368e7 and https://github.com/helix-editor/helix/commit/378f438fb033561831cd6e0f94845feaf82bbbcb

It should still fail to jump to the symbol, but at least not crash anymore. Formatting should be fixed.

**Comment by pascalkuthe** [comment] 2023-01-30 00:03
It sounds like this issue can be closed. As the bug was resolved by @archseer and now it's just a case of the LS returning an invalid path (for which helix reports a proper error now).

**Closed by pascalkuthe** 2023-01-30 00:03 UTC
Labels: C-bug, A-language-server

**Comment by Multirious** [comment] 2024-01-18 04:24
Can goto symbol be fixed? Currently I've got error `unable to convert URI to filepath: file:///%24metadata%24%5CProject%5Ctest_csharp%5CAssembly%5CGodotSharp%5CSymbol%5CGodot%5CProjectSettings.cs` in Helix while in goto in vscode would point me to a valid file.
