### ISSUE TITLE
[Feature Request] built-in tree-mode file browser

### ISSUE THREAD

**Issue by xialvjun** [helix-editor/helix#1702] opened 2022-02-23 12:44 UTC
#### Describe your feature request

I don't know if this has been implemented but not documented, or it should be a feature request.

At this version (helix@0.6.0), we can open a directory with `hx my-project-dir` and then it will show a flat file list 

![image](https://user-images.githubusercontent.com/4413712/155319729-c1751b3c-40c0-4021-b0b4-3ebd7b4f5715.png)

We can type to search a file, we can navigate the list with up and down( ↑↓ ) and press Enter to select a file to open. 
> Besides, in the image above, the project has a node_modules directory, it doesn't show in it, that's good. But what's the rule? And the file list order is weird.

But after we opened a file, it seems we can never go to the flat file list view anymore. **I hope `:open` with no arguments can go to that view**.

And more, why it's a flat file list? **Why not a tree file list? If it's a tree file list, we can navigate it with ↑↓←→ . No need to explain ↑↓, → is to expand and ← is to collapse.**

**Comment by sudormrfbin** [comment] 2022-02-23 13:56
> But after we opened a file, it seems we can never go to the flat file list view anymore.

`space + f` opens the file picker again (The [keymap docs](https://docs.helix-editor.com/keymap.html) have an overview of all keybindings).

> Besides, in the image above, the project has a node_modules directory, it doesn't show in it, that's good. But what's the rule?

The file picker respects `gitignore`, so any files specified in it is automatically not shown. There's also a [configurable option](https://docs.helix-editor.com/configuration.html#editorfile-picker-section) that sets whether to show hidden directories.

> And the file list order is weird.

Files are sorted by last access time.

> Why not a tree file list?

#200

**Comment by kirawi** [comment] 2022-02-24 01:43
I think this can be closed as a duplicate of #200?

**Closed by kirawi** 2022-02-24 01:43 UTC
Labels: C-enhancement
