### ISSUE TITLE
Support for single line comments for JSX/TSX elements

### ISSUE THREAD

**Issue by idr4n** [helix-editor/helix#6832] opened 2023-04-20 15:11 UTC
This was mainly described in #5453, which was closed based on block comments not being supported. However, I think the main issue is that even for single line comments, JSX elements use a different style of comments.

That is, if I want to comment even one single line in JSX/TSX elements, the comment style should be `{/* ... */}`, and for the rest of the file (simple JS or TS elements) it should be `//` as it is currently implemented.

Thanks in advance!

**Comment by pascalkuthe** [comment] 2023-04-20 16:03
blocks comments are any comments that include text that is not inserted at the start of the line so this was correctly closed as a duplicate of #1505.  JSX and TSX are implemented as injections so this should work automatically as soon as block comment support is available and the comment style is updated in `languages.toml`.

This feature is being implemented in #4718 which @gabydd plans to finish once he has more time afaik.

**Closed by pascalkuthe** 2023-04-20 16:03 UTC
Labels: C-enhancement

**Comment by gabydd** [comment] 2023-04-20 16:17
Yeah I was looking at  https://github.com/helix-editor/helix/pull/1937 recently so I need to reconsider the block comment config to support this as well. I might work on it today actually.
