### ISSUE TITLE
Latest binary release (23.03) does not work on Slackware64-15.0 Linux

### ISSUE THREAD

**Issue by toolonely** [helix-editor/helix#6876] opened 2023-04-25 10:24 UTC
### Summary

Running the AppImage produces the error:

    $ ./helix-23.03-x86_64.AppImage
    /tmp/.mount_helix-jzcV0s/usr/bin/hx: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_helix-jzcV0s/usr/bin/hx)

The same happens when downloading https://github.com/helix-editor/helix/releases/download/23.03/helix-23.03-x86_64-linux.tar.xz and running `hx` from it:

    $ ./hx
    ./hx: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./hx)

Suggestion: for a start, modify https://docs.helix-editor.com/install.html#linux to mention this. Ideally, make it work on Slackware64-15.0, which uses `glibc-2.33`.

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

xfce4-terminal 0.8.10 (Xfce 4.16)

### Helix Version

helix 23.03

**Comment by David-Else** [comment] 2023-04-25 10:33
[glibc compatability](https://github.com/helix-editor/helix/issues/1932)

**Comment by pascalkuthe** [comment] 2023-04-25 13:51
(closing as duplicate of #1932)

**Closed by pascalkuthe** 2023-04-25 13:51 UTC
Labels: C-bug
