### ISSUE TITLE
:quit panic

### ISSUE THREAD

**Issue by robinvd** [helix-editor/helix#278] opened 2021-06-16 08:34 UTC
### Reproduction steps

 

Hard to reproduce, but in using helix i've had it multiple times.

1. run the `:quit` command
2. see the error
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', helix-lsp/src/transport.rs:100:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Environment

- Platform: linux
- Helix version: v0.0.10-66-g9baf1ec

**Comment by archseer** [comment] 2021-06-16 08:45
I'm guessing the LSP terminates early and the receive loop fails. We probably want to send proper shutdown signals to LSPs before exiting. I suspect this is also the cause of #266  (also \cc-ing @batonius for thoughts, they've cleaned up a bunch of other panics in that crate)

A quick fix would be

https://github.com/helix-editor/helix/blob/d1c8a74771b241ee0824853bd5e8229cb0ab4187/helix-lsp/src/transport.rs#L100

and 

https://github.com/helix-editor/helix/blob/d1c8a74771b241ee0824853bd5e8229cb0ab4187/helix-lsp/src/transport.rs#L105

replacing `.unwrap()` with `?` so we don't panic.

(Sidenote: your Helix version seems to be different, it's still on 0.0.10 but contains new commits)

**Comment by archseer** [comment] 2021-06-20 07:41
Can you still reproduce this with #287 merged?

**Comment by robinvd** [comment] 2021-06-20 16:30
Ill test it for a while, and report back.

**Closed** 2021-07-07 13:38 UTC
Labels: A-helix-term, C-bug
