### ISSUE TITLE
Soft wrap can be empty

### ISSUE THREAD

**Issue by vwkd** [helix-editor/helix#6765] opened 2023-04-15 08:20 UTC
### Summary

I'm occassionally experiencing an empty soft wrap. I suspect this happens due to the trailing newline character being treated as a "normal character" that is wrapped when the line width happens to be just right.

Here's a screenshot. Note, there is **_no_** trailing whitespace in the line.

<img width="751" alt="empty-soft-wrap" src="https://user-images.githubusercontent.com/33468089/232199264-53348ff6-0a77-4d44-ba50-27fb7c855f9d.png">

### Reproduction Steps

1. Open helix with soft wrap enabled
2. Fill text until the end of the line
3. If the issue doesn't occur, change the terminal width and/or zoom and repeat from 2.

Note, it needs a bit of fiddling around with terminal width and/or zoom to hit the right line width but it happens often enough for me to hit quickly.

Here's a screen recording. Note, there is **_no_** trailing whitespace in the line, just inserting and deleting "k".

https://user-images.githubusercontent.com/33468089/232199185-6d66dc62-1e76-45ae-8e5a-ef481c0edf44.mov

### Platform

macOS

### Terminal Emulator

iTerm2

### Helix Version

helix 23.03 (3cf03723)

**Comment by pascalkuthe** [comment] 2023-04-15 13:07
This is intentional. The newline character is always selectable in helix. What you are seeing is the newline char being wrapped to the next line. If that wasnt the case the cursor would disappear offscreen when selecting the newline char

**Comment by vwkd** [comment] 2023-04-15 16:39
Makes sense. I must say it's visually confusing to see newline being a character, but I guess it just takes getting used to.

**Comment by vwkd** [comment] 2024-01-03 09:14
I still believe this is confusing as the single newline character is visually indistinguishable from a blank line. Despite knowing it, I continue to get fooled by it every time.

A proposed solution: A simple fix could be to wrap the last two characters instead of the last, if the last one is the newline character. This would still create the issue if there is trailing whitespace in the line. So the final rule could be to wrap the last X characters from the line until the first non-whitespace character.

**Comment by th7mo** [comment] 2024-01-13 19:40
I had this issue as well, it happens more than I would think would happen.

I understand this behavior is not a bug and the newline character should be selectable of course. But... I don't think this implementation is desirable for most people.

I find it very confusing however when I use Helix those empty lines (except for the `\n` char of course) appear as demonstrated by @vwkd and it throws me off when editing text or code.

The soft-wrap feature already wraps an entire word to the next line when it does not fit on the line. Why wouldn't it treat the newline character the same as any other regular character? The newline character is not a word so it should not be wrapped as one. It is more like a `.` (period) to indicate the end of a sentence.

I propose that the soft-wrap feature treats the newline character not as a whitespace, but as a 'normal character' (or like the `.` (period) character. This makes the newline character the last character of the last word of the line. The result of this change will let the soft-wrap feature wrap the word with the newline character to a new space, instead of only the newline character.

I hope this will be reconsidered as it would improve the awesome soft-wrap feature even more!

**Comment by pascalkuthe** [comment] 2024-01-13 20:42
none of these special case solutions will be implemented. As I said many times before we will not special case newline characters. Currently the wrapping is pretty simple and essentially just wraps anything that counts as a word character together (as a word) and otherwise, everything as an individual characters (so there is no distinction between a period and a newline character for example). The way this will be improved is generally wrapping all trailing non-word chars with their preceding word as one unit. Duplicate of #6829

**Closed by pascalkuthe** 2024-01-13 20:42 UTC
Labels: C-bug
