### ISSUE TITLE
Show LSP loader

### ISSUE THREAD

**Issue by ElYaiko** [helix-editor/helix#11880] opened 2024-10-13 22:59 UTC
Sometimes some actions like `Code actions` or `Go declaration/definition` takes time to load to the LSP, so it would be good to show the LSP loader indicator when this actions are loading too not only when the LSP is starting.
Thanks

**Comment by kirawi** [comment] 2024-10-13 23:11
Duplicate of https://github.com/helix-editor/helix/issues/8704

**Closed by kirawi** 2024-10-13 23:11 UTC
Labels: C-enhancement
