### ISSUE TITLE
git integration?

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#2261] opened 2022-04-25 00:42 UTC
Just curious if there are any plans to offer a basic git integration

- change indicators in gutters
- diff comparisons
- stage, unstage
- stash, apply, pop
- change branch
- fetch, pull, push

**Comment by the-mikedavis** [comment] 2022-04-25 00:48
Duplicate of https://github.com/helix-editor/helix/issues/227

**Closed by the-mikedavis** 2022-04-25 00:48 UTC

**Comment by the-mikedavis** [comment] 2022-04-25 00:49
Diff signs in the gutter: https://github.com/helix-editor/helix/pull/1623

Staging, committing, or any non-read-only operation on the git index is likely to live outside of Helix as a plugin.

**Comment by lukepighetti** [comment] 2022-04-25 02:05
Is there any documentation on creating plugins?

**Comment by the-mikedavis** [comment] 2022-04-25 02:11
The main issue for the plugin system: https://github.com/helix-editor/helix/pull/1839#issuecomment-1084210835

It isn't implemented yet though, it's still in design / experimentation phase.

**Comment by lukepighetti** [comment] 2022-04-25 11:00
Is there a roadmap/discussion that describes which features will be integrated, and which will be plugins? I do believe that a thoughtful git integration should be within the scope of included features, especially if we are providing line gutters.

**Comment by the-mikedavis** [comment] 2022-04-25 12:38
What belongs in core and what should live as a plugin tends to become a per-feature conversation. If you read through the open issues (especially those marked `A-plugin`) you'll see some of the opinions. There isn't a hard rule though so it would be tough to document.

With respect to git in particular, my opinion is that read-only operations on the index like diff gutters or a blame gutter are fine for core but anything that takes on write features like committing, stashing, pushing, etc. should live as a plugin. Git porcelain plugins like magit or even fugitive have huge scopes and deserve to be their own projects.

**Comment by pickfire** [comment] 2022-04-25 15:42
> Is there a roadmap/discussion that describes which features will be integrated, and which will be plugins? I do believe that a thoughtful git integration should be within the scope of included features, especially if helix is providing line gutters. IMHO there is very little missing from helix at the moment, and this appears to be the biggest one.

I didn't discussed this with the other maintainers but my own opinion is similar to what @the-mikedavis mentioned, something as generic and useful for the public like git on line gutters will probably be built-in, and something like git operations which users could have more opinion on is more likely to be on the plugin. Quite scary that the maintainers often have a similar opinion on what things should be in core and as plugin, maybe because we used quite a couple of editors and form an opinion on what should be the basic for built-in for modern editors?

**Comment by yvess** [comment] 2023-04-22 15:53
I use `lazygit` if I want a bit more UI in a separate terminal window, goes nicely with helix editor

**Comment by macshaggy** [comment] 2023-04-29 14:25
@yvess How do you use lazygit with helix if it's run in a different window?

**Comment by mattmc3** [comment] 2023-05-24 23:49
> @yvess How do you use lazygit with helix if it's run in a different window?
> 

Usually, [with tmux](https://youtu.be/D0RvVkebVSY).

**Comment by nshern** [comment] 2023-07-13 07:35
> I use [lazygit](https://github.com/jesseduffield/lazygit) if I want a bit more UI in a separate terminal window, goes nicely with helix editor

But when you switch back to the helix window do you always need to `:reload` if you switched branch in LazyGit?

**Comment by quantonganh** [comment] 2023-07-24 14:34
@alexandershern Here's the workaround to `:reload-all` automatically using [WezTerm](https://wezfurlong.org/wezterm/index.html):

1. Create a [custom event](https://wezfurlong.org/wezterm/config/lua/wezterm/on.html#predefined-events):

```lua
function basename(s)
  return string.gsub(s, '(.*[/\\])(.*)', '%2')
end

wezterm.on('reload-helix', function(window, pane)
  local top_process = basename(pane:get_foreground_process_name())
  if top_process == 'hx' then
    local bottom_pane = pane:tab():get_pane_direction('Down')
    if bottom_pane ~= nil then
      local bottom_process = basename(bottom_pane:get_foreground_process_name())
      if bottom_process == 'lazygit' then
        local action = wezterm.action.SendString(':reload-all\r\n')
        window:perform_action(action, pane);
      end
    end
  end
end)
```

2. [Emit that event](https://wezfurlong.org/wezterm/config/lua/keyassignment/EmitEvent.html) when switching back to the helix:

```lua
config.keys = {
  {
    key = '[',
    mods = 'CMD',
    action = act.Multiple {
      act.ActivatePaneDirection 'Up',
      act.EmitEvent 'reload-helix',
    }
  },
```
