### ISSUE TITLE
Implement quickfix / location list

### ISSUE THREAD

**Issue by sschuldenzucker** [helix-editor/helix#8199] opened 2023-09-07 08:25 UTC
I'm coming from neovim/nvchad and one workflow I often use is:
- Trigger global (directory) search and search for something and press `C-q` to copy the list of matching locations to the vim's quickfix list
- Alternatively, perform a search in an external tool like ripgrep and load the results into the quickfix list via `:cfile`
- Step through the quickfix list one-by-one and review/fix things.

AFAIU helix doesn't have anything like a quickfix list and I feel it's a real omission because:
- The quickfix list is stateful: it provides a stable and visible place of all locations I want to look at, and it remembers the location in the list where I am right now.
- It doesn't seem to have any good counterpart in helix right now: I don't see any other helix features that could help me realize the above workflow.

IMHO it's not necessary to implement a quickfix- *and* location list, like vim. A single one should be enough. As a first step, implementing something like `:cfile` would also be enough IMHO.

**Comment by sschuldenzucker** [comment] 2023-09-07 08:26
Related: #5902

**Comment by pascalkuthe** [comment] 2023-09-07 08:37
Yeah duplicate of  #5902

The only thing I see us implementing is multi buffers (like  #4381 but with better UI)

**Closed** 2023-09-07 08:37 UTC
Labels: C-enhancement
