### ISSUE TITLE
Goto matching bracket not working in yaml

### ISSUE THREAD

**Issue by icholy** [helix-editor/helix#3614] opened 2022-08-31 14:09 UTC
### Summary

The Goto matching bracket not working in yaml.

### Reproduction Steps

I tried this:

1.  Place cursor on either `{` or `}` and press `mm`.

![image](https://user-images.githubusercontent.com/943597/187699050-fd3cdf69-4a05-4e98-b34c-14bab9330e7f.png)

I expected the cursor to move to the matching bracket, but it didn't move.

### Platform

Linux

### Terminal Emulator

alacritty 0.9.0

### Helix Version

helix 22.05 (83f177d2)

**Comment by alevinval** [comment] 2022-10-13 21:35
I've been looking at that issue. I'm using the following YAML document
```yaml
key: ${value}
```

I've added some debug traces, now I run `mm` on line 1, which yields:
```
2022-10-13T23:28:27.687 helix_core::match_brackets [DEBUG] >>>>>> FIND PAIR CALL <<<<<<
2022-10-13T23:28:27.687 helix_core::match_brackets [DEBUG] {Node string_scalar (0, 5) - (0, 13)}
2022-10-13T23:28:27.687 helix_core::match_brackets [DEBUG] pos=6
2022-10-13T23:28:27.687 helix_core::match_brackets [DEBUG] start_byte=5 end_byte=12
2022-10-13T23:28:27.687 helix_core::match_brackets [DEBUG] start_char=5 end_char=12
2022-10-13T23:28:27.687 helix_core::match_brackets [DEBUG] start=$
2022-10-13T23:28:27.688 helix_core::match_brackets [DEBUG] end=}
2022-10-13T23:28:27.688 helix_core::match_brackets [DEBUG] not valid pair...
```

It will never match because it considers the start character to be the `$` which will never match the `}`.
I also notice the `find_pair` is called up to 24 times, for that single action.

I notice that the `find_matching_bracket_fuzzy` is not running the sanity check that `find_matching_bracket` does, which first checks that the start character is a valid bracket in the first place.

**Comment by alevinval** [comment] 2022-10-13 21:55
Surely we could implement a hacky workaround like this one:

```patch
diff --git a/helix-core/src/match_brackets.rs b/helix-core/src/match_brackets.rs
index 0189dedd..a2aae514 100644
--- a/helix-core/src/match_brackets.rs
+++ b/helix-core/src/match_brackets.rs
@@ -51,7 +51,11 @@ fn find_pair(syntax: &Syntax, doc: &Rope, pos: usize, traverse_parents: bool) ->

     loop {
         let (start_byte, end_byte) = surrounding_bytes(doc, &node)?;
-        let (start_char, end_char) = (doc.byte_to_char(start_byte), doc.byte_to_char(end_byte));
+        let (mut start_char, end_char) = (doc.byte_to_char(start_byte), doc.byte_to_char(end_byte));
+
+        if doc.char(start_char) == '$' && end_char > start_char {
+            start_char += 1
+        }

         if is_valid_pair(doc, start_char, end_char) {
             if end_byte == pos {
```

This should be relatively safe, because the `$` char is not a valid matching pair. If we ever encounter it, we could try skipping to the next character, which worst-case scenario is not a pair either, and best-case scenario we find someone doing variable interpolation with `${...}` and then we would match correctly. While I feel this is strictly working as intended, it's pretty common to have YAMLs with string interpolation, so this small change could indeed improve the user experience, and the expectations when running `mm` on a YAML file.

**Comment by alevinval** [comment] 2022-10-13 22:11
I've opened a [draft PR](https://github.com/helix-editor/helix/pull/4259) in case that we're interested in adding such things. I feel this is somewhat ugly, yet at the same time may provide a better experience in some cases. But this may also introduce odd behavior in other cases or languages.

**Comment by the-mikedavis** [comment] 2022-10-14 16:45
Let's close this in favor of https://github.com/helix-editor/helix/issues/3357 which is the same problem

**Closed by the-mikedavis** 2022-10-14 16:45 UTC
Labels: C-bug
