### ISSUE TITLE
crash and Out Of Range Error when using pipe

### ISSUE THREAD

**Issue by anzhi0708** [helix-editor/helix#3061] opened 2022-07-13 20:31 UTC
I have 23+ files under ../

I was editing a python file under `.` and language server (pylsp) was on.

I moved the cursor to the bottom of the buffer and used `|` then typed `ls ..` to pipe the output into the buffer. Then I immediately pressed `u` to undo, and helix crashed.

Since I have 23+ files under `..` the output was relatively long. Probably some buffer size issue or LSP issue?

## Traceback

<details>

```
thread 'main' panicked at 'Position 1809 is out of range for changeset len 1785!', helix-core/src/transaction.rs:397:13
stack backtrace:
   0:        0x101177987 - __mh_execute_header
   1:        0x100a5f43b - __mh_execute_header
   2:        0x1011718ac - __mh_execute_header
   3:        0x10117cc90 - __mh_execute_header
   4:        0x10117c9c4 - __mh_execute_header
   5:        0x10102c36b - __mh_execute_header
   6:        0x10117d346 - __mh_execute_header
   7:        0x10117d184 - __mh_execute_header
   8:        0x10117af67 - __mh_execute_header
   9:        0x10117cea0 - __mh_execute_header
  10:        0x10121b903 - __mh_execute_header
  11:        0x100af4c99 - __mh_execute_header
  12:        0x100fc0aab - __mh_execute_header
  13:        0x100fc1f83 - __mh_execute_header
  14:        0x100e9d5d2 - __mh_execute_header
  15:        0x100d5b3f1 - __mh_execute_header
  16:        0x100d5cf3d - __mh_execute_header
  17:        0x100db0629 - __mh_execute_header
  18:        0x100d54528 - __mh_execute_header
  19:        0x1010286ee - __mh_execute_header
  20:        0x10103ddcf - __mh_execute_header
  21:        0x10100cbdd - __mh_execute_header
  22:        0x101002ef4 - __mh_execute_header
  23:        0x100ff55f2 - __mh_execute_header
  24:        0x10101b89f - __mh_execute_header
  25:        0x100fd6cd2 - __mh_execute_header
  26:        0x100ffd166 - __mh_execute_header
  27:        0x10100c651 - __mh_execute_header
  28:        0x10116b585 - __mh_execute_header
  29:        0x100fd6de9 - __mh_execute_header
```
</details>

I tried several times, get the same crash every time.

## Helix Log
<details>

```

(skipping...)
2022-07-14T03:06:28.879 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 25 }, end: Position { line: 54, character: 50 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:06:31.547 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 33 }, end: Position { line: 54, character: 66 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:06:53.444 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 55, character: 16 }, end: Position { line: 55, character: 32 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:07:55.002 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 56, character: 20 }, end: Position { line: 56, character: 41 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:36:20.798 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 56, character: 34 }, end: Position { line: 56, character: 68 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:36:39.892 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 56, character: 5 }, end: Position { line: 56, character: 38 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:36:56.616 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 56, character: 5 }, end: Position { line: 56, character: 40 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:36:57.787 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 56, character: 5 }, end: Position { line: 56, character: 42 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:41:21.669 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 58, character: 22 }, end: Position { line: 58, character: 46 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:44:56.883 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 61, character: 0 }, end: Position { line: 61, character: 100 } }, severity: Some(Warning), code: Some(String("E901")), code_description: None, source: Some("pycodestyle"), message: "E901 TokenError: EOF in multi-line statement", related_information: None, tags: None, data: None }
2022-07-14T03:53:06.876 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 14 }, end: Position { line: 52, character: 56 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:08.429 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 16 }, end: Position { line: 52, character: 58 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:09.677 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 20 }, end: Position { line: 52, character: 62 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "EOF while scanning triple-quoted string literal", related_information: None, tags: None, data: None }
2022-07-14T03:53:10.442 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 19 }, end: Position { line: 52, character: 61 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:11.378 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 20 }, end: Position { line: 52, character: 62 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "f-string: empty expression not allowed", related_information: None, tags: None, data: None }
2022-07-14T03:53:12.438 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 24 }, end: Position { line: 52, character: 66 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:15.192 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 27 }, end: Position { line: 52, character: 69 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:17.687 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 32 }, end: Position { line: 52, character: 74 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:19.002 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 34 }, end: Position { line: 52, character: 76 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:20.777 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 38 }, end: Position { line: 52, character: 80 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:22.687 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 43 }, end: Position { line: 52, character: 85 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:24.273 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 52, character: 47 }, end: Position { line: 52, character: 89 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:27.208 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 53, character: 9 }, end: Position { line: 53, character: 27 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T03:53:34.583 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 53, character: 20 }, end: Position { line: 53, character: 38 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:53:56.856 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 29 }, end: Position { line: 54, character: 61 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:57:03.353 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 38 }, end: Position { line: 54, character: 70 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T03:57:24.330 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 53 }, end: Position { line: 54, character: 85 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "EOL while scanning string literal", related_information: None, tags: None, data: None }
2022-07-14T03:57:44.125 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 55, character: 31 }, end: Position { line: 55, character: 144 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:01:03.431 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 47 }, end: Position { line: 54, character: 104 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:01:10.435 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 46 }, end: Position { line: 54, character: 92 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "unmatched ')'", related_information: None, tags: None, data: None }
2022-07-14T04:01:10.435 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 56, character: 0 }, end: Position { line: 56, character: 100 } }, severity: Some(Warning), code: Some(String("E901")), code_description: None, source: Some("pycodestyle"), message: "E901 TokenError: EOF in multi-line statement", related_information: None, tags: None, data: None }
2022-07-14T04:02:25.146 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 55 }, end: Position { line: 54, character: 109 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "EOL while scanning string literal", related_information: None, tags: None, data: None }
2022-07-14T04:03:30.807 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 24 }, end: Position { line: 54, character: 80 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:05:29.356 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 25 }, end: Position { line: 54, character: 60 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:38:25.273 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 44, character: 7 }, end: Position { line: 44, character: 55 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:38:27.176 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 44, character: 8 }, end: Position { line: 44, character: 56 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:38:29.292 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 44, character: 9 }, end: Position { line: 44, character: 57 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:38:33.136 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 44, character: 20 }, end: Position { line: 44, character: 68 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:38:38.920 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 45, character: 1 }, end: Position { line: 45, character: 37 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T04:38:41.856 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 46, character: 1 }, end: Position { line: 46, character: 35 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T04:38:43.467 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 44, character: 10 }, end: Position { line: 44, character: 58 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:38:45.069 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 44, character: 18 }, end: Position { line: 44, character: 66 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:38:54.219 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 47, character: 1 }, end: Position { line: 47, character: 2 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T04:38:58.127 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 48, character: 1 }, end: Position { line: 48, character: 17 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T04:38:59.805 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 48, character: 1 }, end: Position { line: 48, character: 17 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T04:40:04.482 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 51, character: 12 }, end: Position { line: 51, character: 24 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:57:50.184 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 9 }, end: Position { line: 54, character: 18 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:57:50.701 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 13 }, end: Position { line: 54, character: 26 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:57:58.875 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 12 }, end: Position { line: 54, character: 24 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:58:24.090 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 13 }, end: Position { line: 54, character: 26 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:58:27.120 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 55, character: 1 }, end: Position { line: 55, character: 2 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T04:58:33.516 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 55, character: 5 }, end: Position { line: 55, character: 10 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T04:58:48.394 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 55, character: 21 }, end: Position { line: 55, character: 42 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:58:52.946 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 55, character: 33 }, end: Position { line: 55, character: 120 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:58:56.461 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 55, character: 33 }, end: Position { line: 55, character: 120 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:58:58.031 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 54, character: 14 }, end: Position { line: 54, character: 28 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T04:59:01.001 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 55, character: 5 }, end: Position { line: 55, character: 10 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T04:59:31.574 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 56, character: 25 }, end: Position { line: 56, character: 50 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:59:33.604 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 56, character: 31 }, end: Position { line: 56, character: 63 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:59:36.268 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 56, character: 36 }, end: Position { line: 56, character: 72 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:59:40.517 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 57, character: 5 }, end: Position { line: 57, character: 10 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected an indented block", related_information: None, tags: None, data: None }
2022-07-14T04:59:43.561 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 57, character: 20 }, end: Position { line: 57, character: 40 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:59:46.904 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 57, character: 20 }, end: Position { line: 57, character: 40 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:59:53.240 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 57, character: 19 }, end: Position { line: 57, character: 38 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:59:55.410 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 58, character: 19 }, end: Position { line: 58, character: 38 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T04:59:59.594 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 58, character: 19 }, end: Position { line: 58, character: 38 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T05:00:54.174 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 58, character: 35 }, end: Position { line: 58, character: 70 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T05:08:38.188 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 59, character: 211 }, end: Position { line: 59, character: 422 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "EOF while scanning triple-quoted string literal", related_information: None, tags: None, data: None }
2022-07-14T05:09:26.986 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 60, character: 14 }, end: Position { line: 60, character: 28 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T05:09:42.170 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 60, character: 21 }, end: Position { line: 60, character: 42 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T05:09:44.673 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 60, character: 30 }, end: Position { line: 60, character: 60 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T05:09:49.218 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 60, character: 39 }, end: Position { line: 60, character: 79 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T05:09:55.174 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 60, character: 44 }, end: Position { line: 60, character: 88 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T05:10:12.659 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 61, character: 16 }, end: Position { line: 61, character: 32 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T05:10:28.589 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 62, character: 14 }, end: Position { line: 62, character: 28 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-07-14T05:10:33.125 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 62, character: 25 }, end: Position { line: 62, character: 50 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }

```
</details>

For some reason I can't turn the python LSP down to test more right now, and after finishing the code I'm working on, I will test a little more

**Comment by the-mikedavis** [comment] 2022-07-13 20:35
Duplicate of https://github.com/helix-editor/helix/issues/2237

**Closed by the-mikedavis** 2022-07-13 20:35 UTC
