### ISSUE TITLE
Text appears on the left side (crashes in some cases)

### ISSUE THREAD

**Issue by GreasySlug** [helix-editor/helix#4148] opened 2022-10-08 02:29 UTC
### Summary

![helix-crash](https://user-images.githubusercontent.com/106496265/194683087-a7e06851-4caf-43d6-aa9c-2ab520a3eb3a.png)

### Reproduction Steps

 

I can't reproduce it well, so I'll just describe what I was able to do.

- PowerShell: crash
- cmd: crash
- windows terminal(PowerShell): doesn't crash

Open a file with the following string using helix.

```plaintext
"begin": "((?:[[:alpha:]_\\p{Lu}\\p{Ll}\\p{Lt}\\p{Lm}\\p{Lo}\\p{Nl}\\p{Sc}⅀-⅄∿⊾⊿⊤⊥∂∅-∇∎∏∐∑∞∟∫-∳⋀-⋃◸-◿♯⟘⟙⟀⟁⦰-⦴⨀-⨆⨉-⨖⨛⨜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃ⁱ-⁾₁-₎∠-∢⦛-⦯℘℮゛-゜𝟎-𝟡]|[^\\P{So}←-⇿])(?:[[:word:]_!\\p{Lu}\\p{Ll}\\p{Lt}\\p{Lm}\\p{Lo}\\p{Nl}\\p{Sc}⅀-⅄∿⊾⊿⊤⊥∂∅-∇∎∏∐∑∞∟∫-∳⋀-⋃◸-◿♯⟘⟙⟀⟁⦰-⦴⨀-⨆⨉-⨖⨛⨜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃ⁱ-⁾₁-₎∠-∢⦛-⦯℘℮゛-゜𝟎-𝟡]|[^\\P{Mn}\u0001-¡]|[^\\P{Mc}\u0001-¡]|[^\\P{Nd}\u0001-¡]|[^\\P{Pc}\u0001-¡]|[^\\P{Sk}\u0001-¡]|[^\\P{Me}\u0001-¡]|[^\\P{No}\u0001-¡]|[′-‷⁗]|[^\\P{So}←-⇿])*)({(?:[^{}]|{(?:[^{}]|{[^{}]*})*})*})?\\.?(\\()",
```

Then move the cursor over the special characters and the characters will appear on the left side.

If you change the window size when the file is in this state, the terminal crashes (windows terminal does not crash)

I have experienced a similar phenomenon with tui-rs

The terminal itself crashes when I try to draw in a location larger than the terminal size

I think this is similar to that.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-10-08T10:49:24.860 helix_view::editor [ERROR] Failed to initialize the LSP for `source.json` { cannot find binary path }
```

In the log, the json file is opened, but it also happens with plaintext.
</details>

### Platform

Windows

### Terminal Emulator

cmd, PowerShell and windows terminal

### Helix Version

helix 22.08.1 (d5d6da94)

**Comment by A-Walrus** [comment] 2022-10-08 09:39
Duplicate of #3643?

**Comment by GreasySlug** [comment] 2022-10-08 09:54
I think you're probably right.

I would add that resizing the terminal in this status will cause the terminal itself to crash.

**Closed** 2022-10-15 05:18 UTC
Labels: C-bug
