### ISSUE TITLE
File tree?

### ISSUE THREAD

**Issue by UltiRequiem** [helix-editor/helix#1016] opened 2021-11-08 13:23 UTC
Is there something like https://github.com/kyazdani42/nvim-tree.lua ?

#### Describe your feature request

A plugin or a native feature of a file tree.

**Comment by archseer** [comment] 2021-11-08 13:29
Duplicate of https://github.com/helix-editor/helix/issues/200

**Closed by archseer** 2021-11-08 13:29 UTC
Labels: C-enhancement
