### ISSUE TITLE
The consecutive selections will be automatically merged after `c`

### ISSUE THREAD

**Issue by xcpky** [helix-editor/helix#11925] opened 2024-10-22 09:15 UTC
The consecutive selections will be automatically merged after `c`, this is unreasonable.
for example:
1. search for four spaces:
![Screenshot From 2024-10-22 17-10-38](https://github.com/user-attachments/assets/238dad66-9762-43f7-b3a0-ecde1abc502f)
2. press c, there is only one cursor
![Screenshot From 2024-10-22 17-10-42](https://github.com/user-attachments/assets/e431d590-f4e9-4f5f-82fd-e47866433ea3)
3. the same happens for searching for a and press c, only one cursor appears.
![Screenshot From 2024-10-22 17-10-57](https://github.com/user-attachments/assets/abe6e5b5-605d-4764-8a71-5d5e5225660f)
![Screenshot From 2024-10-22 17-11-00](https://github.com/user-attachments/assets/f66cf810-fba6-4e24-b5cb-f4c7673be5a9)

**Comment by kirawi** [comment] 2024-10-22 20:36
Duplicate of https://github.com/helix-editor/helix/issues/2298

**Closed by kirawi** 2024-10-22 20:36 UTC
