### ISSUE TITLE
Panic opening hx

### ISSUE THREAD

**Issue by webdevdunce** [helix-editor/helix#29] opened 2021-06-01 20:20 UTC
I get this running on Windows. I am running in the clone folder itself.

```
thread 'main' panicked at 'index out of bounds: the len is 2496 but the index is 2496', helix-tui\src\buffer.rs:185:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by lduguid** [comment] 2021-06-01 23:00
Same here, window 10.

![image](https://user-images.githubusercontent.com/105060/120400297-6eb28700-c2f2-11eb-9af5-ee566eddf1c8.png)

![image](https://user-images.githubusercontent.com/105060/120400309-7a05b280-c2f2-11eb-860a-e5ce521f511a.png)

**Comment by archseer** [comment] 2021-06-02 02:19
Closing this as a duplicate of #22, something is wrong with rendering on windows. Will do some tests today

**Closed by archseer** 2021-06-02 02:19 UTC
