### ISSUE TITLE
:wq is very slow while :w then :q is not

### ISSUE THREAD

**Issue by sorenrade** [helix-editor/helix#4871] opened 2022-11-24 06:26 UTC
### Summary

Obviously this is not a pressing issue as this is not the intended use for hx but considering that performing the operations one after another is fast it seems like it could be an easy fix. 

Thanks!

### Reproduction Steps

Steps to reproduce:

1) open a 1Mb, 20k line, plaintext file
2) delete the last line
3) :wq
4) the save takes more than 10min

Alternatively :w then :q, there will be a reasonable amount of lag as the large file is written, maybe 10sec

### Helix log

Nothing notable in the log

### Platform

Linux 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Terminal Emulator

alacritty / zellij

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by archseer** [comment] 2022-11-24 06:58
Duplicate of #3975

This was fixed in #2267

**Closed by archseer** 2022-11-24 06:58 UTC
Labels: C-bug

**Comment by sorenrade** [comment] 2022-11-28 04:50
Thanks! I'll test on main first next time.
