### ISSUE TITLE
Opening file picker in large repo takes excessively long

### ISSUE THREAD

**Issue by joshuawarner32** [helix-editor/helix#1910] opened 2022-03-31 19:29 UTC
### Summary

The file picker seems to load the entire git repository, which in my case has ~500K files (i.e. half a million). It takes about 10 seconds to load the file picker.

There's obviously only so much optimization that can actually be done here - `find . >/dev/null` alone takes 13 seconds for me.

A few thoughts on possible improvements:
* `git ls-tree -r HEAD --name-only` takes only 400ms - much better, tho still longer than I'd like
* Ideally there could be a setting to only pick files under the current directory - which in my case is _much_ smaller than the entire repo
* This list should hopefully be handled by some daemon and asynchronously kept up to date. In my case, `watchman` is already running - maybe there could be an integration there?

### Reproduction Steps

 

I tried this:

1. `hx`
2. type `<space>`, `<f>` to load the file picker
3. wait

I expected this to happen:

File picker should load in "interactive" time - definitely under a second, ideally under 100ms

Instead, this happened:

I had to wait

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

`~/.cache/helix/helix.log` is empty (but exists)
`hx -h` confirms this the correct path.

</details>

### Platform

macOS 12.3

### Terminal Emulator

iTerm2 v3.4.15

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by the-mikedavis** [comment] 2022-03-31 19:44
duplicate of https://github.com/helix-editor/helix/issues/1707

**Closed by the-mikedavis** 2022-03-31 19:44 UTC
Labels: C-bug
