### ISSUE TITLE
Hybrid indentation can cause incorrect results at the end of indent scopes

### ISSUE THREAD

**Issue by tsaraki** [helix-editor/helix#10336] opened 2024-04-10 16:50 UTC
### Summary

On windows, using Windows Terminal (new), in golang after closing curly brace open_below and/or open_above lost identation and start insert mode from first char of the line. But if before closing bracket is empty line, all works fine. Helix log doesnt represent much

### Reproduction Steps

 

I tried this:

----some := 50                                                                                                                                                                                                     
----if some > 34 {
--------fmt.Println("herhe")
----} <- cursor

open_below

I expected this to happen:

----some := 50                                                                                                                                                                                                     
----if some > 34 {
--------fmt.Println("herhe")
----} 
----<- cursor

Instead, this happened:

----some := 50                                                                                                                                                                                                     
----if some > 34 {
--------fmt.Println("herhe")
----} 
<- cursor

I tried this:

----some := 50                                                                                                                                                                                                     
----if some > 34 {
--------fmt.Println("herhe")

----} <- cursor

open_below

As usually:

----some := 50                                                                                                                                                                                                     
----if some > 34 {
--------fmt.Println("herhe")

----} 
----<- cursor
    

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

 2024-04-10T19:44:20.771 helix_lsp::transport [ERROR] gopls err: <- StreamClosed  

</details>

### Platform

Windows

### Terminal Emulator

wt 1.19.240322001

### Installation Method

releases page

### Helix Version

helix 24.3 (2cadec0b)

**Comment by pascalkuthe** [comment] 2024-04-11 10:19
@Triton171 this is a regression caused by https://github.com/helix-editor/helix/pull/8307.

The hybrid indentation heuristic is not working as intended here. `:set indentation-heuristic tree-sitter` fixes this.

Proper reproduction case:

``` go
func main() {
	some := 50
	if some > 34 {
		fmt.Println("herhe")
	}
}
```

indentation after the second last closing brace is wrong.

With `tree-sitter` heuristic `i<ret>foo` inserts
``` go
func main() {
	some := 50
	if some > 34 {
		fmt.Println("herhe")
	}
    foo
}
```

Doing the same thing with the `hybrid` heuristic produces:

``` go
``` go
func main() {
	some := 50
	if some > 34 {
		fmt.Println("herhe")
	}
foo
}
```
```

**Comment by Triton171** [comment] 2024-04-20 11:42
Thanks for the clean reproduction case @pascalkuthe! The issue was caused by the code that decides whether a tree-sitter node is the first in a line: Previously, we checked this by looking at the syntax tree but that can go wrong if the tree-sitter grammar creates nodes that end with whitespace. The Go grammar inserts "newline" nodes for some reason, which causes Helix to treat the newline node as the beginning of the line & not the node afterwards (`}` in this case). The linked PR fixes this & also simplifies the code a bit.

In theory, this issue could also occur with the `tree-sitter` indent heuristic, but the necessary circumstances are a lot less likely (due to the way most indent queries are currently structured).

**Closed** 2024-04-20 22:58 UTC
Labels: C-bug, A-indent
