### ISSUE TITLE
Suggestions often inserted in incorrect place

### ISSUE THREAD

**Issue by Elias-Graf** [helix-editor/helix#4851] opened 2022-11-22 11:37 UTC
### Summary

Suggestions are often inserted into the incorrect place. This does occur more frequently when the computer itself is not the quickest (e.g. happens more often on my laptop than on my desktop), and is way more frequent on larger code bases. 

See this video that shows the issue in action:

https://user-images.githubusercontent.com/46671625/203301244-0cc20f2a-d9de-4955-a3f1-25e922c74c12.mov

Notice how I'm trying to complete after I typed "expe", but the completions seem to be "old". So it then seems to use old position information and just inserts it before the "p", leaving me with "expectp". Same thing happens with "e" ("expecte") in a different try after that.

Btw. the project in question is in React / TypeScript.

Sometimes this leaves me with up to three redundant characters on a completion "attempt" (which I use extensively), so it's not rare that I need to correct four different things on a single line.

### Reproduction Steps

Sadly, there is no clear-cut reproduction I can provide. But it feels like a race condition to me?

### Helix log

As far as I'm able to tell, there is no log produced during the entirety of the issue.

### Platform

macOs

### Terminal Emulator

iTerm 2

### Helix Version

helix-term 22.08.1 (5ad3befe)

**Comment by Elias-Graf** [comment] 2022-11-22 13:03
Here is the same thing in the helix codebase:


https://user-images.githubusercontent.com/46671625/203320548-9fa7b7f6-a86e-4dcf-b742-203d48d524cc.mov

It was significantly harder to reproduce than on the React / TypeScript codebase.

**Comment by archseer** [comment] 2022-11-22 15:04
Can you check if this PR fixes it for you? https://github.com/helix-editor/helix/pull/1819

**Comment by Elias-Graf** [comment] 2022-11-22 15:16
@archseer Hey, how would I properly test this? I tried merging it into current master which lead to merge conflicts. That pull request is currently 428 commits behind. The bug could have been introduced in one of those. Do you have any prior commit you would want me to try to confirm that the issue existed before the fix?

**Comment by archseer** [comment] 2022-11-22 15:33
I'm pretty sure the issue is with the LSP response being slow and extra characters being typed before it comes back and has always been there. That PR is specifically supposed to address that.

**Comment by David-Else** [comment] 2022-11-22 20:28
@archseer https://github.com/helix-editor/helix/pull/1819 needs to be rebased to master for people to test, @Elias-Graf was saying there are merge conflicts. 

There seems to be problems with the pull request reported too... I have been hit by this serious bug using Rust https://github.com/helix-editor/helix/issues/4380, it would be great to get it sorted for `22.11`, maybe add it to [the 22.11 milestone ](https://github.com/helix-editor/helix/pulls?q=is%3Aopen+is%3Apr+milestone%3A22.11) ?

**Comment by Elias-Graf** [comment] 2022-11-22 20:36
@archseer I'm going to test tomorrow with the fixed but old version. The like 15 mins I have been using it today, it seemed like that issue was gone (although I couldn't always autocomplete, since the sorting of the items seemed worse). ***If*** this fixes the issue, I would really appreciate if it could be merged quickly, as it's actively preventing me from programming, and I've switched back to VS Code for languages where the language server is apparently slower than my typing.

**Comment by archseer** [comment] 2023-03-09 04:03
Should be fixed by https://github.com/helix-editor/helix/pull/6173

**Closed by archseer** 2023-03-09 04:03 UTC
Labels: C-bug, A-language-server
