### ISSUE TITLE
Show function definition when in insert mode between brackets

### ISSUE THREAD

**Issue by colaxdev** [helix-editor/helix#2342] opened 2022-04-30 08:54 UTC
# Idea

```zig
         ---------------------
         |function definition|
         ---------------------
helix_is("very c|ool");
                ^
                | cursor
```

**Comment by thomkeh** [comment] 2022-04-30 09:38
I think this is being worked on in #1755

**Comment by the-mikedavis** [comment] 2022-04-30 11:48
Duplicate of https://github.com/helix-editor/helix/issues/1331

**Closed by the-mikedavis** 2022-04-30 11:48 UTC
Labels: C-enhancement
