### ISSUE TITLE
Auto completing deletes character cursor is currently on.

### ISSUE THREAD

**Issue by dogunbound** [helix-editor/helix#5761] opened 2023-02-01 05:18 UTC
### Summary

A video is better at explaining it:

https://user-images.githubusercontent.com/64436119/215956561-d4abd9c2-0617-4946-9413-2d8d83b8ccfc.mp4

### Reproduction Steps

Open a rust project.

In main create a local variable then do:
type:
`dbg!(`
Then try and autofill the local variable

The opening parenthesis should disappear. 

### Helix log

No log gets outputted when this issue occurs.

My config:
```
theme="dracula"

[editor]
mouse=false
completion-trigger-len=1
idle-timeout=0
auto-save=true
scrolloff=3

[keys.select]
 k = ["ensure_selections_forward", "flip_selections", "extend_line_up"]```

### Platform

Linux

### Terminal Emulator

Konsole

### Helix Version

22.12

**Comment by gabydd** [comment] 2023-02-01 06:24
Might be helpful to post a relevant snippet of your log with when running ``helix -vvvv``

**Comment by CptPotato** [comment] 2023-02-01 07:49
I think this could be resolved by #1819

**Comment by dogunbound** [comment] 2023-02-01 23:46
https://user-images.githubusercontent.com/64436119/216193482-b07f9d3f-7a4b-4c86-a6fb-433357183c06.mp4



> Try setting idle-timeout to a low but more reasonable value like 100 (still way below human reaction time). An idle timeout of 0 is known to cause issues. Although I also think that #1819 might be the real fix to this problem

didn't help

**Comment by pascalkuthe** [comment] 2023-02-01 23:50
Thanks for testing. That's a bit odd I will try to reproduce this locally. These bugs are very hard to reproduce usually but given that you seem to be able to do it reliably (no matter the idle timeout) then maybe I can reproduce this

**Comment by dogunbound** [comment] 2023-02-02 02:04
> Might be helpful to post a relevant snippet of your log with when running `helix -vvvv`

empty log file.

**Comment by kirawi** [comment] 2023-02-05 16:26
Did you try executing the auto-complete action with logs enabled? The log shouldn't be empty if the LSP is working.

**Comment by dogunbound** [comment] 2023-02-06 01:38
[helix.log](https://github.com/helix-editor/helix/files/10636748/helix.log)

**Comment by pascalkuthe** [comment] 2023-03-03 19:37
This is unrelated to #1819 / #6173 (not fixed by either). I am able to reproduce.

**Comment by pascalkuthe** [comment] 2023-03-03 22:24
I have managed to confirm this is an upstream issue with rust-analyzer. RA seems to always send a range that starts one character too early when completing a macro arg when no text has been typed yet.

Minimal reproducible example:
``` rust
macro_rules! foo {
    ($val:expr $(,)?) => {
        $val
    };
}

fn main(){
    foo!(); // buggy
    foo!(b); // ok
}
```

Place the curosor between the brackets of the first `foo()` press `c-x` and select any completion (important **do not type any text**). This will insert the completion and remove the bracket. For the second macro invocation `foo!(b)` the same bug does not occur. The same issue can reproduced in vscode. Again no text must be typed and instead the completion must be manually invoked with `c-space`.

Interestingly enough this bug is quite noticeable in helix because helix triggers completion on trigger chars (the `(` in this case, which is one of the trigger chars provided by RA `[":", ".", "'", "("]`) vscode does not trigger completions in this case despite the fact that it's documentation claims that it does

**Comment by pascalkuthe** [comment] 2023-03-03 22:55
Ah it seems that RA prevents showing many completions  when the trigger character is a `(` as in this case:

https://github.com/rust-lang/rust-analyzer/blob/73e2505cfa8be6838f5151b272f1d24869b2a3d6/crates/ide-completion/src/lib.rs#L158

We currently don't send the trigger character. I think there is actually a lot of room to improve the way helix handles trigger characters. From the LSP spec it actually sounds like the client should treat any word character as a completion trigger too (which is what vscode does):


 	  The additional characters, beyond the defaults provided by the client (typically
 	  [a-zA-Z]), that should automatically trigger a completion request. For example
 	  `.` in JavaScript represents the beginning of an object property or method and is
 	  thus a good candidate for triggering a completion request.
 	  
 	  Most tools trigger a completion request automatically without explicitly
 	  requesting it using a keyboard shortcut (e.g. Ctrl+Space). Typically they
 	  do so when the user starts to type an identifier. For example if the user
 	  types `c` in a JavaScript file code complete will automatically pop up
 	  present `console` besides others as a completion item. Characters that
 	  make up identifiers don't need to be listed here.


I know @archseer doesn't like completions popping up instantly so instead of changing the default here we could simply add a config option for that. I believe this is also the correct fix for #5054, https://github.com/helix-editor/helix/issues/2027 and https://github.com/helix-editor/helix/issues/2581. VSCode actually does no "on idle" completions at all, it just has these additional trigger chars. So for people that want fast completions that seems like a much better approach (especially because it requires one redraw less and doesn't break other idle timeout related things) .


This bug is orthogonal to that and should be fixed upstream but these might be nice improvements for helix regardless.

**Comment by pascalkuthe** [comment] 2023-03-04 01:42
Upstream PR submitted: #14247

**Comment by gyreas** [comment] 2023-03-04 07:25
This happened to me yesterday (for the first time), using the Hx 22.12

**Comment by gyreas** [comment] 2023-03-04 07:25
This happened to me yesterday (for the first time), using the Hx 22.12

**Comment by pascalkuthe** [comment] 2023-03-04 09:48
The upstream PR fixes this issue has been merged. To fix the issue you can build rust analyzer from source for now. The fix will be includes with the next RA release on Monday

**Closed by pascalkuthe** 2023-03-04 09:48 UTC
Labels: C-bug, upstream

**Comment by dogunbound** [comment] 2023-03-24 04:39
This is still happening to me on ra 1.68.1


https://user-images.githubusercontent.com/64436119/227425880-4a35ffe4-196e-4548-85e6-0484523a49fd.mp4

**Comment by dogunbound** [comment] 2023-03-24 15:00
Moved my RA version to nightly. It works now.
