### ISSUE TITLE
Diagnostics can overlay warnings addressed by cursor

### ISSUE THREAD

**Issue by Rudxain** [helix-editor/helix#12197] opened 2024-12-05 23:06 UTC
### Summary

(inline?) diagnostics can block the view of arbitrary text, including the source of the warn/error itself. This makes it hard for users to fix it.

Workarounds:
- Use low zoom level (small font): Not always possible, since the source of the warn/err can be at the top of the file.
- Move the view-port, and/or add lines before the source of error: requires reverting the change manually after fixing the warn/err

### Reproduction Steps

The following example screenshots are contrived, but the general problem happens frequently for me (high zoom):
![Cursor not on error: no diagnostic](https://github.com/user-attachments/assets/9b28909d-9e36-4146-a2c6-9bf3483cfa47)

![Cursor on error (underline): diagnostic now makes the entire line invisible](https://github.com/user-attachments/assets/1b13b9e5-da83-4aa1-8656-b63255c3d598)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

GNOME Terminal 3.54.2 using VTE 0.78.2 +BIDI +GNUTLS +ICU +SYSTEMD for GNOME 47 

### Installation Method

AppImage from releases page

### Helix Version

helix 24.7 (079f5442)

**Comment by the-mikedavis** [comment] 2024-12-05 23:30
I don't think those are inline diagnostics - https://github.com/helix-editor/helix/pull/6417 was merged right after the 24.07 release so if you're using the latest stable it shouldn't be possible to use them. (The screenshot looks like non-inline-diagnostics: the text is right-aligned.)

So this may be a duplicate of #1462

**Closed** 2024-12-06 00:27 UTC
Labels: C-bug
