### ISSUE TITLE
Default select register value isn't updated in the register menu 

### ISSUE THREAD

**Issue by TheAndrewJackson** [helix-editor/helix#7698] opened 2023-07-21 13:32 UTC
### Summary

The register menu (`"`) isn't updating the default select register (`/`) after the first time it has been automatically filled.

### Reproduction Steps

https://github.com/helix-editor/helix/assets/17103888/962faf39-5ae6-4a88-a4e6-e5ab9501f77c

I tried this:

1. `hx --tutor`
2. `s` select "Welcome"
3. `"` register menu shows "/ Welcome"
4. `s` select for "Helix"

I expected this to happen:
`"` register menu shows "/ Helix"
Instead, this happened:
`"` register menu shows "/ Welcome"

I've noticed that the same thing happens when using the `*` command on a selection.

One interesting finding is manually setting the register with `"/y` does correctly update the displayed value in the register menu. It seems like the commands that automatically fill in the the select register (`s` and `*`) aren't doing it after it has been filled in one time.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
I emptied the log file before recording the video and nothing was in it afterwards.
</details>

### Platform

macOS

### Terminal Emulator

kitty 0.25.0

### Helix Version

helix 23.05 (7f5940be)

**Comment by the-mikedavis** [comment] 2023-07-21 13:46
Duplicate of https://github.com/helix-editor/helix/issues/5241

**Closed by the-mikedavis** 2023-07-21 13:46 UTC
Labels: C-bug
