### ISSUE TITLE
Resume cursor at last position (feature request)

### ISSUE THREAD

**Issue by sscheele** [helix-editor/helix#4371] opened 2022-10-19 17:43 UTC
When I open a file with vim, my cursor appears either at the first row/column (if I've never opened it before) or wherever it was when I last closed the file. This is particularly nice for debugging code, when I'm frequently closing the editor to run the file and then reopening it when I get an error message. It's also generally nice to be able to directly pick up where I left off in a file without having to pause and reorient myself. Could there be a configuration option for this?

**Comment by the-mikedavis** [comment] 2022-10-19 17:50
Duplicate of https://github.com/helix-editor/helix/issues/2104

See #401

**Closed by the-mikedavis** 2022-10-19 17:50 UTC
