### ISSUE TITLE
json language server name not right

### ISSUE THREAD

**Issue by fastfading** [helix-editor/helix#5500] opened 2023-01-11 08:21 UTC
### Summary

current json  language server  is vscode-json-languageserver not vscode-json-language-server
https://www.npmjs.com/package/vscode-json-languageserver
https://github.com/microsoft/vscode-json-languageservice

when I install it  
npm install -g vscode-json-languageserver

json syntax highlight works.  
but  Binary for language server: Not found

❯ hx --health json
Configured language server: vscode-json-language-server
Binary for language server: Not found in $PATH
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✘
Indent queries: ✓

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macos

### Terminal Emulator

iterm2

### Helix Version

22.12

**Comment by archseer** [comment] 2023-01-11 12:32
Contribute a PR?

**Comment by the-mikedavis** [comment] 2023-01-11 13:24
Actually this is intentional: https://github.com/helix-editor/helix/pull/2749#issuecomment-1152994986

**Comment by the-mikedavis** [comment] 2023-01-11 13:25
Duplicate of https://github.com/helix-editor/helix/issues/2761

**Closed by the-mikedavis** 2023-01-11 13:25 UTC
Labels: C-bug
