### ISSUE TITLE
It would be nice to have colored indent guides

### ISSUE THREAD

**Issue by Moanrisy** [helix-editor/helix#8620] opened 2023-10-26 04:24 UTC
Still little hard to see because
- all indent guides have the same color
- it can't show currently active guides (maybe it should be bold or something)

![image](https://github.com/helix-editor/helix/assets/17421945/3961ecfb-6154-419e-bff9-4555e3223cdb)

**Comment by David-Else** [comment] 2023-10-26 09:44
https://github.com/helix-editor/helix/pull/4493

**Comment by pascalkuthe** [comment] 2023-10-26 10:59
duplicate of #4010

**Closed by pascalkuthe** 2023-10-26 10:59 UTC
