### ISSUE TITLE
Primary selection not distinguishable from others

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#6221] opened 2023-03-07 14:51 UTC
### Summary

https://user-images.githubusercontent.com/666539/223457878-d258ed91-c049-41b6-9064-22512c316d22.mov

On tokyonight_storm (also tokyonight, and default) there's no visual indication of which selection is the primary selection

### Platform

ProductName:		macOS ProductVersion:		13.2.1 BuildVersion:		22D68

### Terminal Emulator

iTerm 3.5.0beta7

### Helix Version

helix 22.12 (96ff64a8)

**Comment by kirawi** [comment] 2023-03-07 15:51
Duplicate of #3842

**Closed by kirawi** 2023-03-07 15:51 UTC
Labels: C-bug
