### ISSUE TITLE
OCaml: toggle_comment doesn't enclose text

### ISSUE THREAD

**Issue by tuohy** [helix-editor/helix#2873] opened 2022-06-25 00:26 UTC
### Summary

Using toggle_comment (ctrl-c) adds an empty comment to the beginning of the line your cursor is on / the beginning of each line you have selected, leaving the line /selection outside of the comment.

### Reproduction Steps

 
asciinema demonstration:
https://asciinema.org/a/s8wHb2tHswrfjFZxWhFRaE2gw

I tried this:

1. Open a .ml file in helix
2. (Optional) select multiple characters or lines
3. Press ctrl-c to invoke toggle_comment

I expected this to happen:
When no selection is made, the whole line should be wrapped inside a comment:
`  | 0 -> 1` should become `(*  | 0 -> 1 *)`
If a selection is made, it should be transformed into a multi line comment inside a `(* *)` pair:
```
let () = let a = f 1 in
  print_endline (string_of_int a)
```
should become:
```
(*
let () = let a = f 1 in
  print_endline (string_of_int a)
*)
```
Instead, this happened:
The line or lines have an empty comment `(**)` added at the start of the line, i.e. the latter example above becomes
```
(**) let () = let a = f 1 in
(**)   print_endline (string_of_int a)
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

[helix.log](https://github.com/helix-editor/helix/files/8983548/helix.log)

</details>

### Platform

Linux

### Terminal Emulator

st, alacritty

### Helix Version

22.05-128-gc107f4ea

**Comment by the-mikedavis** [comment] 2022-06-25 01:40
Duplicate of https://github.com/helix-editor/helix/issues/2770

**Closed by the-mikedavis** 2022-06-25 01:40 UTC
Labels: C-bug
