### ISSUE TITLE
Unusable in large files (slow syntax highlight)

### ISSUE THREAD

**Issue by ZuixAlias** [helix-editor/helix#6427] opened 2023-03-24 15:39 UTC
I had copy pasted a cpp code snippet in my rust project (it was a huge array, containing font data), helix was way to slow to do anything after that. (The file size after saving it was ~170kb)
Motions were fine (in all modes), but each key press took 4-5sec to register in insert mode (including some actions like undo, redo, deleting selection, deleting char, etc...)
(_Note: No LSP or any other features were active, just plain helix_)

It's not as bad if the array was of the same language, same as the lang of the file containg it. But still, even if it's the same language, the editing is noticably and visibly slow compared to other mainstream editors (it's all good with them) if the file is large (slow not just on an array but code in general).

Culprit i think is the syntax highlighting (could be parsing more text than which is visible)...as changing to `lang text` solves the issue.

(EDIT: It's `rust`'s highlight that is slow compared to others, `go` too, etc...`C` 's is much faster, but visibly slow still)

**Comment by kirawi** [comment] 2023-03-24 15:44
Please use the bug template next time. This is a duplicate of https://github.com/helix-editor/helix/issues/338 or https://github.com/helix-editor/helix/issues/3072

**Closed by kirawi** 2023-03-24 15:44 UTC
