### ISSUE TITLE
Crash when closing dot file buffers

### ISSUE THREAD

**Issue by Hoidigan** [helix-editor/helix#3211] opened 2022-07-27 07:47 UTC
### Summary

After creating a dot file and writing the buffer, attempting to close the buffer while viewing a different buffer causes a crash.

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-view\src\editor.rs:633:51
```

I ran into this after trying to write a .gitignore file.

### Reproduction Steps

 

I tried this:

1. `hx`
2. `:w .test`
3. `:n`
4. `:bca`

I expected this to happen:

The .test buffer to close.

Instead, this happened:

The program crashed

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-07-27T00:41:28.692 helix_loader [DEBUG] Located configuration folders: []
2022-07-27T00:41:28.699 globset [DEBUG] glob converted to regex: Glob { glob: "*.{zip,gz,bz2,zst,lzo,sz,tgz,tbz2,lz,lz4,lzma,lzo,z,Z,xz,7z,rar,cab}", re: "(?-u)^[^/]*\\.(cab|rar|7z|xz|Z|z|lzo|lzma|lz4|lz|tbz2|tgz|sz|lzo|zst|bz2|gz|zip)$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: false }, tokens: Tokens([ZeroOrMore, Literal('.'), Alternates([Tokens([Literal('c'), Literal('a'), Literal('b')]), Tokens([Literal('r'), Literal('a'), Literal('r')]), Tokens([Literal('7'), Literal('z')]), Tokens([Literal('x'), Literal('z')]), Tokens([Literal('Z')]), Tokens([Literal('z')]), Tokens([Literal('l'), Literal('z'), Literal('o')]), Tokens([Literal('l'), Literal('z'), Literal('m'), Literal('a')]), Tokens([Literal('l'), Literal('z'), Literal('4')]), Tokens([Literal('l'), Literal('z')]), Tokens([Literal('t'), Literal('b'), Literal('z'), Literal('2')]), Tokens([Literal('t'), Literal('g'), Literal('z')]), Tokens([Literal('s'), Literal('z')]), Tokens([Literal('l'), Literal('z'), Literal('o')]), Tokens([Literal('z'), Literal('s'), Literal('t')]), Tokens([Literal('b'), Literal('z'), Literal('2')]), Tokens([Literal('g'), Literal('z')]), Tokens([Literal('z'), Literal('i'), Literal('p')])])]) }
2022-07-27T00:41:28.699 globset [DEBUG] built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 1 regexes
2022-07-27T00:41:28.700 ignore::walk [DEBUG] ignoring .\.git: Ignore(IgnoreMatch(Hidden))
2022-07-27T00:41:28.700 helix_term::ui [DEBUG] file_picker init 2.0186ms
```

</details>

### Platform

Windows

### Terminal Emulator

Windows terminal

### Helix Version

helix 22.05

**Comment by the-mikedavis** [comment] 2022-07-27 08:39
Duplicate of https://github.com/helix-editor/helix/issues/2367

**Closed by the-mikedavis** 2022-07-27 08:39 UTC
Labels: C-bug
