### ISSUE TITLE
syntax highlighting on Alpine Linux didn't work

### ISSUE THREAD

**Issue by Carlo-Monte** [helix-editor/helix#11407] opened 2024-08-02 17:43 UTC
### Discussed in https://github.com/helix-editor/helix/discussions/9683

<div type='discussions-op-text'>

<sup>Originally posted by **DrSensor** February 21, 2024</sup>

Please see the discussion linked above.

In summary, "hx -g fetch; hg -g build" fails under Alpine to create symlinks from ~/.config/helix/runtime/grammars/sources/LANG/queries to ~/.config/helix/runtime/queries/LANG.

It is not clear at all how this is supposed to work in the ideal case. This must please be explained by someone in the Team (here or in a documentation link), before the problem can be relegated to Alpine. I doubt that the person responsible at Alpine knows how this specific function works with Helix.

Thank you (I am a happy Helix user :+1: ).

**Comment by the-mikedavis** [comment] 2024-08-02 18:15
An extra issue fragments the discussion. Duplicate of #9683

**Closed by the-mikedavis** 2024-08-02 18:15 UTC

**Comment by Carlo-Monte** [comment] 2024-08-02 20:33
Please explain. A discussion is not an issue but a request for information. A discussion does not lead to a fix, like a bug?

**Comment by the-mikedavis** [comment] 2024-08-02 20:48
Discussions aren't that simplistic: we use them for a wider variety, for example the Troubleshooting section for reports that don't have enough information to clearly show a bug. Reports often need some investigation and that can lead to a fix (either in Helix or elsewhere) and discussions are a better format for that investigation. Discussions are just a format.

Also though you _are_ requesting information.

**Comment by Carlo-Monte** [comment] 2024-08-02 21:24
Thank you.
