### ISSUE TITLE
RFC: `line` text object

### ISSUE THREAD

**Issue by hirschenberger** [helix-editor/helix#8903] opened 2023-11-24 20:11 UTC
We have all kinds of obscure text objects like paragraphs, functions, arguments... but it seems that a `line` textobject is a natural and useful extension.

Assumed that `l` is the letter for `line` (which is still available), you could do things like `mild` to clear a line, `mald` to delete a line, `milms}` to put brackets around the current line.

I know all of this can be done with other key-combos, but they all seem like hacks or workarounds and are not as intuitive.

e.g. do clear a line: `xdO<esc>`, `xvhd` or `x_d`.

**Comment by pascalkuthe** [comment] 2023-11-24 20:19
duplicate of #4234, both `X` and `X_`  already work and are easy enough to use.

Note that we also don't have a formal RFC process (#8853 is an experiment and something like this is only intended *major* design changes not minor keymap changes)

**Closed by pascalkuthe** 2023-11-24 20:19 UTC
Labels: C-enhancement

**Comment by hirschenberger** [comment] 2023-11-24 21:25
So as #4234 is an open issue, is that a thing that would be accepted as a PR? Then I'd give it  a try.

**Comment by the-mikedavis** [comment] 2023-11-24 21:42
It seems unnecessary to me to have this re-implemented as a text-object: it's already implemented as `extend_to_line_bounds` or `["extend_to_line_bounds", "trim_selections"]`, or whatever the equivalent keys are for the `]`/`[` parts (https://github.com/Delapouite/kakoune-text-objects/blob/da9a268c3f239e40e0ca4665faa17f709563795b/text-objects.kak#L44-L62 in kakoune). Rather I'd like to see it be possible to add or change text-object bindings which are currently hardcoded in `select_textobject_inner`/`select_textobject_around`.

That isn't as straightforward as it seems though (like in https://github.com/helix-editor/helix/pull/4287) since the fall-through behavior for "whatever character is typed next" isn't currently mappable.
