### ISSUE TITLE
C-Sharp LSP not starting when opening .cs files

### ISSUE THREAD

**Issue by MAST1999** [helix-editor/helix#2616] opened 2022-05-30 20:16 UTC
### Summary

I have installed omnisharp and checked with `hx --health c-sharp` to make sure it is ok.

But when I open a `.cs` file in a `c-sharp` project the LSP doesn't start.

Do I have to open a special file or in a special directory for it to work?

### Reproduction Steps

I built from the source and checked with `hx --health c-sharp` and it showed that the LSP was found.

I also fetched the grammar and built them.

Then I opened a `.cs` file in a project but nothing worked and trying code actions told me that no LSP was running for the current buffer.

### Helix log

```
2022-05-31T00:41:23.562 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:23.875 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:23.875 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:24.174 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:24.174 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:24.485 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:24.485 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:24.975 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:24.975 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:25.287 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:25.287 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:25.671 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:25.671 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:25.953 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:41:25.953 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-05-31T00:44:26.843 helix_view::theme [WARN] Theme: malformed hexcode: fg
2022-05-31T00:44:26.843 helix_view::theme [WARN] Theme: malformed hexcode: form
```

### Platform

Windows

### Terminal Emulator

Windows Terminal Version: 1.12.10983.0

### Helix Version

helix 22.05 (370a16d0)

**Comment by the-mikedavis** [comment] 2022-05-31 01:24
That message is coming from this block: https://github.com/helix-editor/helix/blob/eba82250bb4403fcb2e3ade74ba7301a680bc561/helix-term/src/application.rs#L401-L410

So it looks like the language server is sending an invalid [`Notification`](https://github.com/helix-editor/helix/blob/eba82250bb4403fcb2e3ade74ba7301a680bc561/helix-lsp/src/lib.rs#L255-L263). You can read the communication between helix and the language server in [the log file](https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file) when running helix in verbose mode (`-v`, up to three `-vvv` for more verbosity) to see what the language server is sending.

**Comment by MAST1999** [comment] 2022-05-31 01:51
Thanks, @the-mikedavis
I check with `hx -vvv` and I think most things are working correctly until these two lines (I didn't include a lot of the glob and file selection to avoid making this too big):
```
helix_lsp::transport [INFO] Language server not initialized, delaying request
2022-05-31T06:14:38.382 helix_term::application [ERROR] Timed out waiting for language servers to shutdown
```
The second line is the only error in the log.

I don't know what it means, but if there is a problem with omnisharp, I can open an issue over there.

```
2022-05-31T06:14:30.388 helix_term::ui::picker [DEBUG] picker score 28.6µs
2022-05-31T06:14:31.754 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
2022-05-31T06:14:31.754 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-05-31T06:14:31.754 mio::poll [TRACE] registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
2022-05-31T06:14:31.754 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":false},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"publishDiagnostics":{},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":false}},"window":{"workDoneProgress":true},"workspace":{"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"workspaceFolders":true}},"processId":31856,"rootPath":"H:\\work-repos\\Beyond\\gplus-gallery","rootUri":"file:///H:/work-repos/Beyond/gplus-gallery","workspaceFolders":[{"name":"gplus-gallery","uri":"file:///H:/work-repos/Beyond/gplus-gallery"}]},"id":0}
2022-05-31T06:14:32.841 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"OmniSharp.Services.DotNetCliService: Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK | "}}
2022-05-31T06:14:32.842 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "OmniSharp.Services.DotNetCliService: Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK | " }
2022-05-31T06:14:32.842 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"OmniSharp.Services.DotNetCliService: Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK | "}}
2022-05-31T06:14:32.842 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"OmniSharp.Services.DotNetCliService: Using the 'dotnet' on the PATH. | "}}
2022-05-31T06:14:32.842 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"OmniSharp.Services.DotNetCliService: Using the 'dotnet' on the PATH. | "}}
2022-05-31T06:14:32.842 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"OmniSharp.Services.DotNetCliService: DotNetPath set to dotnet | "}}
2022-05-31T06:14:32.842 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"OmniSharp.Services.DotNetCliService: DotNetPath set to dotnet | "}}
2022-05-31T06:14:32.843 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "OmniSharp.Services.DotNetCliService: Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK | " }
2022-05-31T06:14:32.843 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "OmniSharp.Services.DotNetCliService: Using the 'dotnet' on the PATH. | " }
2022-05-31T06:14:32.843 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "OmniSharp.Services.DotNetCliService: Using the 'dotnet' on the PATH. | " }
2022-05-31T06:14:32.843 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "OmniSharp.Services.DotNetCliService: DotNetPath set to dotnet | " }
2022-05-31T06:14:32.843 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "OmniSharp.Services.DotNetCliService: DotNetPath set to dotnet | " }
2022-05-31T06:14:33.019 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"OmniSharp.MSBuild.Discovery.MSBuildLocator: Located 2 MSBuild instance(s)\r\n            1: Visual Studio Enterprise 2022 17.3.32505.426 17.3.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\MSBuild\\Current\\Bin\"\r\n            2: Visual Studio Community 2022 17.1.32210.238 17.1.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\" | "}}
2022-05-31T06:14:33.019 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"OmniSharp.MSBuild.Discovery.MSBuildLocator: Located 2 MSBuild instance(s)\r\n            1: Visual Studio Enterprise 2022 17.3.32505.426 17.3.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\MSBuild\\Current\\Bin\"\r\n            2: Visual Studio Community 2022 17.1.32210.238 17.1.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\" | "}}
2022-05-31T06:14:33.019 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "OmniSharp.MSBuild.Discovery.MSBuildLocator: Located 2 MSBuild instance(s)\r\n            1: Visual Studio Enterprise 2022 17.3.32505.426 17.3.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\MSBuild\\Current\\Bin\"\r\n            2: Visual Studio Community 2022 17.1.32210.238 17.1.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\" | " }
2022-05-31T06:14:33.021 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "OmniSharp.MSBuild.Discovery.MSBuildLocator: Located 2 MSBuild instance(s)\r\n            1: Visual Studio Enterprise 2022 17.3.32505.426 17.3.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\MSBuild\\Current\\Bin\"\r\n            2: Visual Studio Community 2022 17.1.32210.238 17.1.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\" | " }
2022-05-31T06:14:33.027 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"OmniSharp.MSBuild.Discovery.MSBuildLocator: Registered MSBuild instance: Visual Studio Enterprise 2022 17.3.32505.426 17.3.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\MSBuild\\Current\\Bin\" | "}}
2022-05-31T06:14:33.027 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"OmniSharp.MSBuild.Discovery.MSBuildLocator: Registered MSBuild instance: Visual Studio Enterprise 2022 17.3.32505.426 17.3.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\MSBuild\\Current\\Bin\" | "}}
2022-05-31T06:14:33.027 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "OmniSharp.MSBuild.Discovery.MSBuildLocator: Registered MSBuild instance: Visual Studio Enterprise 2022 17.3.32505.426 17.3.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\MSBuild\\Current\\Bin\" | " }
2022-05-31T06:14:33.027 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "OmniSharp.MSBuild.Discovery.MSBuildLocator: Registered MSBuild instance: Visual Studio Enterprise 2022 17.3.32505.426 17.3.0 - \"C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\MSBuild\\Current\\Bin\" | " }
2022-05-31T06:14:37.867 helix_lsp::transport [INFO] Language server not initialized, delaying request
2022-05-31T06:14:38.382 helix_term::application [ERROR] Timed out waiting for language servers to shutdown
2022-05-31T06:14:38.385 mio::poll [TRACE] deregistering event source from poller
2022-05-31T06:14:38.385 mio::poll [TRACE] deregistering event source from poller
2022-05-31T06:14:38.385 mio::poll [TRACE] deregistering event source from poller
2022-05-31T06:14:45.804 helix_view::theme [WARN] Theme: malformed hexcode: form
2022-05-31T06:14:45.804 helix_view::theme [WARN] Theme: malformed hexcode: fg

```

**Comment by the-mikedavis** [comment] 2022-05-31 02:30
The duplicate back-to-back messages from the server are a bit odd but I don't see anything bad in that log. In that case it looks like it didn't send the malformed notification messages since this log doesn't have any of those error messages. Instead it looks like the language server timed out initializing. Can you give it a few more runs and see if you can provoke that "received malformed notification from Language Server: Unhandled" error message?

**Comment by archseer** [comment] 2022-05-31 15:49
Can you give us a full backtrace again?

**Comment by archseer** [comment] 2022-05-31 15:51
Ah ok, one is in https://github.com/helix-editor/helix/issues/2430#issuecomment-1120706243=

**Comment by MAST1999** [comment] 2022-05-31 16:59
Is the backtrace in the `helix.log` @archseer ?

**Comment by the-mikedavis** [comment] 2022-05-31 17:02
To get the full backtrace, you'll need to set the `RUST_BACKTRACE` environment variable to `full` and then reproduce the crash, and it will start with

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value...
```

**Comment by MAST1999** [comment] 2022-05-31 22:37
Here is the backtrace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char range out of bounds: char range 18446744073709551538..18446744073709551599, Rope/RopeSlice char length 31489', C:\Users\mast\.cargo\registry\src\github.com-1ecc6299db9ec823\ropey-1.5.0\src\rope.rs:546:37
stack backtrace:
   0:     0x7ff7ff0ff154 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7ff0ff154 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7ff0ff154 - std::sys_common::backtrace::_print_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff7ff0ff154 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff7fe90caaa - core::fmt::write
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\fmt\mod.rs:1194
   5:     0x7ff7ff0f7d39 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\io\mod.rs:1655
   6:     0x7ff7ff10290b - std::sys_common::backtrace::_print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff7ff10290b - std::sys_common::backtrace::print
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff7ff10290b - std::panicking::default_hook::closure$1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:295
   9:     0x7ff7ff1025a9 - std::panicking::default_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:314
  10:     0x7ff7fefbc177 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::take_box::h52ec70c93fbd4a4e
  11:     0x7ff7ff10304f - std::panicking::rust_panic_with_hook
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:702
  12:     0x7ff7ff102dc3 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:588
  13:     0x7ff7ff1003a7 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\sys_common\backtrace.rs:138
  14:     0x7ff7ff102a7f - std::panicking::begin_panic_handler
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
  15:     0x7ff7ff196e05 - core::panicking::panic_fmt
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
  16:     0x7ff7ff196f13 - core::result::unwrap_failed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\result.rs:1785
  17:     0x7ff7fea1a8e7 - ropey::rope::Rope::remove::h71a8c51dcd799fc0
  18:     0x7ff7fe9a8202 - helix_core::transaction::ChangeSet::apply::h2941207579129f02
  19:     0x7ff7fef4d437 - helix_view::document::Document::apply_impl::haca85cb6e25e3aa3
  20:     0x7ff7fef4f389 - helix_view::document::Document::apply::h0809faa69b10a8ea
  21:     0x7ff7fee11e6f - helix_term::commands::lsp::apply_workspace_edit::h72619662e4a1b8b4
  22:     0x7ff7fee115fc - helix_term::commands::lsp::apply_workspace_edit::h72619662e4a1b8b4
  23:     0x7ff7fefb7d00 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::take_box::h52ec70c93fbd4a4e
  24:     0x7ff7fefd2310 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7f584e36a034d767
  25:     0x7ff7fef962f4 - tokio::park::thread::CachedParkThread::block_on::h5b87153c9bac0673
  26:     0x7ff7fef83e28 - tokio::runtime::thread_pool::ThreadPool::block_on::hae968876f2d490c0
  27:     0x7ff7fefada45 - tokio::runtime::Runtime::block_on::hd01dae295923f5e9
  28:     0x7ff7fef654fc - hx::setup_logging::h0f2a86d807b38468
  29:     0x7ff7fef5aab6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h60e6b2f4bf6f9de1
  30:     0x7ff7fefa92ba - std::rt::lang_start::{{closure}}::h0d05cec207e622c1
  31:     0x7ff7ff0f0f42 - core::ops::function::impls::impl$2::call_once
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs:259
  32:     0x7ff7ff0f0f42 - std::panicking::try::do_call
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:492
  33:     0x7ff7ff0f0f42 - std::panicking::try
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:456
  34:     0x7ff7ff0f0f42 - std::panic::catch_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panic.rs:137
  35:     0x7ff7ff0f0f42 - std::rt::lang_start_internal::closure$2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\rt.rs:128
  36:     0x7ff7ff0f0f42 - std::panicking::try::do_call
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:492
  37:     0x7ff7ff0f0f42 - std::panicking::try
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:456
  38:     0x7ff7ff0f0f42 - std::panic::catch_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panic.rs:137
  39:     0x7ff7ff0f0f42 - std::rt::lang_start_internal
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\rt.rs:128
  40:     0x7ff7fef65697 - main
  41:     0x7ff7ff190edc - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  42:     0x7ff7ff190edc - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  43:     0x7ff8090554e0 - BaseThreadInitThunk
  44:     0x7ff80ae2485b - RtlUserThreadStart
```

**Comment by MAST1999** [comment] 2022-06-02 21:53
Is this enough or do I need to add more?
@the-mikedavis

**Comment by the-mikedavis** [comment] 2022-06-02 21:59
No that looks good. archseer is taking a look at this in #2430

**Comment by fopsdev** [comment] 2023-01-12 10:59
@MAST1999 Would you mind attach your `omnisharp.json` file. (I'm not able to get rid off ```2023-01-12T11:51:14.107 helix_lsp [ERROR] failed to initialize language server: request timed out
``` from `helix.log`)

**Comment by varon** [comment] 2023-03-24 21:01
@fopsdev  - Also suffering from this - can you provide your omnisharp.json file?

**Comment by chrismightier** [comment] 2023-04-05 21:30
I was experiencing a similar issue, my logs contained timeout which I believe to be the root problem.
`helix_term::application [ERROR] Timed out waiting for language servers to shutdown`

From what I can tell, the default timeout (20 seconds) was too short for my project. I adjusted languages.toml to the following:
```
[[language]]
name = "c-sharp"
scope = "source.cs"
injection-regex = "c-?sharp"
roots = ["sln", "csproj"]
file-types = ["cs"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
language-server = { command = "omnisharp", args = ["-lsp"], timeout=10000 }
```

Specifically, this line:
`language-server = { command = "omnisharp", args = ["-lsp"], timeout=10000 }`

Hope this helps someone else.

**Comment by pascalkuthe** [comment] 2023-09-12 01:11
The crash encounter here was fixed (see https://github.com/helix-editor/helix/issues/2430). There doesnt seem to be any actionable issue left here so I am closing this issue.

**Closed by pascalkuthe** 2023-09-12 01:11 UTC
Labels: C-bug
