### ISSUE TITLE
Match theme to system brightness

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#2296] opened 2022-04-27 00:09 UTC
Given two themes, `rose_pine_dawn` and `rose_pine`, and a system whose brightness changes based on time of day, it would be nice to be able to set a light mode theme, a dark mode theme, and if it should match the current system brightness.

**Comment by the-mikedavis** [comment] 2022-04-27 00:24
Duplicate of https://github.com/helix-editor/helix/issues/2158

**Closed by the-mikedavis** 2022-04-27 00:24 UTC
Labels: C-enhancement
