### ISSUE TITLE
Way to remap groups in the TOML file. And the ablility to give names to the groups

### ISSUE THREAD

**Issue by IsotoxalDev** [helix-editor/helix#1508] opened 2022-01-14 12:40 UTC
Is there a way to remap groups in the config TOML file?.
![image](https://user-images.githubusercontent.com/62714538/149516890-de9dfef7-6b2c-4cef-b503-e059060cdba8.png)

**Comment by NNBnh** [comment] 2022-01-14 16:05
Try:

```toml
[keys.normal."g"]
  "g" = "goto_file_start"
  "e" = "goto_last_line"
```

**Comment by IsotoxalDev** [comment] 2022-01-14 16:08
what about the group name?

**Comment by IsotoxalDev** [comment] 2022-01-14 16:09
i want to change g to d as i use colemak keyboard layout

**Comment by sudormrfbin** [comment] 2022-01-14 16:57
The names are hard-coded for now, but you can certainly remap keys. From what I understand you want to move all keys under `g` to `d` so that goto mode is essentially under `d` -- currently you'll have to manually rebind it in the config file. #133 might interest you.

**Comment by IsotoxalDev** [comment] 2022-01-14 16:58
i was seeing if there was a way to do it with the config. But ye i can do it myself. Thanks. Should i close this issue?

**Comment by Omnikar** [comment] 2022-01-23 17:16
This should probably be reopened, as it would be a good feature to have, even though it's entirely possible to get by without.

**Comment by IsotoxalDev** [comment] 2022-01-24 11:13
okay then

**Comment by pascalkuthe** [comment] 2024-04-11 23:47
Duplicate of #1752

**Closed by pascalkuthe** 2024-04-11 23:47 UTC
Labels: C-enhancement, A-helix-term
