### ISSUE TITLE
CTRL+K (kill_to_line_end) selects autocomplete option

### ISSUE THREAD

**Issue by johalun** [helix-editor/helix#4963] opened 2022-12-01 18:32 UTC
### Summary

When I go to insert mode on code that pops up the autocomplete list I can't do CTRL+K (kill_to_line_end), instead it selects an option from the autocomplete menu and inserts into the editor. On a comment for example where there's no autocomplete options, CTRL+K works as expected.

### Reproduction Steps

 

I tried this:

1. `cd helix` # clone of helix repo
2. `hx helix-core/src/diagnostic.rs`
3. Put cursor on something that will autocomplete, for example on the `i` in `usize`
4. Go to insert mode
5. See the autocomplete menu popup with `us` completions like `usize2x` etc
6. Press CTRL+K to kill to end of line

I expected this to happen:
The characters after the cursor to be deleted

Instead, this happened:
`usize` is replaced with the last item in the autocomplete list `usizex8`

### Helix log

Nothing relevant in the log

### Platform

macOS

### Terminal Emulator

iTerm2

### Helix Version

helix 22.05 (06a5bca7)

**Comment by the-mikedavis** [comment] 2022-12-01 21:41
(Misclick sorry 😅)

**Comment by the-mikedavis** [comment] 2022-12-01 21:41
Can you reproduce this on master? It looks like you're on a branch based on #2377

**Comment by philipgiuliani** [comment] 2022-12-05 08:44
I can reproduce this more or less on master (59b886cf5e89dadfd73d93b638b2c552ce5537f6). Found out about CTRL+k today but everytime before I use it the LSP pops up with the suggestions and CTRL+k inserts the first suggestion from the list.

Tested in elixir files using elixir-ls.

1. Switching to insert mode:
![Screenshot 2022-12-05 at 09 43 49](https://user-images.githubusercontent.com/5446019/205592786-9bc040f6-ae4e-4311-8ae1-bd7b274543a9.png)
2. Clicking CTRL+k
![Screenshot 2022-12-05 at 09 43 56](https://user-images.githubusercontent.com/5446019/205592847-abb878d1-d017-40fe-ab36-67327c9a10f5.png)

**Comment by DylanBulfin** [comment] 2022-12-08 14:33
I'm new to the codebase so I could be wrong, but it seems that whenever the completion menu pops up, it takes precedence in handling certain key commands such as `C-k` (kill to end of line) ,`C-j` (insert newline), tab, etc. The workaround is to press `C-c` to exit the completion menu first. (check [the menu file](https://github.com/helix-editor/helix/blob/master/helix-term/src/ui/menu.rs) for input handling info)

I'm not totally sure why the `C-j` and `C-k` bindings are used there in the first place, as moving up and down in the completion menu can already be done with shift-tab/`C-p` and tab/`C-n` respectively, just like in pickers. Is there any specific reason why menus specifically have those bindings but pickers don't?

**Comment by DylanBulfin** [comment] 2022-12-08 15:19
There was a similar issue with pickers at one point, where `C-k` navigation overwrote the intended behavior of `C-k` killing to end of line in the prompt. This was addressed by https://github.com/helix-editor/helix/pull/1792, made a new PR https://github.com/helix-editor/helix/pull/5070 to try and resolve this for the completion menu as well

**Comment by the-mikedavis** [comment] 2023-02-15 14:26
Fixed in https://github.com/helix-editor/helix/pull/5070

**Closed by the-mikedavis** 2023-02-15 14:26 UTC
Labels: C-bug
