### ISSUE TITLE
Write to file with sudo/doas

### ISSUE THREAD

**Issue by ayes-web** [helix-editor/helix#5887] opened 2023-02-09 02:25 UTC
Would it be possible to get a feature for attempting to write to file with sudo/doas when not enough permissions? 
[Similar to how micro does it](https://github.com/zyedidia/micro/issues/158)
https://github.com/zyedidia/micro/blob/master/runtime/help/options.md#sucmd

**Comment by kirawi** [comment] 2023-02-09 02:55
Duplicate of https://github.com/helix-editor/helix/discussions/4251

**Closed by kirawi** 2023-02-09 02:55 UTC
Labels: C-enhancement

**Comment by pchampin** [comment] 2023-12-01 08:15
I respectfully disagree that this is a duplicate of #4251. That discussion is about *starting* helix with sudo.

The question in this issue, and the linked-to feature of micro, is about *writing* a file with sudo, in an instance of helix that was started *as a regular user*. I agree that this would be a super useful feature.

**Comment by kirawi** [comment] 2023-12-01 15:23
They are actually duplicates because the question in the discussion was not about starting Helix with sudo, but generally how to write with sudo. There are mentions of the system from micro as well.

**Comment by the-mikedavis** [comment] 2023-12-01 15:52
I don't want to see this added to core. It's a hack as micro says that pipes the buffer contents through `sudo tee` and you can do that already with the shell_pipe command: `%|sudo tee <path>`, using `C-z` to suspend and `sudo -v && fg` in the terminal so you don't have to enter the password.
