### ISSUE TITLE
Helix cannot delete the last blank line(s) of the buffer when the cursor is at the very last line

### ISSUE THREAD

**Issue by OpenFoam-User** [helix-editor/helix#4433] opened 2022-10-23 13:33 UTC
**Steps to reproduce**:

* open helix.
* press <kbd>i</kbd>.
* Press <kbd>Enter</kbd> 5 times.
* press <kbd>Esc</kbd>
* press <kbd>g</kbd><kbd>e</kbd>

Now if you keep pressing `d` key it won't remove all the empty lines. (as it is expected in neovim).

**What is the expected behavior**:

I expect the cursor to move up to the previous empty line so when you keep pressing `d` it will delete all the line but it seems that this is not the case for helix.

**Comment by the-mikedavis** [comment] 2022-10-23 14:00
Helix's `d` behaves sort-of like Vi's `x` if Vi's `x` could act on newlines - it deletes the current selection and the cursor itself is a 1-width selection. In the reproduction steps, the cursor is resting on a newline character and `d` deletes that character. Then the cursor rests on the EOF character which cannot be deleted. This can be easier to visualize if you enable visible whitespace: https://docs.helix-editor.com/configuration.html#editorwhitespace-section.

This is the intended behavior for `d`.

**Comment by pascalkuthe** [comment] 2023-01-18 11:51
Closing this issue as it's intended behaviour

**Closed** 2023-01-18 12:04 UTC
