### ISSUE TITLE
Feature request: Popup for LSP diagnostics

### ISSUE THREAD

**Issue by Domerpig** [helix-editor/helix#2553] opened 2022-05-23 19:35 UTC
The LSP diagnostics in the upper right corner can sometimes be way out of my view and I have to glance back and forth between my code and the diagnostic. An option to have a popup that shows the diagnostic at the same place of the code would be nice. Or maybe showing it at the end of the line. Just somewhere closer.

**Comment by kirawi** [comment] 2022-05-23 22:17
Related to #411

**Comment by kaleidawave** [comment] 2022-05-31 21:28
Have found the code for rendering diagnostics, which is called by `render_view` (found above in the file)

https://github.com/helix-editor/helix/blob/370a16d0f00d6146fdeb87cc16fb352e860e2377/helix-term/src/ui/editor.rs#L600-L652

Wondering how hard it would be to add a option to render it either under the cursor while it is highlighted or something?

**Comment by JakeHL** [comment] 2022-06-22 09:14
I think this falls under the same issue, but I have a slightly different grievance.

Very often imports in various languages are at the top of the file, and very often I make typos when importing stuff.

The LSP complains and then gets in the way of me fixing the issue.
![image](https://user-images.githubusercontent.com/9119973/174991715-6a5f15ce-9941-4c2b-9a6a-efb34e6d2fa1.png)

*please ignore that I'm using archaic nodeJS, some clients like it old school 😭*

**Comment by poliorcetics** [comment] 2022-07-29 16:05
On master there is now `space+g/G` for file/workspace diangostic which makes the user jump to the exact position of the diagnostic, does it at least partially fix the issue ?

**Comment by pascalkuthe** [comment] 2022-12-16 11:20
I think is is a duplicate of #1953 so I am closing this issue in favor of that. If you don't think that is right and that these are two separate issues feel free to reopen.

**Closed by pascalkuthe** 2022-12-16 11:20 UTC
Labels: C-enhancement, A-helix-term

**Comment by AddictArts** [comment] 2023-03-22 20:21
For anyone else trying to find it, now `space+d`, the `g` is the debug experimental.
