### ISSUE TITLE
gopls completions re-ordered

### ISSUE THREAD

**Issue by losnappas** [helix-editor/helix#5103] opened 2022-12-10 03:02 UTC
### Summary

https://github.com/joaotavora/eglot/issues/576

That bug also happens in helix. Completions get reordered.

```go
package main

func fooBar() {}

func _() {
	var sbp string
	var s struct { blah int }
	var _ int = sb.
}
```

Helix: 

![image](https://user-images.githubusercontent.com/25119292/206825528-d201f178-08da-4822-a33a-a09a760b5e8f.png)

Vscode:

![image](https://user-images.githubusercontent.com/25119292/206825576-011e46d9-52ae-47b7-a5ce-4609aab1c508.png)

The suggestion by gopls is sorted correctly (because of the type `int`), but helix pushes it to 2nd.

### Reproduction Steps

```
golang.org/x/tools/gopls v0.10.1
golang.org/x/tools/gopls@v0.10.1 h1:JoHe17pdZ8Vsa24/GUO8iTVTKPh0EOBiWpPop7XJybI=
```

### Platform

Linux

### Terminal Emulator

irrelevant

### Helix Version

helix-term 22.12 (d14de277)

**Comment by pascalkuthe** [comment] 2024-04-04 01:56
Completion ordering is editor dependent and depends on the exact fuzzy matching algorithm. Order differing between editors is expected and ok 

The only exceptions are incomplete completion requests. That is tracked in #9797 so closing as duplicate of that

**Closed by pascalkuthe** 2024-04-04 01:56 UTC
Labels: C-bug, A-helix-term

**Comment by losnappas** [comment] 2024-04-04 04:13
But it's making incompatible completions. In my example it's giving a `string` to an `int`, it isn't semantically aware. I would hope to be able to turn the ordering off completely, since it's being more harm than good.
