### ISSUE TITLE
Helix needs fix

### ISSUE THREAD

**Issue by elintendo** [helix-editor/helix#5834] opened 2023-02-05 10:29 UTC
### Summary

I was typing usual, boring text in Helix, suddenly the app closed and I was in terminal. The text was not saved. The same issue also happened once while ago.

### Reproduction Steps

I created file with `hx hypr.sh` and typed bash script in there. Then Helix crashed and I was in kitty again.

The error was:
thread 'main' panicked at 'Position 49 is out of range for changeset len 1!', helix-core/src/transaction.rs:397:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Helix log

2023-02-05T12:59:46.072 helix_term::application [WARN] failed to load theme `dracula_at_night` - No such file or directory (os error 2)
2023-02-05T13:00:50.602 helix_term::application [WARN] failed to load theme `dracula_at_night` - No such file or directory (os error 2)
2023-02-05T13:01:07.217 helix_term::application [WARN] failed to load theme `dracula_at_night` - No such file or directory (os error 2)
2023-02-05T13:01:16.187 helix_term::application [WARN] failed to load theme `dracula_at_night` - No such file or directory (os error 2)
2023-02-05T13:01:16.188 helix_view::editor [ERROR] Failed to initialize the LSP for `source.css` { cannot find binary path }
2023-02-05T13:09:22.557 helix_term::application [WARN] failed to load theme `dracula_at_night` - No such file or directory (os error 2)
2023-02-05T13:12:41.346 helix_term::application [WARN] failed to load theme `dracula_at_night` - No such file or directory (os error 2)
2023-02-05T13:12:56.635 helix_term::application [WARN] failed to load theme `dracula_at_night` - No such file or directory (os error 2)
2023-02-05T13:13:01.924 helix_term::application [WARN] failed to load theme `dracula_at_night` - No such file or directory (os error 2)
2023-02-05T13:15:29.451 helix_term::application [WARN] failed to load theme `dracula_at_night` - No such file or directory (os error 2)
2023-02-05T13:15:29.453 helix_view::editor [ERROR] Failed to initialize the LSP for `source.bash` { cannot find binary path }
2023-02-05T13:20:28.217 helix_term::application [WARN] failed to load theme `dracula_at_night` - No such file or directory (os error 2)

### Platform

Linux, Arch

### Terminal Emulator

kitty 0.27.0-1

### Helix Version

helix 22.12 (7e191f59)

**Comment by pascalkuthe** [comment] 2023-02-05 12:11
> I created file with hx hypr.sh and typed bash script in there. Then Helix crashed and I was in kitty again.

This is not a reproduction case. What exactly caused the issue depends on what **exactly** you did. Meaning what text did you type, did you paste anything, ... You also didn't provide a backtrace (`RUST_BACKTRACE=1` ) which would atleast give some hints at what is going wrong.

 This sounds like it might be a duplicate of #5733 and therefore would already be fixed in current master by #5790. I would suggest that you rebuild from the master branch and try again. If you encounter thiss crash with master you can post a backtrace or reproduction case here

**Comment by pascalkuthe** [comment] 2023-02-11 21:09
closing as this is likely fixed by https://github.com/helix-editor/helix/pull/5790 and no reproduction case was provided on request.

If you are still having issues feel free to open a new issue

**Closed by pascalkuthe** 2023-02-11 21:09 UTC
Labels: C-bug, S-waiting-on-author
