### ISSUE TITLE
hi, does hx support nerdtree-like file browser?

### ISSUE THREAD

**Issue by jinfagang** [helix-editor/helix#4067] opened 2022-10-02 06:22 UTC
hi, does hx support nerdtree-like file browser?

**Comment by CptPotato** [comment] 2022-10-02 06:24
It's being worked on: #2377

**Comment by dead10ck** [comment] 2022-10-02 11:39
Duplicate of #200

**Closed by dead10ck** 2022-10-02 11:39 UTC

**Comment by Mizux** [comment] 2024-10-08 10:53
github tricks: please use list when listing github issue:
* #2377
* #200
