### ISSUE TITLE
Pretty status bar

### ISSUE THREAD

**Issue by bestouff** [helix-editor/helix#1177] opened 2021-11-26 15:08 UTC
I'd love to use the status bar for many informations, e.g.:
![image](https://user-images.githubusercontent.com/1163188/143600098-852c1cdd-0ff8-41df-96c2-db7db744758a.png)
Here we see the git branch, file name, modification status, git lines added/changed/removed, LSP errors/warnings, in-tree indicator, LSP server and lang, and "scrollbar" position.  
As showed here it uses nerd fonts, so that probably requires a config item to degrade from nerd font to plain unicode.

**Comment by NNBnh** [comment] 2021-11-26 16:03
Cool idea, but this might be/somewhat a duplicate of #708.

**Closed** 2021-11-26 16:55 UTC
Labels: C-enhancement

**Comment by bestouff** [comment] 2021-11-26 20:35
Sorry for the wasted time, I used the wrong terms when searching for similar issues.
