### ISSUE TITLE
comment mode

### ISSUE THREAD

**Issue by llogiq** [helix-editor/helix#7284] opened 2023-06-07 22:12 UTC
In VSCode, when I type "enter" in line comments, it extends the comment automatically, e.g.

Before
```rust
/// something something| (<- cursor is here)
```
After pressing the *enter* key
```rust
/// something something
/// | (<- cursor is here)
```

Unfortunately, helix doesn't seem to do that yet.

**Comment by the-mikedavis** [comment] 2023-06-07 22:13
Duplicate of https://github.com/helix-editor/helix/issues/1730

**Closed by the-mikedavis** 2023-06-07 22:13 UTC
Labels: C-enhancement

**Comment by llogiq** [comment] 2023-06-08 06:15
Oops, I somehow missed that, even with issue search for comment/comments. Sorry. I blame GitHub search.
