### ISSUE TITLE
Hover floating terminal

### ISSUE THREAD

**Issue by seongs1024** [helix-editor/helix#3155] opened 2022-07-22 17:27 UTC
## Background to request the feature

When i wrote the `rust` code below by `helix` and excecuted `:run-shell-command cargo run` 

```rust
use std::thread::sleep;
use std::time::Duration;

const CLEAR_TERMINAL: &str = "\x1B[2J\x1B[1;1H";

fn main() {
    let nums = (0..5).into_iter();
    nums.for_each(|n| {
        let progress = "*".repeat(n);
        println!("{}{}", CLEAR_TERMINAL, progress);
        sleep(Duration::from_secs(1));
    });
}
```

The result was that whole aggregated lines appeared after all the process had been done.

![image](https://user-images.githubusercontent.com/56729421/180492290-5b58d8df-e6b2-4c3f-9d53-5a61dccc221f.png)

But actually what i expected was that, every second, the terminal cleared and the `*` was increasing up to `****`.

The `:run-shell-command` is inconvenient in that:
   - it should wait until the command done
   - the output might be able to be different
   - if the command failed, the only `Command failed` phrase shows up at the bottom so cannot know what went wrong with it.

## Request 

Popup terminal like [`vim-floaterm`](https://github.com/voldikss/vim-floaterm) plugin

**Comment by sudormrfbin** [comment] 2022-07-22 17:30
Duplicate of https://github.com/helix-editor/helix/issues/1976

**Closed by sudormrfbin** 2022-07-22 17:30 UTC
Labels: C-enhancement
