### ISSUE TITLE
feature: Cursor style does not change when switching input modes

### ISSUE THREAD

**Issue by zX3no** [helix-editor/helix#785] opened 2021-09-25 03:09 UTC
In other editors the cursor changes from a block to a line when swapping to insert mode. 
Neovim for example: ![](https://cdn.discordapp.com/attachments/542248938015555604/891158857840214037/cursor.gif)
It's a nice feature and would make the change a little clearer.

**Comment by archseer** [comment] 2021-09-25 03:48
Duplicate of #323

**Closed by archseer** 2021-09-25 03:48 UTC
