### ISSUE TITLE
"Slow" navigation in `insert` mode -> completions that mangle items

### ISSUE THREAD

**Issue by NukeManDan** [helix-editor/helix#8264] opened 2023-09-12 18:21 UTC
### Summary

Related to #8263 , when I am navigating with arrow keys in insert mode "slowly" enough for the lsp to suggest a term for where the cursor is, the lsp result is injected where I _intended_ to just keep navigating.

This is _a massive pain_ as I am in insert mode and working, with this unwanted junk injected... and now I cannot undo _only_ that junk, but the entire insert :face_exhaling: - so I have to manually delete and replace the item. Big waste of time.

### Reproduction Steps

1. enter `insert` mode
2. "slowly" move up/down lines with a cursor inside some item
3. LSP autocomplete injects and cycles options, where you meant to move up/down a line.
4. you cannot `u` in normal mode to undo just that injection, but the whole insert.
5. Manually edit the injected junk to get back the original item

  

### Platform

Linux

### Terminal Emulator

wezterm 20230712-072601-f4abf8fd

### Helix Version

helix 23.05 (7f5940be)

**Comment by pascalkuthe** [comment] 2023-09-12 18:23
Helix is a modal editor. You are not supposed to move in insert mode. Normal mode is intended for movement.


Duplicate of #2027

**Closed by pascalkuthe** 2023-09-12 18:23 UTC
Labels: C-bug
