### ISSUE TITLE
Support number mapping

### ISSUE THREAD

**Issue by abiriadev** [helix-editor/helix#8796] opened 2023-11-12 23:41 UTC
## The problem

In Vim, I used to map `8` and `9`(which are too big numbers to repeat a single command in 99% of cases) to `10j` and `10k`, respectively, to quickly move the cursor.

## What I tried

```toml
[keys.normal]
"8" = [
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
]
"9" = [
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
]
```

## Expected result

It should work like Vim. 
Or at least, it should show a warning message that it won't support number mapping.

## Actual result

The editor starts without any error message, and the mappings are completely ignored.

Do you have any plans to support this feature? (I know this is not a common use case)

Regards.

**Comment by pascalkuthe** [comment] 2023-11-13 12:45
duplicate of #8113

Generally this seems really niche to me (why not just type 10j/10k) and don't really have an interest in this. If somebody implements a fix that does not regress any existing functionality and is small/easy to review and well implemented I wouldn't be opposed

**Closed by pascalkuthe** 2023-11-13 12:45 UTC
Labels: C-enhancement
