### ISSUE TITLE
Search In Code Actions

### ISSUE THREAD

**Issue by John-Toohey** [helix-editor/helix#9848] opened 2024-03-11 19:03 UTC
Forgive me if this is already in Helix and I am just oblivious to it, but I believe that being able to search code actions would be helpful.  In Kakoune, with kak-lsp, when one goes to preform code actions, you get the ability to search through them.  This is greatly helpful in most circumstances, especially when there are many code actions to sift through.  Could this, perhaps, be implemented as a picker?

**Comment by kirawi** [comment] 2024-03-12 20:31
Duplicate of https://github.com/helix-editor/helix/issues/3502

**Closed by kirawi** 2024-03-12 20:31 UTC
Labels: C-enhancement
