### ISSUE TITLE
Signature help gets stuck

### ISSUE THREAD

**Issue by theli-ua** [helix-editor/helix#3112] opened 2022-07-19 20:14 UTC
### Summary

Occasionally signature help gets stuck without (at least I couldn't find it) ability to to hide it.
I am yet to come up with minimal reproduction example but once I find it I'll update this.

(this all not to say that signature help in general makes experience incredibly frustrating inside things as iterator::map or , say, tokio::spawn)

### Reproduction Steps

pending

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
I am unable to share full log and could not find anything relevant there
```

</details>

### Platform

Linux

### Terminal Emulator

kitty

### Helix Version

helix 22.05 (791bf7e5)

**Comment by kirawi** [comment] 2022-07-19 21:36
Does `esc` or `ctrl-c` not work to close it?

**Comment by n0s4** [comment] 2022-07-19 22:49
> Does `esc` or `ctrl-c` not work to close it?

For me `C-c` works to close it but not `esc`.

I also managed to reproduce it by creating a macro that just enters and then exits insert mode, then running it with the cursor on a function parameter.

**Comment by theli-ua** [comment] 2022-07-20 21:57
`C-c` works indeed

**Comment by the-mikedavis** [comment] 2022-09-29 23:13
When I see this get stuck, I think it's because the signature help reply arrives when we're in normal mode. I see this getting stuck much more often with a slow language server (erlang_ls) rather than a fast language server (rust-analyzer). When it arrives in insert mode and we switch to normal mode, the popup is closed by this block: https://github.com/helix-editor/helix/blob/8a7a6e4cff1db3ef65a2c20e0e90c60b44516e27/helix-term/src/ui/editor.rs#L857-L862

I think it would be a good improvement to discard the signature help reply when the editor is in normal mode.

**Closed** 2022-10-28 23:20 UTC
Labels: C-bug, A-helix-term
