### ISSUE TITLE
Set file type

### ISSUE THREAD

**Issue by volucris1** [helix-editor/helix#2265] opened 2022-04-25 12:25 UTC
How can i change file type when i editing file. Just like vim:
```vim
:setf file_type
```

**Comment by the-mikedavis** [comment] 2022-04-25 12:33
Duplicate of https://github.com/helix-editor/helix/issues/1794

**Comment by the-mikedavis** [comment] 2022-04-25 12:34
Implemented in https://github.com/helix-editor/helix/pull/1866

This was merged after the 22.03 release though.

**Closed by the-mikedavis** 2022-04-25 12:34 UTC
Labels: C-enhancement
