### ISSUE TITLE
helix version of prettify mode from emacs or other equivalent functionallity

### ISSUE THREAD

**Issue by SomeGuyNamedMy** [helix-editor/helix#7299] opened 2023-06-09 13:33 UTC
Emacs has a mode in which you can replace certain characters when viewing a file with unicode characters but keeps the internal representation as a plain text file with no unicode.
for example 
forall -> ∀
exists -> ∃

**Comment by pascalkuthe** [comment] 2023-06-09 13:40
Duplicate of #5798

**Closed by pascalkuthe** 2023-06-09 13:40 UTC
Labels: C-enhancement
