### ISSUE TITLE
Cursor shape is not correctly restored after exit

### ISSUE THREAD

**Issue by chermnyx** [helix-editor/helix#2946] opened 2022-07-02 20:03 UTC
### Summary

The cursor shape on helix exit is always block, while terminal defaults may be different 

### Reproduction Steps

1. Configure terminal emulator (konsole in my case) to use bar cursor shape
![Screenshot_20220703_005758](https://user-images.githubusercontent.com/27727194/177014650-46a30438-5e12-41f9-999d-a89cee44a759.png)
![Screenshot_20220703_010306](https://user-images.githubusercontent.com/27727194/177014763-15c151a6-f19b-4a96-aac3-478c9743a2f0.png)

2. Open helix and close it

3. Cursor shape changes
![Screenshot_20220703_005846](https://user-images.githubusercontent.com/27727194/177014669-c80b4631-ac12-447b-8a91-0b720d3dc552.png)

Similar to https://github.com/neovim/neovim/issues/4396

### Platform

Linux 

### Terminal Emulator

konsole 22.04.2

### Helix Version

helix 22.05

**Comment by the-mikedavis** [comment] 2022-07-02 20:16
Duplicate of https://github.com/helix-editor/helix/issues/2684

**Closed by the-mikedavis** 2022-07-02 20:16 UTC
Labels: C-bug
