### ISSUE TITLE
Vim compatibility mode

### ISSUE THREAD

**Issue by certik** [helix-editor/helix#5310] opened 2022-12-27 01:41 UTC
I like the idea of Helix, all the six Pros from https://helix-editor.com/. But I want to use it using Vim bindings, since I am used to them after 20+ years of using Vim / Neovim. The first FAQ says "It's a joke. If Neovim is the modern Vim, then Helix is post-modern." Except that my workflow (I only use around 20 commands in Vim) that works in Vim works in Neovim. But completely breaks in Helix. Here is my config for Helix that introduces Vim like bindings:

https://github.com/certik/dotfiles/blob/182ce03774b31347e6430ab9f661cfa12b22e76b/.config/helix/config.toml

But unfortunately the commands that they map to are not equivalent to Vim/Neovim, so they behave slightly differently.

For example, in Vim, `V` selects a full line, then I can use `jk` to select a few lines, then I do "y" to yank. Then I go where I want to paste it and press `p` and it pastes it below the current line. In Helix, it pastes it in the middle of the current line, thus breaking the current line in two, one before the selection, one after the selection. There are many of such slight incompatibilities that every time I try Helix, I just come back to Neovim or Vim.

Question 1: Is Helix open to allow Vim compatibility?

Question 2: If yes, how should it be designed? One idea is to introduce Vim compatible commands, that the user can use for mapping; then I could update my config to use those commands and I would a Vim compatible mode that I can use, while other Helix users who prefer the default behavior would not see any breakage.

If the answer is no, there is some fundamental design reason that would not make it practical to support Vim compatibility mode for the few basic commands that I use, then I recommend to document it clearly in the FAQ, that Helix is inspired by Vim, but you will have to learn a new editor, there will be slight differences in behavior that cannot be emulated. Given the prevalence of Vim, and given how close Helix is to fully work for me, I am hoping that one could achieve full compatibility for the small subset that I use. If so, I am happy to report all the differences that I found and we can look at each of them and see how to make it compatible.

**Comment by kirawi** [comment] 2022-12-27 03:07
Duplicate of https://github.com/helix-editor/helix/issues/4419

**Closed by kirawi** 2022-12-27 03:07 UTC
Labels: C-enhancement

**Comment by certik** [comment] 2022-12-27 03:38
Ok, thanks for the clarification. You should document that clearly on the webpage as well.
