### ISSUE TITLE
freeze with md file

### ISSUE THREAD

**Issue by masriomarm** [helix-editor/helix#9804] opened 2024-03-04 13:20 UTC
### Summary

Editor freeze with this code snippet in md files

### Reproduction Steps

 

I tried this:

1. `hx temp.md`
2. paste this snippet from clipboard, if copied surrounded with \``` it works normally.
```
<Structure>
  <Array>
    <UInt8 Value="0" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="2" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="4" />
    <UInt8 Value="4" />
    <UInt8 Value="4" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="8" />
    <UInt8 Value="0" />
    <UInt8 Value="8" />
    <UInt8 Value="8" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="0" />
    <UInt8 Value="8" />
    <UInt8 Value="0" />
  </Array>
</Structure>
```
Assume cursor position at the start of line with `=` sign. moving cursor left towards `=`, editor freezes when reaching `=` , can't open logs or any other command, total freeze. has to close terminal window containing helix.

Issue seems with the left double quote, reaching this quote from left or right seems to trigger the freeze.
I expected this to happen:
cursor move between chars normally
Instead, this happened:
editor freeze when reaching the first left double quotes `"`.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows

### Terminal Emulator

Windows terminal , alacritty 0.13.0 (78fa4d6), wezterm 20240203-110809-5046fc22

### Installation Method

choco install helix

### Helix Version

helix 23.10 (f6021dd0)

**Comment by kirawi** [comment] 2024-03-04 13:27
Duplicate of https://github.com/helix-editor/helix/issues/8709

**Closed by kirawi** 2024-03-04 13:27 UTC
Labels: C-bug
