### ISSUE TITLE
Comments in multi language files

### ISSUE THREAD

**Issue by DoctorRyner** [helix-editor/helix#9917] opened 2024-03-18 17:07 UTC
In such files as svelte we need to properly handle comments, e.g. :toggle_comments should work properly in proper places.

For Svelte when I put a comment it display syntax errors

```svelte
<script>
  // ..
</script>

<!-- ... -->

<style>
  // ...
</style>
```

**Comment by the-mikedavis** [comment] 2024-03-18 17:13
Duplicate of https://github.com/helix-editor/helix/issues/7364

**Closed by the-mikedavis** 2024-03-18 17:13 UTC
Labels: C-enhancement
