### ISSUE TITLE
Feature Request: magit/fugitive like functionality

### ISSUE THREAD

**Issue by heliostatic** [helix-editor/helix#1051] opened 2021-11-10 01:58 UTC
I'd love integrated git tooling. 

It could be something like https://github.com/magit/magit or https://github.com/tpope/vim-fugitive, or a wrapper around gitui/lazygit like https://github.com/kdheepak/lazygit.nvim. 

Today, I just have https://github.com/extrawurst/gitui/ in another tmux pane, which is fine, but having some amount of this functionality built-in would be great.

**Comment by kirawi** [comment] 2021-11-10 02:00
Duplicate of #227

**Closed by kirawi** 2021-11-10 02:00 UTC
Labels: C-enhancement
