### ISSUE TITLE
Helix freezes in Windows 11 editing Markdown text

### ISSUE THREAD

**Issue by lskbr** [helix-editor/helix#11782] opened 2024-09-26 15:54 UTC
### Summary

Helix freezes when I edit a markdown text file in Windows 11 when I hit the source code formatted part.

### Reproduction Steps

[batalhas.md](https://github.com/user-attachments/files/17151806/batalhas.md)
hx batalhas.md

<img width="639" alt="Capture d'écran 2024-09-26 173444" src="https://github.com/user-attachments/assets/9ff74f20-32b3-4bf4-9b62-cf92b9eb034d">

Steps to reproduce:
- Go to lines 288, 286 and start adding \ before the "
- Do the same on lines 282, 283
- The editor freezes, I have to quit with a break.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-09-26T17:36:36.079 helix_lsp::transport [ERROR] marksman err <- "[17:36:36 INF] <LSP Entry> Starting Marksman LSP server: {}\r\n"
2024-09-26T17:36:36.510 helix_lsp::transport [ERROR] marksman err <- "[17:36:36 WRN] <ServerUtil> Workspace folder is bogus: {\"root\": \"RootPath (AbsPath \\\"c:\\\\Users\\\\User\\\")\"}\r\n"
2024-09-26T17:36:39.432 helix_lsp::transport [ERROR] err: <- Other(failed to send a message to server

Caused by:
    channel closed)
2024-09-26T17:36:39.432 helix_lsp::transport [ERROR] marksman err: <- StreamClosed
```

</details>

### Platform

Windows 11 [version 10.0.22631.4169]

### Terminal Emulator

Windows Terminal 1.21.2361.0

### Installation Method

winget

### Helix Version

helix 23.10 (f6021dd0)

**Comment by the-mikedavis** [comment] 2024-09-26 16:00
This was a bug upstream in tree-sitter that was fixed a while ago. We updated to a version of tree-sitter with the fix after the 23.10 release. Upgrading to 24.03 or 24.07 should fix this.

Duplicate of https://github.com/helix-editor/helix/issues/7689

**Closed by the-mikedavis** 2024-09-26 16:00 UTC
Labels: C-bug
