### ISSUE TITLE
Duplicating Cursors behaved wierd on blank lines

### ISSUE THREAD

**Issue by glyh** [helix-editor/helix#1413] opened 2021-12-31 03:51 UTC
### Reproduction steps

1. Create several empty lines.
2. Duplicate the cursor from some empty line.
3. Two cursor will appear, but they are seperated by one empty line. 
See this video:

[![asciicast](https://asciinema.org/a/yfjbcwWkL2wi4uMGwFybd3OOm.svg)](https://asciinema.org/a/yfjbcwWkL2wi4uMGwFybd3OOm)

### Environment

- Platform: `Linux arch 5.15.11-arch2-1 #1 SMP PREEMPT Wed, 22 Dec 2021 09:23:54 +0000 x86_64 GNU/Linux`
- Helix version: `helix v0.5.0-321-g8fda87af`

helix.log is empty.

**Comment by Omnikar** [comment] 2021-12-31 04:14
Duplicate of #1367.

**Closed** 2021-12-31 04:39 UTC
Labels: C-bug, A-helix-term
