### ISSUE TITLE
Extend/Select mode: Selecting next/prev treesitter sibling wipes current selection

### ISSUE THREAD

**Issue by LukeHalasy** [helix-editor/helix#8122] opened 2023-08-31 00:15 UTC
When in extend/select mode, the `select_prev_sibling`/`select_next_sibling` commands wipe the current selection.

https://github.com/helix-editor/helix/assets/13665101/ae775d36-da6f-43c8-9f87-8040f8c454ca

I would like to tackle this, but before I do I just want confirmation that this is an "issue" and not the desired behavior.

**Comment by the-mikedavis** [comment] 2023-08-31 15:54
Duplicate of https://github.com/helix-editor/helix/issues/1999

**Closed by the-mikedavis** 2023-08-31 15:54 UTC
