### ISSUE TITLE
Can't add auto-pairs for /* and */

### ISSUE THREAD

**Issue by sudokit** [helix-editor/helix#6443] opened 2023-03-25 21:50 UTC
trying to add auto-pair for /* and */ just results in an error:
the doc used: [doc](https://docs.helix-editor.com/configuration.html#editorauto-pairs-section)

config:
```
[editor.auto-pairs]
'/*' = '*/'
```

error:
```
Bad config: TOML parse error at line 12, column 1
   |
12 | [editor.auto-pairs]
   | ^^^^^^^^^^^^^^^^^^^
data did not match any variant of untagged enum AutoPairConfig

Press <ENTER> to continue with default config
```

**Comment by gabydd** [comment] 2023-03-25 21:55
Duplicate of https://github.com/helix-editor/helix/issues/4035 (as of now the editor doesn't support multi character auto pairs)

**Closed** 2023-03-25 23:37 UTC
