### ISSUE TITLE
Open File Picker takes a very long time in large repos 

### ISSUE THREAD

**Issue by trimonovds** [helix-editor/helix#5324] opened 2022-12-28 11:23 UTC
`Open file picker` or `Open file picker in cwd` commands takes several seconds to complete (from key press to picker become visible) when working in large repos (like https://github.com/chromium/chromium). In my current work repo it takes about 10 sec. `Search files by name` in VSCode (Cmd+P) works pretty fast at the same time. It would be great to speed up 'open file picker' scenario in helix, since it is the only way to search for files and poor experience makes it impossible to use helix on every day basis.
P.S. 10 sec mentioned above is after copy-pasting VSCode "files.exclude" used in our repo to `.ignore` file

**Comment by the-mikedavis** [comment] 2022-12-28 13:50
Duplicate of https://github.com/helix-editor/helix/issues/1707

**Closed by the-mikedavis** 2022-12-28 13:50 UTC
Labels: C-enhancement
