### ISSUE TITLE
Feature Request: Builtin terminal

### ISSUE THREAD

**Issue by CaptainDrewBoy** [helix-editor/helix#2313] opened 2022-04-28 20:22 UTC
#### Describe your feature request

In vim (post version 8) and neovim you are able to pull up a terminal by using `:term`. This is most useful, especially because it can be used in a smaller split.
This alone would be amazing, but it would be doubly great if some functionality from neomux (https://github.com/nikvdp/neomux) was included, such as the `vw` and `vwp` commands that allow the terminal and editor window to interact.

**Comment by the-mikedavis** [comment] 2022-04-28 20:26
Duplicate of https://github.com/helix-editor/helix/issues/1976

**Closed by the-mikedavis** 2022-04-28 20:26 UTC
Labels: C-enhancement

**Comment by CaptainDrewBoy** [comment] 2022-04-28 20:33
Darn it, I ran a search! Must've somehow missed that...

**Comment by the-mikedavis** [comment] 2022-04-28 20:38
No worries, it took me a few tries to find it even though I knew which one I was looking for 😅

Strange that "builtin terminal" doesn't bring it up 🤔 https://github.com/helix-editor/helix/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+builtin+terminal
