### ISSUE TITLE
Placement of Beam Cursor should be offset by 1 when more than 1 characters are selected

### ISSUE THREAD

**Issue by aspizu** [helix-editor/helix#5215] opened 2022-12-19 16:48 UTC
1. The cell under the cursor is not highlighted when using a beam cursor
2. the placement of the beam cursor should be offset by 1 cell when more than 1 characters are selected

**Comment by the-mikedavis** [comment] 2022-12-20 00:16
Duplicate of https://github.com/helix-editor/helix/issues/1568

**Closed by the-mikedavis** 2022-12-20 00:16 UTC

**Comment by aspizu** [comment] 2022-12-20 09:13
what about point 2?

**Comment by the-mikedavis** [comment] 2022-12-20 13:54
Is that not covered by #1568? I though it was covered by the "1 character wider" part. Could you explain more what you mean?

**Comment by aspizu** [comment] 2022-12-20 17:11
1. Cursor placed at the beginning of selection
2. Cursor placed at the end of selection (What it should look like?)
3. Cursor placed at the beginning of the last cell of selection (What it looks like currently)
![demonstration image](https://cdn.discordapp.com/attachments/972556399928299661/1054807403461357630/image.png)

Even though 2 looks correct, its actually incorrect because the cursor itself is a selection.

**Comment by the-mikedavis** [comment] 2022-12-20 23:31
Oh I see. I think that is https://github.com/helix-editor/helix/issues/1977, right?

**Comment by aspizu** [comment] 2022-12-21 14:35
sure
