### ISSUE TITLE
Autocompletion results in duplicated letters

### ISSUE THREAD

**Issue by arumugamramaswamy** [helix-editor/helix#5313] opened 2022-12-27 05:23 UTC
### Summary

When using autocompletion with python, sometimes I experience duplicated letters. This usually occurs when the autocompletion window opens up following which I type a few letters and then tab to autocomplete.

### Autocompletion Target
`self._namespace`

### Autocmpletion Result
`self.__namespace`

### Reproduction Steps

 
[bug.cast.tar.gz](https://github.com/helix-editor/helix/files/10306093/bug.cast.tar.gz)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-12-27T05:10:10.081 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 11, character: 0 }, end: Position { line: 11, character: 100 } }, severity: Some(Warning), code: Some(String("E901")), code_description: None, source: Some("pycodestyle"), message: "E901 TokenError: EOF in multi-line statement", related_information: None, tags: None, data: None }
2022-12-27T05:10:18.141 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 12, character: 27 }, end: Position { line: 12, character: 54 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:10:29.464 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 15, character: 27 }, end: Position { line: 15, character: 54 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:10:52.657 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 17, character: 26 }, end: Position { line: 17, character: 52 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:13:32.140 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 0, character: 8 }, end: Position { line: 0, character: 16 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:13:37.286 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 2, character: 13 }, end: Position { line: 2, character: 26 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:13:38.109 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 2, character: 11 }, end: Position { line: 2, character: 22 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:13:40.008 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 4, character: 9 }, end: Position { line: 4, character: 19 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:13:41.792 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 4, character: 17 }, end: Position { line: 4, character: 34 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:13:43.432 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 4, character: 23 }, end: Position { line: 4, character: 46 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:13:45.686 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 6, character: 9 }, end: Position { line: 6, character: 18 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "unexpected EOF while parsing", related_information: None, tags: None, data: None }
2022-12-27T05:13:49.286 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 6, character: 14 }, end: Position { line: 6, character: 28 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:13:56.921 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 9, character: 14 }, end: Position { line: 9, character: 28 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:13:58.422 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 9, character: 14 }, end: Position { line: 9, character: 28 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:14:17.797 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 14, character: 27 }, end: Position { line: 14, character: 54 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:14:18.945 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 14, character: 27 }, end: Position { line: 14, character: 54 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:14:19.889 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 14, character: 27 }, end: Position { line: 14, character: 54 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:14:25.682 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 16, character: 27 }, end: Position { line: 16, character: 54 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:14:39.801 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 21, character: 27 }, end: Position { line: 21, character: 54 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
2022-12-27T05:14:40.611 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 21, character: 28 }, end: Position { line: 21, character: 56 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "invalid syntax", related_information: None, tags: None, data: None }
```

</details>

### Platform

Linux

### Terminal Emulator

xterm-256color

### Helix Version

22.12-46-gba3c24aa

**Comment by kirawi** [comment] 2022-12-27 13:48
Either duplicate of https://github.com/helix-editor/helix/issues/4131 or https://github.com/helix-editor/helix/issues/4851

**Closed by kirawi** 2022-12-27 13:48 UTC
Labels: C-bug
