### ISSUE TITLE
helix panics when the current directory disappears

### ISSUE THREAD

**Issue by smason** [helix-editor/helix#2917] opened 2022-06-29 15:03 UTC
### Summary

helix panics losing all work if the current working directory disappears

I noticed this because the `sshfs` mount I was using happened to have a temporary network issue which caused helix to panic and loose the changes I was working on

### Reproduction Steps

 

the following one-liner reproduces this:

```sh
mkdir tmp ; ( sleep 1 ; rmdir tmp ) & env -C tmp hx test.txt
```

then any action in Helix after that second results in a panic.

it appears I need to have a file open and not just a scratch buffer

### Helix log

nothing is logged to `~/.cache/helix/helix.log`, but the following is printed:

```none
thread 'main' panicked at 'couldn't determine current directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', helix-core/src/path.rs:86:45
```

### Platform

Linux

### Terminal Emulator

foot

### Helix Version

22.05-161-g15ac1142

**Comment by the-mikedavis** [comment] 2022-06-29 15:04
Duplicate of https://github.com/helix-editor/helix/issues/2527

**Closed as completed by the-mikedavis** 2022-06-29 15:04 UTC
Labels: C-bug, R-duplicate
