### ISSUE TITLE
Allow C-u / C-d to travel to extents 

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4491] opened 2022-10-27 21:10 UTC
In Helix if you page up/down you cannot navigate to the first or last line of the file

In Neovim you can

https://user-images.githubusercontent.com/666539/198398499-4dd8dc17-e11c-438f-af39-28ce535a5b87.mov

**Comment by Manosmer** [comment] 2022-11-04 11:24
On it!

**Comment by xJonathanLEI** [comment] 2022-11-06 07:27
Honestly I've always wanted to submit this issue but wasn't sure if this is by design (i.e. moving view instead of cursor). I frequently find myself going half page down (`C-d`), centering view (`zz`), and everything stays exactly the same as before, when I was actually intending to move my cursor by half page.

Maybe @archseer can kindly shed some light on this? Thanks!

**Comment by MAST1999** [comment] 2022-12-19 16:44
I agree with this as well.

I ended up being confused for half an hour why I couldn't use the shortcut I created to move easier (I had the same shortcut in vim).

I usually set `C-d` and alike to center the view after moving to keep the cursor centered which I find helps me a lot to move after I reach near where I want.

**Comment by dv1x3r** [comment] 2022-12-19 17:09
@MAST1999 I also prefer that approach. The closest action I figured out:

```
[keys.normal]
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up", "goto_window_center"]
```

**Comment by pascalkuthe** [comment] 2024-04-04 01:59
See discussion  in PRs not going forward with this

**Closed by pascalkuthe** 2024-04-04 01:59 UTC
Labels: C-enhancement
