### ISSUE TITLE
Editor freezes when saving a html file

### ISSUE THREAD

**Issue by Overbryd** [helix-editor/helix#3805] opened 2022-09-11 15:24 UTC
### Summary

The editor freezes for a long time when saving a simple HTML file.

### Reproduction Steps

1. Install helix

```
$ brew install helix
$ helix --version
helix 22.08.1 (66276ce6)
```

2. Edit a html file

```
$ helix index.html
```

3. Write an `<h1></h1>`

4. Attempt to save the file `:x<enter>`

The editor gets stuck for >1 minute and exits, spilling some scrambled stuff onto the console.

```
editor-tests$ hx index.html 35;88;34M35;89;34M35;90;34M35;90;35M35;91;35M35;92;35M35;93;35M35;93;36M35;94;36M35;95;36M35;95;37M35;96;37M35;96;38M35;97;38M35;98;39M35;99;39M35;99;40M35;99;41M35;99;42M35;98;42M35;97;42M35;98;42M35;98;43M35;99;43M35;98;43M35;99;43M35;100;43M35;101;43M35;102;43M35;102;42M35;103;42M35;104;42M35;105;42M35;106;42M35;108;42M35;109;42M35;110;42M35;112;42M35;113;41M35;115;41M35;116;41M35;117;41M35;119;41M^C
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-09-11T17:23:12.094 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2022-09-11T17:23:33.723 helix_view::document [WARN] LSP formatting failed: request timed out
```

</details>

### Platform

macOS

### Terminal Emulator

Allacrity 0.10.1

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by Overbryd** [comment] 2022-09-11 15:42
The problem can be fixed/worked-around by disabling `auto-format` in `~/.config/helix/languages.toml`:

```
# Note: fixes https://github.com/helix-editor/helix/issues/3805
[[language]]
name = "html"
auto-format = false
```

**Comment by the-mikedavis** [comment] 2022-09-11 16:43
Duplicate of https://github.com/helix-editor/helix/issues/1639

**Closed by the-mikedavis** 2022-09-11 16:43 UTC
Labels: C-bug
