### ISSUE TITLE
Loading bar for go to definition

### ISSUE THREAD

**Issue by Vilhelm-Ian** [helix-editor/helix#8605] opened 2023-10-24 19:41 UTC
In rust functions that are defined by external crates go-to definition takes some time. During the period while it's searching for the definition nothing on the screen indicates that it's currently working

**Comment by the-mikedavis** [comment] 2023-10-24 19:56
Duplicate of https://github.com/helix-editor/helix/issues/1060

**Closed by the-mikedavis** 2023-10-24 19:56 UTC
Labels: C-enhancement
