### ISSUE TITLE
Allow to disable themes background

### ISSUE THREAD

**Issue by oworope** [helix-editor/helix#11456] opened 2024-08-09 11:20 UTC
In neovim most themes have an option to disable background color - that makes your background transparent if you set transparency in your terminal. However, I couldn't find this in Helix - using it with transparent background only possible with some `term_*` and `base16_*` themes.

My proposal is to add an option to override theme background to allow transparency

**Comment by the-mikedavis** [comment] 2024-08-09 12:33
Duplicate of https://github.com/helix-editor/helix/discussions/10223

**Closed by the-mikedavis** 2024-08-09 12:33 UTC
Labels: C-enhancement
