### ISSUE TITLE
Disappearing syntax highlighting due to scrolling

### ISSUE THREAD

**Issue by GuyKlaassen** [helix-editor/helix#5731] opened 2023-01-30 10:30 UTC
### Summary

When my Python imports get scrolled out of view, they no longer get the correct syntax highlighting when they are being used. See the base64 and requests import on uses in the screenshots below. When the import line gets scrolled out of view, the syntax highlighting changes from red to white. I've tried it with multiple themes, it happens for all of them.

![image](https://user-images.githubusercontent.com/50806487/215449937-4c8f07d7-f0a2-42ed-8c50-65fab1f714de.png)
![image](https://user-images.githubusercontent.com/50806487/215449967-ad677d68-219f-4ce7-b557-6ba873514d43.png)
![image](https://user-images.githubusercontent.com/50806487/215450001-a2418bdf-5a0e-4b0b-bb4e-c56f910f2378.png)

### Reproduction Steps

Create a new Python file, put imports at the top and use them in the script.
Scroll the import lines out of view and see the syntax highlighting disappear.

### Helix log

N/A?

### Platform

macOS

### Terminal Emulator

wezterm 20221119-145034-49b9839f

### Helix Version

helix 22.12 (96ff64a8)

**Comment by pascalkuthe** [comment] 2023-01-30 11:01
duplicate of #1151

**Closed by pascalkuthe** 2023-01-30 11:01 UTC
Labels: C-bug
