### ISSUE TITLE
No autocomplete for nested settings in get/set-option

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3181] opened 2022-07-25 09:51 UTC
### Summary

When using the `:set-option` (or `:get-option`) there is no completion for nested options, such as `search.wrap-around`

### Reproduction Steps

 

I tried this:

1. `hx`
2. `:set-option search.`

I expected this to happen:
See completions for search settings: (`wrap-around`, `smart-case`)

Instead, this happened:
No completions appear

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 22.05, also 22.05-275-gdad6d0f3

**Comment by the-mikedavis** [comment] 2022-07-26 04:13
Duplicate of https://github.com/helix-editor/helix/issues/2772

**Closed** 2022-07-26 04:13 UTC
Labels: C-bug
