### ISSUE TITLE
helix-lsp crash

### ISSUE THREAD

**Issue by clumsy** [helix-editor/helix#9182] opened 2023-12-28 16:15 UTC
### Summary

I'm trying to setup `python-lsp-server` with `python-lsp-ruff` but LSP won't start or crashes with `"Language server exited"` when I try to `:lsp-restart`:

`RUST_BACKTRACE=full hx -vvv`
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Other(channel closed)', helix-lsp/src/lib.rs:921:14
stack backtrace:
   0:        0x10cbc3d1d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he69c0e17cb41f255
   1:        0x10c10332b - core::fmt::write::h66293df4c7dd941a
   2:        0x10cb9fc26 - std::io::Write::write_fmt::h2f5a7ea5f48a0b56
   3:        0x10cbc3b00 - std::sys_common::backtrace::print::h71fd332624ce1826
   4:        0x10cbc4fa5 - std::panicking::default_hook::{{closure}}::ha2a0e70fb3678142
   5:        0x10cbc4d49 - std::panicking::default_hook::hb166cd42dec7ff92
   6:        0x10cbc5668 - std::panicking::rust_panic_with_hook::h2b924837648ff0c0
   7:        0x10cbc5434 - std::panicking::begin_panic_handler::{{closure}}::h04e24a68d30d9f5c
   8:        0x10cbc3f39 - std::sys_common::backtrace::__rust_end_short_backtrace::hd45b5152c8265971
   9:        0x10cbc51d2 - _rust_begin_unwind
  10:        0x10cca4f53 - core::panicking::panic_fmt::h9302663e63786640
  11:        0x10cca4f15 - core::result::unwrap_failed::h090ca2893fd37497
  12:        0x10c4667ad - helix_lsp::start_client::{{closure}}::h22c988bc6bb7b64a
  13:        0x10c45b022 - tokio::runtime::task::core::Core<T,S>::poll::h24efe92de45eb54d
  14:        0x10c3e342e - tokio::runtime::task::harness::Harness<T,S>::poll::h78d83569317f5666
  15:        0x10cbf8e20 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h99735e2d2e717587
  16:        0x10cbf84a9 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hd44c9d35851a1d00
  17:        0x10cc16cd9 - tokio::runtime::context::scoped::Scoped<T>::set::h2fad565c96a8d0a5
  18:        0x10cbfebf1 - tokio::runtime::context::runtime::enter_runtime::hadfc6426ce337d8b
  19:        0x10cbf7dcb - tokio::runtime::scheduler::multi_thread::worker::run::h73de726241d08f67
  20:        0x10cc036cd - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf78e3f1057d3e90f
  21:        0x10cbf2e67 - tokio::runtime::task::harness::Harness<T,S>::poll::h1f7ac6e67baa9b4e
  22:        0x10cc00a08 - tokio::runtime::blocking::pool::Inner::run::h3d98b400dbc5801b
  23:        0x10cc17de7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h93988f6420da4eb6
  24:        0x10cc0552d - core::ops::function::FnOnce::call_once{{vtable.shim}}::h01907e9b95363c6c
  25:        0x10cbdc769 - std::sys::unix::thread::Thread::new::thread_start::h31e0aaf433594e70
  26:     0x7ff801c841d3 - __pthread_start
```

I tried searching for ways to troubleshoot this but didn't find any information.

E.g. I'm curious why I don't see [this error message](https://github.com/helix-editor/helix/blob/master/helix-lsp/src/lib.rs#L913)

### Reproduction Steps

`pip list | grep lsp`:
```
python-lsp-black                    1.0.0
python-lsp-jsonrpc                  1.1.2
python-lsp-ruff                     2.0.1
python-lsp-server                   1.9.0
```

`pip list | grep ruff`:
```
python-lsp-ruff                     2.0.1
ruff                                0.1.9
```

`languages.toml`:
```
[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
language-servers = ["pylsp"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}

black = {enabled = false, line_length = 120}
pylsp-mypy = {enabled = false}
flake8 = {enabled = false}
isort = {enabled = false, profile = "black"}
ruff = {enabled = false, ignore = ["F401"], lineLength = 120}
```

I tried this:

`/tmp/test.py`:
```
print("test")
```

1. `RUST_BACKTRACE=full hx -vvv /tmp/test.py`
2. `:lsp-restart`

I expected this to happen:
pylsp to work

Instead, this happened:
"Language server stopped"

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-12-28T11:21:36.367 helix_view::clipboard [DEBUG] Using pbcopy+pbpaste to interact with the system clipboard
2023-12-28T11:21:36.404 helix_vcs [INFO] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/private/tmp",
        },
    ),
}
2023-12-28T11:21:36.404 helix_vcs [INFO] failed to open diff base for /private/tmp/test.py
2023-12-28T11:21:36.404 helix_vcs [INFO] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/private/tmp",
        },
    ),
}
2023-12-28T11:21:36.404 helix_vcs [INFO] failed to obtain current head name for /private/tmp/test.py
2023-12-28T11:21:36.407 mio::poll [TRACE] registering event source with poller: token=Token(140159240651008), interests=READABLE | WRITABLE
2023-12-28T11:21:36.407 mio::poll [TRACE] registering event source with poller: token=Token(140159240651392), interests=READABLE | WRITABLE
2023-12-28T11:21:36.407 mio::poll [TRACE] registering event source with poller: token=Token(140159240651776), interests=READABLE | WRITABLE
2023-12-28T11:21:36.408 helix_view::editor [DEBUG] editor status: Loaded 1 file.
2023-12-28T11:21:36.408 helix_lsp::client [INFO] Using custom LSP config: {"pylsp":{"plugins":{"autopep8":{"enabled":false},"black":{"enabled":false,"line_length":120},"flake8":{"enabled":false},"isort":{"enabled":false,"profile":"black"},"mccabe":{"enabled":false},"pycodestyle":{"enabled":false},"pyflakes":{"enabled":false},"pylint":{"enabled":false},"pylsp-mypy":{"enabled":false},"ruff":{"enabled":false,"ignore":["F401"],"lineLength":120},"yapf":{"enabled":false}}}}
2023-12-28T11:21:36.408 mio::poll [TRACE] registering event source with poller: token=Token(140159151545856), interests=READABLE | WRITABLE
2023-12-28T11:21:36.408 mio::poll [TRACE] registering event source with poller: token=Token(140159151546112), interests=READABLE | WRITABLE
2023-12-28T11:21:36.408 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"positionEncodings":["utf-8","utf-32","utf-16"]},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"isPreferredSupport":true,"resolveSupport":{"properties":["edit","command"]}},"completion":{"completionItem":{"deprecatedSupport":true,"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"inlayHint":{"dynamicRegistration":false},"publishDiagnostics":{"versionSupport":true},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":true},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":false},"executeCommand":{"dynamicRegistration":false},"inlayHint":{"refreshSupport":false},"symbol":{"dynamicRegistration":false},"workspaceEdit":{"documentChanges":true,"failureHandling":"abort","normalizesLineEndings":false,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"helix","version":"23.10 (f6021dd0)"},"initializationOptions":{"pylsp":{"plugins":{"autopep8":{"enabled":false},"black":{"enabled":false,"line_length":120},"flake8":{"enabled":false},"isort":{"enabled":false,"profile":"black"},"mccabe":{"enabled":false},"pycodestyle":{"enabled":false},"pyflakes":{"enabled":false},"pylint":{"enabled":false},"pylsp-mypy":{"enabled":false},"ruff":{"enabled":false,"ignore":["F401"],"lineLength":120},"yapf":{"enabled":false}}}},"processId":39018,"rootPath":"/private/tmp","rootUri":null,"workspaceFolders":[]},"id":0}
2023-12-28T11:21:36.408 helix_tui::backend::crossterm [DEBUG] The keyboard enhancement protocol is not supported in this terminal (checked in 143.575µs)
2023-12-28T11:21:36.619 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-28T11:21:37.922 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-28T11:21:39.355 helix_lsp::transport [INFO] pylsp <- {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"documentFormattingProvider":true,"documentHighlightProvider":true,"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"definitionProvider":true,"executeCommandProvider":{"commands":[]},"hoverProvider":true,"referencesProvider":true,"renameProvider":true,"foldingRangeProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","="]},"textDocumentSync":{"change":2,"save":{"includeText":true},"openClose":true},"notebookDocumentSync":{"notebookSelector":[{"cells":[{"language":"python"}]}]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"experimental":{}},"serverInfo":{"name":"pylsp","version":"1.9.0"}}}
2023-12-28T11:21:39.355 helix_lsp::transport [INFO] pylsp <- {"capabilities":{"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":[]},"experimental":{},"foldingRangeProvider":true,"hoverProvider":true,"notebookDocumentSync":{"notebookSelector":[{"cells":[{"language":"python"}]}]},"referencesProvider":true,"renameProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","="]},"textDocumentSync":{"change":2,"openClose":true,"save":{"includeText":true}},"workspace":{"workspaceFolders":{"changeNotifications":true,"supported":true}}},"serverInfo":{"name":"pylsp","version":"1.9.0"}}
2023-12-28T11:21:39.355 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"initialized","params":{}}
2023-12-28T11:21:39.355 helix_term::application [DEBUG] received editor event: LanguageServerMessage((0, Notification(Notification { jsonrpc: None, method: "initialized", params: None })))
2023-12-28T11:21:39.356 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"python","text":"print(\"TEST\")\n","uri":"file:///private/tmp/test.py","version":0}}}
2023-12-28T11:21:39.356 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"pylsp":{"plugins":{"autopep8":{"enabled":false},"black":{"enabled":false,"line_length":120},"flake8":{"enabled":false},"isort":{"enabled":false,"profile":"black"},"mccabe":{"enabled":false},"pycodestyle":{"enabled":false},"pyflakes":{"enabled":false},"pylint":{"enabled":false},"pylsp-mypy":{"enabled":false},"ruff":{"enabled":false,"ignore":["F401"],"lineLength":120},"yapf":{"enabled":false}}}}}}
2023-12-28T11:21:39.389 helix_term::application [DEBUG] received editor event: Redraw
2023-12-28T11:21:39.862 helix_lsp::transport [INFO] pylsp <- {"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/private\/tmp\/test.py","diagnostics":[]}}
2023-12-28T11:21:39.863 helix_term::application [DEBUG] received editor event: LanguageServerMessage((0, Notification(Notification { jsonrpc: Some(V2), method: "textDocument/publishDiagnostics", params: Map({"diagnostics": Array [], "uri": String("file:///private/tmp/test.py")}) })))
2023-12-28T11:21:39.896 helix_term::application [DEBUG] received editor event: Redraw
2023-12-28T11:21:40.334 mio::poll [TRACE] registering event source with poller: token=Token(140159236458752), interests=READABLE | WRITABLE
2023-12-28T11:21:40.334 mio::poll [TRACE] registering event source with poller: token=Token(140159236459136), interests=READABLE | WRITABLE
2023-12-28T11:21:40.334 mio::poll [TRACE] registering event source with poller: token=Token(140159162073600), interests=READABLE | WRITABLE
2023-12-28T11:21:40.334 helix_lsp::client [INFO] Using custom LSP config: {"pylsp":{"plugins":{"autopep8":{"enabled":false},"black":{"enabled":false,"line_length":120},"flake8":{"enabled":false},"isort":{"enabled":false,"profile":"black"},"mccabe":{"enabled":false},"pycodestyle":{"enabled":false},"pyflakes":{"enabled":false},"pylint":{"enabled":false},"pylsp-mypy":{"enabled":false},"ruff":{"enabled":false,"ignore":["F401"],"lineLength":120},"yapf":{"enabled":false}}}}
2023-12-28T11:21:40.334 helix_lsp::file_event [DEBUG] Removing LSP client: 0
2023-12-28T11:21:40.334 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"shutdown","id":1}
2023-12-28T11:21:40.335 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"textDocument/didClose","params":{"textDocument":{"uri":"file:///private/tmp/test.py"}}}
2023-12-28T11:21:40.335 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"positionEncodings":["utf-8","utf-32","utf-16"]},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"isPreferredSupport":true,"resolveSupport":{"properties":["edit","command"]}},"completion":{"completionItem":{"deprecatedSupport":true,"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"inlayHint":{"dynamicRegistration":false},"publishDiagnostics":{"versionSupport":true},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":true},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":false},"executeCommand":{"dynamicRegistration":false},"inlayHint":{"refreshSupport":false},"symbol":{"dynamicRegistration":false},"workspaceEdit":{"documentChanges":true,"failureHandling":"abort","normalizesLineEndings":false,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"helix","version":"23.10 (f6021dd0)"},"initializationOptions":{"pylsp":{"plugins":{"autopep8":{"enabled":false},"black":{"enabled":false,"line_length":120},"flake8":{"enabled":false},"isort":{"enabled":false,"profile":"black"},"mccabe":{"enabled":false},"pycodestyle":{"enabled":false},"pyflakes":{"enabled":false},"pylint":{"enabled":false},"pylsp-mypy":{"enabled":false},"ruff":{"enabled":false,"ignore":["F401"],"lineLength":120},"yapf":{"enabled":false}}}},"processId":39018,"rootPath":"/private/tmp","rootUri":null,"workspaceFolders":[]},"id":0}
2023-12-28T11:21:40.335 helix_lsp::transport [INFO] pylsp <- {"jsonrpc":"2.0","id":1,"result":null}
2023-12-28T11:21:40.335 helix_lsp::transport [INFO] pylsp <- null
2023-12-28T11:21:40.335 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"exit"}
2023-12-28T11:21:40.335 mio::poll [TRACE] deregistering event source from poller
2023-12-28T11:21:40.355 mio::poll [TRACE] deregistering event source from poller
2023-12-28T11:21:40.355 helix_lsp::transport [ERROR] pylsp err: <- StreamClosed
2023-12-28T11:21:40.355 mio::poll [TRACE] deregistering event source from poller
2023-12-28T11:21:40.355 helix_term::application [DEBUG] received editor event: LanguageServerMessage((0, Notification(Notification { jsonrpc: None, method: "exit", params: None })))
2023-12-28T11:21:40.355 helix_view::editor [DEBUG] editor status: Language server exited
2023-12-28T11:21:40.355 helix_lsp::file_event [DEBUG] Removing LSP client: 0
2023-12-28T11:21:40.391 helix_term::application [DEBUG] received editor event: Redraw

```

</details>

### Platform

macOS

### Terminal Emulator

warp

### Installation Method

brew

### Helix Version

23.10

**Comment by Chaostheorie** [comment] 2023-12-28 17:18
Can reproduce with another lsp that takes along time restarts and likes to die, haskell language server. It likes to start on the third or fourth lsp-restart and sometimes panics helix when taking too long.

**Comment by pascalkuthe** [comment] 2023-12-28 17:39
Duplicate of #9103

**Closed by pascalkuthe** 2023-12-28 17:39 UTC
Labels: C-bug
