### ISSUE TITLE
Time machine?

### ISSUE THREAD

**Issue by pickfire** [helix-editor/helix#60] opened 2021-06-02 14:30 UTC
`:ear ~1f` and `:lat 1h` in vim IIRC

And also history branching like `g+` and `g-`, not sure if kakoune supports them but I miss them.

**Comment by archseer** [comment] 2021-06-03 03:56
I would be interested in this, it should be possible to build by extending the `History` implementation (we'd need to store a timestamp of each change as well).

@pickfire Since you've been quite active so far, can I invite you to join us on the [Matrix channel](https://matrix.to/#/#helix-community:matrix.org)?

**Comment by jbaa** [comment] 2021-06-03 17:24
I'd like to take a stab at this. It sounds like a good feature to get to know the editor state, the history representation, and adding new commands.

My current understanding is that for the :earlier and :later commands we can reuse the current history implementation. For branching we'd need to represent the change history as a change tree that branches on new insertions.

Therefore it will be easier to start with the time machine, and follow up with branching, or even split branching out to a separate issue.

**Comment by archseer** [comment] 2021-06-04 00:43
Go for it! The issue is yours :)

**Comment by archseer** [comment] 2021-06-11 13:08
Closed by #194 !

**Closed by archseer** 2021-06-11 13:08 UTC
Labels: enhancement
