### ISSUE TITLE
[Proposal] Extend till next selection

### ISSUE THREAD

**Issue by jabcross** [helix-editor/helix#11524] opened 2024-08-19 13:58 UTC
What it says on the tin. A motion to be used with multiple cursors that will extend the selection until the next cursor.

So that this (brackets are selections)

```
[A1]
A2
A3
[B1]
B2
[C1]
C2
C3
```

becomes this:

```
A1
[A2
A3
]B1
[B2
]C1
[C2
C3
... EOF ]
```

Would be handy for a couple of use cases that currently require macros.

**Comment by chtenb** [comment] 2024-08-19 16:06
Sounds like "select till" rather than extend. Could you also mention the use cases you talked about?

**Comment by jabcross** [comment] 2024-08-19 17:13
Example: converting

```
if char == 'a':
   # some arbitrary number of lines
   return 'value'
elif char == 'b':
   # some other arbitrary
   # number of lines
   return 'value'
elif char == 'c':
   # some third
   # arbitrary
   # number of lines
   return 'value'
# ...
```
to

```
if char == 'a':
   # some arbitrary number of lines
   return 'value_a'
elif char == 'b':
   # some other arbitrary
   # number of lines
   return 'value_a'
elif char == 'c':
   # some third
   # arbitrary
   # number of lines
   return 'value_a'
# ...
```

Process:
- `%s==<enter>` (put a cursor in each `==`)
- `llly` (copy the appropriate character to the per-cursor clipboard)
-  `select_till_next_selection` (proposed action, will select the body of each `if`)
- `sreturn<enter>` (select each `return`)
- `2t'a_<esc>` (insert `_` at end of string)
-  `p` (paste the character from the per-cursor clipboard)

I cannot find another way to do this with multiple cursors. A macro that does this process with a single cursor will not work properly with multiple cursors.

If there was a variant of `f` that took a string, or if `/` worked independently with multiple cursors, this could also be achieved, but I think this method is more general.

**Comment by kirawi** [comment] 2024-08-19 21:32
Something like this would depend on resolving the latter part of https://github.com/helix-editor/helix/issues/2298#issuecomment-1792133538. This also sounds like it is a duplicate of https://github.com/helix-editor/helix/issues/5672

**Closed by kirawi** 2024-08-19 21:32 UTC
Labels: C-enhancement

**Comment by jabcross** [comment] 2024-08-20 04:31
Well, my proposal doesn't really create adjacent selections, so I don't understand what you mean by the linked comment. The original selections will not end up selected and will therefore be between any of the resulting selections.

Also, this was just one example of usage. I can think of other uses than the multicursor search problem. Not sure how it's a duplicate.

**Comment by chtenb** [comment] 2024-08-20 07:41
> Also, this was just one example of usage. I can think of other uses than the multicursor search problem. 

Can you elaborate and actually give the example that could not be solved by multicursor search?

**Comment by jabcross** [comment] 2024-08-20 09:47
Any situation where you have a list of header-body type structures and you want to alter the bodies with information from the heads. But I think my provided example is enough.

I'm sure many things could be solved with multicursor search, but I don't think that being the "only" solution to a given situation should be the sole cutoff criterion to whether a proposal is considered or not. After all, anything *could* be solved with just regex substitutions and `hjkl` or with macros. It's just handy to have options.

I just wanted to know if this is something people would find useful, to maybe work on a PR. And if not, what are your perceived downsides, to inform future suggestions.
