### ISSUE TITLE
Appending to adjacent selections does not work as expected

### ISSUE THREAD

**Issue by chariotsofiron** [helix-editor/helix#9110] opened 2023-12-18 19:01 UTC
### Summary

The `append_mode` command (insert after selection, `a` key) does not work as expected when the selections are adjacent to each other.

### Reproduction Steps

If a buffer contains the text `aaa` and I run the commands `%sa<enter>ab`, i.e. select all the `a`s, and append the letter `b` after each `a`. I expect the buffer to contain `ababab`, but instead it contains `aaab`.

Similarly, if the buffer contains `ababab` and I run the commands `%sab<enter>ac`, I expect the buffer to contain `abcabcabc`, but instead it contains `abababc`.

By comparison, if the buffer contains `acaca` and I run `%sa<enter>ab`, I get `abcabcab`, as expected.

### Platform

macOS

### Terminal Emulator

kitty 0.31.0

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by chariotsofiron** [comment] 2023-12-18 19:09
Duplicate of https://github.com/helix-editor/helix/issues/2298

**Comment by kirawi** [comment] 2023-12-18 20:29
Yeah it's a duplicate of that one

**Closed by kirawi** 2023-12-18 20:29 UTC
Labels: C-bug
