### ISSUE TITLE
Multi-cursor position is shifted

### ISSUE THREAD

**Issue by ghost** [helix-editor/helix#2991] opened 2022-07-07 00:29 UTC
### Summary

If the language server is not running and there are only newlines, typing with a multi-cursor does not work as expected.
It works as expected if the language server is running or if there are chars.

### Reproduction Steps

I tried this:

1. `hx`
2. add some newlines
3. add new cursors
4. input auto-pair like (, { etc..
ex)
(aaa)
aaa()
aaa()
(aaa) <- primary cursor

I expected this to happen:
(aaa)
(aaa)
(aaa)
(aaa) <- primary cursor

### Helix log

```sh
2022-07-07T09:14:08.222 helix_term::commands [TRACE] entering insert mode with sel: Selection { ranges: [Range { anchor: 0, head: 2, horiz: None }], primary_index: 0 }, text: "\r\n"
2022-07-07T09:14:13.430 helix_term::commands [TRACE] entering insert mode with sel: Selection { ranges: [Range { anchor: 0, head: 2, horiz: None }, Range { anchor: 2, head: 4, horiz: None }, Range { anchor: 4, head: 6, horiz: None }, Range { anchor: 6, head: 8, horiz: None }, Range { anchor: 8, head: 10, horiz: None }], primary_index: 4 }, text: "\r\n\r\n\r\n\r\n\r\n"
2022-07-07T09:14:14.584 helix_core::auto_pairs [TRACE] autopairs hook selection: Selection {
    ranges: [
        Range {
            anchor: 2,
            head: 0,
            horiz: None,
        },
        Range {
            anchor: 4,
            head: 2,
            horiz: None,
        },
        Range {
            anchor: 6,
            head: 4,
            horiz: None,
        },
        Range {
            anchor: 8,
            head: 6,
            horiz: None,
        },
        Range {
            anchor: 10,
            head: 8,
            horiz: None,
        },
    ],
    primary_index: 4,
}
2022-07-07T09:14:14.584 helix_core::auto_pairs [DEBUG] auto pair transaction: Transaction {
    changes: ChangeSet {
        changes: [
            Insert(
                "()",
            ),
            Retain(
                2,
            ),
            Insert(
                "()",
            ),
            Retain(
                2,
            ),
            Insert(
                "()",
            ),
            Retain(
                2,
            ),
            Insert(
                "()",
            ),
            Retain(
                2,
            ),
            Insert(
                "()",
            ),
            Retain(
                2,
            ),
        ],
        len: 10,
        len_after: 20,
    },
    selection: Some(
        Selection {
            ranges: [
                Range {
                    anchor: 2,
                    head: 1,
                    horiz: None,
                },
                Range {
                    anchor: 4,
                    head: 5,
                    horiz: None,
                },
                Range {
                    anchor: 6,
                    head: 17,
                    horiz: None,
                },
            ],
            primary_index: 2,
        },
    ),
}
2022-07-07T09:14:15.118 helix_core::auto_pairs [TRACE] autopairs hook selection: Selection {
    ranges: [
        Range {
            anchor: 2,
            head: 1,
            horiz: None,
        },
        Range {
            anchor: 4,
            head: 5,
            horiz: None,
        },
        Range {
            anchor: 6,
            head: 17,
            horiz: None,
        },
    ],
    primary_index: 2,
}
2022-07-07T09:14:15.258 helix_core::auto_pairs [TRACE] autopairs hook selection: Selection {
    ranges: [
        Range {
            anchor: 3,
            head: 2,
            horiz: None,
        },
        Range {
            anchor: 6,
            head: 7,
            horiz: None,
        },
        Range {
            anchor: 8,
            head: 20,
            horiz: None,
        },
    ],
    primary_index: 2,
}
2022-07-07T09:14:15.388 helix_core::auto_pairs [TRACE] autopairs hook selection: Selection {
    ranges: [
        Range {
            anchor: 4,
            head: 3,
            horiz: None,
        },
        Range {
            anchor: 8,
            head: 9,
            horiz: None,
        },
        Range {
            anchor: 10,
            head: 23,
            horiz: None,
        },
    ],
    primary_index: 2,
}
2022-07-07T09:14:15.539 helix_core::auto_pairs [TRACE] autopairs hook selection: Selection {
    ranges: [
        Range {
            anchor: 5,
            head: 4,
            horiz: None,
        },
        Range {
            anchor: 10,
            head: 11,
            horiz: None,
        },
        Range {
            anchor: 12,
            head: 26,
            horiz: None,
        },
    ],
    primary_index: 2,
}
2022-07-07T09:14:15.815 helix_core::auto_pairs [TRACE] autopairs hook selection: Selection {
    ranges: [
        Range {
            anchor: 6,
            head: 5,
            horiz: None,
        },
        Range {
            anchor: 12,
            head: 13,
            horiz: None,
        },
        Range {
            anchor: 14,
            head: 29,
            horiz: None,
        },
    ],
    primary_index: 2,
}
2022-07-07T09:14:15.951 helix_core::auto_pairs [TRACE] autopairs hook selection: Selection {
    ranges: [
        Range {
            anchor: 7,
            head: 6,
            horiz: None,
        },
        Range {
            anchor: 14,
            head: 15,
            horiz: None,
        },
        Range {
            anchor: 16,
            head: 32,
            horiz: None,
        },
    ],
    primary_index: 2,
}
```

### Platform

Windows

### Terminal Emulator

windows terminal

### Helix Version

helix 22.05 (230ba264)

**Comment by the-mikedavis** [comment] 2022-07-31 18:55
This appears to be a problem with CRLF line-endings. LF line-endings produce the expected result.

I can reproduce this with a language server running though, I think that's unrelated. The language server formatting is most likely replacing the CRLF line-endings with LF.

**Comment by pascalkuthe** [comment] 2023-09-03 00:29
This seems to be the same issue as #8043 which has more details and a linked PR with a fix so I am closing in favor of that issue

**Closed by pascalkuthe** 2023-09-03 00:29 UTC
Labels: C-bug, A-helix-term
