### ISSUE TITLE
A way to disable going to the next line when you reach the end on the line using h, j, k, l.

### ISSUE THREAD

**Issue by mkblast** [helix-editor/helix#6637] opened 2023-04-06 23:50 UTC
Add an option to disable jumping to the next line if you reached the end of the current line.

 
[Screencast from 2023-04-07 00-06-37.webm](https://user-images.githubusercontent.com/73954836/230513451-ffc69c02-5dc4-4dbf-b73e-11cb163446db.webm)

**Comment by gabydd** [comment] 2023-04-07 02:01
Duplicate of https://github.com/helix-editor/helix/issues/4268 (there is a pr for it but it needs to be rebased for some of the recent changes in rendering)

**Closed** 2023-04-07 14:43 UTC
Labels: C-enhancement

**Comment by kirawi** [comment] 2023-04-08 04:50
I think this is actually closer to a duplicate of https://github.com/helix-editor/helix/issues/768

**Comment by gabydd** [comment] 2023-04-08 05:01
Oh you are right, funnily enough I linked the correct one here a couple weeks ago https://github.com/helix-editor/helix/issues/6237
