### ISSUE TITLE
Replace with adjacent cursors moves cursor over

### ISSUE THREAD

**Issue by emilyyyylime** [helix-editor/helix#9987] opened 2024-03-24 13:36 UTC
### Reproduction Steps

```
$ echo ab | hx
xs.<ret>r0
```
Now there is a gap between the two cursors (`[0]0[\n]` rather than `[0][0]\n`)

### Platform

Arch Linux

### Terminal Emulator

Kitty

### Installation Method

source

### Helix Version

helix 23.10 (8f65bfe0)

**Comment by pascalkuthe** [comment] 2024-04-06 02:13
Duplicate of #5910

**Closed by pascalkuthe** 2024-04-06 02:13 UTC
Labels: C-bug
