### ISSUE TITLE
Enhancement: make a running helix instance open a file by path

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#6054] opened 2023-02-19 18:10 UTC
Right now there is no file tree (#200) within helix, but there are plenty of file tree programs like `nnn`, `lf`, `ranger`, etc. There are also terminal composers/multiplexers like `zellij` that have the opportunity to launch `hx`, then on keybinding show an instance of `nnn`, take the picked result, and pass the path to the contained instance of `hx` to have it open that file

However, as it stands, I don't believe there is a way to ask an existing instance of `hx` to open a file by path

Originally posted in this comment: https://github.com/helix-editor/helix/issues/200#issuecomment-1424561864

**Comment by thomasgoulet** [comment] 2023-02-19 18:33
To add to this, it would be nice if the option / flag would let you specify to open a new instance of helix if no instance is found and to open the file inside an existing instance if one is found. 

One design issue that'd need to be figured out is that sometimes there might be multiple instances of helix.

**Comment by the-mikedavis** [comment] 2023-02-19 19:23
Duplicate of https://github.com/helix-editor/helix/issues/2177

**Closed by the-mikedavis** 2023-02-19 19:23 UTC

**Comment by yashpalgoyal1304** [comment] 2023-02-20 01:39
hey both, please thumbs up that issue and share your input over there :smiley:

**Comment by quantonganh** [comment] 2023-08-01 10:07
> However, as it stands, I don't believe there is a way to ask an existing instance of `hx` to open a file by path

I know that you may already be using the file explorer from #5768 but I still want to share how I integrated `hx` with WezTerm to solve this.

First, create a `nnn-hx.sh` script and add it to your `$PATH`:

```sh
#!/usr/bin/env sh

fpath="$1"

pane_id=$(wezterm cli get-pane-direction right)
if [ -z "${pane_id}" ]; then
  pane_id=$(wezterm cli split-pane --right --percent 80)
fi

program=$(wezterm cli list | awk -v pane_id="$pane_id" '$3==pane_id { print $6 }')
if [ "$program" = "hx" ]; then
  echo ":open ${fpath}\r" | wezterm cli send-text --pane-id $pane_id --no-paste
else
  echo "hx ${fpath}" | wezterm cli send-text --pane-id $pane_id --no-paste
fi

wezterm cli activate-pane-direction --pane-id $pane_id right
```

Next, call it as a custom opener:

```sh
$ export NNN_OPENER=nnn-hx.sh
$ nnn -c
```

This integration allows you to use `nnn-hx.sh` script as a custom opener in WezTerm to handle file paths and open them accordingly in the desired pane.
