### ISSUE TITLE
global search on tutor

### ISSUE THREAD

**Issue by notusertelken** [helix-editor/helix#4960] opened 2022-12-01 16:31 UTC
### Summary

unhandled edge case of performing a globa-search on tutor

### Reproduction Steps

 

I tried this:

run `helix --tutor`
space+/ and search a term

I expected this to happen:
I'd expect to only search the tutor file, as if it was in a workspace/folder by itself

Instead, this happened:
process freezes (Im assuming its doing a search on the cwd or complete system wide global search)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

linux

### Terminal Emulator

alacritty

### Helix Version

22.08.1

**Comment by the-mikedavis** [comment] 2022-12-01 21:51
Duplicate of https://github.com/helix-editor/helix/issues/4207

**Closed by the-mikedavis** 2022-12-01 21:51 UTC
Labels: C-bug
