### ISSUE TITLE
Auto-indenting of braces breaks inside quotes

### ISSUE THREAD

**Issue by jw013** [helix-editor/helix#9067] opened 2023-12-13 05:07 UTC
### Summary

Auto-indenting breaks inside quotes for most file types.

### Baseline: plain text file

- `hx foo.txt`
- enter Insert mode 
- type `a<space>{<enter>b<space>{<enter>c<space>{<enter>`. 

### Result
```
a {
    b {
        c {
            | <- cursor is here
        }
    }
}
```
This seems perfectly normal. 

### Rust

- `hx foo.rs`
- prepare the following
  ```
  const S: &str = "
  | <- place cursor here in insert mode
  ";
  ```
- type the same `a { b { c {` sequence as above

### Result
```
const S: &str = "
a {
    b {
    c {
    | <- cursor 
}
}
}
";
```

This issue is not specific to rust, I initially ran into it trying to edit a large multi-line string in a `.ron` file. Similar behavior can be reproduced with `.py` and `.js`:

`hx foo.py` results:

```
"""
a {
    b {
    c {
    
}
}
}
"""
```

`hx foo.js` results:
```
`
a {
  b {
  c {
  
}
}
}
`
```

### Platform

Linux

### Terminal Emulator

gnome-terminal

### Installation Method

source

### Helix Version

helix 23.10 (cb0bc25a)

**Comment by kirawi** [comment] 2023-12-13 21:06
This seems like a duplicate of https://github.com/helix-editor/helix/issues/6939

**Closed by kirawi** 2023-12-13 21:06 UTC
Labels: C-bug
