### ISSUE TITLE
prepend comment token on new line when writing comments

### ISSUE THREAD

**Issue by akabinds** [helix-editor/helix#6365] opened 2023-03-18 22:41 UTC
When writing comments such as documentation comments, it is pretty annoying that the comment token (`//!` or `///` in Rust for example) isn't prepended to the next line when ENTER is hit. This can mess up the flow of writing comments as you have to manually type the comment token every time. It would be nice if Helix used the comment token (the one specified by the `comment-token` field under `[[language]]` in `languages.toml`) and prepend it to the next line, with a space, when ENTER is hit. 

There would of course be some questions that could arise with this feature. In Rust, for example, there are multiple kinds of comment tokens that start with `//`. How would Helix handle this? One suggestion of mine would be to somehow check if there is another character after the `//` prefix and append that to some "buffer" caching the token prefix. This would require some discussion though I believe.

**Comment by gabydd** [comment] 2023-03-18 23:36
Duplicate of https://github.com/helix-editor/helix/issues/1730

**Closed** 2023-03-19 01:10 UTC
Labels: C-enhancement
