### ISSUE TITLE
Closest pair does not match on quotes

### ISSUE THREAD

**Issue by asvln** [helix-editor/helix#4885] opened 2022-11-25 12:18 UTC
### Reproduction
- open a new buffer
- insert `"testing"`
- move cursor inside `"`
- `mim`

### Summary

This should select the word `testing`, it currently does nothing.

This does not work with `"` or `'`.
If I add any other characters to the `PAIRS` const within the `match_brackets.rs` file, those pairs also do not match.

I do not know where/how `mim`/`mam` is called in source so I do not know how to debug further

### Helix Version
22.08.1-501-ge6dad960

**Comment by gabydd** [comment] 2022-11-25 13:11
[Some context](https://github.com/helix-editor/helix/issues/4475) also helix-core/surround.rs is where the functionality to find the position of the nearest pair is which is used [here](https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs#L4529) to select nearest pair

**Comment by the-mikedavis** [comment] 2022-11-25 15:06
Duplicate of https://github.com/helix-editor/helix/issues/4475

**Closed by the-mikedavis** 2022-11-25 15:06 UTC
Labels: C-bug

**Comment by asvln** [comment] 2022-11-25 15:43
Apologies, I am apparently not good at finding existing issues.

Thank you @gabydd

**Comment by gabydd** [comment] 2022-11-25 15:49
No problem I have notifications on for the helix repo so I see pretty much all the issues and I remembered one existed for this, also GitHub issue search is pretty bad so it's understandable that you couldn't find the existing one
