### ISSUE TITLE
Inline hints for rust analyzer 

### ISSUE THREAD

**Issue by elferherrera** [helix-editor/helix#2049] opened 2022-04-09 10:31 UTC
Is there any plan to support inline hints for RA?

**Comment by the-mikedavis** [comment] 2022-04-09 13:10
I believe we do want to support these but the rendering is a little tricky. https://github.com/helix-editor/helix/pull/417 has some progress towards it.

**Comment by kirawi** [comment] 2022-04-09 21:53
Duplicate of #411

**Closed by kirawi** 2022-04-09 21:53 UTC
Labels: C-enhancement
