### ISSUE TITLE
Running command status

### ISSUE THREAD

**Issue by mfirhas** [helix-editor/helix#11433] opened 2024-08-06 01:16 UTC
When we executed long running commands(e.g. `cargo build --release`, maven commands, etc) using `:sh`, there's nothing telling us the command is running, it's just blank empty space. 

We can add message before `Command succeeded` appeared, e.g. `Running command "command input"...`

**Comment by the-mikedavis** [comment] 2024-08-08 19:10
Duplicate of https://github.com/helix-editor/helix/issues/7338

**Closed by the-mikedavis** 2024-08-08 19:10 UTC
