### ISSUE TITLE
Implemet tabout

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#2816] opened 2022-06-19 18:24 UTC
Tabout is a common feature in many IDEs. It works as described here:
https://github.com/abecodes/tabout.nvim#-taboutnvim

**Comment by EpocSquadron** [comment] 2022-06-19 19:03
This is achievable with `alt-o` and `alt-i`, and is more general as it works with syntax nodes.

**Comment by sudormrfbin** [comment] 2022-06-19 19:13
Duplicate of #1587.

**Closed by sudormrfbin** 2022-06-19 19:13 UTC
Labels: C-enhancement
