### ISSUE TITLE
Would it be possible to implement a file browser ?

### ISSUE THREAD

**Issue by onerciller** [helix-editor/helix#5550] opened 2023-01-16 09:48 UTC
Hi @archseer , 

Although The open file picker is very easy and excellent, folder management features such as creating, copying, and deleting are not included. In addition, using external file management tools is pretty distracting.

Would it be possible to implement a file browser similar to [telescope-file-browser.nvim ](https://github.com/nvim-telescope/telescope-file-browser.nvim)instead of file explorer ?

![149016073-6fcc9383-a761-422b-be40-17d4b854cd3c](https://user-images.githubusercontent.com/7740849/212647195-43afd257-dfca-45bd-b6d7-41f552a8e2dc.gif)

**Comment by ayoub-benali** [comment] 2023-01-16 11:32
This looks like a duplicate of https://github.com/helix-editor/helix/issues/200

**Comment by pascalkuthe** [comment] 2023-01-16 14:05
Closing as duplicate of #200

**Closed by pascalkuthe** 2023-01-16 14:05 UTC
