### ISSUE TITLE
Matching does not work on functions if there is only one function

### ISSUE THREAD

**Issue by ryan-bandler-lilly** [helix-editor/helix#8277] opened 2023-09-13 20:47 UTC
### Summary

If I have a file which only has one function:

```go
func main(){
    fmt.Println("hi")
    //other stuff
}
```

if my cursor is within that function, and I wanna select the function using `maf` or select all the contents of the function using `mif`, this does not work. This is the case for every programming language I have tried. This functionality should work even if there is just one function in the file.

### Platform

macOS

### Terminal Emulator

iterm2

### Helix Version

helix 23.05 (7f5940be)

**Comment by pascalkuthe** [comment] 2023-09-13 21:07
in my testing this works perfectly fine as long as there is a trailing newline. There is an existing issue about that specific case and once I find it again this can be closed as duplicate

**Comment by the-mikedavis** [comment] 2023-09-13 21:07
Duplicate of https://github.com/helix-editor/helix/issues/3408

**Closed by the-mikedavis** 2023-09-13 21:07 UTC
Labels: C-bug, R-duplicate
