### ISSUE TITLE
How to add description to key remap?

### ISSUE THREAD

**Issue by rubiktubik** [helix-editor/helix#12166] opened 2024-12-01 16:00 UTC
Hi, 

i added a custom keymap to config.toml

```toml
[keys.normal]
"ä" = { "b" = ":run-shell-command fvm dart pub run build_runner build --delete-conflicting-outputs" }
```

In Helix i see:
<img width="932" alt="grafik" src="https://github.com/user-attachments/assets/4964d4c3-3910-4a70-a8b2-e27291c0c816">

How can i give it a friendly name?

I have seen the `"b: FriendlyName"` syntax but it doesnt work in my case i think i'am using it wrong.

Can someone help me?

Btw. I love this editor!

**Comment by kirawi** [comment] 2024-12-01 16:22
Duplicate of https://github.com/helix-editor/helix/issues/1752

**Closed by kirawi** 2024-12-01 16:22 UTC

**Comment by rubiktubik** [comment] 2024-12-01 18:31
@kirawi can you explain why it is marked as not planned? I’am not so deep informed in the helix 🧬 development decisions.

**Comment by kirawi** [comment] 2024-12-01 21:09
It's a duplicate
