### ISSUE TITLE
Remember themes or set light/dark depending on terminal colorscheme

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#4011] opened 2022-09-28 17:14 UTC
If a user hasn't set a theme then reloading the previously set theme on startup would be nice.

Better than that, letting the user set their light theme and a dark theme in config so that if the current terminal theme is light then switch to the light, user preferred theme and vice-versa.

**Comment by dead10ck** [comment] 2022-09-28 17:20
> If a user hasn't set a theme then reloading the previously set theme on startup would be nice.

If the user wants to persist a theme, then the config file is exactly what this is for.

> Better than that, letting the user set their light theme and a dark theme in config so that if the current terminal theme is light then switch to the light, user preferred theme and vice-versa.

Duplicate of #2158

**Closed by dead10ck** 2022-09-28 17:20 UTC
Labels: C-enhancement

**Comment by zim0369** [comment] 2022-09-28 17:28
> If the user wants to persist a theme, then the config file is exactly what this is for.

It's not that the user only wants the exact same theme to persist or be set the entire time. If a user is usually changing themes, say setting they set "gruvbox" now then exited. On restart, the theme should be "gruvbox". Now, the user sets "ayu_dark", exits & restarts, so now theme should be "ayu_dark". This isn't the same as setting a theme in the config.

**Comment by dead10ck** [comment] 2022-09-28 17:33
I would hazard an assumption that most users don't change their themes around that often, once they find one or two that they like. In any case, this could probably be served by #401.

**Comment by zim0369** [comment] 2022-09-28 17:41
@dead10ck Coming from a long term use of neovim and interaction with the vim community, I have come across a lot of users that keep changing themes. Not too frequently.

Implementing this doesn't seem hard. A weak implementation would be saving theme to a tmp file or much better saving it to a database. It would be just more convenient.

> Better than that, letting the user set their light theme and a dark theme in config so that if the current terminal theme is light then switch to the light, user preferred theme and vice-versa.

To me personally, this sounds really cool & quite useful. This seems to be definitely covered in #2158.

**Comment by dead10ck** [comment] 2022-09-28 18:11
> Implementing this doesn't seem hard. A weak implementation would be saving theme to a tmp file or much better saving it to a database. It would be just more convenient.

Cool, then I guess we can expect you get involved in the discussion in #401, come up with a concrete plan, and submit a PR.

**Comment by zim0369** [comment] 2022-09-28 18:17
@dead10ck Sure, to get involved but can't say anything about a PR.
