### ISSUE TITLE
Add support for key to key remapping

### ISSUE THREAD

**Issue by KyleUltimate** [helix-editor/helix#3551] opened 2022-08-26 07:03 UTC
#### Describe your feature request
I wanna remap a key to another key, instead of remapping a key's action alone
The reason for this is because I'm a colemak user, and using qwerty homerow on colemak is a pain.
The following is vim's way of handling this problem
![image](https://user-images.githubusercontent.com/68589851/186842260-13bd86e9-1979-42ba-9249-0bed386d327f.png)
#### Additional Context
https://github.com/helix-editor/helix/issues/3367
This issue demonstrate what a pain is to rebind four keys, imagine having to remap your entire keyboard

**Comment by Omnikar** [comment] 2022-08-26 10:40
Duplicate of #1383.

**Closed** 2022-08-26 13:25 UTC
Labels: C-enhancement
