### ISSUE TITLE
Watch open files for updates and auto-update to latest versions when changed externally

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#1900] opened 2022-03-31 09:55 UTC
## The problem 

Say I have (knowingly or unknowingly) File A open in two different instances of Helix – Editor X and Y.

File A:

```
1. hello
2. goodbye
```

1. I change line 1 in File A in Editor X To `1. hi` and save it (`:w`)
2. I look at Editor Y, line 1 still reads `1. hello`.
3. If in Editor Y, I change line 2 to `2. bye` and save, I’ve overwritten the change in Editor X.

## How other editors handle it

Editors (e.g., VSCode) handle this by watching open files for changes. If a change is detected, the file in the editor is automatically updated to the latest version from disk.

**Comment by archseer** [comment] 2022-03-31 16:01
Duplicate of #1125

**Closed by archseer** 2022-03-31 16:01 UTC
Labels: C-enhancement
