### ISSUE TITLE
Weird overlap between function parameter popup, and completion popup

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#5372] opened 2023-01-02 21:01 UTC
### Summary

Sometimes both the function parameters popup and completion popup will be visibile and overlap one another.
for example with this code
```rust
fn main() {
    example(
}

fn example(str: &str, int: usize) {}

```
typing the parenthesis after `example` results in this:
![image](https://user-images.githubusercontent.com/58790821/210277601-89221177-362b-42be-86b8-bc5d895f3c9b.png)

### Reproduction Steps

 

I tried this:

1. `hx`
2. paste in text from above
3. delete and retype parenthesis

I expected this to happen:
Only one popup is visible at a time

Instead, this happened:
Both are overlapped

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Gnome console

### Helix Version

22.12-86-gd4565b44

**Comment by ItsEthra** [comment] 2023-01-02 23:08
Happens for me as well but in my case, function docs covers the whole completion popup. When I press tab it does autocomplete but does not bring completion popup to front.
![image](https://user-images.githubusercontent.com/107059409/210283829-a828a448-dc09-46a9-982d-921ce1957113.png)

**Comment by the-mikedavis** [comment] 2023-01-03 03:11
Duplicate of https://github.com/helix-editor/helix/issues/3821

**Closed by the-mikedavis** 2023-01-03 03:11 UTC
Labels: C-bug
