### ISSUE TITLE
Not Implemented Panic on `[ "extend_line", "delete_selection", "open_above" ]` depending on keybind

### ISSUE THREAD

**Issue by d12bb** [helix-editor/helix#3529] opened 2022-08-24 09:11 UTC
### Summary

In my ongoing quest to battle Helix's behavior with newlines, I added `x = { c = [ "extend_line", "delete_selection", "open_above" ] }` to my `config.toml`. While working as intended, I had to realize this breaks every other use of `x`, so I changed the binding to use `S` instead. Having changed nothing but the key, it panics with not implemented.

### Reproduction Steps

I tried this:

1. Set the keybind in `config.toml`: `S = [ "extend_line", "delete_selection", "open_above" ]`
2. Use it.

I expected this to happen:
It works, as it does when set to `xc`.

Instead, this happened:
```
❯ RUST_BACKTRACE=1 hx src/lib.rs 
thread 'main' panicked at 'not implemented', helix-term/src/ui/editor.rs:1230:34
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
   4: helix_term::compositor::Compositor::handle_event
   5: helix_term::application::Application::handle_terminal_events
   6: helix_term::application::Application::event_loop_until_idle::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: tokio::park::thread::CachedParkThread::block_on
  10: tokio::runtime::thread_pool::ThreadPool::block_on
  11: tokio::runtime::Runtime::block_on
  12: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Platform

macOS 12.5.1

### Terminal Emulator

Kitty 0.25.2

### Helix Version

22.05-418-g18909aa

**Comment by the-mikedavis** [comment] 2022-08-24 12:50
Duplicate of https://github.com/helix-editor/helix/issues/2051

**Closed by the-mikedavis** 2022-08-24 12:50 UTC
Labels: C-bug

**Comment by d12bb** [comment] 2022-08-24 13:01
I actually don't believe this to be a duplicate (I've seen #2051 before submitting the issue), as it works when set to `xc`, but please just keep it closed if I'm wrong:
```toml
S = [ "extend_line", "delete_selection", "open_above" ]           # panic
x = { c = [ "extend_line", "delete_selection", "open_above" ] }   # fine
```

**Comment by the-mikedavis** [comment] 2022-08-24 14:34
The panic for `S` comes from the `unimplemented!` in #2051: https://github.com/helix-editor/helix/blob/ccae718a67f39542281125610764b733d90b26f8/helix-term/src/ui/editor.rs#L1225-L1229

That block assumes that you are only entering insert mode by a single key bound to a single command. `xc` _should_ panic from that same `unimplemented!` but currently the lookup of `xc` in `self.keymaps.get(mode, key)` mistakenly only looks up the `c` key event which gives `KeymapResult::Matched(MappableCommand("change_selection"))` - the binding for `c`. It looks like both problems are solved by https://github.com/helix-editor/helix/pull/2634
