### ISSUE TITLE
Continue moving the cursor for (half) page scrolling

### ISSUE THREAD

**Issue by antoyo** [helix-editor/helix#1731] opened 2022-03-03 03:20 UTC
Hi.
Not sure if it is the same as #750, so feel free to close if it is the same.

#### Describe your feature request

I'd like `C-u`, `C-d`, `C-b`, `C-f` in normal mode to behave the same as in vim (**edit:** actually, `C-b` does not have this behavior in vim), that is, even if you see the start/end of the document, those shortcuts continue to move the cursor up/down until the very first/last time.
Helix instead will stop moving the cursor when you see the start/end of the buffer.

**Comment by pascalkuthe** [comment] 2024-04-04 01:01
Pretty sure this was a duplicate of #750/#7639 and addressed by #8015

**Closed by pascalkuthe** 2024-04-04 01:01 UTC
Labels: C-enhancement, A-helix-term
