### ISSUE TITLE
C auto-indent has unexpected tab width and indent style.

### ISSUE THREAD

**Issue by mikkelfj** [helix-editor/helix#4556] opened 2022-11-01 09:46 UTC
(The C bug report template doesn't allow me submit in Firefox, so dumping it all here).

Summary
------
Auto-indent and formatting style does not work as expected with clangd on MacOS even when clangd diagnostics and tree-sitter is operational. That is, it does something, but uses unexpected styling. This is largely a showstopper for C developers because it is too much work to fix formatting all the time.

Reproduction Steps
--------------------
Helix 22.08, with clangd configured and diagnostics reporting on MacOS BigSur Intel:
Autoindent is always 2 spaces even if set to 4 spaces in languages.toml. Using `clangd --fallback-style=WebKit` does not change that in languages.tom. Note that WebKit uses 4 spaces.
I then generated .clang-format and compile_commands.json file at the root of a project and created a new test.c file with a switch statement. WebKit uses IndentCaseLabels false, but formatting insists on a 2 space indent after return on `switch (1) {` where there should be none.
The  helix log file produced below shows compile_commands.json being processed and the test.c file operated upon.

Note: compile_commands.json and .clang-format shouldn't really be required for formatting to work, it was just part of the testing. I also tried without, with and without --fallback-style, same results. Formatting such as :fmt does work, it just doesn't work as expected.
I created `compile_commands.json` with uncommented CMake instruction:
https://github.com/dvidelabs/flatcc/blob/41e9e7b0b25d698821072f1603d62ca34b57eaf3/CMakeLists.txt#L11
and `ln -s build/Debug/compile_commands.json compile_commands.json`
and `.clang-format` with:
`clang-format -dump-config -style=WebKit > .clang-format`
Note that the project is largely unimportant it just provides a context.

Note: I had to install a recent llvm with homebrew and add paths to shell before clangd and tree-sitter was fully operational (this is not well documented but there is a bit on Wiki).

Kitty terminal has been configured with Option as Alt on MacOS, not that it should matter here.

Also, documentation regarding clangd, .clang-format, and compile_commands.json could perhaps be improved.

```
$ clangd --version
Homebrew clangd version 14.0.6
Features: mac+xpc
Platform: x86_64-apple-darwin20.6.0

$ clang-format --version
Homebrew clang-format version 14.0.6
```

Helix Log
---------
<details><summary>~/.cache/helix/helix.log</summary>

```
3:34.212 helix_lsp::transport [ERROR] err <- "I[16:33:34.212] ASTWorker building file /Users/mikkelfj/work/pub/flatcc/test.c version 0 with command inferred from /Users/mikkelfj/work/pub/flatcc/test/json_test/test_basic_parse.c\n"
2022-10-31T16:33:34.213 helix_lsp::transport [ERROR] err <- "[/Users/mikkelfj/work/pub/flatcc/build/Debug]\n"
2022-10-31T16:33:34.213 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/cc -I/Users/mikkelfj/work/pub/flatcc/build/Debug/test/json_test/generated -I/Users/mikkelfj/work/pub/flatcc/include -DFLATCC_REFLECTION=1 -Wstrict-prototypes -Wsign-conversion -Wconversion -pedantic -Wall -Wextra -Werror -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.7 -c -std=c11 -resource-dir=/usr/local/Cellar/llvm/14.0.6/lib/clang/14.0.6 -- /Users/mikkelfj/work/pub/flatcc/test.c\n"
2022-10-31T16:33:34.214 helix_lsp::transport [ERROR] err <- "I[16:33:34.214] --> window/workDoneProgress/create(0)\n"
2022-10-31T16:33:34.215 helix_lsp::transport [ERROR] err <- "I[16:33:34.215] Enqueueing 46 commands for indexing\n"
2022-10-31T16:33:34.215 helix_lsp::transport [ERROR] err <- "I[16:33:34.215] <-- reply(0)\n"
2022-10-31T16:33:34.215 helix_lsp::transport [ERROR] err <- "I[16:33:34.215] --> $/progress\n"
2022-10-31T16:33:34.215 helix_lsp::transport [ERROR] err <- "I[16:33:34.215] --> $/progress\n"
2022-10-31T16:33:34.229 helix_lsp::transport [ERROR] err <- "I[16:33:34.229] --> textDocument/publishDiagnostics\n"
2022-10-31T16:33:34.231 helix_lsp::transport [ERROR] err <- "I[16:33:34.231] Loaded compilation database from /Users/mikkelfj/work/pub/flatcc/build/Debug/compile_commands.json\n"
2022-10-31T16:33:34.683 helix_lsp::transport [ERROR] err <- "I[16:33:34.683] --> $/progress\n"
2022-10-31T16:33:34.683 helix_lsp::transport [ERROR] err <- "I[16:33:34.683] --> $/progress\n"
2022-10-31T16:33:34.683 helix_lsp::transport [ERROR] err <- "I[16:33:34.683] --> $/progress\n"
2022-10-31T16:33:35.069 helix_lsp::transport [ERROR] err <- "I[16:33:35.069] Indexed /Users/mikkelfj/work/pub/flatcc/samples/monster/monster.c (1020 symbols, 5488 refs, 107 files)\n"
2022-10-31T16:33:35.112 helix_lsp::transport [ERROR] err <- "I[16:33:35.112] <-- textDocument/didChange\n"
2022-10-31T16:33:35.112 helix_lsp::transport [ERROR] err <- "I[16:33:35.112] <-- textDocument/signatureHelp(1)\n"
2022-10-31T16:33:35.117 helix_lsp::transport [ERROR] err <- "I[16:33:35.117] --> reply:textDocument/signatureHelp(1) 5 ms\n"
2022-10-31T16:33:35.167 helix_lsp::transport [ERROR] err <- "I[16:33:35.167] ASTWorker building file /Users/mikkelfj/work/pub/flatcc/test.c version 1 with command inferred from /Users/mikkelfj/work/pub/flatcc/test/json_test/test_basic_parse.c\n"
2022-10-31T16:33:35.167 helix_lsp::transport [ERROR] err <- "[/Users/mikkelfj/work/pub/flatcc/build/Debug]\n"
2022-10-31T16:33:35.167 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/cc -I/Users/mikkelfj/work/pub/flatcc/build/Debug/test/json_test/generated -I/Users/mikkelfj/work/pub/flatcc/include -DFLATCC_REFLECTION=1 -Wstrict-prototypes -Wsign-conversion -Wconversion -pedantic -Wall -Wextra -Werror -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.7 -c -std=c11 -resource-dir=/usr/local/Cellar/llvm/14.0.6/lib/clang/14.0.6 -- /Users/mikkelfj/work/pub/flatcc/test.c\n"
2022-10-31T16:33:35.181 helix_lsp::transport [ERROR] err <- "I[16:33:35.181] --> textDocument/publishDiagnostics\n"
2022-10-31T16:33:35.405 helix_lsp::transport [ERROR] err <- "I[16:33:35.404] --> $/progress\n"
2022-10-31T16:33:35.966 helix_lsp::transport [ERROR] err <- "I[16:33:35.966] <-- textDocument/didChange\n"
2022-10-31T16:33:36.021 helix_lsp::transport [ERROR] err <- "I[16:33:36.021] ASTWorker building file /Users/mikkelfj/work/pub/flatcc/test.c version 2 with command inferred from /Users/mikkelfj/work/pub/flatcc/test/json_test/test_basic_parse.c\n"
2022-10-31T16:33:36.021 helix_lsp::transport [ERROR] err <- "[/Users/mikkelfj/work/pub/flatcc/build/Debug]\n"

```

</details>

Platform
---------
MacOS 11.7 BigSur Intel

Terminal Emulator
-----------------
kitty 0.26.4 created by Kovid Goyal

Helix Version
-------------
helix 22.08.1 (66276ce6)

**Comment by DrunkRandomWalker** [comment] 2022-11-03 22:07
I'm having the same problem here.

**Comment by ventoso** [comment] 2022-12-02 03:59
I'm having the same problem here.

**Comment by creikey** [comment] 2022-12-02 06:02
Same problem. Even though it's set in clang-format which works with clangd. It was just working yesterday too! No idea what changed

**Comment by creikey** [comment] 2022-12-02 06:10
It seems like the `indent` field doesn't do anything, when it's set to `indent = { tab-width = 0, unit = "fjdskla" }` no behavior changes

**Comment by creikey** [comment] 2022-12-02 06:17
The indentation is only breaking inside a case statement, odd

**Comment by mikkelfj** [comment] 2022-12-02 09:06
I can add that although I did add .h to the C language extensions, indent is much more broken in .h files than in .c files.

**Comment by mikkelfj** [comment] 2022-12-02 15:03
> The indentation is only breaking inside a case statement, odd
No that is just particular instance. It's all over the place but hard to pin down.

**Comment by WhirlBean** [comment] 2022-12-22 05:18
add this commands under `[[language]]` to use clang-format
```
formatter = { command = 'clang-format', args = ["-dump-config > ~/.clang-format"] }
auto-format = true
```
`~/.clang-format` should be the path to your .clang-format file

**Comment by Triton171** [comment] 2023-02-11 13:04
I just created a PR (#5918) that removes some inconsistencies in the handling of indentation styles in Helix. If you want, you can check whether this resolves your issue. If not, it would be very helpful if you could post a small example of your issue so I can reproduce it.

Note that in general, helix doesn't handle `.clang-format` or other external style specifications, so they only matter if you're using an external formatter that looks for them. Additionally, the `unit` field in `languages.toml` should contain the string for _one level of indentation_. So if you want to indent with e.g. 4 spaces, then it should be `unit = "    "`. However, the setting in `languages.toml` may be overridden by:
- the auto-detected style of the file you're currently editing. Helix tries to "guess" the indentation that a file uses and if it has a high enough confidence, it will use this instead of the language default.
- invoking the `indent-style` command.

**Comment by pascalkuthe** [comment] 2023-07-16 02:02
I am closing this since #5918 has landed and there is no reproducible example here. Since the issue is quite old its likely been fixed (I haven't running in problems with C)

**Closed by pascalkuthe** 2023-07-16 02:02 UTC
Labels: C-bug, A-language-support

**Comment by mikkelfj** [comment] 2023-07-16 08:23
I'm sorry I did not follow up on this. I can only test on a released products. I have not seen it fixed yet, but I'm also not working much with latest Helix version in C for the time being. I will report back if I find it to still be an issue.

**Comment by blueneogeo** [comment] 2024-11-08 19:55
Since the problem does not seem to have been solved, I was able to solve this on my Mac by creating a `.clang-format` file in my project directory.  May not work on every project.

As an example, this is the content of my `.clang-format` file:

```
# from https://forum.juce.com/t/automatic-juce-like-code-formatting-with-clang-format/31624/20
---
AccessModifierOffset: -4
AlignAfterOpenBracket: DontAlign
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignEscapedNewlines: Left
AlignOperands: Align
AlignTrailingComments: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: Never
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: All
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: Yes
BinPackArguments: false
BinPackParameters: false
BreakAfterJavaFieldAnnotations: false
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Custom
BraceWrapping: # Allman except for lambdas
  AfterClass: true
  AfterCaseLabel: true
  AfterFunction: true
  AfterNamespace: true
  AfterStruct: true
  BeforeElse: true
  AfterControlStatement: Always
  BeforeLambdaBody: false
BreakBeforeTernaryOperators: true
BreakConstructorInitializersBeforeComma: false
BreakStringLiterals: false
ColumnLimit: 0
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: false
DerivePointerAlignment: false
DisableFormat: false
ExperimentalAutoDetectBinPacking: false
IndentCaseLabels: true
IndentPPDirectives: BeforeHash
IndentWidth: 4
IndentWrappedFunctionNames: true
KeepEmptyLinesAtTheStartOfBlocks: false
Language: Cpp
MaxEmptyLinesToKeep: 1
FixNamespaceComments: false
NamespaceIndentation: All
PointerAlignment: Left
ReflowComments: false
SortIncludes: true
SpaceAfterCStyleCast: true
SpaceAfterLogicalNot: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeCpp11BracedList: true
SpaceBeforeParens: NonEmptyParentheses
SpaceInEmptyParentheses: false
SpaceBeforeInheritanceColon: true
SpacesInAngles: false
SpacesInCStyleCastParentheses: false
SpacesInContainerLiterals: true
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard: "c++20"
TabWidth: 4
UseTab: Never
UseCRLF: false
---
Language: ObjC
BasedOnStyle: Chromium
BreakBeforeBraces: Allman
ColumnLimit: 0
IndentWidth: 4
KeepEmptyLinesAtTheStartOfBlocks: false
ObjCSpaceAfterProperty: true
ObjCSpaceBeforeProtocolList: true
PointerAlignment: Left
SpacesBeforeTrailingComments: 1
TabWidth: 4
UseTab: Never
```
