### ISSUE TITLE
Automatically add commenting on newline while inside a comment

### ISSUE THREAD

**Issue by 2dav** [helix-editor/helix#6719] opened 2023-04-12 05:23 UTC
When editing rust-lang doc-comments it would be handy to have `///` or `//!` automatically inserted when user inputs a new line. This might also cover usual single-line comments `//` too. 

As an example of this feature in action look at vim with `rust.vim` plugin
```
//! comment\n
//! _
```
apart from '//!' it also adds a space.
With a multi-line comment it adds `*` and surrounding spaces to align the caret
```
/* comment\n
 * _
```
and if you type a closing `/` it removes the last space to get a `*/`.

**Comment by gabydd** [comment] 2023-04-12 05:39
duplicate of https://github.com/helix-editor/helix/issues/1730

**Closed** 2023-04-12 05:40 UTC
Labels: C-enhancement

**Comment by johnbchron** [comment] 2024-11-25 12:07
Hey this really feels like it should be a config-switched feature, and probably disabled by default. This is a "breaking change" experience-wise, especially for people who don't want to use this feature.

(For reference, my specific use case is writing doc comments for Rust struct fields. Most of the time they're just 1 line, and then when I hit newline I have to delete the comment characters before I write the field)
