### ISSUE TITLE
Adjacent multi-cursors (selections) fuse into one after a change

### ISSUE THREAD

**Issue by eed3si9n** [helix-editor/helix#5611] opened 2023-01-20 20:25 UTC
### Summary

When multi-selections are adjacent, hitting `c` to change fuses into one.

### Reproduction Steps

 

I tried this:

Given

```
orangeorange
```

I typed `xsorange<nl>capple<esc>`

I expected the buffer to contain:

```
appleapple
```

Instead, the buffer contains:

```
apple
```

### Platform

Linux

### Terminal Emulator

tmux + iTerm

### Helix Version

22.12-148-gf43f3b49

**Comment by the-mikedavis** [comment] 2023-01-21 18:29
Duplicate of https://github.com/helix-editor/helix/issues/2298

Also see https://github.com/helix-editor/helix/issues/3632

**Closed by the-mikedavis** 2023-01-21 18:29 UTC
Labels: C-bug
