### ISSUE TITLE
thread main panicked - after clicking undo

### ISSUE THREAD

**Issue by norregaarden-scalgo** [helix-editor/helix#4777] opened 2022-11-16 14:21 UTC
### Summary

by the way you hit some nice numbers: ![image](https://user-images.githubusercontent.com/104500282/202204825-f5edd445-9d5c-424a-ba9c-e182458b6b21.png)

this is the error I got when Helix closed with unsaved changes...

```
thread 'main' panicked at 'Position 6815 is out of range for changeset len 6814!', helix-core/src/transaction.rs:397:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Ubuntu

### Terminal Emulator

Alacritty

### Helix Version

22.08.1-445-gdf6d0442

**Comment by the-mikedavis** [comment] 2022-11-16 16:18
Do you have a concrete reproduction case that can cause this crash? This particular panic is hard to reproduce.

If you were using window splits, this may be fixed by #4733

**Comment by norregaarden-scalgo** [comment] 2022-11-17 09:22
I do not have a concrete reproduction case that can cause this crash. Honestly I'm not sure if it is even because I clicked undo. Helix has crashed similar to this many times, not only when I didn't know what I clicked, but mostly when I started using Helix a month or two ago, so I reported this because it is now a rare event.

Can I ask, while we're here, is Helix supposed to forget your registers when you close the program? I don't want to type my macros again every time.

I must say, thank you for making this editor, it is fun to follow the project. I really don't mind the lack of plugins and sessions (and saving registers), that simplicity makes it nice. And the selection mode is just what I missed.

Another unrelated thing while we're here: In the beginning, I was quite happy about the keybind menus, but I wanted a menu in the beginning that said which keys open keybind menus, i.e.   `:`, `[`, `g`, `space`. I had FOMO about there being a menu I didn't know about.

I was using vertical window split, but I don't know if it is related.

Thanks again. Just go ahead and close the issue.

**Comment by the-mikedavis** [comment] 2022-11-18 00:22
Since you had a split I think this is https://github.com/helix-editor/helix/issues/4732. I'll close in favor of that.

> is Helix supposed to forget your registers when you close the program?

Persisting state like registers is covered in https://github.com/helix-editor/helix/issues/401

**Closed by the-mikedavis** 2022-11-18 00:22 UTC
Labels: C-bug, A-core
