### ISSUE TITLE
Syntax Highlighting color shifts for `variable.parameter` based on code in viewport

### ISSUE THREAD

**Issue by tauseefk** [helix-editor/helix#10057] opened 2024-03-30 22:47 UTC
### Summary

The syntax highlighting for `variable.parameter` changes based on whether the function declaration (specifically the parameter) is visible in the viewport or not.

| Correct Color  | Incorrect Color |
| ------------- | ------------- |
| <img width="1419" alt="Screenshot 2024-03-30 at 2 59 21 PM" src="https://github.com/helix-editor/helix/assets/11029896/72913f12-93c6-48e4-9a25-31fb0018b5cb">  | <img width="1419" alt="Screenshot 2024-03-30 at 2 59 33 PM" src="https://github.com/helix-editor/helix/assets/11029896/2ed06603-32e2-4d51-ac79-9351593a358e"> |

My guess is that the editor doesn't look at variables declared outside the viewport as an optimization, however the UX is somewhat jarring.

### <theme>.toml
```TOML
...
"variable" = "pine"
"variable.parameter" = { fg = "sand" }
"variable.other.member" = { fg = "sand" } # accessed fields of structs
"variable.builtin" = { fg = "pine" }
...

[palette]
bright-pine = '#7AA697'
pine = '#3D8C8C'
dim-pine = '#747D6A'
dark-pine = '#354247'
sand = '#FFF4BA'
```

### Reproduction Steps

I tried this:

I've been able to reproduce this on several repos (some rust, and some typescript).
[![asciicast](https://asciinema.org/a/vUuGLzagZ5MGqdjjxmyTmgFmy.svg)](https://asciinema.org/a/vUuGLzagZ5MGqdjjxmyTmgFmy)

Observe that the color of the variable `tx_callback` is different depending on whether the function declaration is in the viewport or not.

Repo that can be used to reproduce: https://github.com/tauseefk/streamformers

1. `git clone git@github.com:tauseefk/streamformers.git`
2. `cd streamformers`
3. `hx src/main.rs`
4. scroll to function `infer` line `75`

I expected this to happen:
1. variable `tx_callback` to be colored `#FFF4BA`

Instead, this happened:
1. variable `tx_callback` to be colored `#7AA697`

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```
2024-03-30T14:30:47.278 helix_view::editor [ERROR] Failed to initialize the language servers for `source.toml` - `taplo` { cannot find binary path }
2024-03-30T14:41:25.192 helix_view::editor [ERROR] editor error: No configured language server supports range formatting
2024-03-30T14:55:13.214 helix_view::editor [ERROR] Failed to initialize the language servers for `source.toml` - `taplo` { cannot find binary path }
2024-03-30T15:03:23.671 helix_view::editor [ERROR] Failed to initialize the language servers for `source.toml` - `taplo` { cannot find binary path }
2024-03-30T15:18:55.920 helix_view::editor [ERROR] Failed to initialize the language servers for `source.css` - `vscode-css-language-server` { cannot find binary path }
2024-03-30T15:19:08.618 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-30T15:19:08.731 helix_term::application [WARN] Received unregistration request for unsupported method: workspace/didChangeConfiguration
2024-03-30T15:19:08.731 helix_term::application [WARN] Received unregistration request for unsupported method: textDocument/rangeFormatting
2024-03-30T15:19:08.731 helix_term::application [WARN] Received unregistration request for unsupported method: textDocument/onTypeFormatting
2024-03-30T15:19:08.731 helix_term::application [WARN] Received unregistration request for unsupported method: textDocument/rename
2024-03-30T15:19:08.731 helix_term::application [WARN] Received unregistration request for unsupported method: textDocument/formatting
2024-03-30T15:19:08.731 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
2024-03-30T15:19:08.731 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
2024-03-30T15:19:08.731 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
2024-03-30T15:23:41.876 helix_view::editor [ERROR] Failed to initialize the language servers for `source.toml` - `taplo` { cannot find binary path }

</details>

### Platform

MacOS Sonoma (14.2.1 (23C71))

### Terminal Emulator

Alacritty version 0.13.1

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by the-mikedavis** [comment] 2024-03-30 22:49
Duplicate of #1151

**Closed by the-mikedavis** 2024-03-30 22:49 UTC
Labels: C-bug
