### ISSUE TITLE
Rename custom mappings to readable text

### ISSUE THREAD

**Issue by alibektas** [helix-editor/helix#6863] opened 2023-04-24 11:29 UTC
I kinda want to customize how a command like this following snippet from my
`config.toml` 

```toml
[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
```

rendered to text when I press `Space`. What is now rendered is `:toggle lsp.display-inlay-hints` but I want it to be plainly `Toggle inlay hints`. Is there such a feature ?

**Comment by the-mikedavis** [comment] 2023-04-24 11:55
Duplicate of https://github.com/helix-editor/helix/issues/1752

**Closed** 2023-04-24 11:55 UTC
