### ISSUE TITLE
Feature Request: Global Search via <Space> / behave like telescope.live_grep()

### ISSUE THREAD

**Issue by thienpow** [helix-editor/helix#2092] opened 2022-04-13 01:53 UTC
it would be great if the global search can popup immediately for the search result preview instead of staying at bottom status bar then only show the popup... also the input textbox at the popup should do the global fuzzy search instead of filter by filename....

**Comment by the-mikedavis** [comment] 2022-04-13 02:31
duplicate of #196

I updated the title of that issue to make it clearer. The intention is for global search to be interactive as you say - the current implementation is a first step.

**Closed by the-mikedavis** 2022-04-13 02:31 UTC
