### ISSUE TITLE
:write will select entire buffer and move the cursor

### ISSUE THREAD

**Issue by PORTALSURFER** [helix-editor/helix#4028] opened 2022-09-29 13:27 UTC
Whenever I write a buffer to disk using :w 
The entire buffer is selected, and my cursor is moved to the starting position.

I would prefer it if I can continue from where my cursor was before saving instead of losing it every time and having to find where I was again.

**Comment by kirawi** [comment] 2022-09-29 13:45
Duplicate of #3859

**Closed by kirawi** 2022-09-29 13:45 UTC
