### ISSUE TITLE
Duplicated key event on Windows

### ISSUE THREAD

**Issue by yzwduck** [helix-editor/helix#6144] opened 2023-03-01 00:34 UTC
### Summary

When pressing a key, the event is registered twice: one at keydown, the other at keyup. It makes impossible to type any command (on Windows).

git bisect suggests 79bf5e3094e16a34637703b14c7bf090d2dcf155 is the offending commit.

### Reproduction Steps

I tried this:

1. `hx`,
2. Press `:` key once,

I expected this to happen:

Single `:` appears at the bottom.

Instead, this happened:

`::` appears at the bottom.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-03-01T08:28:10.236 helix_loader [DEBUG] Located configuration folders: ["D:\\Rust\\helix\\.helix"]
2023-03-01T08:28:10.312 helix_term::application [WARN] failed to load theme `base16_transparent` - The system cannot find the path specified. (os error 3)
2023-03-01T08:28:10.327 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-01T08:28:10.334 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-01T08:28:10.340 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-01T08:28:10.731 helix_term::application [DEBUG] received editor event: IdleTimer
2023-03-01T08:28:11.081 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-01T08:28:11.144 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-01T08:28:11.493 helix_term::application [DEBUG] received editor event: IdleTimer
2023-03-01T08:28:11.916 helix_view::editor [ERROR] editor error: no such command: ':'
2023-03-01T08:28:11.918 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-01T08:28:12.017 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-03-01T08:28:12.420 helix_term::application [DEBUG] received editor event: IdleTimer
2023-03-01T08:28:14.114 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
```

</details>

### Platform

Windows

### Terminal Emulator

cmd

### Helix Version

22.12-310-g8dab8a0a

**Comment by kirawi** [comment] 2023-03-01 00:39
Duplicate of https://github.com/helix-editor/helix/issues/6144

**Closed by kirawi** 2023-03-01 00:39 UTC
Labels: C-bug
