### ISSUE TITLE
:write command not working as expected

### ISSUE THREAD

**Issue by curioustolearn** [helix-editor/helix#8360] opened 2023-09-22 22:49 UTC
### Summary

I added the following lines to my config file

```
[keys.insert]
'j' = {'k' = [":write", "normal_mode"]}  ## map jk to save and exit to normal mode.
```

When I type the `jk` keys in the insert mode, the editor enters the normal mode as expected. It also shows a message that the file was written. However, the `[+]` symbol in the modeline does not go away. When I try to close the buffer, I get a warning that there are unsaved changes. If I switch to insert mode again and then press `jk` again then the `[+]` symbol goes away, and it is as if I type `:w` in the normal mode.

### Reproduction Steps

 

I tried this:

1. Add the following lines to the config file and reload:

```
[keys.insert]
'j' = {'k' = [":write", "normal_mode"]}  ## map jk to save and exit to normal mode.
```

2. Open a file and write something to it. Press `jk`.

At this point I expect the `[+]` symbol in the modeline to go away. But it does not. The editor goes into the `normal_mode` as expected.

3. Press `i` to enter insert mode and then type `jk` again. Now, the `[+]` symbol goes away. 

### Platform

macOS

### Terminal Emulator

iterm2

### Helix Version

helix 23.05 (7f5940be)

**Comment by kirawi** [comment] 2023-09-23 00:41
Dupe of https://github.com/helix-editor/helix/issues/6513

**Closed by kirawi** 2023-09-23 00:41 UTC
Labels: C-bug
