### ISSUE TITLE
set-option completion shown after first argument is set

### ISSUE THREAD

**Issue by askreet** [helix-editor/helix#5947] opened 2023-02-12 14:15 UTC
### Summary

Noticed this while looking at #5939. If you start typing `:set-option bufferline` you get completion while typing `bufferline`. If you then press space you get _new_ completion of options for the 2nd argument. Perhaps we want completion that is related to the option, but at least the completion probably should not be displayed for the 2nd argument.

### Reproduction Steps

 

I tried this:

1. Start typing `set-option mouse true`.

I expected this to happen:

No completion after `set-option mouse` while typing the 2nd argument.

Instead, this happened:

New completion showing all options is shown.

### Platform

macOS

### Terminal Emulator

iTerm 2

### Helix Version

22.12-257-ga4751db8

**Comment by the-mikedavis** [comment] 2023-02-12 17:28
Duplicate of https://github.com/helix-editor/helix/issues/2772

**Closed by the-mikedavis** 2023-02-12 17:28 UTC
Labels: C-bug, R-duplicate
