### ISSUE TITLE
feature request: need a complement feature like VIM's default Ctrl+p

### ISSUE THREAD

**Issue by miketang84** [helix-editor/helix#7026] opened 2023-05-12 02:58 UTC
feature request: need a complement feature like VIM's default Ctrl+p.

Ctrl + p is very useful for tokens in already open buffers.

**Comment by kirawi** [comment] 2023-05-12 04:51
Duplicate of https://github.com/helix-editor/helix/issues/1063
Next time, please search for previous issues and use the most appropriate issue template.

**Closed** 2023-05-12 04:51 UTC
