### ISSUE TITLE
Helix crashes when opening file picker

### ISSUE THREAD

**Issue by timrekelj** [helix-editor/helix#4653] opened 2022-11-08 15:25 UTC
### Summary

In some situations, helix freezes when opening file picker. In my case it breaks in rust project and home directory, but works well in vue project (those are the only ones I tried).

Another thing, if I open helix with `hx .`, it succesfully opens file picker, but then crashes when I try to open it again.

### Reproduction Steps

 

I tried this:
1. `cd` into project directory (in my case rust project)
2. `hx`
3. `<space> F` or `<space> f`

I expected this to happen:
File picker should open.

Instead, this happened:
Helix freezes and I have to restart terminal to use it again. 

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-11-08T10:53:52.858 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T11:20:52.241 helix_view::editor [ERROR] Failed to initialize the LSP for `source.sql` { LSP not defined }
2022-11-08T13:46:11.394 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T13:57:48.193 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T13:58:21.497 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T13:59:26.653 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T14:01:32.669 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2022-11-08T14:01:33.682 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:01:33.682 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:01:33.682 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.\n"
2022-11-08T14:01:33.683 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:01:33.683 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createCallExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:02:53.227 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T14:04:29.066 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2022-11-08T14:04:30.038 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:04:30.038 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:04:30.038 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.\n"
2022-11-08T14:04:30.038 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:04:30.038 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createCallExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:07:01.850 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T14:11:28.253 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T14:11:46.947 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2022-11-08T14:11:47.869 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:11:47.869 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:11:47.869 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.\n"
2022-11-08T14:11:47.869 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:11:47.869 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createCallExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:12:52.127 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2022-11-08T14:12:53.096 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:12:53.096 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:12:53.096 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.\n"
2022-11-08T14:12:53.096 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:12:53.096 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createCallExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:17:38.526 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T14:25:12.068 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T14:26:57.865 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2022-11-08T14:26:58.750 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:26:58.750 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:26:58.750 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.\n"
2022-11-08T14:26:58.750 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:26:58.750 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createCallExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:31:33.162 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2022-11-08T14:31:34.071 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:31:34.072 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:31:34.072 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.\n"
2022-11-08T14:31:34.072 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:31:34.072 helix_lsp::transport [ERROR] err <- "DeprecationWarning: 'createCallExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.\n"
2022-11-08T14:33:33.052 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-08T14:51:51.504 helix_view::editor [ERROR] Failed to initialize the LSP for `source.lua` { cannot find binary path }
```

</details>

### Platform

Linux (Fedora 36)

### Terminal Emulator

Kitty and terminator

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by timrekelj** [comment] 2022-11-08 15:27
I submited helix.log but I don't think it is relevant as I was trying to fix at around 15:30 nut there is no log from that time

**Comment by the-mikedavis** [comment] 2022-11-08 15:45
Duplicate of https://github.com/helix-editor/helix/issues/1707

**Closed by the-mikedavis** 2022-11-08 15:45 UTC
Labels: C-bug
