### ISSUE TITLE
bug with default theme color `ui.selection.primary` same as `ui.selection`

### ISSUE THREAD

**Issue by yashpalgoyal1304** [helix-editor/helix#5314] opened 2022-12-27 06:48 UTC
bug with default theme color `ui.selection.primary` same as `ui.selection`

just tested on hx v22.05, and I'd say that this is a bug indeed with the default theme.

_Originally posted by @yashpalgoyal1304 in https://github.com/helix-editor/helix/issues/5309#issuecomment-1365621210_

**Comment by kirawi** [comment] 2022-12-27 13:47
Duplicate of https://github.com/helix-editor/helix/issues/3842

**Closed by kirawi** 2022-12-27 13:47 UTC

**Comment by yashpalgoyal1304** [comment] 2022-12-27 14:05
hi @kirawi 
thanks for linking to the above issue. umh, so, will u reject the pr as well? 😅 

umh, this issue can be considered to be worthwhile to stay open as this is for the default theme, while the other one refers to themes in general.

With default theme, one expects it to be good enough for different distinctions, whereas when using a different theme, it's given that it may not be a proper one.
