### ISSUE TITLE
Automated save of selection state history -> allow for undoing selections with cursor returning to pre-selection state

### ISSUE THREAD

**Issue by theHausdorffMetric** [helix-editor/helix#2950] opened 2022-07-03 13:28 UTC
Frequently when making an erroneous selection (e.g. vim muscle memory presses `x`) I would like to unselect and remain at the pre-selection location. Collapsing the selection with `;` jumps to the end of the selection, necessitating jumping back. Saving the last n selections would allow for an undo selection operation.

**Comment by sudormrfbin** [comment] 2022-07-15 18:21
Duplicate of #1596.

**Closed by sudormrfbin** 2022-07-15 18:21 UTC
Labels: C-enhancement
