### ISSUE TITLE
Python auto indent not working

### ISSUE THREAD

**Issue by willparsons** [helix-editor/helix#1935] opened 2022-04-02 19:49 UTC
### Summary

When making a new line it is not auto-indenting.

### Reproduction Steps

 

I tried this:

*  Make a new line in a function

I expected this to happen:
* Automatically indent the line

Instead, this happened:
* Nothing

### Platform

Ubuntu WSL

### Terminal Emulator

windows terminal  1.11.3471.0

### Helix Version

22.03

**Comment by kirawi** [comment] 2022-04-02 20:34
Which language is this with?

**Comment by kirawi** [comment] 2022-04-02 22:11
This might be a dupe of https://github.com/helix-editor/helix/issues/763

**Closed** 2022-04-02 22:11 UTC
Labels: C-bug
