### ISSUE TITLE
Helix leaves the cursor blinking

### ISSUE THREAD

**Issue by iio7** [helix-editor/helix#3741] opened 2022-09-07 23:14 UTC
I have my xterm cursor setup to not blink:

```
xterm*cursorBlink: false
```

In Helix, the cursor doesn't blink. But when I exit a file and returns to xterm, the cursor is blinking.

This only happens with Helix in xterm, not with Helix in st, Alacritty or kitty.

I am running Arch Linux 5.19.7-arch1-1 with Helix version 22.08.1.

**Comment by the-mikedavis** [comment] 2022-09-07 23:21
Partially a duplicate of https://github.com/helix-editor/helix/issues/2684

The PR against that issue fixed the problem on most terminals but some may interpret the `\x1B[0 q` code differently. Once we have terminfo knowledge we should be able to restore the cursor more consistently across terminals

**Closed by the-mikedavis** 2022-09-07 23:21 UTC
