### ISSUE TITLE
Show Symbol type and allow filter by type in the Symbol Picker UI

### ISSUE THREAD

**Issue by that-ambuj** [helix-editor/helix#8352] opened 2023-09-22 07:32 UTC
When opening the file or workspace symbol picker in helix; the left panel only shows symbol names without any indication of the type of the symbol(struct, method or function, etc.). It would be great if we could hint these types alongside of the symbol names. It would also be easier to filter the symbols by type (like searching for method).

![image](https://github.com/helix-editor/helix/assets/97109381/255f6056-da83-496d-8e40-5d74a6fac582)
_This is how neovim's Telescope shows symbols alongwith their types_

![image](https://github.com/helix-editor/helix/assets/97109381/813de931-840c-4eb5-8875-2e304fb17838)
_This is how helix does this, only allowing to search by name and not type_

**Comment by the-mikedavis** [comment] 2023-09-22 11:30
Duplicate of https://github.com/helix-editor/helix/issues/5446

**Closed by the-mikedavis** 2023-09-22 11:30 UTC
Labels: C-enhancement
