### ISSUE TITLE
Support interactive grep in global search UI

### ISSUE THREAD

**Issue by dasBurdock** [helix-editor/helix#2233] opened 2022-04-23 08:55 UTC
I believe using the FilePicker UI for global_search isn't as ergonomic as interactively editing the grep regex. In addition, it prevents extending the picker with substitution syntax. 

I imagine supporting something like `live_grep` by inverting the dialog, creating a FilePicker with two dialogs, or maybe just using a `:picker-filter {regex}` command. 

`live_grep` example: https://github.com/nvim-telescope/telescope.nvim

**Comment by the-mikedavis** [comment] 2022-04-23 12:57
Duplicate of https://github.com/helix-editor/helix/issues/196

**Closed by the-mikedavis** 2022-04-23 12:57 UTC
Labels: C-enhancement
