### ISSUE TITLE
LSP autocomplete complete a different text then the popup

### ISSUE THREAD

**Issue by otavioschwanck** [helix-editor/helix#5317] opened 2022-12-27 12:59 UTC
### Summary

<img width="730" alt="image" src="https://user-images.githubusercontent.com/9551316/209670121-a948cff2-6e89-4573-aa45-da78da7caf5c.png">

### Reproduction Steps

<img width="730" alt="image" src="https://user-images.githubusercontent.com/9551316/209670121-a948cff2-6e89-4573-aa45-da78da7caf5c.png">

### Helix log

https://pasteio.com/x4ZCuSuN8uvE

### Platform

mac

### Terminal Emulator

alacritty

### Helix Version

helix 22.12 (96ff64a8)

**Comment by kirawi** [comment] 2022-12-27 13:45
Duplicate of https://github.com/helix-editor/helix/issues/4851

**Closed by kirawi** 2022-12-27 13:45 UTC
Labels: C-bug
