### ISSUE TITLE
A way to auto-install LSPs like mason.nvim

### ISSUE THREAD

**Issue by mkblast** [helix-editor/helix#6555] opened 2023-04-02 14:00 UTC
Hi, great project!

To make installing Lsps more easy, a feature like [mason.nvim](https://github.com/williamboman/mason.nvim).
This would make using helix closer to an actual code editor.

**Comment by the-mikedavis** [comment] 2023-04-02 14:02
Duplicate of https://github.com/helix-editor/helix/issues/2152

**Closed by the-mikedavis** 2023-04-02 14:02 UTC
