### ISSUE TITLE
GIt Blame inline

### ISSUE THREAD

**Issue by holtkampjs** [helix-editor/helix#10721] opened 2024-05-09 20:14 UTC
# Suggestion

In popular editors like VSCode, one feature I enjoyed (while it sometimes muddied up the visual field) was inline git blame annotations

I.E.
![image](https://github.com/helix-editor/helix/assets/76000251/a717e4ad-ebc3-4276-b87d-90cd69cae97d)

Helix is my daily driver and sometimes I think it would be beneficial to have blame to see the last time a line was touched and by who. 

## Not as relevant

The reason I am submitting this enhancement is because I had recently been using `git blame [filename]` in my CLI and was just frustrated by the overwhelming/non-customizable output I was seeing (NOTE: I am aware various parts of the output such as hash length, email, and date-time format can be customized). I was just wishing I could view it in a more context friendly view. 

My initial reaction was to attempt a bash script to customize what I see using `git blame ... | awk '...' | bat -l <language>` and my alternative being to write it in a more organized manner in some language (e.g. Zig, Rust, Python, etc.). Through thinking about this, I realized that it may be more wieldy to push for the feature in the tools I use already i.e. this (`helix`) or `bat`.

Thank you for consideration.

**Comment by pascalkuthe** [comment] 2024-05-09 20:23
Duplicate of #3035

**Closed by pascalkuthe** 2024-05-09 20:23 UTC
Labels: C-enhancement
