### ISSUE TITLE
`underline` and `bar` cursor-shapes don't render the character under the cursor as selected.

### ISSUE THREAD

**Issue by leira** [helix-editor/helix#3296] opened 2022-08-02 00:40 UTC
The character under the cursor is always selected. It is clear with `block` cursor shape. I can clearly see `o` is part of the selection `ormal`:
<img width="275" alt="Screen Shot 2022-08-01 at 5 35 50 PM" src="https://user-images.githubusercontent.com/39118/182267453-806a9811-267d-41c6-9e14-5937ca88ff28.png">

But it is not obviously so in `underline` or `bar` cursor-shape. It doesn't seem to render the `o` under the cursor as selected:
<img width="266" alt="Screen Shot 2022-08-01 at 5 36 46 PM" src="https://user-images.githubusercontent.com/39118/182267455-5012b11b-a272-4c93-bac7-fad00dd31867.png">
<img width="257" alt="Screen Shot 2022-08-01 at 5 37 00 PM" src="https://user-images.githubusercontent.com/39118/182267456-bc59a9d8-4fc1-4fba-8baa-eadef250e693.png">

I think it would be clearer if the letter `o` has the same background color as `rmal`.

**Comment by Omnikar** [comment] 2022-08-02 07:13
This is a duplicate of #1568.

**Closed** 2022-08-02 10:06 UTC
Labels: C-enhancement
