### ISSUE TITLE
Helix stops responding when typing in nix file under specific, unknown conditions

### ISSUE THREAD

**Issue by Sympel** [helix-editor/helix#5874] opened 2023-02-07 22:30 UTC
### Summary

I was working on some nix flake file when helix suddenly stopped responding and my cpu usage skyrocketed. It always happened after adding a character in a specific place in the file. I reduced it to the minimal file I could find where I could still reproduce the issue:
`
pkgs.stdenv.mkDerivation {
  installPhase = ''
    mkdir -p $out/share/${a}
    cp -r ${a}/(${a}) .
  '';
};
`

When typing something  at the location marked with `#` `cp -r ${a}/(${a}#) .`, helix immediately stops responding. I don't know if this is an issue with helix, with treesitter or with something else.

### Reproduction Steps

 

I tried this:

1. `hx test.nix` with the following content:
`
pkgs.stdenv.mkDerivation {
  installPhase = ''
    mkdir -p $out/share/${a}
    cp -r ${a}/(${a}) .
  '';
};
`
2. Type something after `(${a}`
3. Watch helix freeze

I expected this to happen:
The text I typed should be inserted.

Instead, this happened:
Helix stopped responding and my cpu usage increased massively.

### Helix log

Does not contain anything relevant as far as I can tell, I had to kill helix before my pc gets overloaded.
<details><summary>~/.cache/helix/helix.log</summary>

```
2023-02-07T23:27:16.222 helix_loader [DEBUG] Located configuration folders: []
2023-02-07T23:27:16.229 helix_view::clipboard [INFO] Using wl-copy+wl-paste to interact with the system and selection (primary) clipboard
2023-02-07T23:27:16.249 helix_view::editor [ERROR] Failed to initialize the LSP for `source.nix` { cannot find binary path }
2023-02-07T23:27:16.249 helix_view::editor [DEBUG] editor status: Loaded 1 files.
2023-02-07T23:27:16.249 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
2023-02-07T23:27:16.249 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2023-02-07T23:27:16.250 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE
2023-02-07T23:27:16.250 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE
2023-02-07T23:27:16.250 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-02-07T23:27:16.330 helix_term::application [DEBUG] received editor event: IdleTimer
2023-02-07T23:27:17.518 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-02-07T23:27:17.619 helix_term::application [DEBUG] received editor event: IdleTimer
2023-02-07T23:27:17.703 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-02-07T23:27:17.804 helix_term::application [DEBUG] received editor event: IdleTimer
2023-02-07T23:27:17.859 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-02-07T23:27:17.960 helix_term::application [DEBUG] received editor event: IdleTimer
2023-02-07T23:27:18.056 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-02-07T23:27:18.143 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-02-07T23:27:18.244 helix_term::application [DEBUG] received editor event: IdleTimer
2023-02-07T23:27:18.313 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-02-07T23:27:18.414 helix_term::application [DEBUG] received editor event: IdleTimer
2023-02-07T23:27:18.615 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-02-07T23:27:18.716 helix_term::application [DEBUG] received editor event: IdleTimer
2023-02-07T23:27:18.775 helix_term::commands [TRACE] entering insert mode with sel: Selection { ranges: [Range { anchor: 96, head: 97, horiz: None }], primary_index: 0 }, text: "pkgs.stdenv.mkDerivation {\n  installPhase = ''\n    mkdir -p $out/share/${a}\n    cp -r ${a}/(${a}) .\n  '';\n};\n"
2023-02-07T23:27:18.775 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-02-07T23:27:18.876 helix_term::application [DEBUG] received editor event: IdleTimer
2023-02-07T23:27:18.876 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-02-07T23:27:18.939 helix_core::auto_pairs [TRACE] autopairs hook selection: Selection {
    ranges: [
        Range {
            anchor: 97,
            head: 96,
            horiz: None,
        },
    ],
    primary_index: 0,
}
```

</details>

### Platform

Linux

### Terminal Emulator

kitty 0.26.5

### Helix Version

helix 22.12

**Comment by the-mikedavis** [comment] 2023-02-07 22:41
This is another reproduction case of https://github.com/helix-editor/helix/issues/4862, I will close in favor of that issue.

It's caused by a bug in tree-sitter which has been fixed on tree-sitter's master branch. Once that is released to crates, we can upgrade and this will be fixed.

In the meantime if you're building from source you can add an override for the tree-sitter dependency to use master:

```toml
# ... add this block at the end of the Cargo.toml file in the helix repository root: ...
[patch.crates-io]
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter", rev = "e021d6e9799903312dfa3a1ed39e160008fe52ac" }
```

**Closed by the-mikedavis** 2023-02-07 22:41 UTC
Labels: C-bug
