### ISSUE TITLE
Allow to specify commands to execute as helix flag

### ISSUE THREAD

**Issue by Axlefublr** [helix-editor/helix#11587] opened 2024-08-27 11:38 UTC
Nvim has `-c cmd` and `+cmd` that lets you execute a command right after starting nvim. \
This is very convenient, and I would love to see this feature in helix! \
If you decide not to add this, for whatever reason, the current `--config` flag in helix can only be specified once; It would be more helpful if you could specify it multiple times, the latter configuration files overriding keys specified in the former.

To explain why either of those are useful: kitty lets you pipe the scrollback buffer into a program. \
That lets you execute some shell command, and then go quickly copy the output into your clipboard using your favorite editor. \
My favorite editor is no longer nvim, yet I'm forced to use it, because it allows me to set softwrap to false, specifically in the kitty pager thing:
```
map alt+space launch --type=overlay --stdin-source=@screen nvim -c 'KittyInput' -c 'norm 50%'
map shift+alt+space launch --type=overlay --stdin-source=@screen_scrollback nvim -c 'KittyInput' -c 'norm G'
```

To replicate this special behavior, currently I would have to copy paste my entire helix config into a new file, change softwrap from true to false there, and use it with the `-c` option.

**Comment by kirawi** [comment] 2024-08-27 14:59
Duplicate of https://github.com/helix-editor/helix/discussions/10021

**Closed by kirawi** 2024-08-27 14:59 UTC
Labels: C-enhancement
