### ISSUE TITLE
JSON schema for config files

### ISSUE THREAD

**Issue by niklasravnsborg** [helix-editor/helix#10990] opened 2024-06-18 15:54 UTC
Having schemas for the Helix config files (`config.toml`, `some_theme.toml`, `languages.toml`) would be highly beneficial. This would not only facilitate easier editing of configurations but could also enable auto-generation of documentation tables or other useful outputs.

Schemas can be integrated using the `$schema` key to enable editor completions:

```toml
"$schema" = 'https://example.org/schema.json'
```

For reference, here are a few example schema files:
- [Starship](https://github.com/starship/starship): https://starship.rs/config-schema.json
- [Yazi](https://github.com/sxyazi/yazi): https://raw.githubusercontent.com/yazi-rs/schemas/main/schemas/yazi.json
- [Alacritty](https://github.com/alacritty/alacritty): https://raw.githubusercontent.com/distinction-dev/alacritty-schema/main/alacritty/reference.json

Resources for creating a schema:

- [Writing a schema](https://json-schema.org/learn/getting-started-step-by-step)
- [Adding a schema to JSON Schema Store](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#how-to)

**Comment by the-mikedavis** [comment] 2024-06-18 16:09
Duplicate of https://github.com/helix-editor/helix/issues/3901, also see https://github.com/helix-editor/helix/pull/8644

**Closed by the-mikedavis** 2024-06-18 16:09 UTC
Labels: C-enhancement
