### ISSUE TITLE
It seems there is no way to change the mapping for window mode

### ISSUE THREAD

**Issue by lennyitb** [helix-editor/helix#10941] opened 2024-06-12 20:43 UTC
There is no command associated with entering window mode, and it therefore seems I can't create a mapping like:
```
[keys.normal.space]
ret = "window_mode"
```
or even alternatively:
```
[keys.normal.space]
ret = "C-w"
```
Neither of these work; this may seem like a silly thing, but I would like for `<space-w>` to map to `:w`, I'm certain I'm not alone as this is a somewhat common vim mapping. With this I therefore would like an alternative way to get into window mode. For now I've simply mapped `ret = ":w"`, to me it's an acceptable workaround.

Adding the command `window_mode` would be useful for many and a breaking a breaking change for no one. Thanks for your consideration, as well as this project. I hope this input is helpful.

**Comment by the-mikedavis** [comment] 2024-06-12 20:54
Duplicate of https://github.com/helix-editor/helix/issues/5734, also see https://github.com/helix-editor/helix/issues/10389. This is something we want to solve eventually with a more powerful config system but for now you need to remap each of the commands in window mode

**Closed by the-mikedavis** 2024-06-12 20:54 UTC
Labels: C-enhancement
