### ISSUE TITLE
Treesitter parameter highlighting only works when definition is visible on screen

### ISSUE THREAD

**Issue by rosvall** [helix-editor/helix#2285] opened 2022-04-26 09:05 UTC
### Summary

I'm trying to get parameter highlighting working. I can only make it work when parameter definition is visible. 

I'm guessing helix is only running the visible text through tree-sitter. 
Is this is on purpose or a bug?

### Screenshots:
1. **GOOD:** Parameter `parameter` defined on line 3 correctly underlined both on line 3 and when referenced on line 11.
   ![screenshot_1](https://user-images.githubusercontent.com/1581070/165258910-12bb2186-0405-4151-a7c8-cfbebc9c8a4a.png)
   
2. **BAD:** Viewport scrolled so definition isn't visible. Reference no longer underlined.
   ![screenshot_2](https://user-images.githubusercontent.com/1581070/165258941-193b8525-53d0-4ae0-bd46-087f5e1ea138.png)

### Reproduction Steps

Reproduction for **javascript**: 
1. Copy-paste contents of 
   `runtime/queries/javscript/highlight-params.scm`
   in to the top of
   `runtime/queries/javscript/highlight.scm`
3. Add a 
   `"variable.parameter" = {modifiers=["underlined"]}`
   rule to your theme.

### Platform

Linux

### Terminal Emulator

xfce4-terminal (vte)

### Helix Version

helix 22.05-dev

**Comment by the-mikedavis** [comment] 2022-04-26 11:51
Duplicate of https://github.com/helix-editor/helix/issues/1151

**Closed by the-mikedavis** 2022-04-26 11:51 UTC
Labels: C-bug
