### ISSUE TITLE
Auto import doesn't work

### ISSUE THREAD

**Issue by sohnryang** [helix-editor/helix#2142] opened 2022-04-17 11:38 UTC
### Summary

I tried out the auto-import feature that got [merged recently](https://github.com/helix-editor/helix/pull/2088), but it is not working.

### Reproduction Steps

 

I tried this:

0. Create a new Rust project using `cargo new test_project`, and `cd` to the project root.
1. Run the editor using `hx src/main.rs`.
2. Make a new line after the line containing `println!`, and type `Dur`.
3. LSP suggests `Duration`. Select it by pressing control-n.

I expected this to happen:
By selecting the suggestion, `use std::time::Duration` should be added to the source code.

Instead, this happened:
The editor completes to `Duration`, but does not add `use` statement to the code.

### Helix log

The log is too long, so I'll attach it separately.
[helix.log](https://github.com/helix-editor/helix/files/8501476/helix.log)

### Platform

Linux (kernel version: `5.17.2-arch3-1`)
`rust-analyzer 2022-04-11`

### Terminal Emulator

`wezterm 20220408-101518-b908e2dd`

### Helix Version

`22.03-95-gc45fb08a`

**Comment by archseer** [comment] 2022-04-19 12:44
@andreytkachenko I also can't get this working, the completion appears but the import isn't getting added. I assume `additionalTextEdits` isn't resolved correctly

**Comment by andreytkachenko** [comment] 2022-04-19 14:50
@archseer The only case I can reproduce the bug with if there are some changes happened between `complete` and `resolve` requests and server responds with content changed error (I guess we need handle that error somehow). But I didn't noticed any resolve requests in attached logs. It looks like `additionalTextEdits` contains something, but logs don't shows that `additionalTextEdits` in after `complete` contains something. Sorry I need more data to reproduce that. I am using RA version 2022-03-28, helix 22.05-dev (855e438f), both debug and release, wezterm, alacritty, gnome-terminal. But unable to reproduce it. I did pure clone and pure `cargo new` for demo project, but it works.

**Comment by theli-ua** [comment] 2022-06-10 01:03
I can reproduce this if I start typing Dur and make selection before ra completes indexing/etc

**Comment by sohnryang** [comment] 2022-06-12 23:14
I realized that I had to press enter in order to get auto-import... :sweat_smile:
Works fine for me now. Should I close this ticket?

**Comment by andreytkachenko** [comment] 2022-06-13 06:52
I can confirm that problem is not solved. I will fix it. Leave it open please for reference.

**Comment by pascalkuthe** [comment] 2023-07-16 14:03
I can not reproduce this anymore. It's hard to retroactively pinpoint but I guess this was likely fixed by #6173 or #6594 (likely the latter)

**Closed by pascalkuthe** 2023-07-16 14:03 UTC
Labels: C-bug, A-language-server
