### ISSUE TITLE
Display recent files at the top of file picker

### ISSUE THREAD

**Issue by DoctorRyner** [helix-editor/helix#11465] opened 2024-08-11 18:18 UTC
The title says it all

**Comment by Diogenesoftoronto** [comment] 2024-08-15 00:41
This is a good idea. Just managing recents in general like emacs recentf.

**Comment by the-mikedavis** [comment] 2024-08-15 15:10
This is mostly a duplicate of #2179

I don't think we should be changing the default sorting of the regular file finder for this. A separate picker should specialize in showing recent files.

**Closed by the-mikedavis** 2024-08-15 15:10 UTC
Labels: C-enhancement
