### ISSUE TITLE
Yank History Navigation after paste

### ISSUE THREAD

**Issue by otavioschwanck** [helix-editor/helix#4477] opened 2022-10-26 14:48 UTC
After pasting some with p or P, would be awesome to navigate on yank history with C-p and C-n.  Emacs already do that.

**Comment by tennix** [comment] 2022-11-13 03:58
+1. Coming from Emacs, I really wish Helix supports similar feature. Visualizing yank history makes it easier to copy & paste.

**Comment by pascalkuthe** [comment] 2024-04-12 00:35
Duplicate of #6900

**Closed by pascalkuthe** 2024-04-12 00:35 UTC
Labels: C-enhancement
