### ISSUE TITLE
Allow remapping of dot

### ISSUE THREAD

**Issue by ellbur** [helix-editor/helix#11054] opened 2024-06-29 02:59 UTC
Currently, with this in `config.toml`:

```toml
[keys.normal]
"." = "move_char_left"
```

the <kbd>.</kbd> key continues to have its default function (repeat last insert).

It would be nice to allow it to be remapped.

**Comment by the-mikedavis** [comment] 2024-06-29 04:04
Duplicate of https://github.com/helix-editor/helix/issues/1488. Currently `.` has special handling so it can't be remapped but it should be refactored as a regular command (which that issue covers)

**Closed by the-mikedavis** 2024-06-29 04:04 UTC
Labels: C-enhancement
