### ISSUE TITLE
Terminal freezes after `shell_insert_output` or `shell_append_output` and a command that reads from stdin

### ISSUE THREAD

**Issue by GabrielDertoni** [helix-editor/helix#4154] opened 2022-10-09 03:24 UTC
### Summary

When using the shell keymaps `|` or `Alt+|` (`shell_insert_output` and `shell_append_output`) the editor will prompt for a command to run. If that command requires stdin (like `cat -`) however, the entire shell will freeze since the child process will inherit the `stdin` from the parent which is not the expected behaviour.

The fix for this is pretty simple and I will submit a PR shortly.

### Reproduction Steps

I tried this:

1. (in normal mode) `|cat -`

I expected this to happen:

Nothing (or the selection to be fed as input to the command's stdin).

Instead, this happened:

The entire terminal froze up as I couldn't send stdin for the child process (`cat -`) that started.

### Helix log

Not applicable

### Platform

Linux (WSL)

### Terminal Emulator

Alacritty

### Helix Version

helix 22.08.1 (c15f1ea2)

**Comment by kirawi** [comment] 2022-10-09 03:33
Duplicate of #3524

**Closed by kirawi** 2022-10-09 03:33 UTC
Labels: C-bug
