### ISSUE TITLE
f-String support in Python

### ISSUE THREAD

**Issue by Renkai** [helix-editor/helix#6601] opened 2023-04-05 07:07 UTC
### Summary

When coding in Python if I type `"` after `f`, the matching `"` won't show, then I type `"` after `{foo}`, two `"` appears, I have to exit insert mode by `esc` and delete the extra `"` to get a correct Python expression.

```
foo = 3
bar = f"2333 {foo}"
print(bar)
```

### Reproduction Steps

 

I tried this:

1. `hx` with a Python file.
2. type a f-String

I expected this to happen:
Give me two `"` when I type the first `"`

Instead, this happened:
Give one `"` when I type the first `"`, give one extra `"` when I type the second `"`, then I have to remove the extra one.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-05T15:04:59.483 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/Users\/renkaige\/renkai-lab\/gitui-test\/hehe.py","diagnostics":[{"source":"pyflakes","range":{"start":{"line":2,"character":19},"end":{"line":2,"character":30}},"message":"EOL while scanning string literal","severity":1}]}}
2023-04-05T15:05:05.384 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":18,"line":2},"start":{"character":18,"line":2}},"text":"\"\""}],"textDocument":{"uri":"file:///Users/renkaige/renkai-lab/gitui-test/hehe.py","version":19}}}
2023-04-05T15:05:05.889 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":"b576f29b-428c-4e39-b5bb-49080d541edc","method":"window\/workDoneProgress\/create","params":{"token":"d87e1ce7-6cde-4ddd-a620-5ee44a79ab52"}}
2023-04-05T15:05:05.889 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","result":null,"id":"b576f29b-428c-4e39-b5bb-49080d541edc"}
2023-04-05T15:05:05.890 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"d87e1ce7-6cde-4ddd-a620-5ee44a79ab52","value":{"kind":"begin","title":"lint: pyflakes"}}}
2023-04-05T15:05:05.890 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"d87e1ce7-6cde-4ddd-a620-5ee44a79ab52","value":{"kind":"end"}}}
2023-04-05T15:05:05.890 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":"0e23df04-d6e5-4227-8c4d-cdd34b569022","method":"window\/workDoneProgress\/create","params":{"token":"902b139c-72f1-407c-8b7c-58f648636c8e"}}
2023-04-05T15:05:05.891 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","result":null,"id":"0e23df04-d6e5-4227-8c4d-cdd34b569022"}
2023-04-05T15:05:05.891 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"902b139c-72f1-407c-8b7c-58f648636c8e","value":{"kind":"begin","title":"lint: pycodestyle"}}}
2023-04-05T15:05:05.893 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"902b139c-72f1-407c-8b7c-58f648636c8e","value":{"kind":"end"}}}
2023-04-05T15:05:05.893 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":"ccb58dbf-c8b0-49d9-bbd7-f020321c9d56","method":"window\/workDoneProgress\/create","params":{"token":"be129e96-d416-4361-8df4-230ef4019670"}}
2023-04-05T15:05:05.893 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","result":null,"id":"ccb58dbf-c8b0-49d9-bbd7-f020321c9d56"}
2023-04-05T15:05:05.893 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"be129e96-d416-4361-8df4-230ef4019670","value":{"kind":"begin","title":"lint: mccabe"}}}
2023-04-05T15:05:05.894 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"be129e96-d416-4361-8df4-230ef4019670","value":{"kind":"end"}}}
2023-04-05T15:05:05.894 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/Users\/renkaige\/renkai-lab\/gitui-test\/hehe.py","diagnostics":[{"source":"pyflakes","range":{"start":{"line":2,"character":21},"end":{"line":2,"character":32}},"message":"EOL while scanning string literal","severity":1}]}}
2023-04-05T15:05:33.533 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":20,"line":2},"start":{"character":19,"line":2}},"text":""}],"textDocument":{"uri":"file:///Users/renkaige/renkai-lab/gitui-test/hehe.py","version":20}}}
2023-04-05T15:05:34.037 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":"ad8d1d57-08e0-4d81-ad8d-371ee12a8cfa","method":"window\/workDoneProgress\/create","params":{"token":"f2a6f14d-0db4-4869-9d8d-367d71cc089b"}}
2023-04-05T15:05:34.038 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","result":null,"id":"ad8d1d57-08e0-4d81-ad8d-371ee12a8cfa"}
2023-04-05T15:05:34.038 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"f2a6f14d-0db4-4869-9d8d-367d71cc089b","value":{"kind":"begin","title":"lint: pyflakes"}}}
2023-04-05T15:05:34.039 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"f2a6f14d-0db4-4869-9d8d-367d71cc089b","value":{"kind":"end"}}}
2023-04-05T15:05:34.039 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":"6dc4cc21-eb12-44eb-8f3e-23810071bb88","method":"window\/workDoneProgress\/create","params":{"token":"3a690b01-f804-4324-9151-3e04ad868953"}}
2023-04-05T15:05:34.039 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","result":null,"id":"6dc4cc21-eb12-44eb-8f3e-23810071bb88"}
2023-04-05T15:05:34.039 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"3a690b01-f804-4324-9151-3e04ad868953","value":{"kind":"begin","title":"lint: pycodestyle"}}}
2023-04-05T15:05:34.041 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"3a690b01-f804-4324-9151-3e04ad868953","value":{"kind":"end"}}}
2023-04-05T15:05:34.041 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":"71254550-feeb-4300-ab11-01067919f8f1","method":"window\/workDoneProgress\/create","params":{"token":"db066d47-0259-47bb-8ea7-8ec2e2e3f17b"}}
2023-04-05T15:05:34.041 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","result":null,"id":"71254550-feeb-4300-ab11-01067919f8f1"}
2023-04-05T15:05:34.041 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"db066d47-0259-47bb-8ea7-8ec2e2e3f17b","value":{"kind":"begin","title":"lint: mccabe"}}}
2023-04-05T15:05:34.041 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"$\/progress","params":{"token":"db066d47-0259-47bb-8ea7-8ec2e2e3f17b","value":{"kind":"end"}}}
2023-04-05T15:05:34.041 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/Users\/renkaige\/renkai-lab\/gitui-test\/hehe.py","diagnostics":[]}}
```

</details>

### Platform

macOS

### Terminal Emulator

wezterm

### Helix Version

helix 23.03

**Comment by gabydd** [comment] 2023-04-05 12:11
Duplicate of https://github.com/helix-editor/helix/issues/4035

**Closed** 2023-04-05 14:02 UTC
Labels: C-bug
