### ISSUE TITLE
Freezes when editing Markdown with embedded JavaScript

### ISSUE THREAD

**Issue by LukasKnuth** [helix-editor/helix#10032] opened 2024-03-28 10:57 UTC
### Summary

While editing a fenced JavaScript code-snippet in a Markdown file, the Editor freezes up. It does not react to anything and I have to `kill -9` it in order to close the process.

### Reproduction Steps

    ```javascript
     {
    arg
    }

    ```

**NOTE** The empty line at the end of the code-block is important!

I tried this:

1. `hx minimal_error.md`
2. Navigate the cursor _somehow_ onto the closing curly-bracket
3. The editor freezes while hovering the closing curly-bracket

**NOTE:** I can navigate around that closing curly-bracket as much as I like. It does not matter if I navigate onto it from the top using jjj or from the bottom using gekk. As long as I don't hover the bracket, the editor behaves as expected.

I expected this to happen:

The editor does not freeze and 

Instead, this happened:

The editor freezes and must be killed using `kill -9`

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
I have killed the editor about 30 times now trying to get a minimum reproducible snippet. All I see in the log from that time are the errors listed below, there is no additional information.

```
2024-03-28T11:50:37.771 helix_lsp::transport [ERROR] marksman err <- "[11:50:37 INF] <LSP Entry> Starting Marksman LSP ser
ver: {}\n"
2024-03-28T11:52:03.098 helix_lsp::transport [ERROR] marksman err <- "[11:52:03 INF] <LSP Entry> Starting Marksman LSP ser
ver: {}\n"
2024-03-28T11:52:57.661 helix_lsp::transport [ERROR] marksman err <- "[11:52:57 INF] <LSP Entry> Starting Marksman LSP ser
ver: {}\n"
2024-03-28T11:54:21.963 helix_lsp::transport [ERROR] marksman err <- "[11:54:21 INF] <LSP Entry> Starting Marksman LSP ser
ver: {}\n"
```

</details>

### Platform

macOS

### Terminal Emulator

iTerm2

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by pascalkuthe** [comment] 2024-03-28 11:21
know issue withi the last release caused by a bug in an old treesitter version, this has been fixed on master for a long time

**Closed by pascalkuthe** 2024-03-28 11:21 UTC
Labels: C-bug

**Comment by LukasKnuth** [comment] 2024-03-28 11:44
So the fix is to build the editor from source?

Any plans for a new release with the fixes?

**Comment by the-mikedavis** [comment] 2024-03-28 12:40
Or await the next release. We're planning to cut the next release in the next few days #9946
