### ISSUE TITLE
file-name element doesn't update when saving under INS mode

### ISSUE THREAD

**Issue by Hpmason** [helix-editor/helix#4719] opened 2022-11-12 04:31 UTC
### Summary

Saving file while in insert mode doesn't properly update the file-name `[+]`. It seems to mostly be just a graphical error, but on Linux (at least the machine I was SSHed into), saving in insert mode saves the file, but helix doesn't let you quit.
(And the saving while in insert mode is done with key mapping)

### Reproduction Steps

 
`config.toml`:
```
[keys.insert]
 C-s = ":w"
```
I tried this:

1. Open file `hx temp.txt`
2. Enter ins mode `i`
3. Enter text "hello world"
4. While still in insert mode try to save `C-s`
5. Quit out of file `ESC`, `:q`

I expected this to happen:
File would save and [+] would go away

Instead, this happened:
On windows:
File successfully saved, but the `[+]` did not successfully update on the file-name status bar.

On Linux (at least though SSH)
`[+]` graphic did not update, but the following message appeared under the status bar: `'temp.txt' written 4L 34B`. 
After exiting INS mode and trying to `:q` I get the following message: `1 unsaved buffer(s) remaining: ["temp.txt"]`. Force quitting exits the editor and the file seems to have saved correctly.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-11-12T04:17:39.287 helix_view::clipboard::provider [WARN] No clipboard provider found! Yanking and pasting will be internal to Helix
2022-11-12T04:17:53.244 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["temp.txt"]
2022-11-12T04:18:09.911 helix_view::clipboard::provider [WARN] No clipboard provider found! Yanking and pasting will be internal to Helix
2022-11-12T04:20:13.897 helix_view::clipboard::provider [WARN] No clipboard provider found! Yanking and pasting will be internal to Helix
2022-11-12T04:20:23.360 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["temp.txt"]
2022-11-12T04:20:28.330 helix_view::clipboard::provider [WARN] No clipboard provider found! Yanking and pasting will be internal to Helix
2022-11-12T04:20:41.857 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["temp.txt"]
2022-11-12T04:24:58.337 helix_view::clipboard::provider [WARN] No clipboard provider found! Yanking and pasting will be internal to Helix
2022-11-12T04:25:09.863 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["temp.txt"]
2022-11-12T04:26:34.739 helix_view::clipboard::provider [WARN] No clipboard provider found! Yanking and pasting will be internal to Helix
2022-11-12T04:28:19.549 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: [".cache/helix/helix.log"]
```

</details>

### Platform

Windows + Linux over SSH

### Terminal Emulator

Windows Terminal & xterm-256color over SSH

### Helix Version

helix 22.08.1 (001e4e30)

**Comment by vanarok** [comment] 2022-11-12 05:05
У меня тоже есть эта проблема:
config.toml
```
[keys.insert]
a = { k = ["normal_mode", ":update"] }
```

**Comment by archseer** [comment] 2022-11-19 04:25
Duplicate of https://github.com/helix-editor/helix/issues/3501

**Closed by archseer** 2022-11-19 04:25 UTC
Labels: C-bug, A-gui
