### ISSUE TITLE
Ctr-v Past in Windows 11 

### ISSUE THREAD

**Issue by xchray** [helix-editor/helix#10678] opened 2024-05-04 15:36 UTC
### Summary

I Feel this is a bug. Let me know this is not I am closing this issue. 
I am using windows 11 + powershell 7 + Win terminal. 
Now if I am opening HX, now I am in normal mode and ctrl-v past text, it is working but a bit strange way, The text seems been dump into hx through powershell or terminal, But the text will be inserted into HX if an insert command is encountered and only the text after the insert command will be past into HX. 

Everything is fine if I explicitly press i into insert mode. 

Thanks. 

### Reproduction Steps

 

I tried this:

1. `hx`
2. using example "This is example "
3. since i char trigger insert mode, and result being pasted is "s is example"

I expected this to happen:
I am not sure what to expect. Maybe all or nothing?

instead: 
 "s is example"

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

windows 

### Terminal Emulator

win terminal + powershell 7

### Installation Method

release page.

### Helix Version

24.3

**Comment by kirawi** [comment] 2024-05-04 15:39
Duplicate of https://github.com/helix-editor/helix/discussions/10295

**Closed by kirawi** 2024-05-04 15:39 UTC
Labels: C-bug
