### ISSUE TITLE
Failure 1/1: gemini Git command failed.  Trying to compile from source. Stdout: Stderr: fatal: unable to access 'https://git.sr.ht/~sfr/tree-sitter-gemini/': URL error: 403

### ISSUE THREAD

**Issue by gdimatis** [helix-editor/helix#9042] opened 2023-12-10 12:10 UTC
### Summary

the adress changed to: ~nbsp/tree-sitter-gemini tree-sitter grammar for gemtext

### Reproduction Steps

 

Stderr: fatal: unable to access 'https://git.sr.ht/~sfr/tree-sitter-gemini/': The requested URL returned error: 403
==============
You cannot try anything, change  the address to this https://git.sr.ht/~nbsp/tree-sitter-gemini

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
``` Failure 1/1: gemini Git command failed.
  Stdout: 
  Stderr: fatal: unable to access 'https://git.sr.ht/~sfr/tree-sitter-gemini/': The requested URL returned error: 403


  --- stderr
  thread 'main' panicked at helix-term/build.rs:5:26:
  Failed to fetch tree-sitter grammars: 1 grammars failed to fetch
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


</details>


### Platform

Linux

### Terminal Emulator

xterm

### Installation Method

source

### Helix Version

helix-23.10

**Comment by dead10ck** [comment] 2023-12-10 13:02
Duplicate of https://github.com/helix-editor/helix/issues/8933

**Closed** 2023-12-10 13:02 UTC
Labels: C-bug
