### ISSUE TITLE
Random(?) freezes in one specific vitepress project only

### ISSUE THREAD

**Issue by nkoehring** [helix-editor/helix#9292] opened 2024-01-09 15:48 UTC
### Summary

I would really like to give more details on this, but it is hard to pinpoint the issue, because it feels really exotic:
When ever I edit files in _one specific project_, and only this project, the editor randomly freezes, consuming 100% CPU (at least on one core) without recover except `kill -9`.
The project is nothing special though, and I worked on it with Helix all the time. The project is a vitepress project ([the Vuejs//Berlin homepage](https://github.com/VuejsBerlin/new.vuejs.berlin)) and the crashes seem to happen in the Vue files only.

### Reproduction Steps

Unfortunately, I cannot give a safe way to reproduce, because it happens from time to time, but not all the time. All I do is edit a Vue or Markdown file, like [an event file](https://github.com/VuejsBerlin/new.vuejs.berlin/blob/vitepress/events/2024-01-09-vuejs-berlin-new-years-edition.md) or [a Vue component](https://github.com/VuejsBerlin/new.vuejs.berlin/blob/vitepress/NextEvent.vue). It didn't happen at all in other Vite/Vue related projects (didn't specifically try vitepress projects, though).

### Helix log

The log is very large(38MB, 172277 lines), but it ends with nothing extraordinary. I will post here only the last view lines, but if the whole log is needed, I will keep it for later inspection.

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-01-09T16:35:46.910 helix_view::document [DEBUG] submitting save of doc 'Some("/home/normankoehring/src/koehr/vuejs.berlin/events/2024-01-09-vuejs-berlin-new-years-edition.md")'
2024-01-09T16:35:46.912 helix_term::application [DEBUG] received editor event: DocumentSaved(Ok(DocumentSavedEvent { revision: 33, doc_id: DocumentId(1), path: "/home/normankoehring/src/koehr/vuejs.berlin/events/2024-01-09-vuejs-berlin-new-years-edition.md", text: /* redacted for clarity */ }))
2024-01-09T16:35:46.912 helix_term::application [DEBUG] document Some("/home/normankoehring/src/koehr/vuejs.berlin/events/2024-01-09-vuejs-berlin-new-years-edition.md") saved with revision 33
2024-01-09T16:35:46.912 helix_view::document [DEBUG] doc 1 revision updated 18 -> 33
2024-01-09T16:35:46.912 helix_lsp::file_event [DEBUG] Received file event for "/home/normankoehring/src/koehr/vuejs.berlin/events/2024-01-09-vuejs-berlin-new-years-edition.md"
2024-01-09T16:35:46.912 helix_view::editor [DEBUG] editor status: 'events/2024-01-09-vuejs-berlin-new-years-edition.md' written, 54L 2717B
2024-01-09T16:36:33.165 helix_term::application [DEBUG] received editor event: IdleTimer
2024-01-09T16:36:33.545 helix_term::application [DEBUG] received editor event: IdleTimer
2024-01-09T16:36:34.381 helix_term::application [DEBUG] received editor event: IdleTimer
2024-01-09T16:36:34.601 helix_vcs::diff::worker [INFO] Diff computation timed out, update of diffs might appear delayed
2024-01-09T16:36:34.840 helix_term::application [DEBUG] received editor event: IdleTimer
2024-01-09T16:36:35.396 helix_vcs::diff::worker [INFO] Diff computation timed out, update of diffs might appear delayed
2024-01-09T16:36:36.472 helix_term::application [DEBUG] received editor event: IdleTimer
2024-01-09T16:36:36.853 helix_view::document [DEBUG] submitting save of doc 'Some("/home/normankoehring/src/koehr/vuejs.berlin/events/2024-01-09-vuejs-berlin-new-years-edition.md")'
2024-01-09T16:36:36.854 helix_term::application [DEBUG] received editor event: DocumentSaved(Ok(DocumentSavedEvent { revision: 34, doc_id: DocumentId(1), path: "/home/normankoehring/src/koehr/vuejs.berlin/events/2024-01-09-vuejs-berlin-new-years-edition.md", text: /* redacted for clarity */ }))
2024-01-09T16:36:36.854 helix_lsp::file_event [DEBUG] Received file event for "/home/normankoehring/src/koehr/vuejs.berlin/events/2024-01-09-vuejs-berlin-new-years-edition.md"
2024-01-09T16:36:36.854 helix_term::application [DEBUG] document Some("/home/normankoehring/src/koehr/vuejs.berlin/events/2024-01-09-vuejs-berlin-new-years-edition.md") saved with revision 34
2024-01-09T16:36:36.854 helix_view::document [DEBUG] doc 1 revision updated 33 -> 34
2024-01-09T16:36:36.854 helix_view::editor [DEBUG] editor status: 'events/2024-01-09-vuejs-berlin-new-years-edition.md' written, 54L 2718B
2024-01-09T16:36:42.665 helix_term::application [DEBUG] received editor event: IdleTimer
```

</details>

### Platform

Linux

### Terminal Emulator

foot version: 1.16.1 -pgo +ime +graphemes -assertions

### Installation Method

dnf (Fedora, via copr.fedorainfracloud.org/varlad/helix)

### Helix Version

helix 23.10 (f6021dd0)

**Comment by kirawi** [comment] 2024-01-09 15:51
Likely a dupe of https://github.com/helix-editor/helix/issues/8709

**Closed** 2024-01-13 05:11 UTC
Labels: C-bug, S-waiting-on-author
