### ISSUE TITLE
Crash in update_positions

### ISSUE THREAD

**Issue by timokoesters** [helix-editor/helix#10105] opened 2024-04-02 10:34 UTC
### Summary

thread 'main' panicked at 'Positions [(4, After), (5, Before)] are out of range for changeset len 1!', helix-core/src/transaction.rs:478:9

### Reproduction Steps

In the config, add this:

[keys.insert]
"C-l" = [
  "select_mode",
  "goto_file_start",
  ":pipe cat",
]

Open a new file, then:
1. Start insert mode
2. type "test", don't leave insert mode
3. Press ctrl+L

### Platform

Linux

### Terminal Emulator

alacritty

### Installation Method

compiled myself

### Helix Version

helix 24.3 (88d455af)

**Comment by timokoesters** [comment] 2024-04-02 10:35
This bug does not happen if I use the same commands in [keys.normal]

**Comment by pascalkuthe** [comment] 2024-04-02 10:42
Duplicate of #3501

**Closed by pascalkuthe** 2024-04-02 10:42 UTC
Labels: C-bug
