### ISSUE TITLE
Panic on "undo" in insert mode

### ISSUE THREAD

**Issue by leandrobbraga** [helix-editor/helix#8419] opened 2023-09-29 12:01 UTC
### Summary

Hello, if you try to bind "undo" in insert mode to, let's say `C-z`, enter insert mode, type something and try to use it, the editor will panic with the following message:

```console
thread 'main' panicked at 'assertion failed: original_doc.len_chars() == self.len', helix-core/src/transaction.rs:268:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It doesn't happen 100% of time, but it's up there.

I know that the current "undo" was not designed to be used in insert mode, but my opinion is that:
1) Either it does nothing (consequently not crash)
2) Or it behaves as a "undo" in the "insert-level" (only undo things that were done during the "insert session")

### Reproduction Steps

https://asciinema.org/a/2i0eGe9mA6FpHkh3Xs0U8Uo4n

1) Bind C-z to "undo" in insert mode
2) Insert some text
3) Leave insert mode
4) Enter insert mode, type something
5) Press C-z (crash)

### Platform

Linux

### Terminal Emulator

GNOME Terminal 3.48.0

### Helix Version

helix 23.05 (7f5940be)

**Comment by pascalkuthe** [comment] 2023-09-29 13:02
duplicate of  #3501, helix is a moadl editor, these kind of actions are supposed to be done in normal mode. Insertmode is only intended for inserting a single unit of change.

**Closed by pascalkuthe** 2023-09-29 13:02 UTC
Labels: C-bug

**Comment by leandrobbraga** [comment] 2023-09-29 13:08
OK. Since Helix does not plan to have undo in insert mode, and the user should not try to use it, shouldn't it be a no-op and the user be warned somehow? 

To discover that's not intended with "crashing" doesn't seem the best user experience
