### ISSUE TITLE
Helix buffer becomes unresponsive/slow on paste operation

### ISSUE THREAD

**Issue by matthias-kuklinski** [helix-editor/helix#1484] opened 2022-01-12 00:11 UTC
### Reproduction steps

Copying the content of [README.md](https://raw.githubusercontent.com/helix-editor/helix/master/README.md) from my system's clipboard into a helix buffer through `CTRL+SHIFT+V` results in the following:

[![asciicast](https://asciinema.org/a/3G5vrCYfpw7qjr911HBakLFq8.svg)](https://asciinema.org/a/3G5vrCYfpw7qjr911HBakLFq8)

### Issues:

1. The content is (visually) inserted line by line. As a result pasting larger content results in a slow and unresponsive operation, as any input by the user seems to be ignored until the content is fully pasted into the helix buffer.
2. User action is required as can be seen in the asciinema-clip: on line 37 and 73 I had to press a key in order to let helix proceed. I pressed the `ESC` key. I tried pressing other keys, such as `j`, which were literally appended to the pasted content.

### Environment

- Platform: Sway (Wayland) on Arch Linux
- Helix version: helix v0.6.0
- Helix log: empty

**Comment by kirawi** [comment] 2022-01-12 00:34
Duplicate of #1021

**Comment by kirawi** [comment] 2022-01-12 00:35
I'm guessing you're pasting in insert mode via `ctrl-v` instead of `space-p` in normal mode. We currently don't have bracketed paste support because crossterm doesn't support it yet (https://github.com/crossterm-rs/crossterm/pull/557), so without that pressing `ctrl-v` literally works as if you typed out the pasted text character by character.

_Originally posted by @archseer in https://github.com/helix-editor/helix/issues/1021#issuecomment-963353157_

**Closed by kirawi** 2022-01-12 00:34 UTC
Labels: C-bug
