### ISSUE TITLE
Copy to clipboard error messages from LSP

### ISSUE THREAD

**Issue by ipochi** [helix-editor/helix#7346] opened 2023-06-15 14:10 UTC
I was wondering if there is a facility to copy the error message shown by an LSP to the system clipboard.

I know I can press Space + d to see all the errors thrown by LSP in a separate buffer but I'd like to copy the error message for debugging/searching on the internet.

**Comment by CptPotato** [comment] 2023-06-15 14:17
There currently isn't.

Also, this is a duplicate of #7062

**Comment by ipochi** [comment] 2023-06-15 14:20
Ah , ok, sorry about the duplicate issue. I suppose this can then be closed.

**Closed** 2023-06-15 14:20 UTC
