### ISSUE TITLE
Add shortcut to close buffer

### ISSUE THREAD

**Issue by sourproton** [helix-editor/helix#6690] opened 2023-04-10 13:38 UTC
It would be nice to be able to close the buffer currently containing the cursor (which is doable by adding custom shortcuts now), or with a shortcut in the buffer picker, like `Ctrl-q` or `Ctrl-x` (currently impossible to implement yourself).

**Comment by the-mikedavis** [comment] 2023-04-10 13:50
Duplicate of https://github.com/helix-editor/helix/issues/1593

**Closed as not planned by the-mikedavis** 2023-04-10 13:50 UTC
Labels: R-duplicate, C-enhancement
