### ISSUE TITLE
Crashes on :sh cargo run

### ISSUE THREAD

**Issue by ArikRahman** [helix-editor/helix#3950] opened 2022-09-23 16:44 UTC
### Summary

Simply running a hello world froze the terminal. Works outside of helix, but not inside helix.

### Reproduction Steps

 

I tried this:

1. Running this code:
2. use std::io::{self, *};

macro_rules! love_you {
    () => {
        println!("I love you 2.")
    };
}

fn call() {
    let mut x = String::new();
    io::stdin().read_line(&mut x).expect("Woah");
    println!("{}", x);
}

fn main() {
    love_you!();
    println!();
    call();
    //test
}

I expected this to happen:
Cargo run works

Instead, this happened:
Freezes on :sh cargo run

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux Fedora

### Terminal Emulator

Gnome Default Terminal

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by the-mikedavis** [comment] 2022-09-23 16:48
Duplicate of https://github.com/helix-editor/helix/issues/3524

`:sh` runs commands from the shell synchronously. It's mostly meant for key-bindings or quick shell commands like `:sh git status` and isn't a replacement for #1976

**Closed by the-mikedavis** 2022-09-23 16:48 UTC
Labels: C-bug
