### ISSUE TITLE
Line numbers are now configurable via the gutters setting but apparently can't be changed with the :set command

### ISSUE THREAD

**Issue by groovy9** [helix-editor/helix#2206] opened 2022-04-21 00:50 UTC
I'd like to be able to toggle line numbers on and off while editing.  [#1967](https://github.com/helix-editor/helix/pull/1967) added a gutters setting that allows disabling line numbers by simply not including "line-numbers" in the gutters array, which is great.  But :set throws an error if I try to set gutters to the referenced values:

`
:set gutters ["diagnostics"]
`
`
Bad arguments. Usage: ':set key field'
`

**Comment by CptPotato** [comment] 2022-04-21 09:38
`:set gutters ["diagnostics"]` doesn't error for me. If it does for you, you might be using the latest release which doesn't include that functionality, yet.

Apart from that, there seem to be two things happening here:

1. `:set` fails to parse the list, if it contains spaces
   - i.e. `["diagnostics", "line-numbers"]` fails, but `["diagnostics","line-numbers"]` works
2. the gutter is only updated when the window is created/update
   - opening a split will update it (closing one *sometimes* updates it?)

**Comment by the-mikedavis** [comment] 2022-08-06 13:03
I can reproduce this. The error comes from this line: https://github.com/helix-editor/helix/blob/24f5a47ceca5468ef22e21cdbb53e737782ff878/helix-term/src/commands/typed.rs#L1214-L1216

It looks like we're parsing the arguments so that `:set gutters ["diagnostics"]` is parsed as `["gutters", "[", "diagnostics", "]"]`.

`:set gutters "[\"diagnostics\"]"` is parsed correctly as a workaround but ideally we should be  fixing the argument parser

**Comment by the-mikedavis** [comment] 2022-08-06 13:28
Hmm actually on further investigation this looks like the intended behavior of `helix_core::shellwords` based on the tests. You should escape quotes with `\"`. Tuning that behavior could be discussed though.

`:set gutters` on its own doesn't refresh the gutters as CptPotato says. The `helix_view::editor::Editor::refresh_config` function (or maybe something in `Application`) will need some extra handling for gutters

**Comment by jcalabro** [comment] 2024-03-08 22:04
Hi there! Sorry to dig up an old issue, but I believe this is the way to do it in 23.10 at least?

```
:set gutters.layout ["line-numbers"]
```

**Comment by phlippieb** [comment] 2024-05-18 09:20
> Hi there! Sorry to dig up an old issue, but I believe this is the way to do it in 23.10 at least? This is working for me
> 
> ```
> :set gutters.layout ["line-numbers"]
> ```

This seems to work, but only if the list contains exactly zero or one elements. Not sure how to set multiple elements. `:set gutters.layout ["line-numbers", "spacer"] still errors with the "Bad arguments" message.

**Comment by pascalkuthe** [comment] 2024-05-18 12:47
This doesn't work because we parse the command input as json but have our own parsing/word splitting. This isn't really a bug on its own. You can use set like this you just need to comeup with the right way to escape it.

This will be covered by the config factor refsctor and moving away from implementing :set using serde_json.

Closing in favor of #8853

**Closed by pascalkuthe** 2024-05-18 12:47 UTC
Labels: C-enhancement, A-helix-term, A-core

**Comment by Hckr1123** [comment] 2025-01-21 12:00
Sharing what worked for me in case it may be useful for someone:
```
   [keys.normal]                                                                                                                                               
   "A-n" = ':set gutters.layout ["diagnostics","spacer","diff"]'                                                                                               
   "A-l" = ':set gutters.layout ["diagnostics","line-numbers","spacer","diff"]' 
```
This way I could map it to use these keyboard shortcuts to disable/enable line numbers.

**Comment by RoloEdits** [comment] 2025-05-19 06:51
On master, it should now be able to toggle just fine.

Ex:
```
:toggle gutters.layout ["diagnostics","spacer","diff"] ["diagnostics","line-numbers","spacer","diff"]
```
