### ISSUE TITLE
Multicursor merges when entering insert  mode via 'a' keystroke

### ISSUE THREAD

**Issue by blitzarx1** [helix-editor/helix#10866] opened 2024-06-02 12:56 UTC
First of all, thanks for this editor, I 've been using it actively for almost a year now.

I've encountered some strange behavior but I am not sure if it intended. 

I had a line with repeating characters and I wanted to insert another symbol after each of them. 

But I was not able to do it, because when I select a line and search for the repeating character, entering multicursor editing, when I then enter the insert mode by pressing `a`, all the neighboring multicursors are merged into one.

I other word I was trying to transform the following line ```aaaaaa1bbba1ba1``` into ```a1a1a1a1a1a11bbba11ba11``` but got ```aaaaaa11bbba11ba11```.

Strange is that when I am doing the same thing but press `i` for insert mode, all multicursors are working just fine. I expected the same behavior when I enter the insert mode with `a` keystroke.

Video demonstrates current behavior.

https://github.com/helix-editor/helix/assets/32969427/dcd50faf-3c0a-427f-8385-cca251d78c58

```bash
starlord@Dmitriis-MacBook-Pro patterns-rs % hx --version
helix 24.3 (2cadec0b)
```

**Comment by kirawi** [comment] 2024-06-02 20:32
Duplicate of https://github.com/helix-editor/helix/issues/2298

**Closed by kirawi** 2024-06-02 20:32 UTC
