### ISSUE TITLE
Can we give a title to our own minor mode?

### ISSUE THREAD

**Issue by jabbalaci** [helix-editor/helix#6852] opened 2023-04-22 18:18 UTC
When you activate a built-in minor mode, a pop-up appears with all the options. This pop-up "window" has a title in the top left corner. For instance, when you press space, the pop-up has the title "Space", "g" brings up the goto pop-up with the title "Goto", etc.

We can also create our own minor modes, but these pop-ups are untitled. Is it possible to give them a title? They would be much more informative.

For instance, I have this:

```
[keys.normal.C-u]  # my Utils
b = "save_selection"  # bookmark
j = "jumplist_picker"
```

For this, I would like to see the title "Utils".

**Comment by gabydd** [comment] 2023-04-23 00:07
Duplicate of https://github.com/helix-editor/helix/issues/1752

**Closed** 2023-04-23 00:14 UTC
