### ISSUE TITLE
Allow unix style paths on Windows

### ISSUE THREAD

**Issue by JackMordaunt** [helix-editor/helix#6484] opened 2023-03-30 06:48 UTC
When picking files on Windows I'm constantly frustrated that I have to use backslash `\` to pick files. 

I think it would trivial to support both styles in the file picker. The moment you type `/` the fuzzy searching just chokes and matches nothing.

**Comment by helmesjo** [comment] 2023-04-01 22:50
That makes two of us: #5414

**Comment by the-mikedavis** [comment] 2023-04-02 14:00
Duplicate of https://github.com/helix-editor/helix/issues/5414

**Closed by the-mikedavis** 2023-04-02 14:00 UTC
Labels: C-enhancement
