### ISSUE TITLE
Helix crashes when trying to save and quit large files

### ISSUE THREAD

**Issue by quasigod-io** [helix-editor/helix#4585] opened 2022-11-03 20:40 UTC
### Summary

Editing a large file ([this file from nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix)), Helix crashes when trying to save and quit after any change.

### Reproduction Steps

 

I tried this:

1. Open the file with Helix
2. Made any change
3. Tried to quit with `:wq`

I expected this to happen:
For Helix to write the file and close.

Instead, this happened:
Helix becomes completely unresponsive, a CPU core becomes locked at 100%, and Helix stops writing to the log file.

### Helix log

[helix.log](https://github.com/helix-editor/helix/files/9932813/helix.log)
[helix-v.log](https://github.com/helix-editor/helix/files/9932816/helix-v.log)

### Platform

Linux (NixOS)

### Terminal Emulator

wezterm 20220905-102802-7d4b8249

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by the-mikedavis** [comment] 2022-11-03 21:00
Duplicate of https://github.com/helix-editor/helix/issues/3975

**Comment by David-Else** [comment] 2022-11-03 21:01
It seems to work perfectly for me on the latest master, quits instantly.

**Closed by the-mikedavis** 2022-11-03 21:00 UTC
Labels: C-bug

**Comment by quasigod-io** [comment] 2022-11-03 21:02
I guess it could be related to the Nixpkgs version

**Comment by David-Else** [comment] 2022-11-03 21:03
I downloaded the file 1.2meg file `all-packages.nix` you linked, altered it and `:wq` saved several times.

**Comment by David-Else** [comment] 2022-11-03 21:04
Do you have the lsp installed? I don't, could that be related?

**Comment by David-Else** [comment] 2022-11-03 21:07
> I guess it could be related to the Nixpkgs version

Yes, it should be fixed, I suggest you compile from master.
