### ISSUE TITLE
Code in hover popup spills out of window

### ISSUE THREAD

**Issue by thomasschafer** [helix-editor/helix#10911] opened 2024-06-09 14:15 UTC
### Summary

Long code snippets split out of the hover popup window (see bottom right):

<img width="812" alt="Screenshot 2024-06-09 at 15 07 32" src="https://github.com/helix-editor/helix/assets/54135831/aa3ca7d5-84db-4eb0-8e2a-922c777571b6">

### Reproduction Steps

Navigate to [this line](https://github.com/helix-editor/helix/blob/aa1630a41af774946f12872ffa539f3145eac89e/helix-tui/src/buffer.rs#L411) (`hx helix-tui/src/buffer.rs:411`) and press `space + k` (`hover`). The code snippet will spill out of the window.

### Platform

macOS

### Terminal Emulator

alacritty 0.13.2 (bb8ea18)

### Installation Method

source

### Helix Version

6f1437e9

**Comment by kirawi** [comment] 2024-06-09 14:27
This looks like a duplicate of https://github.com/helix-editor/helix/issues/6012

**Closed by kirawi** 2024-06-09 14:27 UTC
Labels: C-bug

**Comment by thomasschafer** [comment] 2024-06-09 14:37
> This looks like a duplicate of #6012

Ah yes - thank you!
