### ISSUE TITLE
Remove documentation modal after move cursor

### ISSUE THREAD

**Issue by zongUMR** [helix-editor/helix#1049] opened 2021-11-10 01:45 UTC
#### Describe your feature request
Helix will show doc modal while pressing `space+k`, could we let helix automatically remove the modal after moving the cursor, so we do not need to use `Esc to quit it again and again.

**Comment by kirawi** [comment] 2021-11-10 01:49
Duplicate of #14

**Closed by kirawi** 2021-11-10 01:49 UTC
Labels: C-enhancement

**Comment by zongUMR** [comment] 2021-11-10 01:53
Thanks, I had not found that duplication.
