### ISSUE TITLE
Add Emmet LSP support

### ISSUE THREAD

**Issue by boba-fettt** [helix-editor/helix#9496] opened 2024-02-01 19:26 UTC
I'm a front-end Dev, and it's really annoying when I have to type the boilerplate out tag by tag, indent by indent and attribute by attribute. I'd love to have to have emmet LSP, considering it's already available on npm.

**Comment by the-mikedavis** [comment] 2024-02-01 19:37
Duplicate of https://github.com/helix-editor/helix/issues/1896

**Closed by the-mikedavis** 2024-02-01 19:37 UTC
Labels: C-enhancement
