### ISSUE TITLE
Helix freezes at angle bracket in Markdown file

### ISSUE THREAD

**Issue by phoenixr-codes** [helix-editor/helix#9140] opened 2023-12-22 15:38 UTC
### Summary

When editing a Markdown file, Helix freezes in a specific scenario.

````markdown
```
foo
  > foo
```
````

Moving over the angle bracket results in Helix freezing completely. Using the escape key does not work.

This may also be an issue with treesitter or the LSP.

### Reproduction Steps

 

**I tried this:**

1. `hx`.
2. type `:lang markdown`.
3. disable marksman `:lsp-stop`
4. Enter insert mode (`i`)
5. Create a fenced code block (` ``` `).
6. Within the code block write a line.
7. Indent the next line with two spaces.
8. Type a closing angle bracket (`>`).
9. Type space and add text after it.
10. Move over that line to the left (ESC, `h`)

**I expected this to happen:**

It should not freeze.

**Instead, this happened:**

It freezes

### Helix log

<details><summary>Log with `RUST_BACKTRACE=1 hx -vv`</summary>

```
2023-12-22T16:32:53.251 helix_view::clipboard [DEBUG] Using xclip to interact with the system and selection (primary) clipboard
2023-12-22T16:32:53.265 helix_tui::backend::crossterm [DEBUG] The keyboard enhancement protocol is not supported in this terminal (checked in 14.345854ms)
2023-12-22T16:32:53.265 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:53.266 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:53.502 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:32:55.064 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:55.315 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:32:55.505 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:56.225 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:56.476 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:32:56.476 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:56.503 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:56.649 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:56.836 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:57.087 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:32:57.087 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:57.087 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:57.267 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:57.459 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:57.609 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:57.750 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:58.001 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:32:58.001 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:58.129 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:58.129 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:58.691 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:58.691 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:59.074 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:59.325 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:32:59.415 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:59.629 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:32:59.733 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:00.136 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:00.987 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:01.364 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:01.520 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:01.605 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:02.003 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:02.468 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:02.688 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:02.718 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:02.805 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:03.150 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:03.649 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:04.016 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:04.218 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:04.309 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:04.595 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:04.711 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:05.043 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:05.409 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:05.864 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:06.115 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:06.248 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:06.623 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:06.724 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:07.111 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:07.444 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:07.706 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:08.079 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:08.838 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:09.134 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:10.619 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:11.436 helix_core::auto_pairs [DEBUG] auto pair transaction: Transaction {
    changes: ChangeSet {
        changes: [
            Insert(
                "``",
            ),
            Retain(
                1,
            ),
        ],
        len: 1,
        len_after: 3,
    },
    selection: Some(
        Selection {
            ranges: [
                Range {
                    anchor: 2,
                    head: 1,
                    old_visual_position: None,
                },
            ],
            primary_index: 0,
        },
    ),
}
2023-12-22T16:33:11.448 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:11.688 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:11.688 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:11.757 helix_core::auto_pairs [DEBUG] auto pair transaction: Transaction {
    changes: ChangeSet {
        changes: [
            Retain(
                3,
            ),
        ],
        len: 3,
        len_after: 3,
    },
    selection: Some(
        Selection {
            ranges: [
                Range {
                    anchor: 3,
                    head: 2,
                    old_visual_position: None,
                },
            ],
            primary_index: 0,
        },
    ),
}
2023-12-22T16:33:11.757 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:12.008 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:12.008 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:12.064 helix_core::auto_pairs [DEBUG] auto pair transaction: Transaction {
    changes: ChangeSet {
        changes: [
            Retain(
                2,
            ),
            Insert(
                "``",
            ),
            Retain(
                1,
            ),
        ],
        len: 3,
        len_after: 5,
    },
    selection: Some(
        Selection {
            ranges: [
                Range {
                    anchor: 4,
                    head: 3,
                    old_visual_position: None,
                },
            ],
            primary_index: 0,
        },
    ),
}
2023-12-22T16:33:12.064 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:12.315 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:12.315 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:12.535 helix_core::auto_pairs [DEBUG] auto pair transaction: Transaction {
    changes: ChangeSet {
        changes: [
            Retain(
                5,
            ),
        ],
        len: 5,
        len_after: 5,
    },
    selection: Some(
        Selection {
            ranges: [
                Range {
                    anchor: 5,
                    head: 4,
                    old_visual_position: None,
                },
            ],
            primary_index: 0,
        },
    ),
}
2023-12-22T16:33:12.535 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:12.653 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:12.886 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:13.040 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:13.291 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:13.291 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:13.432 helix_core::auto_pairs [DEBUG] auto pair transaction: Transaction {
    changes: ChangeSet {
        changes: [
            Retain(
                5,
            ),
            Insert(
                "``",
            ),
            Retain(
                1,
            ),
        ],
        len: 6,
        len_after: 8,
    },
    selection: Some(
        Selection {
            ranges: [
                Range {
                    anchor: 7,
                    head: 6,
                    old_visual_position: None,
                },
            ],
            primary_index: 0,
        },
    ),
}
2023-12-22T16:33:13.433 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:13.684 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:13.684 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:13.740 helix_core::auto_pairs [DEBUG] auto pair transaction: Transaction {
    changes: ChangeSet {
        changes: [
            Retain(
                8,
            ),
        ],
        len: 8,
        len_after: 8,
    },
    selection: Some(
        Selection {
            ranges: [
                Range {
                    anchor: 8,
                    head: 7,
                    old_visual_position: None,
                },
            ],
            primary_index: 0,
        },
    ),
}
2023-12-22T16:33:13.741 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:13.992 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:13.992 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:14.046 helix_core::auto_pairs [DEBUG] auto pair transaction: Transaction {
    changes: ChangeSet {
        changes: [
            Retain(
                7,
            ),
            Insert(
                "``",
            ),
            Retain(
                1,
            ),
        ],
        len: 8,
        len_after: 10,
    },
    selection: Some(
        Selection {
            ranges: [
                Range {
                    anchor: 9,
                    head: 8,
                    old_visual_position: None,
                },
            ],
            primary_index: 0,
        },
    ),
}
2023-12-22T16:33:14.047 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:14.298 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:14.298 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:14.357 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:14.507 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:14.618 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:14.870 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:14.870 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.169 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.261 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.301 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.325 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.355 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.375 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.627 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:15.627 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.627 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.648 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.899 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:15.899 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:15.975 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:16.227 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:16.227 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:16.357 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:16.608 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:16.608 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:16.704 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:16.774 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:17.026 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:17.026 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:17.082 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:17.193 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:17.278 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:17.462 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:17.713 helix_term::application [DEBUG] received editor event: IdleTimer
2023-12-22T16:33:17.713 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:17.714 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:17.962 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:18.013 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-12-22T16:33:18.063 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0

```

</details> 

### Platform

GNU/Linux x86_64

### Terminal Emulator

xfce4

### Installation Method

pacman

### Helix Version

23.10

**Comment by pascalkuthe** [comment] 2023-12-22 16:40
Duplicate of #8736

**Closed by pascalkuthe** 2023-12-22 16:40 UTC
Labels: C-bug
