### ISSUE TITLE
`*` doesn't change the content of the / register on the list displayed with `"`

### ISSUE THREAD

**Issue by ohno418** [helix-editor/helix#6314] opened 2023-03-14 09:06 UTC
### Summary

Typing `*` writes the selected value to the search register. But it doesn't seem to change the content of the / register on the list when you can see by typing `"`.

![20230314-17_57_45](https://user-images.githubusercontent.com/24674436/224948596-c9e10dda-f083-4bcf-af1a-5b7db7828393.png)

### Reproduction Steps

 

I tried this:

1. Select some words and type `*`.
2. Confirm that "register '/' set to 'xxx'" is displayed below the status bar.
3. Type `"` to see the list of the register contents.

I expected this to happen:

The content of the / register on the list is the text you select.

Instead, this happened:

The content of the / register on the list doesn't change.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux, Wayland

### Terminal Emulator

foot version: 1.13.1 +pgo +ime +graphemes -assertions

### Helix Version

helix 22.12 (75ebc1fc)

**Comment by the-mikedavis** [comment] 2023-03-14 13:56
Duplicate of https://github.com/helix-editor/helix/issues/5241

**Closed by the-mikedavis** 2023-03-14 13:56 UTC
Labels: C-bug
