### ISSUE TITLE
Fuzzy finder should prioritize files from CWD

### ISSUE THREAD

**Issue by notramo** [helix-editor/helix#7403] opened 2023-06-20 14:50 UTC
Launch `hx` from a subdirectory of a project, e.g. `src/`. The fuzzy finder should sort files from `src/` with higher priority than other files in the Git repo.

**Comment by the-mikedavis** [comment] 2023-06-20 14:58
Duplicate of https://github.com/helix-editor/helix/issues/1452

**Closed by the-mikedavis** 2023-06-20 14:58 UTC
Labels: C-enhancement
