### ISSUE TITLE
Markdown inline-code highlighting fails if opening backtick is followed by dollar sign (conflict with inline-LaTeX?)

### ISSUE THREAD

**Issue by LeoniePhiline** [helix-editor/helix#6762] opened 2023-04-14 20:51 UTC
### Working: The following text renders correctly, with both instances of `variable` rendered in inline-code color:

```
Text `variable` text `variable`
```

#### GitHub rendering:
Text `variable` text `variable`

#### Helix rendering:
![image](https://user-images.githubusercontent.com/22329650/232151308-f4251853-e7c3-4a9d-b21f-ac85b7fad3b9.png)

### Broken: Starting with a dollar sign after the variable makes the second "text" get incorrectly colored in inline-code color

```
Text `$variable` text `variable`
```

#### GitHub rendering:
Text `$variable` text `variable`

#### Helix rendering:
![image](https://user-images.githubusercontent.com/22329650/232151415-d7d42413-f900-41d3-ba55-a5ebb0f06b38.png)

The first backtick appears to get ignored.

## Reproduction Steps

 

I tried this:

1. `hx`
2. `:lang markdown`
3. Copy above markdown snippet
4. `<space> p`

## I expected this to happen:

Helix rendering `$variable` in gray and `text` in white.

### Instead, this happened:

Helix rendering `$variable` in white and `text` in gray; 
the next following inline-code snippet in the same paragraph also becomes white (default text color) again.

All highlighting is shifted by one backtick, as the backtick-dollar combination appears to not be recognized.

This might be caused by a conflict with inline-LaTeX.

Notably, trying to escape `$` with `\` does not help:
![image](https://user-images.githubusercontent.com/22329650/232152441-272f2044-23b5-4f94-8f19-c624743ee3b3.png)

## Helix log

No relevant log output.

## Platform

openSUSE Tumbleweed - Linux

## Terminal Emulator

Konsole

## Helix Version

helix master bb275421997b9e2bd63b04227b7e345a193818d5

**Comment by David-Else** [comment] 2023-04-14 21:43
I can confirm this is the same for Kitty terminal, but I think the best place to report this bug is https://github.com/MDeiml/tree-sitter-markdown, that is where the highlighting for Markdown in Helix (and some other editors) is done.

**Comment by the-mikedavis** [comment] 2023-04-16 14:49
It looks like this has already been fixed in tree-sitter-markdown on the latest commit on the `split_parser`, we just need to update to the latest tree-sitter-markdown

**Closed** 2023-04-18 23:21 UTC
Labels: C-bug, E-easy, E-good-first-issue, A-language-support
