### ISSUE TITLE
Get cursor back to previous session's location 

### ISSUE THREAD

**Issue by mizzunet** [helix-editor/helix#2104] opened 2022-04-14 10:59 UTC
(I couldn't find if this has already been requested)

#### Describe your feature request
Save cursor location on quitting a file, then get back there when reopening it.
That is,
1. Open a file, say main.go
2. Be the cursor on some location, say 5:6
3. Quit the file.
4. Reopen main.go
5. Set the cursor on location on previous session, that 5;6. Instead of at beginning(1:1)

I think this can be done the way `mpv` does to save and get previous playback position(`--save-position-on-quit`), which is by storing the location at `~/.config/mpv/watch_later/<some ID>`

So, for this, a new config.toml, option `save-position` would be needed.

Thank you for this awesome editor (:

**Comment by archseer** [comment] 2022-04-14 13:05
Duplicate of https://github.com/helix-editor/helix/issues/401

**Closed by archseer** 2022-04-14 13:05 UTC
Labels: C-enhancement
