### ISSUE TITLE
search highlight all items in file + counter

### ISSUE THREAD

**Issue by yv-was-taken** [helix-editor/helix#11341] opened 2024-07-27 03:25 UTC
It is a pain for search not to highlight all items in the file. Makes it difficult to determine, while iterating through iterations of the search item, where we are at in the file, and how many iterations there are in the file.

compared to vim, when you `/{search-item}` the editor:
1. highlights all iterations of the search item
2. there is a counter on the bottom right inside the command window indicating which iteration you are on out of total in the file (ex. `1/24`)

I understand the purpose of helix is not to imitate vim, but I think this is a product enhancement that seems missing from the search editor component in order for the search component to be considered of complete functionality :heart:

**Comment by kirawi** [comment] 2024-07-27 03:42
Duplicate of https://github.com/helix-editor/helix/issues/2811

**Closed by kirawi** 2024-07-27 03:42 UTC
Labels: C-enhancement
