### ISSUE TITLE
With multiple languages in a single file, comment type is static

### ISSUE THREAD

**Issue by mersenne-twister** [helix-editor/helix#10633] opened 2024-04-29 21:26 UTC
When you have multiple languages in a single file, comment type doesn't change.

# Example:
In an html file, ^C will make a block comment using `<!--` and  `-->`.
However, in a `<Script>` tag, the correct comment type is `//`, but ^C still results in an html comment.

# Suggested Enhancement:
Make comments dependent on context.

**Comment by the-mikedavis** [comment] 2024-04-29 21:30
Duplicate of https://github.com/helix-editor/helix/issues/7364

**Closed by the-mikedavis** 2024-04-29 21:30 UTC
Labels: C-enhancement
