### ISSUE TITLE
Color Highlighting

### ISSUE THREAD

**Issue by oati** [helix-editor/helix#2100] opened 2022-04-14 07:30 UTC
Like [Neovim Colorizer](https://github.com/norcalli/nvim-colorizer.lua)

![image](https://raw.githubusercontent.com/norcalli/github-assets/master/nvim-colorizer.lua-demo-short.gif)

**Comment by heliostatic** [comment] 2022-04-14 13:44
This would be pretty handy on a per language basis.

**Comment by kirawi** [comment] 2022-04-14 14:45
Duplicate of #1115

**Closed by kirawi** 2022-04-14 14:45 UTC
Labels: C-enhancement
