### ISSUE TITLE
Compile error ErrorKind

### ISSUE THREAD

**Issue by IsotoxalDev** [helix-editor/helix#2545] opened 2022-05-23 15:11 UTC
### Summary

I was compiling the master branch of helix and the build failed.
with the following error
```
 ❯ cargo install --path helix-term
  Installing helix-term v0.6.0 (/var/home/abhi/Downloads/clones/helix/helix-term)
    Updating crates.io index
   Compiling helix-view v0.6.0 (/var/home/abhi/Downloads/clones/helix/helix-view)
   Compiling helix-term v0.6.0 (/var/home/abhi/Downloads/clones/helix/helix-term)
error[E0277]: `ErrorKind` doesn't implement `std::fmt::Display`
   --> helix-view/src/handlers/dap.rs:305:81
    |
305 | ...                   e => panic!("Error to start debug console: {}", e),
    |                                                                       ^ `ErrorKind` cannot be formatted with the default formatter
    |
    = help: the trait `std::fmt::Display` is not implemented for `ErrorKind`
    = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
    = note: this error originates in the macro `$crate::const_format_args` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `helix-view` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `helix-term v0.6.0 (/var/home/abhi/Downloads/clones/helix/helix-term)`, intermediate artifacts can be found at `/var/home/abhi/Downloads/clones/helix/target`
```

### Reproduction Steps

Clone the repository, Compile

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

22.03-243-g35303f74

**Comment by the-mikedavis** [comment] 2022-05-23 15:14
Duplicate of https://github.com/helix-editor/helix/issues/2460

**Closed by the-mikedavis** 2022-05-23 15:14 UTC
Labels: C-bug
