### ISSUE TITLE
Please support + syntax for jumping to lines.

### ISSUE THREAD

**Issue by leahneukirchen** [helix-editor/helix#8355] opened 2023-09-22 10:45 UTC
Helix already supports jumping to a line number by `hx /etc/passwd:10`, but the usual Unix way is to do `hx +10 /etc/passwd`.  It would be very useful to support this too, as many tools use this syntax to pass the line numbers (e.g. by pressing v in less).

This feature is already implemented in vi, vim, emacs, more, less, most, w3m, pico, nano, joe, zile, vile, mg, mcedit, vis, kak...

**Comment by the-mikedavis** [comment] 2023-09-22 11:31
Duplicate of https://github.com/helix-editor/helix/issues/5437

**Closed by the-mikedavis** 2023-09-22 11:31 UTC
Labels: C-enhancement
