### ISSUE TITLE
Three quote

### ISSUE THREAD

**Issue by noahfraiture** [helix-editor/helix#10761] opened 2024-05-14 19:14 UTC
Hello, I'm facing a big issue here extremly import (no it's not).

On several file extension (python, markdown, or else) I need to put 3 quote or double. For instance for this post in markdown if I want to put code, I will need to start with ```.
And in python or in Java I could use """ String on multiple line """

But when we try to write this, the auto-brace will necessarly put a forth one and if we try to remove it directly, it will erase two. My way of working is thus to go in normal mode and remove the char which is kinda annoying. I thought about remove auto-brace but it's still great for a lof of usage. 

Do you have any way of resolving this issue ? Would it be possible to disable auto-brace if there's already two similar char preceding ?

**Comment by kirawi** [comment] 2024-05-14 20:29
Duplicate of https://github.com/helix-editor/helix/issues/4035

**Closed by kirawi** 2024-05-14 20:29 UTC
