### ISSUE TITLE
Completion replaces existing word incorrectly if they end on the same letter

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#5676] opened 2023-01-25 14:05 UTC
Token following where a completion should be inserted is erroneously replaced with the completion.

![Screenshot from 2023-01-25 13-57-45](https://user-images.githubusercontent.com/41798/214583951-582b4576-3db0-4aeb-bf23-12a5390e8edc.png)

I press <kbd>i</kbd> and start typing.

![Screenshot from 2023-01-25 13-57-50](https://user-images.githubusercontent.com/41798/214583949-20afbd40-07d0-43a1-9b1f-574c078b40d2.png)

So far, so good…

![Screenshot from 2023-01-25 13-57-53](https://user-images.githubusercontent.com/41798/214583944-34ab5eb3-7df6-48b7-a612-20156847add1.png)

I select the first completion. And it replaces “events” instead of being inserted before it.

![Screenshot from 2023-01-25 13-57-57](https://user-images.githubusercontent.com/41798/214583943-a1d1b931-1773-4dc7-8b3f-e826c23bf592.png)

helix 22.12 (08c35ab6) on Fedora Silverblue 37  in Black Box terminal under GNOME.

Possibly related to #2580

**Comment by archseer** [comment] 2023-01-25 15:16
I think this is just a missing config here: https://github.com/helix-editor/helix/blob/91dca3f667e146f93e6dca205b0a3f2a7a64b488/helix-term/src/ui/completion.rs#L114-L117

**Comment by archseer** [comment] 2023-01-25 15:17
@pascalkuthe you mentioned this on another issue somewhere ^

**Comment by pascalkuthe** [comment] 2023-01-27 13:44
Sorry forgot about this @archseer . 

This is indeed intended behavior. LSPs provide two options for handeling autocompletions: replace or insert.
Helix is currently hardcoded to always use the replace edit. Many editors default to insert instead (vscode and `nvim.cmp` do atleast). I think adding  a config option here would be an easy PR. all we need to do is to add a condition to use `item.insert` instead of `item.replace` in the snippet @archseer linked.

**Comment by aral** [comment] 2023-01-27 14:20
@pascalkuthe @archseer When would this ever be the desired behaviour? It results in corrupted syntax. I’d highly recommend making insert the default behaviour. I don’t remember once ending up with corrupted syntax while using VSCode (and I’m so glad I don’t have to use VSCode anymore for a multitude of other reasons).

Also, note that the replacement isn’t being carried out perfectly either (the selection goes up to but does not include the final “t”). That might be a separate bug, thought.

**Comment by pascalkuthe** [comment] 2023-01-27 14:48
Simple let's say you have two functions `foo_bar` and `foo_rab`.
Right now your code is `test.foo_rab()` but you want to change it to `test.foo_bar` so you can just start the autcompletion at `foo_` and select `foo_bar` and the `_rab` is automatically removed. The replace behavior is valid and has it's place. There  is good reason that both options are included in the LSP spec.

Offering an option definitely makes sense. I also prefer the `insert` behavior (seems more consistent for insert mode, I usually delete in normal mode instead of insert mode) but both have their merit.

**Comment by pascalkuthe** [comment] 2023-01-28 10:06
Duplicate of #4380

**Closed by pascalkuthe** 2023-01-28 10:06 UTC
