### ISSUE TITLE
interactive global search

### ISSUE THREAD

**Issue by dofinn** [helix-editor/helix#196] opened 2021-06-09 12:52 UTC
The reason I use vim is for ripgrep and fzf. This makes for extremly fast navigation. 

Request:

- Ability to index files in active directory and search via FZF
![20210609_224940_grim](https://user-images.githubusercontent.com/21171128/121357257-ff353b00-c974-11eb-88f4-2376aa6ab611.png)

- Ability to grep through fies in active directory and pipe results in fzf 
- `ripgrep file_config | fzf` <- this opens up in same preview window that FZF provides. 
![20210609_225128_grim](https://user-images.githubusercontent.com/21171128/121357583-41f71300-c975-11eb-9761-69150479e048.png)
![20210609_225136_grim](https://user-images.githubusercontent.com/21171128/121357610-46bbc700-c975-11eb-8222-d77c5003604b.png)

There are many blogs etc writing about this method in vim. EG: https://sidneyliebrand.medium.com/how-fzf-and-ripgrep-improved-my-workflow-61c7ca212861

**Comment by kirawi** [comment] 2021-06-09 16:02
Should this be a core feature of Helix or be implemented as a plugin?

**Comment by pickfire** [comment] 2021-06-09 16:30
I personally think this should be core feature. We already have like skim like thing, implementing ripgrep is just near.

**Comment by dofinn** [comment] 2021-06-10 00:27
is a dependecy on ripgrep something you want to make mandatory? I would imagine having these functions pluggable
grep=plugin(ripgrep)
find=plugin(fzf)

**Comment by pickfire** [comment] 2021-06-10 03:03
I don't think we will pull in ripgrep. We may be implementing our own which is slightly slower compared to ripgrep but work well for our usecase.

**Comment by wojciechkepka** [comment] 2021-06-10 04:09
We could also just import the `grep_searcher` crate that ripgrep uses internally. It's published to crates.io 

https://docs.rs/grep-searcher/0.1.7/grep_searcher/

**Comment by dofinn** [comment] 2021-06-10 11:14
so excuse me for being an idiot. The file picker is already aweesome! cancel the FZF request

**Comment by archseer** [comment] 2021-06-11 02:56
I do think a preview window + some way to actually search through files would be useful though :) 

I think there should be a general way to pipe data into the built-in picker.

**Comment by dofinn** [comment] 2021-06-11 03:02
I agree, after using it last night i did miss the preview window + the actual fuzzy finding where i could use multiple terms seperated by whitespace rather then the exact path/to/target/file

**Comment by archseer** [comment] 2021-06-11 03:03
The finding is fuzzy (we use `skim`'s algorithm, we just don't highlight the matched characters yet.

**Comment by nrdxp** [comment] 2021-06-15 16:26
Does Helix use skim [as a library](https://github.com/lotabout/skim#use-as-a-library)?

**Comment by sudormrfbin** [comment] 2021-06-15 16:38
> Does Helix use skim [as a library](https://github.com/lotabout/skim#use-as-a-library)?

We're using the `fuzzy-matcher` crate which is used internally by skim.

**Comment by heliostatic** [comment] 2021-08-19 01:53
Another vote for searching via the `grep_searcher` crate in the preview UI used for the picker, per https://github.com/helix-editor/helix/issues/196#issuecomment-858283651

**Comment by pppKin** [comment] 2021-08-25 08:01
Hi! I too think that being able to perform a search in current workspace would be immensely helpful. So I started messing around and [implemented something myself](https://github.com/pppKin/helix/tree/global_search) . It's not pretty I know, but it's something for us to talk about as least.
My implementation bind ```space + /``` to display a prompt (like the search prompt), and on ```Enter```, start the search, gathers the result and pop up a FilePicker. A few necessary changes are made, such as ```regex_prompt``` now accepts an extra callback that would be invoked once ```Enter``` is pressed. 
There may be some best practices I missed or some corner cases that I don't know about, but hopefully this can be improved by the community. So before I rush to create a PR, I just want to know if you guys have any thought on what this should look like and how it should be properly implemented. Thank you!

**Comment by archseer** [comment] 2021-08-25 08:17
That's pretty cool! I think instead of `grep` you will want to import `grep_matcher` and `grep_regex` so we avoid some of the extra deps (we don't need `grep_printer` for example). `grep` is just a facade that re-exports all these crates: https://github.com/BurntSushi/ripgrep/blob/master/crates/grep/src/lib.rs

I'm also wondering if we might want to do this without the prompt and just do this interactively in the picker as the user types. It's a bit wasteful though so maybe there could be a key to refresh (ctrl-r or something like it)

The binary detection part is really cool and we likely want to use that in the file preview as well to avoid displaying binary files (on `space + f`).

**Comment by pppKin** [comment] 2021-08-25 08:27
>import grep_matcher and grep_regex so we avoid some of the extra deps (we don't need grep_printer for example)

You're right, I will be cleaning it up shortly :)

**Comment by pppKin** [comment] 2021-08-25 10:54
> just do this interactively in the picker as the user types
@archseer 
Interactive picker might be a more intuitive option, but I wonder what would be a proper way to fuzzily select a file in search results in said picker? Perhaps add another input field and another key binding to  switch between them?

**Comment by EpocSquadron** [comment] 2021-10-31 17:17
@archseer I think this is implemented, any reason to keep this open?

**Comment by pickfire** [comment] 2021-11-14 02:29
Interactive prompt is not available yet so it will be kept open.

**Comment by weakphish** [comment] 2022-09-12 21:04
any update on this?

**Comment by archseer** [comment] 2022-09-13 00:46
Have you looked at the linked PRs? Requires https://github.com/helix-editor/helix/pull/3172 and https://github.com/helix-editor/helix/pull/3110

**Comment by johnrichardrinehart** [comment] 2022-10-10 14:20
@archseer I see #3110 linked above, but not #3172 . Is there an open PR for this feature which explicitly depends on #3172 and #3110 or are you saying that no work fro this feature can/will be done until those two PRs are mergeD?

**Comment by sudormrfbin** [comment] 2022-10-10 16:03
There's no open PR for this issue, but the code in #3110 and #3172 introduce a kind of picker that allows re-populating it with different results whenever the search query changes instead of simply filtering the list, which is essentially what we need for an interactive search (re-run the global search whenever the query changes and inject into the list).

**Comment by johnrichardrinehart** [comment] 2022-10-11 08:48
I understand. #3172 has been merged 🎉. I understand there's some desire to to block #3110 on a debouncing feature. But, I'm worried that this may further delay the implementation of this feature - especially since no one has yet complained about input lag that would be ameliorated by the denouncing (not that they'd really had the chance, but addressing performance problems before they're identified as issues maybe shouldn't block new features).

**Comment by sudormrfbin** [comment] 2022-10-11 16:15
I was initially going to put the debouncing as a TODO, but I could already experience input lag on a release build with `rust-analyzer` as a test case LSP if I type with the speed of knowing exactly what I'm looking for. Granted it's not a huge blocker, but I'd like to get them in together.

**Comment by johnrichardrinehart** [comment] 2022-10-20 08:35
Okay, I understand. Thanks for your contributions to this project and I look forward to testing/playing with your work!

**Comment by davxy** [comment] 2023-02-01 18:02
This is something I use in bash

```bash
#!/bin/bash

# Search using rg and fzf with preview
out=$(rg . --line-number --column --no-heading --glob '!.git' | \
      fzf +i --exact --delimiter : --preview 'batcat --style=full --color=always --highlight-line {2} {1}' --preview-window 'up,~4,+{2}+4/2')

# Remove cruft leaving something like: 'file:line:column'
ref=$(echo $out | sed -E 's/([a-zA-Z0-9/-_]*):([0-9]*):([0-9]*):.*/\1:\2:\3/')

# Check if we want to edit the result
hx $ref
```

Would be super useful to open the found file in a running instance of helix...
Is there a hack to do this?

**Comment by predmijat** [comment] 2023-02-01 20:55
I'm not sure about the _running_ instance, but you can open it in new one by editing `FZF_DEFAULT_OPTS` variable and adding something like this:

`export FZF_DEFAULT_OPTS='... ,ctrl-o:execute(hx $(echo {} | cut -d ":" -f1))`

**Comment by pinpox** [comment] 2023-06-05 08:29
> @davxy, and anyone else interested: I hacked something together for this, you can read about it on [my post on r/HelixEditor](https://reddit.com/r/HelixEditor/comments/13x9a3z/integrating_fuzzylive_grepping_into_helix_my/).

This is cool, but limited to wezterm, right? Is there an option to do live-grep'ing project-wide inside helix itself or are there plans to add it?

**Comment by obxhdx** [comment] 2023-06-05 17:29
> This is cool, but limited to wezterm, right? Is there an option to do live-grep'ing project-wide inside helix itself or are there plans to add it?

It’s like I said on the Reddit post, it’s a opinionated setup but I’m certain it can be adjusted. I’m pretty sure Kitty and Tmux have similar mechanisms for sending keys/text to another pane.

Adding it natively in Helix is the whole point of this issue. I just wanted to share my workaround for those who (like me) are waiting for the native feature.

**Comment by matu3ba** [comment] 2023-08-30 23:29
Potential inspiration for a solution (does not have the matches in file preview due to being additionally complexity):
https://github.com/jake-stewart/jfind.nvim
and
https://github.com/jake-stewart/jfind

**Comment by davxy** [comment] 2023-09-01 12:07
Similar to https://github.com/helix-editor/helix/issues/196#issuecomment-1572672233 but using zellij+fzf

https://github.com/davxy/script-nest/blob/main/bin/helix-ext

The scripts allows to do a couple of IMO useful things (see the script help).

Modifications to helix config:
```
[keys.normal.'space'.'space']
# Extensions using custom script
# Interactive search in current working directory
s = ":pipe-to helix-ext search --current"
# Interactive search in current working directory (include path name in the search)
S = ":pipe-to helix-ext search --current-inc-path"
# Interactive search in current git directory
w = ":pipe-to helix-ext search --workspace"
# Interactive search in current git directory (include path name in the search)
W = ":pipe-to helix-ext search --workspace-inc-path"
# Interactive search in current buffer
b = ":pipe-to helix-ext search --buffer"
# Git status
m = ":pipe-to helix-ext git --status"
# Git blame
B = ":pipe-to helix-ext git --blame"
# Git browse github repo using default browser
O = ":pipe-to helix-ext git --browse"
```

**Comment by chtenb** [comment] 2023-09-10 20:07
I think this feature is related to this issue: https://github.com/helix-editor/helix/issues/2177
That thread also contains several ideas and workarounds to incorporate tools like broot that provide file-name and file-content search similar to fzf and ripgrep. Instead of re-inventing the wheel one could also consider supporting interaction with external tools through some kind of interface.

**Comment by pascalkuthe** [comment] 2023-09-10 20:15
That would involve building in a terminal emulator insixe helix which is much much more work while also being a lot less integrated with the rest of our UI. 


@the-mikedavis already has a working implementation of this based on #8021 and #7265. I have deamoed it and find it quite a bitee nicer tgab other options (and especially since it integrates well with the rest of the editor, which is the reason the picker is builtin to begin with). The columary picker really is a very nice approach.

**Comment by the-mikedavis** [comment] 2023-09-10 20:39
Ah I meant to post a demo here after assigning myself: https://asciinema.org/a/607253

Global search becomes a DynamicPicker like workspace symbol search (`<space>S`). You input a regex that runs across the workspace / cwd and new results are streamed in (like on master after #7814) so the picker doesn't block on become unresponsive, even when you're searching a large directory (my `~/src` is ~120GB).

It needs some more tweaking but I plan to make a draft PR for it after #8021 is merged.

**Comment by TornaxO7** [comment] 2023-11-23 19:01
As far as I know, Helix uses [`nucleo`] when opening the fuzzy file finder. Maybe we could use that for grepping text as well?

[`nucleo`]: https://github.com/helix-editor/nucleo

**Comment by hakan-demirli** [comment] 2023-12-05 12:12
> @davxy, and anyone else interested: I hacked something together for this, you can read about it on [my post on r/HelixEditor](https://reddit.com/r/HelixEditor/comments/13x9a3z/integrating_fuzzylive_grepping_into_helix_my/).

Until this issue is fixed here what I use. I ported the wezterm specific method mentioned in the blog post to tmux since it is terminal agnostic.

https://github.com/helix-editor/helix/assets/78746991/1ef55b2d-3bce-460f-b278-6b50502bf957


Add these three files to your path:
- https://github.com/hakan-demirli/dotfiles/blob/main/.local/bin/live-grep
- https://github.com/hakan-demirli/dotfiles/blob/main/.local/bin/live-grep-helix
- https://github.com/hakan-demirli/dotfiles/blob/main/.local/bin/live-grep-in-split-tmux

Add it to your config:
```toml
[keys.normal.space]
"/" = ":pipe-to live-grep-in-split-tmux"
```

**Comment by cyruseuros** [comment] 2024-04-16 04:45
@the-mikedavis - don't mean to rush things, just pinging in case this got buried (always does for me). Is there a draft of the code to build/play around with now that #8021 has been merged?

**Comment by gabydd** [comment] 2024-04-16 05:25
It's implemented in https://github.com/helix-editor/helix/pull/9647

**Closed** 2024-07-15 14:31 UTC
Labels: C-enhancement, A-helix-term

**Comment by qiu-x** [comment] 2024-12-12 19:52
Are there any plans to fix the regression, that it's not supported anymore to filter the results of a global search?
