### ISSUE TITLE
Diagnostic blocks the codes

### ISSUE THREAD

**Issue by DrunkRandomWalker** [helix-editor/helix#5564] opened 2023-01-17 15:36 UTC
Sometimes the diagnostic covers some part of the codes that need to change.
Is there a way to move the diagnostic to the bottom?
![image](https://user-images.githubusercontent.com/83610610/212940540-b33058dd-b674-4568-b60e-bd17a6467ee9.png)

**Comment by the-mikedavis** [comment] 2023-01-17 15:39
Duplicate of https://github.com/helix-editor/helix/issues/1462

**Closed by the-mikedavis** 2023-01-17 15:39 UTC
Labels: C-enhancement
