### ISSUE TITLE
Configuration override does not work for rulers

### ISSUE THREAD

**Issue by Connortsui20** [helix-editor/helix#8100] opened 2023-08-28 20:36 UTC
When trying to override a ruler setting in the `.helix/config.toml`, it appends the rulers instead of overriding.

I don't think this should be considered correct behavior because 1) you likely don't have more than 3 rulers set up and it should be easy to add rulers manually and 2) as far as I know there is no way to locally _remove_ a ruler that is set in the global config.

Maybe there is another way to do this but if not, here is the issue.

Example:
```toml
# ~/.config/helix/config.toml
[editor]
rulers = [101]
```
```toml
# {dir}/.helix/config.toml
[editor]
rulers = [121]
```
The above results in 2 separate rulers, and I think the correct behavior should be for the local ruler setting to completely override the rulers instead of appending.

**Comment by pascalkuthe** [comment] 2024-04-05 22:35
this caused by the way we merge configs right now, this will be fixed by https://github.com/helix-editor/helix/pull/9318.

Closing as this falls under #8853 and is a know issue that we don't need to track seperatly

**Closed by pascalkuthe** 2024-04-05 22:35 UTC
Labels: C-bug, E-easy, A-helix-term, E-good-first-issue
