### ISSUE TITLE
Disable auto-pairs when you want to past from the clipboard

### ISSUE THREAD

**Issue by bidandows** [helix-editor/helix#3088] opened 2022-07-16 22:22 UTC
### Summary

Hello,

I have tried to copy/paste config from Navigator to configuration file opened via Helix editor, the pasted correctly bug Helix added to the copied text extra brackets and curly brackets.

### Reproduction Steps

 

I tried this:

Copy text from the internet

I expected this to happen:
past it to configuration file
Instead, this happened:
The text was pasted with extra brackets and curly brackets 

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

konsole

### Helix Version

helix 22.05

**Comment by kirawi** [comment] 2022-07-16 23:04
Duplicate of #2239
Use `space` `y` instead.

**Closed by kirawi** 2022-07-16 23:04 UTC
Labels: C-bug
