### ISSUE TITLE
More context to the "go to implementation" picker

### ISSUE THREAD

**Issue by leandrobbraga** [helix-editor/helix#8566] opened 2023-10-18 14:32 UTC
Hello,

The suggestion is to add more context to the "go to implementation" picker to help searching for the correct implementation.

For example, in Rust, if I open the picker for this struct I'm presented with this screen
![image](https://github.com/helix-editor/helix/assets/18340809/3c4dc775-eb7e-43d7-a4d3-a173af35cd8e)

If I'm looking for the "Display" trait and try to search it I get zero results.
![image](https://github.com/helix-editor/helix/assets/18340809/5c07452a-8d61-40c4-bc94-42ac847bcb8e)

Does it make sense to add some context to improve "searchability" ? Or is that too niche to Rust?

**Comment by kirawi** [comment] 2023-10-18 14:47
Duplicate of https://github.com/helix-editor/helix/issues/196

**Closed by kirawi** 2023-10-18 14:47 UTC
Labels: C-enhancement
