### ISSUE TITLE
Syntax highlighting color changes on scroll

### ISSUE THREAD

**Issue by mgpinf** [helix-editor/helix#9749] opened 2024-02-28 15:22 UTC
### Summary

Syntax highlighting color changes on scrolling

### Reproduction Steps

 

Focus on line no. 26 in the below asciinema.org recording

asciinema.org recording:
https://asciinema.org/a/KgmTcBpb3aoIm1yhNe6p1uuw6

I tried this:

1. `hx`

I expected this to happen:
Syntax color to not change upon scrolling

Instead, this happened:
Syntax color to changes upon scrolling

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOs

### Terminal Emulator

wezterm 20240218-133804-85fb1ad2

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by the-mikedavis** [comment] 2024-02-28 15:42
Duplicate of #1151

**Closed by the-mikedavis** 2024-02-28 15:42 UTC
Labels: C-bug
