### ISSUE TITLE
Line wrapping affects `[number][movement]` actions

### ISSUE THREAD

**Issue by FinnPerry** [helix-editor/helix#6937] opened 2023-05-02 01:03 UTC
When a line is wrapped, you can do a movement such as `j` and the cursor will move to the wrapped line rather than to the next "real" line. This behaviour is correct visually and feels nice when tapping `j`, but it feels wrong when you have relative line numbers enabled as if I see a line below the cursor that has the relative line number `5` I expect to be able to press `5j` to go to that line, but if any lines between there are wrapped then those count towards the number and the cursor won't actually reach the expected line.

Could the behaviour be changed so wrapped lines are not counted when performing `[number][movement]` actions? Or it could be an opt-in setting as I guess the current behaviour makes more sense for non relative line number users.

**Comment by pascalkuthe** [comment] 2023-05-02 01:09
The behavior is intentional you can use `gj` and `gk` for textual kine navigation.  Akso a duplicate of #6819

**Closed by pascalkuthe** 2023-05-02 01:09 UTC
