### ISSUE TITLE
Interactive visual feedback for global search

### ISSUE THREAD

**Issue by davxy** [helix-editor/helix#4616] opened 2022-11-06 10:16 UTC
When using  the `Space+/` to perform a global search it would be nice to have a sort of interactive visual feedback about the thing I'm searching for.

To give you an idea about what I'm talking about, the picker that I have in mind should prompt for something like:

```
rg . --line-number --column --no-heading --glob '!.git' | \
      fzf +i --exact --delimiter : --preview 'batcat --style=full --color=always  --highlight-line {2} {1}' --preview-window 'up,~4,+{2}+4/2'
```

That would be super useful, especially to quickly and visually search for something within a project (regardless of LSP search, indeed what I'm searching for could not be a language keyword).

**Comment by archseer** [comment] 2022-11-06 14:32
Duplicate of https://github.com/helix-editor/helix/issues/196

**Closed by archseer** 2022-11-06 14:32 UTC
Labels: C-enhancement
