### ISSUE TITLE
Creating a buffer with :new overwrites existing scratch buffer if read from stdin

### ISSUE THREAD

**Issue by yonatan8070** [helix-editor/helix#5243] opened 2022-12-21 07:28 UTC
### Summary

When piping data into helix via stdin (`echo "..." | hx`) and the creating a new buffer via :new (without writing the first buffer), the data from the first buffer will be deleted.

I noticed that if I modify the stdin buffer before using `:new` it does not get deleted, I'm assuming this is because before it's modified it is wrongly considered an empty buffer, since I also noticed that `:q` works without prompting to save the buffer before leaving.

### Reproduction Steps

 

I tried this:

1. `echo "Hello, world!" | hx`
2. `:new`

I expected this to happen:
A new scratch buffer is created alongside the data from stdin.

Instead, this happened:
The buffer created from stdin was deleted and a new scratch buffer replaced it.

### Helix log

There was nothing written to the log during my testing.

### Platform

Linux

### Terminal Emulator

Konsole

### Helix Version

22.12

**Comment by the-mikedavis** [comment] 2022-12-21 14:04
Duplicate of https://github.com/helix-editor/helix/issues/3305

**Closed by the-mikedavis** 2022-12-21 14:04 UTC
Labels: C-bug

**Comment by yonatan8070** [comment] 2022-12-21 14:17
My bad, didn't see this was a duplicate
