### ISSUE TITLE
Sync languages.toml with the Github Linguist extension list

### ISSUE THREAD

**Issue by yoav-lavi** [helix-editor/helix#8389] opened 2023-09-25 14:12 UTC
See https://github.com/helix-editor/helix/issues/8375#issuecomment-1733774611 for more details

**Comment by the-mikedavis** [comment] 2023-09-25 14:17
Duplicate of https://github.com/helix-editor/helix/issues/5904

**Closed by the-mikedavis** 2023-09-25 14:17 UTC
Labels: C-enhancement
