### ISSUE TITLE
tab in python

### ISSUE THREAD

**Issue by notwidow** [helix-editor/helix#3883] opened 2022-09-18 11:40 UTC
Hi, I have this issue in helix. When i define a function in python and press enter for the next line. then it does not indent ( add tab ) on the line. 
![pyso](https://user-images.githubusercontent.com/112823418/190900115-7f3c6603-b637-4051-81ae-9f88af4ac108.png)

**Expected Behavior**
when i define the funciton and press enter it should have added a tab by default.

**Currernt Behavior**
make a fucntion and press enter  and it will take you to the begining  of next line.

**Steps to reproduce**
create any python file
make a function and press enter 

**Edit**
this does not work at all in python files, i did
```ruby
for i in range(1,101):
```
and was then moved to begining of the next line.
do i need to configure it?

**Comment by archseer** [comment] 2022-09-18 12:19
Duplicate of https://github.com/helix-editor/helix/issues/763

**Closed by archseer** 2022-09-18 12:19 UTC

**Comment by notwidow** [comment] 2022-09-18 13:56
> Duplicate of #763

tell me whether it will be fixed or not? i do programming in python all time and this is totally a mess. it is keeping me from fully convert to helix.

**Comment by archseer** [comment] 2022-09-18 14:06
Did you look at the issue that was linked? It has a PR attached. https://github.com/helix-editor/helix/pull/3382

**Comment by notwidow** [comment] 2022-09-18 14:10
> Did you look at the issue that was linked? It has a PR attached. #3382

i looked at it..but since i tried helix months ago and this issue i faced at that time also. so even after months it exists....

**Comment by archseer** [comment] 2022-09-18 14:12
The fix was recently created (1 month ago) and will eventually be merged. Feel free to contribute and/or test the fix and get it merged sooner.

**Comment by notwidow** [comment] 2022-09-18 14:14
> The fix was recently created (1 month ago) and will eventually be merged. Feel free to contribute and/or test the fix and get it merged sooner.

okay and i noticed that tab inserts 2 spaces... how to change it to 4?

**Comment by archseer** [comment] 2022-09-18 14:16
It should insert 4 for python code: https://github.com/helix-editor/helix/blob/master/languages.toml#L449-L450

**Comment by notwidow** [comment] 2022-09-18 14:17
> It should insert 4 for python code: https://github.com/helix-editor/helix/blob/master/languages.toml#L449-L450

yes but im asking for others... javascript and other langs

**Comment by notwidow** [comment] 2022-09-18 14:17
> It should insert 4 for python code: https://github.com/helix-editor/helix/blob/master/languages.toml#L449-L450

it inserts 2 spaces in js

**Comment by notwidow** [comment] 2022-09-18 14:22
> It should insert 4 for python code: https://github.com/helix-editor/helix/blob/master/languages.toml#L449-L450

there should be an option for tab-width .... some like it 2 some 4 some 3 and some 5

**Comment by Ordoviz** [comment] 2022-09-18 14:27
Add this to your `~/.config/helix/languages.toml`:
```toml
[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
```

**Comment by notwidow** [comment] 2022-09-18 14:30
> Add this to your `~/.config/helix/languages.toml`:
> 
> ```toml
> [[language]]
> name = "javascript"
> indent = { tab-width = 4, unit = "    " }
> ```

i know that but i meant a global one that sets for all. anyway thank you..
that way i will have to write it for every language..
