### ISSUE TITLE
Config option: auto-remove trailing whitespace on save

### ISSUE THREAD

**Issue by Xaeroxe** [helix-editor/helix#4260] opened 2022-10-14 01:01 UTC
Default can be off, but I want helix to remove all trailing whitespace when I save the file.

**Comment by the-mikedavis** [comment] 2022-10-14 01:03
Duplicate of https://github.com/helix-editor/helix/issues/1481

**Comment by Xaeroxe** [comment] 2022-10-14 01:03
Thanks!

**Closed by the-mikedavis** 2022-10-14 01:03 UTC
Labels: R-duplicate, C-enhancement
