### ISSUE TITLE
Support for vim hotkeys

### ISSUE THREAD

**Issue by t0msk** [helix-editor/helix#7343] opened 2023-06-14 12:28 UTC
Hello,

I suggest add vim hotkeys /settings as option, so people who are using vim, doesn't have to learn new shortcuts and they can use their muscle memory :)

**Comment by CptPotato** [comment] 2023-06-14 12:33
I'm pretty sure this is not planned to be part of the official helix build. A lot of things are different from vim for a reason.

I haven't checked it out myself, but you could take a look at [helix-vim](https://github.com/LGUG2Z/helix-vim), though.

**Comment by pascalkuthe** [comment] 2023-06-14 12:34
duplicate of #4419 and not planned. Helix is its own editor with its own semantics that are fundamentally incompatible with vim. We have no intention of ever emulating vim.

**Closed by pascalkuthe** 2023-06-14 12:34 UTC
Labels: C-enhancement
