### ISSUE TITLE
No scrollbar at popup during completion at the bottom of editor

### ISSUE THREAD

**Issue by mgpinf** [helix-editor/helix#8543] opened 2023-10-15 14:21 UTC
### Summary

When at the bottom of the editor when a completion is selected, if it's description spans multiple lines beyond the bottom of the editor from the current position, then there is no way to scroll beyond the first few lines i.e. upto the bottom of the editor.
eg:
![Screenshot 2023-10-15 at 19 28 02](https://github.com/helix-editor/helix/assets/56510798/435f8725-4ca8-4fa9-b4e0-47dc463dcdb4)

This is the full description of the keyword:
![Screenshot 2023-10-15 at 19 28 52](https://github.com/helix-editor/helix/assets/56510798/ac833a83-f9bb-4d45-ab3a-4189e5e0bd4e)

Imo, it would be good to be able to scroll through the description in the first case.

### Platform

macOS

### Terminal Emulator

wezterm 20230712-072601-f4abf8fd

### Helix Version

helix 23.05 (7f5940be)

**Comment by kirawi** [comment] 2023-10-15 15:18
Duplicate of https://github.com/helix-editor/helix/issues/5827

**Closed by kirawi** 2023-10-15 15:18 UTC
Labels: C-bug
