### ISSUE TITLE
Picker preview scrolling

### ISSUE THREAD

**Issue by milosavljevicoa** [helix-editor/helix#4102] opened 2022-10-04 20:34 UTC
In [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) I frequently use to scroll on a given file when in file picker. Unfortunately I have not found a way to this in helix [helix keymap - picker](https://docs.helix-editor.com/keymap.html#picker).

Here is an example. It would be really useful if there was a way to scroll the content of `lib.rs` while in the `file_picker` mode.
![Screenshot from 2022-10-04 22-28-35](https://user-images.githubusercontent.com/47518781/193920696-be9f2641-ea3d-4037-a276-3a0e76a5fc76.png)

 I believe there could be already an issue similar to this, but I could not find it.
Thank for your time :+1:

**Comment by Manosmer** [comment] 2022-10-10 23:26
Hello, I would like to deal with this. I have already started working on it and I believe I have implemented it appropriately

**Comment by neilyio** [comment] 2023-03-03 04:42
It would be great to be able to scroll not just on the preview (right-side), but also on the picker list (left-side).

I find myself wanting to quickly skim across all the files in a folder, and being able to use the mouse-wheel/trackpad to move my selection in the left-side list would be very helpful.

Suggestion:
- When the mouse is over the right side, scroll the preview.
- When the mouse is over the left side, scroll the picker list selection.
- When SHIFT is held down, scroll the right-side preview, regardless of mouse position. After scrolling to beginning/end of file, move the right-side selection up/down continue the scroll into the previous/next file.

This would be amazing for fast codebase navigation.

**Comment by mostafaqanbaryan** [comment] 2023-11-04 09:24
This is really great!
Hope it'd be merged soon.

**Comment by pascalkuthe** [comment] 2024-04-25 22:44
Duplicate of #1018

**Closed by pascalkuthe** 2024-04-25 22:44 UTC
Labels: C-enhancement, A-helix-term
