### ISSUE TITLE
Properly handle html line breaks

### ISSUE THREAD

**Issue by DoctorRyner** [helix-editor/helix#9918] opened 2024-03-18 17:38 UTC
Right now after pressing enter in `<p></p>` for jsx does this:

```html
<p>
  </p>
```

And for html this;

```html
<p>
</p>
```

But it should be:

```html
<p>
  {cursor_here}
</p>
```

**Comment by kirawi** [comment] 2024-03-18 17:45
Duplicate of https://github.com/helix-editor/helix/issues/9425

**Closed by kirawi** 2024-03-18 17:45 UTC
Labels: C-enhancement
