### ISSUE TITLE
Have helix share language servers in a project

### ISSUE THREAD

**Issue by super-secret-github-user** [helix-editor/helix#7535] opened 2023-07-04 13:37 UTC
Currently, each instance of helix spawns its own language server. This is annoying as if I use zellij with strider to open multiple files in helix, I need to wait around a minute for the language server to finish indexing the project in each helix instance.

Could we have an option that lets helix instances share a language server if they are both started in the same zellij session.

Note that this does not require the fully functioning client server model described in [this issue](https://github.com/helix-editor/helix/issues/312).

**Comment by pascalkuthe** [comment] 2023-07-04 13:42
something like that would definitely require a client-server model as described in #312. There needs to be a single press that controls the LS and furthermore, an Ls can only ever have a single version of each file in memory so the helix clients would need to synchronize documents state too (which is the main component of a client server model).

Closing as duplicate of #312

**Closed by pascalkuthe** 2023-07-04 13:42 UTC
Labels: C-enhancement
