### ISSUE TITLE
Underline ignores its color

### ISSUE THREAD

**Issue by st0rmbtw** [helix-editor/helix#7065] opened 2023-05-18 15:54 UTC
### Summary

Underline ignores its color and uses the color of a word.

### Reproduction Steps

 

I tried this:

In `mytheme.toml`:
```toml
"diagnostic.error" = { fg = "blue", underline = { color = "red", style = "curl"} }
```
I expected this to happen:
The color of the underline is red, the color of the word is blue

Instead, this happened:
The color of the underline is blue and the color of the word is also blue
![image](https://github.com/helix-editor/helix/assets/61053971/acaa3eee-4ba7-404d-b7bd-ef9098091c21)

### Platform

Windows

### Terminal Emulator

Windows Terminal, Alacritty

### Helix Version

helix 23.05 (7f5940be)

**Comment by gabydd** [comment] 2023-05-18 16:31
Can you try setting

```
[editor]
undercurl = true
```

To force undercurl it seems that the curly underline isn't showing up at all

**Comment by st0rmbtw** [comment] 2023-05-18 17:35
@gabydd Nope, it didn't help

**Comment by gabydd** [comment] 2023-05-18 17:59
> In config.toml:

theme changes need to be done in a theme file, see making a theme https://docs.helix-editor.com/themes.html#creating-a-theme

you can use ``inherits = "<theme you want to change>"`` in that file to override the underline of a specific theme

**Comment by st0rmbtw** [comment] 2023-05-18 20:33
@gabydd Oh, I meant to write `mytheme.toml` not `config.toml`. I'm going to edit the description.

**Comment by A-Walrus** [comment] 2023-05-19 06:53
I was unable to reproduce, tried on Alacritty but I got the expected results.

**Comment by CptPotato** [comment] 2023-05-19 09:02
If I remember correctly this is a Windows thing. The underline colors and styles get ignored (and filtered out) by conpty, so there's nothing that helix or even the terminal emulator can do.

**Comment by kirawi** [comment] 2023-05-19 21:19
https://github.com/microsoft/terminal/issues/7228

**Comment by gabydd** [comment] 2023-05-19 21:46
This also affects alacritty on windows, so it can probably be marked as upstream and closed

**Comment by st0rmbtw** [comment] 2023-05-20 10:50
![image](https://github.com/helix-editor/helix/assets/61053971/0f0bab47-eb3f-46ee-90fb-d9a901c48740)
Yep, it's a Windows's fault, works on Linux as expected. Should I close this issue?

**Comment by A-Walrus** [comment] 2023-05-20 10:52
Leave it open, in case someone else runs into it

**Comment by andradei** [comment] 2023-07-13 20:03
> Leave it open, in case someone else runs into it

Like me. I can also confirm it's broken on Windows but not on Linux.

**Comment by nkitsaini** [comment] 2023-09-27 18:38
Interestingly I have the issue on Linux with Alacrity using tmux i.e. the undercurl color is derived from syntax highlighting instead of the predefined `red`. The color is accurate (`red`) if I am not inside tmux. I did verify that this is not due to some environment variable by syncing the env variables in both non-tmux and tmux session.

**Comment by nkitsaini** [comment] 2023-09-29 07:21
Update: I was able to get undercurl color working correctly on tmux by following suggestion at: https://old.reddit.com/r/neovim/comments/vqbu8m/undercurl_support_on_different_terminals/ieoxghg/

Specifically enabling coloring by adding following to `~/.tmux.conf`
```
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colors - needs tmux-3.0
```

**Closed** 2024-03-19 11:12 UTC
Labels: C-bug, O-windows, upstream

**Comment by tasnuva1** [comment] 2024-11-02 16:41
> Can you try setting
> 
> ```
> [editor]
> undercurl = true
> ```

Can you please share, How to toggle this by keyboard shortcut?
