### ISSUE TITLE
Jumping between parameters after auto-completion.

### ISSUE THREAD

**Issue by owariee** [helix-editor/helix#8576] opened 2023-10-20 08:45 UTC
![image](https://github.com/helix-editor/helix/assets/100840385/eb649a7c-3e03-4089-b232-e844f2842ff2)
This is more an question about an functionality than anything. After auto-completion, how can i get to the next parameter, and idk if its possible but there is some key bind to get back to the previous parameter as well? After some research i get some answer pointing to Tab and S-Tab but both not work, it just inserts an normal tab into the line, i tried also leaving the insert mode but it causes the auto-completion to finish and parameters get deselected.

**Comment by pascalkuthe** [comment] 2023-10-20 09:28
That's not currently implemented yet. We don't support snippet tabs tops currently. Duplicate of #395

**Closed by pascalkuthe** 2023-10-20 09:28 UTC
