### ISSUE TITLE
[CRASH] Crash when cursor is on <img> element.

### ISSUE THREAD

**Issue by Zh40Le1ZOOB** [helix-editor/helix#9711] opened 2024-02-24 05:02 UTC
### Summary

When the cursor is over quotes surrounding an attribute value of an <img> element nested within a <p> element, Helix gets stuck and CPU usage becomes extremely high.

### Reproduction Steps

Create a new Markdown file, then insert some code like this:

```html
<p>
<img alt="Any text here.">
<p/>
```

Open it with Helix, and move the cursor to the quotation marks.

```html
<p>
<img alt="Any text here.">
^        ^ When the cursor is moved to here, Helix will gets stuck.
Sometimes also stuck at here.
<p/>
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-02-24T12:59:41.485 helix_view::editor [ERROR] Failed to initialize the language servers for `source.md` - `marksman` { cannot find binary path }
```

</details>

### Platform

Arch Linux ARM, aarch64

### Terminal Emulator

PRoot

### Installation Method

pacman

### Helix Version

helix 23.10

**Comment by the-mikedavis** [comment] 2024-02-24 15:00
This has been fixed on master, duplicate of https://github.com/helix-editor/helix/issues/8709

**Closed by the-mikedavis** 2024-02-24 15:00 UTC
Labels: C-bug
