### ISSUE TITLE
Allow documentation of custom keymaps

### ISSUE THREAD

**Issue by maxtremblay** [helix-editor/helix#4082] opened 2022-10-03 15:17 UTC
Hello, I don't know if it is already possible, but I found nothing. I just added a keymap to run the format command more easily.

```toml
[keys.normal]
"space" = { m = ":fmt" } # Format document
```

When I press space in a file and I wait for the helper menu, the command appears but the documentation is a bit weird as you can see in that screenshot. 

![Screenshot from 2022-10-03 11-15-27](https://user-images.githubusercontent.com/52462375/193613530-bd6ad4c5-09b3-4f87-a0cf-bd5e745edc43.png)

It would be nice to have the option to add a custom label. In this case something like "Format document" would look much nicer than ":format []".

**Comment by the-mikedavis** [comment] 2022-10-03 15:25
Duplicate of https://github.com/helix-editor/helix/issues/1752

**Closed by the-mikedavis** 2022-10-03 15:25 UTC
Labels: C-enhancement
