### ISSUE TITLE
Diagnostic message hiding cursor and code

### ISSUE THREAD

**Issue by davidbastien5** [helix-editor/helix#5120] opened 2022-12-11 17:39 UTC
### Summary

Helix's LSP diagnostic error message hides the source code that it is reporting an error for, making it very difficult to (1) see the code that needs fixing and to (2) fix the error. The latter is especially difficult because the LSP message hides the cursor. Note, this issue only occurs when the error being reported by the LSP is on the 2nd line of the source file (i.e., the line where the Helix editor normally displays diagnostics).

### Reproduction Steps

**I tried this**

[![asciicast](https://asciinema.org/a/544775.svg)](https://asciinema.org/a/544775?t=3)

**I expected this to happen**

When an LSP reports an error on the line where Helix normally displays diagnostics, Helix would shift the placement of the error message below or above the line (or anywhere else but on the line itself) to allow the user to see the affected source code in full, and to be able to make the necessary changes.

**Instead, this happened**

Helix displays the error message directly over the source code that it is reporting an error for, as well as the cursor.

### Platform

macOS

### Terminal Emulator

Alacrity 0.11.0-dev

### Helix Version

helix 22.12 (96ff64a8)

**Comment by the-mikedavis** [comment] 2022-12-11 18:25
Duplicate of https://github.com/helix-editor/helix/issues/1462

**Closed by the-mikedavis** 2022-12-11 18:25 UTC
Labels: C-bug
