### ISSUE TITLE
Can't launch helix on the directory , env. %SYSTEMDRIVE% (Windows), Running <hx .> will give an unexpected result.  

### ISSUE THREAD

**Issue by reiend** [helix-editor/helix#2061] opened 2022-04-10 14:01 UTC
### Reproduction step

use windows 10
scoop install helix
run <hx .> on env. %SYSTEMDRIVE%

### Result

I'm not sure how long it takes until this occur
![image](https://user-images.githubusercontent.com/93508511/162622485-25bb0a2f-4be8-4a6d-b0ff-1a6d9840e977.png)

### Platform
Windows 10
Powershell v7.2.2

### Helix Version
helix 22.03

**Comment by kirawi** [comment] 2022-04-10 21:02
I can't reproduce.

**Comment by reiend** [comment] 2022-04-11 04:49
> I can't reproduce, it opens the file picker like expected for me.
my apologies, I didn't check the issue twice. It's working just fine as you said. 
I accidentally enter the file name chipset.exe on the file picker after the hx started.

one thing is, there's some slow loading times on the %SYSTEMDRIVE%
### helix 
![helix_slow](https://user-images.githubusercontent.com/93508511/162666785-031385f3-4797-4ff7-8946-4e2031ea3d08.gif)

### lvim
![lvim](https://user-images.githubusercontent.com/93508511/162666744-5a533ce9-e9c6-4de8-8525-9e6c3c782c0b.gif)

### helix on the other directory
![helix_fast](https://user-images.githubusercontent.com/93508511/162666800-0cdfcb48-fbe7-470e-8a5f-1f34cfcac922.gif)

**Comment by reiend** [comment] 2022-04-11 04:55
I should probably change the title. into, slow startup on the directory  %SYSTEMDRIVE% (Windows). 
or should I create new issue for this one?

**Comment by the-mikedavis** [comment] 2022-04-11 12:14
It looks like `%SYSTEMDRIVE%` has many files and is not a git repository, right?

In that case I'm pretty sure this is a duplicate of https://github.com/helix-editor/helix/issues/1707

**Comment by kirawi** [comment] 2022-04-11 15:57
It's equivalent to the location of the boot drive, so it would search through every file in the drive

**Comment by reiend** [comment] 2022-04-12 00:20
> It looks like `%SYSTEMDRIVE%` has many files and is not a git repository, right?
> 
> In that case I'm pretty sure this is a duplicate of #1707

yes.

thanks for the link @the-mikedavis.

**Comment by the-mikedavis** [comment] 2022-04-12 00:26
In that case, let's close out in favor of the discussion in #1707

**Closed by the-mikedavis** 2022-04-12 00:26 UTC
Labels: O-windows

**Comment by reiend** [comment] 2022-04-12 00:28
> It's equivalent to the location of the boot drive, so it would search through every file in the drive

opening the said directory for the first time will take more time. I think this is where I accidentally open the chipset file.
but once  you open it once, it will behave the same as the first gif I showed above.
