### ISSUE TITLE
ctrl-d ctrl-u not scrolling popup documentation

### ISSUE THREAD

**Issue by jcbritobr** [helix-editor/helix#3062] opened 2022-07-13 22:49 UTC
### Summary

When popuping documentation in helix editor using rust plugin, the keys ctrl-d/ctrl-u doesn't scroll the popup doc window.
![image](https://user-images.githubusercontent.com/6579862/178849810-f627e844-d4a7-4cb4-8ce3-c1756f989ad3.png)

### Reproduction Steps

Type code until the popup documentation appear. If has more documentation hidden, try scroll down using ctrl-d(it will not scroll).

### Platform

Linux, popos 22.04

### Terminal Emulator

alacritty default gnome term

### Helix Version

helix 22.05 (27609f50)

**Comment by jcbritobr** [comment] 2022-07-14 02:24
Also, noticed, if we open the docs with space k, all worked as expected.

**Comment by adsick** [comment] 2022-08-08 18:36
same

**Comment by Dangerised** [comment] 2024-01-29 10:27
Anything about the issue ? I meet the same problem at the newest version

**Comment by pashadia** [comment] 2024-04-10 20:39
I've arrived to this issue looking for another set of Ctrl- based shortcuts.

I think this issue is related to Alacritty, and to some specific control characters. My specific problem was with C-i sending a `\u0009` which translates to a Tab. I am searching for a solution for a proper `alacritty` config.

**Comment by pascalkuthe** [comment] 2024-04-25 22:45
Duplicate of https://github.com/helix-editor/helix/issues/1614

**Closed by pascalkuthe** 2024-04-25 22:45 UTC
Labels: C-bug, A-helix-term

**Comment by babucarr32** [comment] 2025-01-23 13:53
I scroll using `arrow-up` and `arrow-down`
