### ISSUE TITLE
The search register popup does not update visually when you use * to yank to "/

### ISSUE THREAD

**Issue by taranlu-houzz** [helix-editor/helix#7184] opened 2023-05-30 19:04 UTC
### Summary

Going through the `hx --tutor` currently, and I noticed that when I use `"` to bring up the registers popup, it does not correctly show the value for `/` if `*` was used to yank the selected text.

### Reproduction Steps

 

I tried this:

1. Select a word.
2. Use `*` to yank to the `/` register.
3. Use `"` to bring up the registers popup.
4. The value for `/` has not been updated visually (using `n` and `N` works correctly on using the value that was yanked).

I expected this to happen:

The ui should update the popup so that the correct value is displayed for the register.

Instead, this happened:

The value displayed was not updated (despite the fact that the register has is correct).

### Helix log

No log

### Platform

macOS

### Terminal Emulator

wezterm 20230408-112425-69ae8472

### Helix Version

helix 23.05

**Comment by the-mikedavis** [comment] 2023-05-30 22:53
Duplicate of #5241

**Closed** 2023-05-30 22:53 UTC
Labels: C-bug
