### ISSUE TITLE
Delayed escape in tmux

### ISSUE THREAD

**Issue by nrgustilo** [helix-editor/helix#2122] opened 2022-04-15 19:53 UTC
### Summary

Trying out helix and I think I found a bug: normally hitting i, esc, j works as expected dropping cursor by one line, but when running helix under tmux this prints 'j'. If I hit escape twice (i, esc, esc, j), then j works as expected in normal mode. If I wait for ~1 second then j works. It seems like the transition to normal mode is very slow under tmux, which the status bar confirms.

* Tested on Ubuntu 20.04 with Alacritty v22.03
* Also seen on Windows terminal ssh'd into Ubuntu VM compiling from master branch

```
tmux
hx -vvvv <file>
i, esc, j
```
```
2022-04-15T12:40:08.690 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-04-15T12:40:08.690 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-04-15T12:40:08.690 mio::poll [TRACE] registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
2022-04-15T12:40:08.690 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE
2022-04-15T12:40:08.690 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE
2022-04-15T12:40:11.335 helix_core::auto_pairs [DEBUG] autopairs hook selection: Selection {
    ranges: [
        Range {
            anchor: 1,
            head: 0,
            horiz: None,
        },
    ],
    primary_index: 0,
}
```

```
hx -vvvv <file>
i, esc, j
```
```
2022-04-15T12:42:10.158 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-04-15T12:42:10.159 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-04-15T12:42:10.159 mio::poll [TRACE] registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
2022-04-15T12:42:10.159 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE
2022-04-15T12:42:10.159 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE
```

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by the-mikedavis** [comment] 2022-04-15 19:57
Duplicate of #2039

See https://github.com/helix-editor/helix/wiki/Troubleshooting#when-using-tmux-or-screen-there-is-a-delay-after-hitting-escape-before-its-registered

**Closed by the-mikedavis** 2022-04-15 19:57 UTC
Labels: C-bug

**Comment by nrgustilo** [comment] 2022-04-15 20:02
Thanks, that worked. I wonder why Neovim doesn't display the same behavior though if tmux is delaying the character input.
