### ISSUE TITLE
Trailing whitespaces

### ISSUE THREAD

**Issue by 71GA** [helix-editor/helix#8461] opened 2023-10-03 21:01 UTC
Thank you for maintaining end developing Helix! It would really be nice if it could show trailing white spaces somehow! Maybee it could render some user selectable characters  where trailing whitespaces are. I think this could be a quick fix!

Please reconsider my request! Since I switched from Neovim to Helix, my development team constantly argues that I am leaving too many trailing spaces in my source code.

**Comment by the-mikedavis** [comment] 2023-10-03 21:06
Duplicate of https://github.com/helix-editor/helix/issues/2719

**Closed by the-mikedavis** 2023-10-03 21:06 UTC
Labels: C-enhancement
