### ISSUE TITLE
Indent guides inherit formatting of comment blocks

### ISSUE THREAD

**Issue by sbromberger** [helix-editor/helix#10362] opened 2024-04-12 00:16 UTC
### Summary

When using a multi-line comment block, the indent guides appear to inherit the formatting of the comments (in this case, italics). I think this might be a regression because I recall seeing an old issue about this.

Screenshot attached:

<img width="1366" alt="image" src="https://github.com/helix-editor/helix/assets/941359/2bd50a66-1fd1-4ec2-8cbe-d112b625f9f3">

### Reproduction Steps

 

I tried this:

1. `hx foo.cpp`
2. Created a multi-line comment

I expected this to happen:
The indent guide format would be independent of the text.

Instead, this happened:
The indent guides took on the formatting of the text.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Void Linux

### Terminal Emulator

blink.sh via mosh

### Installation Method

source

### Helix Version

helix 24.3 (b974716b)

**Comment by the-mikedavis** [comment] 2024-04-12 01:45
Duplicate of #9305

**Closed by the-mikedavis** 2024-04-12 01:45 UTC
Labels: C-bug
