### ISSUE TITLE
Treat backslashes equivalent to forward slashes in file picker and `:open`

### ISSUE THREAD

**Issue by Boscop** [helix-editor/helix#6744] opened 2023-04-13 15:00 UTC
Thanks for creating Helix, I'm starting to really like it :)
I'm testing it on different OSs and I have a suggestion:
Ideally, on platforms where paths use backslashes (windows), it should still be possible to navigate to `foo\bar\baz.rs` by typing `foo/bar/baz.rs` in the file picker (or in any other situation where file paths are matched, like in `:open`/`:write`, entering `/` should also lead to auto-completion of subdirs as if the user had entered `\`).
Currently both the file picker and `:open` treat backslash as a totally different symbol than forward slash which means that the intended file path doesn't appear because it is not matched.
This would result in a more streamlined cross-platform editing experience.
(Windows explorer / cmd.exe / winapi also resolve paths that use forward slashes.)

**Comment by the-mikedavis** [comment] 2023-04-13 16:17
Duplicate of https://github.com/helix-editor/helix/issues/5414

**Closed by the-mikedavis** 2023-04-13 16:17 UTC
