### ISSUE TITLE
New `:remove` command

### ISSUE THREAD

**Issue by NikitaRevenco** [helix-editor/helix#12169] opened 2024-12-01 18:56 UTC
It's useful to be able to delete the current file. When https://github.com/helix-editor/helix/pull/11164 is merged you'll be able to do it with `:sh rm %{f}`.

But when you do that, the current file is still loaded. If you use `:reload` you'll get an error `Can't find file to reload from "file.txt"`

What would be nice alternative, is when you run `:remove`, you are force switched to a different open buffer. If none are open, a scratch buffer is open instead.

**Comment by the-mikedavis** [comment] 2024-12-02 14:59
Duplicate of https://github.com/helix-editor/helix/issues/4592

**Closed by the-mikedavis** 2024-12-02 14:59 UTC
