### ISSUE TITLE
Pressing tab should insert amount of spaces required for next tab stop

### ISSUE THREAD

**Issue by SN9NV** [helix-editor/helix#3999] opened 2022-09-27 19:58 UTC
### Summary

I will open a file like `hx test.sql`, and while working on the file, it seems that the tab key is just adding 4 spaces instead of adding the required amount of spaces to get to the next tab stop. I'm pretty sure that this was working before, and now it seems that it's not working the way I expect it to. In Go, this seems to work as expected.

### Reproduction Steps

 

I tried this:

1. `hx test.sql`

I expected this to happen:
```
CREATE TABLE a (
    id     SERIAL,
    testa  INT,
    testab INT
)
```

Instead, this happened:
```
CREATE TABLE a (
    id    SERIAL,
    testa    INT,
    testab    INT
)
```

### Platform

Linux

### Terminal Emulator

alacritty 0.10.1

### Helix Version

22.08.1-116-gbdc7b352

**Comment by Ordoviz** [comment] 2022-09-28 07:20
SQL is one of the languages where pressing <kbd>TAB</kbd> inserts spaces, see [languages.toml](https://github.com/helix-editor/helix/blob/master/languages.toml). You can overwrite this by adding the following to your `~/.config/helix/languages.toml`:

```toml
[[language]]
name = "sql"
indent = { tab-width = 4, unit = "\t" }
```

**Comment by SN9NV** [comment] 2022-09-28 10:20
I think you are misunderstanding my issue.

I want and expect spaces. That's not the problem. The problem is that the number of spaces inserted should be the number needed to get to the next tab stop, but it's inserting 4 spaces regardless of the previous position.

For example, if I have a line `id` and I type tab, with a `tab-width` of 4, I expect it to insert 2 more spaces to get me to the next tab stop column: 4, but a tab inserts 4 spaces, taking me to column: 6, which is beyond the next tab stop and then it's a lot of work to figure out where the next tab stop should be and to manually insert the correct number of spaces to get everything to line up.

**Comment by Ordoviz** [comment] 2022-09-28 11:02
Sorry, my bad. What you are describing seems like a useful feature, consider renaming this issue to "Pressing tab should insert amount of spaces required for next tab stop".

I believe the reason this "works" in Go is that tab characters are inserted when you press <kbd>Tab</kbd>:
https://github.com/helix-editor/helix/blob/bdc7b35214ec12a013941f7f6753331d47952bb2/languages.toml#L240-L250

**Comment by SN9NV** [comment] 2022-09-28 11:28
It seems that you are right. I didn't test any other file type. But testing `fish`, and `python`, I can see that tabs are inserting 4 spaces regardless of the language. I expected this to be a base feature of an editor, so it skipped my mind that it would be missing, so it seemed to be a problem with just the SQL configuration or something. It's possible that the previous SQL files I created in the past was done with vim, so it explains why I thought it used to work the way I expected.

I will update the title to reflect this as you suggested.

**Comment by Ordoviz** [comment] 2022-09-28 19:41
I just noticed this is a duplicate of #2124.

**Comment by the-mikedavis** [comment] 2022-09-28 19:51
Duplicate of https://github.com/helix-editor/helix/issues/2124

**Closed by the-mikedavis** 2022-09-28 19:51 UTC
Labels: C-bug
