### ISSUE TITLE
Open file at a given line

### ISSUE THREAD

**Issue by Eloitor** [helix-editor/helix#5705] opened 2023-01-27 19:28 UTC
Hi, is there an option to open a file in a given line? If not I think it could be useful to have something like this:

```
hx +3 test.txt
```

Would open `test.txt` at line 3.

I encountered a need for this here: https://github.com/leahneukirchen/xtools/issues/279

**Comment by the-mikedavis** [comment] 2023-01-27 19:47
Duplicate of https://github.com/helix-editor/helix/issues/5437

**Closed by the-mikedavis** 2023-01-27 19:47 UTC
Labels: C-enhancement
