### ISSUE TITLE
regexp lookarounds support

### ISSUE THREAD

**Issue by 3RM1N3** [helix-editor/helix#3341] opened 2022-08-06 00:12 UTC
Dear helix team:

I noticed that helix does not support regexp lookarounds: Positive/Negative Lookahead, just like `/github(?=.com)/g`, 
but I think lots of people need this feature at work, so do I.

Please add this feature, heartfelt thanks.

**Comment by the-mikedavis** [comment] 2022-08-06 00:39
Duplicate of https://github.com/helix-editor/helix/issues/3065

**Closed by the-mikedavis** 2022-08-06 00:39 UTC
Labels: C-enhancement
