### ISSUE TITLE
The completion menu does not update the content after lsp actions

### ISSUE THREAD

**Issue by vanarok** [helix-editor/helix#7048] opened 2023-05-15 06:38 UTC
I found this when using volar lsp with takevOverMode which allows it to be used with both vue and typescript files.

My languages.toml: 
```[[language]]
name = "vue"
file-types = ['vue']
formatter = { command = 'prettier', args = ["--parser", "vue"] }
roots = ["package.json", "vite.config.js"]
injection-regex = "vue"
auto-format = true
scope = "text.html.vue"
language-servers = [ { name = "volar", except-features = ["format"] }]
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "vue"
source = { git = "https://github.com/ikatyang/tree-sitter-vue", rev = "91fe2754796cd8fba5f229505a23fa08f3546c06" }

[language-server.volar]
args = ["--stdio"]
command = "vue-language-server"

[language-server.volar.config.typescript]
tsdk = '/home/vanarok/.local/share/pnpm/global/5/node_modules/typescript/lib'

[language-server.volar.config.languageFeatures]
semanticTokens = true
references = true
definition = true
typeDefinition = true
callHierarchy = true
hover = true
rename = true
renameFileRefactoring = true
signatureHelp = true
codeAction = true
completion = { defaultTagNameCase = 'both', defaultAttrNameCase = 'kebabCase' }
schemaRequestService = true
documentHighlight = true
documentLink = true
codeLens = true
diagnostics = true
takeOverMode = true

[language-server.volar.config.documentFeatures]
documentColor = false
selectionRange = true
foldingRange = true
linkedEditingRange = true
documentSymbol = true
documentFormatting = { defaultPrintWidth = 100 }

[[language]]
name = "typescript"
roots = ["package.json", "vite.config.js"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [{ name = "volar", except-features = ["format"] ]
auto-format = true
```

Procedure for playback:
1. use renaming for example on a function to change the name to "sky" in the typescript file
2. open the vue file and use the completion menu to get the renamed function - see "sky"
3. Use renaming again e.g. the same function to "river" in the typescript file
4. Change the buffer to the vue file that was opened earlier and use the completion menu to get the renamed function - we see "sky".

**Comment by pascalkuthe** [comment] 2023-05-15 14:01
duplicate of #https://github.com/helix-editor/helix/issues/2479. The Vue LSP is only active for Vue files (which is why we send didChange notification there) but not for the TS buffer (there the TS LSP is active). So fixing the problem will require: saving the TS file and then a file watcher that notifies the server of the changes (missing from helix)

**Closed by pascalkuthe** 2023-05-15 14:01 UTC
