### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by gerardp** [helix-editor/helix#7093] opened 2023-05-21 10:11 UTC
Hello, 
would it be possible to have a sidebar with the directory and file tree as Neovim has?

https://user-images.githubusercontent.com/292349/115996270-78c6c480-a593-11eb-8ed0-7d1400b058f5.png

**Comment by pascalkuthe** [comment] 2023-05-21 10:22
Duplicate of #200

**Closed by pascalkuthe** 2023-05-21 10:22 UTC
Labels: C-enhancement
