### ISSUE TITLE
Panic after pressing tab while in `INSERT` mode

### ISSUE THREAD

**Issue by InappropriatePenguin** [helix-editor/helix#5198] opened 2022-12-17 23:31 UTC
### Summary

I'm consistently encountering a crash while working on a particular Lua file. After adding spaces around `..` on a particular line, pressing `TAB` makes helix panic.

### Reproduction Steps

 

I was modifying the following line in a Lua file:

```lua
techs[Launchpad.name_tech_rocket_cargo_safety.."-"..i]
```

While in `INSERT` mode, I added spaces around the first `..` then pressed `TAB`. This appears to consistently make helix panic in the file I'm working on.

I expected this to happen:

For it not to crash.

Instead, this happened:

Helix crashed with the following stack trace (after setting `RUST_BACKTRACE` to 1):
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid char range 51997..4616: start must be <= end', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/ropey-1.5.1-alpha/src/rope.rs:546:37
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: ropey::rope::Rope::remove
   4: helix_core::transaction::ChangeSet::apply
   5: helix_view::document::Document::apply_impl
   6: helix_view::document::Document::apply
   7: helix_term::ui::completion::Completion::new::{{closure}}
   8: <helix_term::ui::menu::Menu<T> as helix_term::compositor::Component>::handle_event
   9: <helix_term::ui::popup::Popup<T> as helix_term::compositor::Component>::handle_event
  10: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
  11: helix_term::compositor::Compositor::handle_event
  12: helix_term::application::Application::run::{{closure}}
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: tokio::runtime::park::CachedParkThread::block_on
  15: tokio::runtime::runtime::Runtime::block_on
  16: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-12-18T02:53:04.200 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:04.304 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:04.304 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:04.421 helix_term::application [ERROR] Language Server: Method not found window/showMessageRequest
2022-12-18T02:53:04.432 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:04.432 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:04.542 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:04.751 helix_term::application [ERROR] Language Server: Method not found workspace/diagnostic/refresh
2022-12-18T02:53:05.199 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:05.488 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:06.212 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:07.227 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:08.202 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:09.213 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:10.246 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:11.211 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:12.258 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:14.234 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:15.341 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:16.293 helix_term::application [ERROR] Language Server: Method not found workspace/diagnostic/refresh
2022-12-18T02:53:16.302 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:17.222 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:18.224 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:19.228 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:20.233 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:21.236 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:22.239 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:23.242 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:24.247 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:25.251 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:26.254 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:27.254 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:28.259 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:29.262 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:30.266 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:31.270 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:32.940 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:33.277 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:34.323 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:35.284 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:36.289 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:37.293 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:38.117 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:44.136 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:46.224 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:46.340 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:46.934 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:53.000 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:53.329 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:53.654 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:57.062 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:57.334 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:57.744 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:58.415 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:58.570 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:53:59.094 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:06.632 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:07.068 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:09.975 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:10.382 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:10.643 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:12.939 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:13.393 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:13.491 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:16.634 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:17.165 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:18.923 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:19.083 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:19.241 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:19.414 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:19.877 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:20.248 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:20.417 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:54:20.837 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:40.301 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:40.408 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:40.408 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:40.527 helix_term::application [ERROR] Language Server: Method not found window/showMessageRequest
2022-12-18T02:55:40.539 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:40.539 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:40.648 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:40.801 helix_term::application [ERROR] Language Server: Method not found workspace/diagnostic/refresh
2022-12-18T02:55:41.299 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:41.672 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:41.780 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:42.385 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:43.308 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:44.349 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:45.327 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:46.327 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:47.318 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:48.329 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:49.318 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:50.386 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:51.330 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:52.417 helix_term::application [ERROR] Language Server: Method not found workspace/diagnostic/refresh
2022-12-18T02:55:52.426 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:53.323 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:54.326 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:55.327 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:56.327 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:57.331 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:58.334 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:59.334 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:55:59.809 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:56:02.275 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2022-12-18T02:56:02.341 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
```

</details>

### Platform

macOS

### Terminal Emulator

alacritty 0.11.0 (8dbaa0b)

### Helix Version

helix 22.12 (96ff64a8)

**Comment by the-mikedavis** [comment] 2022-12-18 16:05
I can't reproduce this, I think because it needs the full file. Do you have a minimal file that reproduces this?

It looks like it's caused by the ranges the language server sent for a completion item. If you can reproduce this it would also be useful to see the log when running in verbose mode (`hx -v`)

**Comment by InappropriatePenguin** [comment] 2022-12-19 11:13
Thanks a lot for looking into this. While the panic is reproducible for me with that file alone (in a separate workspace), I've not been able to pare it down any further while still encountering the error.

I'm also unfortunately unable to share the verbose log since it appears to include far too many things that I would need to redact before posting online.

I realize I'm not giving you that much to work with, so please feel free to close this issue. I can either re-open it or create a new issue if I come up with a small reproducible example.

**Comment by pascalkuthe** [comment] 2023-01-18 23:14
Closing, see comment above

**Closed by pascalkuthe** 2023-01-18 23:14 UTC
Labels: C-bug, A-helix-term
