### ISSUE TITLE
goto definition with split

### ISSUE THREAD

**Issue by AK-10** [helix-editor/helix#4720] opened 2022-11-12 10:20 UTC
Is it possible to jump definition with split?

I usually use neovim.
I have customized the settings to allow definition jumps while splitting.
the behavior looks like this.
![2022-11-12_19-16-00](https://user-images.githubusercontent.com/27846333/201469609-bbac1e9e-4123-47d8-bf3d-9a36c516e89a.gif)

**Comment by Nojipiz** [comment] 2022-11-15 23:00
I use neovim with the same configuration and is awesome, but i think that this kind of behaviour mustn't be implemented in the core editor, the correct way to create this is using a plugin system.
The mantainers are working on the roadmap for the plugin system at the discutions page.

**Comment by AK-10** [comment] 2022-11-16 13:45
@Nojipiz 
thank you for your reply.

In my opinion, either plugin or core is fine.
vim (neovim) is a plugin and vscode is implemented in core(https://github.com/microsoft/vscode/blob/bd32dd5c8fae9c19cc7cd2455d32ccf41cb74b45/src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts#L317)

I would like to hear maintainer opinion.

@kirawi 
what do you think about this?

(I'm not good at English. sorry if it's bad english)

**Comment by Nojipiz** [comment] 2022-11-16 13:49
Wow! I didn't know about the vscode core implementation.
Anyways, i want to hear the maintainer opinion too.
(Don't worry about English, i'm not native either :smile:)

**Comment by archseer** [comment] 2022-11-17 01:20
This is https://github.com/helix-editor/helix/pull/3652 and possibly duplicate of https://github.com/helix-editor/helix/issues/3167

**Comment by AK-10** [comment] 2022-11-17 15:51
@archseer 
thank you.

I confirmed [this PR](https://github.com/helix-editor/helix/pull/3652)'s behavior.

Nice feature, but not the behavior I expected.
I'd like to split always when jump deifnition.

so, I'm going to create pull request for my expected features.

**Comment by archseer** [comment] 2022-11-19 06:30
You could create a keybind in your user config that calls the vsplit command then goto definition.

**Comment by AK-10** [comment] 2022-11-19 08:22
I created this config.
I got expected behavior!

thank you!

```
[keys.normal]
"g" = { "d" = ["hsplit", "jump_view_up", "goto_definition"] }
```

**Closed** 2022-11-19 08:23 UTC
Labels: C-enhancement, E-easy, A-helix-term, E-good-first-issue
