### ISSUE TITLE
Label custom commands on Space menu

### ISSUE THREAD

**Issue by felipebueno** [helix-editor/helix#11781] opened 2024-09-26 13:10 UTC
Is it possible to label the commands I add to  the ```keys.normal."space"``` menu?

![image](https://github.com/user-attachments/assets/6b17a781-c3d8-4cf1-a61d-fa24381a3626)

**Comment by the-mikedavis** [comment] 2024-09-26 13:23
Not currently. Duplicate of https://github.com/helix-editor/helix/issues/1752

**Closed by the-mikedavis** 2024-09-26 13:23 UTC
