### ISSUE TITLE
Headless mode?

### ISSUE THREAD

**Issue by kylebfredrickson** [helix-editor/helix#7609] opened 2023-07-12 13:38 UTC
I'm a big fan of Helix. The selection system and multiple cursors seems to mesh perfectly, with the end result being a more powerful (and practical) macro system than vim's.

That being said one of the big advantages of NeoVim is its ability to run headless. This gives it the ability to run in other editors (VS Code being a big one) with plugins. I would really like to see something like this come to Helix, and I think it would be a good way to future proof the editor. 

I want to see Helix's modal model live on! It's a strict improvement.

**Comment by pascalkuthe** [comment] 2023-07-12 14:05
duplicate of duplicate of #5880 and https://github.com/helix-editor/helix/issues/312

**Closed by pascalkuthe** 2023-07-12 14:05 UTC
Labels: C-enhancement
