### ISSUE TITLE
Markdown's \`\`\` incorrectly adds a single \`

### ISSUE THREAD

**Issue by TornaxO7** [helix-editor/helix#12124] opened 2024-11-25 01:25 UTC
### Summary

If I open up a markdown file and I'd like to start writing a code block like this:

```rust
fn main() {
    println!("This is an example.");
}
```
you must write \`\`\` in the first line and in the last line to mark the beginning and the end of the codeblock.
If I type the three \`\`\` backticks into a markdown file, helix is automatically adding a forth backtick character.
It would be nice, if it would add \`\`\` instead.

### Reproduction Steps

 

I tried this:

1. `hx /tmp/test.md`
2. Type "i\`\`\`"

## I expected this to happen
```
\`\`\`|\`\`\`
      ^ cursor
```
(ignore the backslashes)

Instead, this happened:
```
\`\`\`|\`
      ^ cursor
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

rio

### Installation Method

nixpkgs

### Helix Version

helix 24.07-215-g38faf74f

**Comment by the-mikedavis** [comment] 2024-11-25 14:44
Duplicate of https://github.com/helix-editor/helix/issues/4035

**Closed by the-mikedavis** 2024-11-25 14:44 UTC
Labels: C-bug

**Comment by TornaxO7** [comment] 2024-11-25 15:28
Oooooooooooof, sorry! ._.
