### ISSUE TITLE
Missing command `move_prev_long_word_end`

### ISSUE THREAD

**Issue by liferooter** [helix-editor/helix#7049] opened 2023-05-15 09:43 UTC
`move_next_long_word_start`: exists.
`move_next_long_word_end`: exists.
`move_prev_long_word_start`: exists.
`move_prev_long_word_end`: doesn't exist.

Why?

I suggest to add such command. At least I'll be able to consistently remap these commands.

**Comment by the-mikedavis** [comment] 2023-05-15 10:59
Duplicate of https://github.com/helix-editor/helix/issues/6904

**Closed by the-mikedavis** 2023-05-15 10:59 UTC
Labels: C-enhancement
