### ISSUE TITLE
Loader for `run-shell-command`

### ISSUE THREAD

**Issue by blitzarx1** [helix-editor/helix#7688] opened 2023-07-20 09:49 UTC
Currently there is no way in helix to know whether shell command which is run with `run-shell-command` is still running or not.

I thinks this will not be to difficult to include loader for run shell command similar to one which is displayed when lsp is indexing. Like on the screenshot.

<img width="525" alt="Screenshot 2023-07-20 at 13 48 45" src="https://github.com/helix-editor/helix/assets/32969427/602cf039-d4b6-441c-bedb-5bd5412be6f4">

**Comment by pascalkuthe** [comment] 2023-07-20 10:16
Duplicate of #7338

**Closed by pascalkuthe** 2023-07-20 10:16 UTC
Labels: C-enhancement
