### ISSUE TITLE
Global search through fuzzy picker

### ISSUE THREAD

**Issue by matoous** [helix-editor/helix#1283] opened 2021-12-17 13:54 UTC
#### Describe your feature request

Global search could be more useful (subjective opinion) if there were live results available. Would it make more sense for global search (`space + /`) to pop fuzzy finder the same way for example `space + f` does for files currently?

**Comment by pppKin** [comment] 2022-01-10 12:32
@archseer thought of this before, but ultimately it was just too troublesome(for me at least) to implement a special type of `Picker` and take care of the "search and update picker view" process. I'd love to help though now that I finally have some more time to work on helix! What do you have in mind?

**Comment by archseer** [comment] 2022-04-13 06:02
Closing this as a duplicate of #196 (we made that the tracking issue now)

**Closed by archseer** 2022-04-13 06:02 UTC
Labels: C-enhancement, A-helix-term, E-hard
