### ISSUE TITLE
Identation inside a multi-line string not aware of surrounding context

### ISSUE THREAD

**Issue by leandrobbraga** [helix-editor/helix#8446] opened 2023-10-02 18:43 UTC
### Summary

Would be nice if the context indentation level would be maintained while editing multi-line strings.

For example:

Vscode
![vscode-indent](https://github.com/helix-editor/helix/assets/18340809/7955596e-56f1-41e8-9df8-38c49c0a18ba)

Helix
![helix-indent](https://github.com/helix-editor/helix/assets/18340809/7034083e-afff-4ec9-a257-bbeb5ad808a9)

My guess is that Helix is using the current indent level of the surrounding function, instead of using the string's  internal content indentation level.

NOTE: I tried with a new commit as well (4e86d1c35adbb7c158b2d262e4c129c2bee41a0a), same behavior

### Reproduction Steps

Create a multi-line string that have some indentation level, example:

```rust
fn my_function() {
    let query = r#"
    SELECT
        id|<- cursor here 
    FROM table"#
}
```

If you try to add a newline with "open-below" (`o`), the indentation will match the "let" level instead of the "id".

What happens
```rust
fn my_function() {
    let query = r#"
    SELECT
        id
    |<- here
    FROM table"#
}
```

What's expected
```rust
fn my_function() {
    let query = r#"
    SELECT
        id
        |<- here
    FROM table"#
}
```

### Platform

Linux

### Terminal Emulator

alacritty 0.12.2 (9d9982df)

### Helix Version

helix 23.05

**Comment by kirawi** [comment] 2023-10-02 18:47
Looks like a duplicate of https://github.com/helix-editor/helix/issues/6939 which is partially resolved by https://github.com/helix-editor/helix/pull/8307

**Closed by kirawi** 2023-10-02 18:47 UTC
Labels: C-bug
