### ISSUE TITLE
View mode changes cursor position

### ISSUE THREAD

**Issue by l4l** [helix-editor/helix#9852] opened 2024-03-11 23:17 UTC
Haven't used view mode a lot but just figure out it changes cursor position which is quite unexpected to me. Not sure how other editors handle that but I believe for helix it breaks the multicursor editing flow.

Use-case is the following: made some selections -> want to check these are correct -> go to view mode via `Z` -> scroll -> find out the selection is removed. 

I'm aware about `alt+(`/`)` but sometimes that's not enough as it still limited to the area around selection.

**Comment by the-mikedavis** [comment] 2024-03-12 13:00
This is a consequence of enforcing that the primary cursor should always be in view

Duplicate of https://github.com/helix-editor/helix/issues/2134

**Closed by the-mikedavis** 2024-03-12 13:00 UTC
Labels: C-enhancement
