### ISSUE TITLE
Add `languages-config-open` command

### ISSUE THREAD

**Issue by bluthej** [helix-editor/helix#7916] opened 2023-08-12 08:03 UTC
I really like the `config-open` and `config-reload` commands, they are super convenient! But I'm missing a `languages-config-open` or maybe a `lang-config-open` to open my `languages.toml`.

I think it would be pretty sweet to have that :)

I have mapped a shortcut to run `:open` with the path to `languages.toml`, but the drawback is that the path will not be the same on Windows, so this config cannot be shared across platforms.

Or maybe there is already a command that does that that I'm not aware of?

**Comment by gabydd** [comment] 2023-08-12 12:13
Duplicate of https://github.com/helix-editor/helix/issues/3495

**Closed** 2023-08-12 12:13 UTC
