### ISSUE TITLE
Unable to scroll popup

### ISSUE THREAD

**Issue by nexovec** [helix-editor/helix#7915] opened 2023-08-12 04:11 UTC
### Summary

Hi,
it is not possible to scroll popups from the ctrl+x autocomplete menu.

### Reproduction Steps

 

I tried this:

1. `open file with a working lsp to get autocomplete, I'll use python here.`
2. `from os import p`
3. Ctrl+x, down arrow (shows documentation popup for os.path)
4. Ctrl+d

I expected this to happen:

Scroll down inside the popup.

Instead, this happened:

Nothing.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
I believe this is not relevant.
```

</details>

### Platform

Linux

### Terminal Emulator

Yakuake

### Helix Version

helix 23.05 (7f5940be)

**Comment by gabydd** [comment] 2023-08-12 04:46
Duplicate of https://github.com/helix-editor/helix/issues/3062

**Closed** 2023-08-12 04:47 UTC
Labels: C-bug
