### ISSUE TITLE
Variable name for the current filename in the active buffer

### ISSUE THREAD

**Issue by muminoff** [helix-editor/helix#4107] opened 2022-10-05 11:52 UTC
Hi folks,

Thanks for your hard work! Helix became my daily main editor.

One thing I would like to ask. Is there any variable name for the current filename?

For example, if I want to run shell command with the filename which is currently opened, how can I achieve it? In Vim/Neovim, there is `%` character for it (in Vim/Neovim I usually do `:!deno run %`). 

I have following lines in my `config.toml` and I want to replace `{filename}` to that variable name if there is any.

```
[keys.normal]
A-a" = { "d" = ":sh deno run {filename}", "r" = ":sh cargo run", "t" = ":sh cargo test" }
```

Edit: inserted placeholder

**Comment by the-mikedavis** [comment] 2022-10-05 12:53
Duplicate of https://github.com/helix-editor/helix/issues/3134

There are some issues and PRs for adding variables but there are not currently any variables implemented.

**Closed by the-mikedavis** 2022-10-05 12:53 UTC
