### ISSUE TITLE
autocomplete triggers in insert mode

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#1381] opened 2021-12-26 12:26 UTC
Oftentimes autocompletion triggers in the middle of a token and starts changing .methods() which is not desired as I'm just navigating the file in insert mode.

**Comment by dead10ck** [comment] 2021-12-26 12:35
Wait, are you saying you're just moving around with the arrow keys in insert mode, and it randomly decides to insert parens? Could you provide step by step instructions to reproduce this behavior?

**Comment by adsick** [comment] 2021-12-26 13:16
> are you saying you're just moving around with the arrow keys in insert mode

Yes. 
I've figured out how to reproduce it:
for example take ```helix-term/src/main.rs:44:18```
switch to append/insert mode
now move your cursor to the letter ```i``` just after the letter ```x``` as on the screenshot
![image](https://user-images.githubusercontent.com/24528839/147409200-9de74331-a494-4216-8150-2118b5c8bdf0.png)
if your minimal number of symbols to trigger autocompletion is 2 or less you will see it appearing which is extremely annoying in case you move vertically from line to line - you might accidentally change a method this way. 

Looks like autocompletion triggers in case there are completions for symbols that are LEFT to the cursor (ignoring the fact that there is stuff RIGHT to it)
I hope the problem is clear, ask if it is not

**Comment by dead10ck** [comment] 2021-12-26 13:59
Ahh, I see; this is just the auto complete being automatically triggered because you're resting the cursor in insert mode. Typically, as a modal editor, the workflow is designed around being in normal mode for navigation and switching to insert mode only to insert text. I'd encourage you to try this kind of workflow to get the most out of the modal editing paradigm.

With that said, there are a few [config options](https://docs.helix-editor.com/configuration.html) you could try. `auto-completion = false` will disable the automatic pop-up, meaning to auto complete, you must explicitly hit Ctrl-x. Setting `idle-timeout` to a bigger value might also help.

As for completing even though there is text to the left, I think this is desired for cases like if you have a chain of method calls and you want to insert another, e.g. `foo|.bar().baz() -> foo.quu|.bar().baz()` and you want it to auto complete `quux`.

**Comment by kirawi** [comment] 2022-05-26 14:03
Closing as the above comment offers a solution.

**Closed by kirawi** 2022-05-26 14:03 UTC
Labels: C-bug

**Comment by kendfss** [comment] 2023-01-16 03:12
> As for completing even though there is text to the right, I think this is desired for cases like if you have a chain of method calls and you want to insert another, e.g. `foo|.bar().baz() -> foo.quu|.bar().baz()` and you want it to auto complete `quux`.

If that's the case then each language should, assuming they don't already, have an "attribute-separators" list of strings and the sequence of characters following the cursor position must be prefixed by one of the elements, or be empty, in order to trigger auto-complete.

**Comment by brokenthorn** [comment] 2023-09-17 23:57
> meaning to auto complete, you must explicitly hit Ctrl-x

My god! I was looking for this information for 2 days, then I hit this "bug" and found the information where I least expected it! Helix needs to make this information easier to discover! 😄 

Thanks!

**Comment by kirawi** [comment] 2023-09-18 00:27
This is in the docs: https://docs.helix-editor.com/keymap.html
