### ISSUE TITLE
Strange behaviour when auto-pairing Unicode brackets

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#3964] opened 2022-09-25 13:01 UTC
### Summary

The Lean programming language uses Unicode braces `⟨⟩`, so I tried adding auto-pairing for them in my config and the cursor ended up moving in unexpected ways.

### Reproduction Steps

1. Add the following to `languages.toml`:
```toml
[[language]]
name = "lean"
[language.auto-pairs]
"⟨" = "⟩"
```
2. `hx foo.lean`
3. Type `⟨`

I expected this to happen:

`⟩` is added after the cursor, and the cursor remains where it is, between `⟨` and `⟩`

Instead, this happened:

`⟩` is added after the cursor, and the cursor moves 4 characters forward from where it should be.
For example, with `|` representing the cursor:
```
|
----
```
Type `⟨`
```
⟨⟩
--|--
```
This behaviour causes Helix to panic if it happens close enough to the end of a file.

### Helix log

Nothing of relevance

### Platform

MacOS

### Terminal Emulator

iTerm2 v3.4.16

### Helix Version

helix 22.08.1 (42e30e7a)

**Comment by dead10ck** [comment] 2022-09-25 13:10
Duplicate of #3946

**Closed by dead10ck** 2022-09-25 13:10 UTC
Labels: C-bug, R-duplicate, A-core
