### ISSUE TITLE
Syntax Highlighting breaks when parts of code is not in view.

### ISSUE THREAD

**Issue by aspizu** [helix-editor/helix#8639] opened 2023-10-27 16:05 UTC
```py
def foo(arg): # <-- If this line is not in view, then...
   ...
   ...
   ...
   arg # ... this will not get highlighted correctly.
```

**Comment by gabydd** [comment] 2023-10-27 16:30
Duplicate of https://github.com/helix-editor/helix/issues/1151

**Closed** 2023-10-27 16:30 UTC
