### ISSUE TITLE
Rename file

### ISSUE THREAD

**Issue by lieskjur** [helix-editor/helix#6825] opened 2023-04-20 00:39 UTC
One feature I am missing is a "rename current file" command which renames the file that is currently focused.

At the moment if I want to do so I
1. save the file
2. close buffer
3. call `:sh mv $file_name $new_name`
4. open file

which seems to me very tedious. But maybe I am missing some other simple approach.

**Comment by sicher** [comment] 2023-04-20 08:45
You write the file with a new name `:w new_name` and then call `:sh rm old_name`.

**Comment by kirawi** [comment] 2023-04-20 15:34
Duplicate of https://github.com/helix-editor/helix/issues/4393

**Closed by kirawi** 2023-04-20 15:34 UTC
Labels: C-enhancement

**Comment by NicTanghe** [comment] 2024-11-25 22:05
if i need to do more then 1 action to move a file or a folder there is something broken in the core design philosophy. also the p4 git thing barely works.

**Comment by kirawi** [comment] 2024-11-25 22:19
Literally just go to the linked issue. It's `:move` then use the keybind `C-r` `%`
