### ISSUE TITLE
LSP - Code action to add type Signature (Haskell)

### ISSUE THREAD

**Issue by 0rphee** [helix-editor/helix#4890] opened 2022-11-26 04:42 UTC
### Summary

Coming from vscode, I expected to be able to add type signatures without typing them myself, but there aren't any code actions in helix for this feature (or so it seems). 

Here's an example between helix (left) and vscode (right)

https://user-images.githubusercontent.com/79347623/204072326-45546008-572a-4a92-8d1b-dbf1e8914f5e.mov

### Reproduction Steps

 

1. `hx test.hs`
1. write a function, ex. `addition x y = x + y`
2. select function, <space> + <a> (search for code actions)
3. the code actions pop-up list contains an "add type signature" action

Instead, this happened:
The code pop-up list doesn't contain such an action

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
PERRAS SAQUE 10 EN EL FINAL DE QUIMICA  
```

</details>

### Platform

macOS

### Terminal Emulator

Alacritty Version 0.11.0 (1)

### Helix Version

22.08.1-437-g4791bd66

**Comment by kirawi** [comment] 2022-11-28 22:20
I believe that these are snippets, which aren't yet supported. https://github.com/helix-editor/helix/issues/395

**Comment by pascalkuthe** [comment] 2022-12-28 13:32
Clsomg as duplicate of  #395

**Closed by pascalkuthe** 2022-12-28 13:32 UTC
Labels: C-bug
