### ISSUE TITLE
Provide an option to enable `auto_format` for individual languages, keeping global disabled

### ISSUE THREAD

**Issue by kchibisov** [helix-editor/helix#7868] opened 2023-08-08 10:38 UTC
Right now the way it works is that you have a global `auto_format` to toggle whether it's enabled or not, and then you have each individual language server doing auto-format
on its own by default.

However when auto format is generally not desired and you want to opt-into it only for a small amount of languages this won't work, because global `auto-format = false` and then
having `auto-format = true` in `[[language]]` section won't do anything.

This is pretty much what the code does.

```rust
    let fmt = if editor_auto_fmt {
        doc.auto_format().map(|fmt| {
```

Given that other default is `true` it's tricky to get it right here, I guess the way it should be implemented is that the config value of each language is populated with the `Option<bool>` and then you `unwrap_or` to global default or global config is populated
during the deserialization(more complex, but you'll remove the need for option and the config global value wouldn't be used at all), that way it'll work automatically without nested bool checking complexity and will meat common expectations,
because right now what `auto-format` does in `[[language]]` is `opt-out`.

**Comment by dead10ck** [comment] 2023-08-19 16:01
This is actually desired behavior; the global setting should take precedence over per language settings. Languages themselves have auto formatting on by default, e.g. Rust, and this would change behavior such that users that don't want auto formatting in Rust would be forced to create a custom `languages.toml`, in addition to the global setting, to "really" turn it off.

One of the two contexts has to take precedence and personally I think auto formatting is a pretty opinionated feature, so if we have to choose, then it should be easier to turn it off than to turn it on.

**Comment by kchibisov** [comment] 2023-08-19 19:46
@dead10ck that's the exact thing I want, I want to turn it off, but keep only for 1 languages, instead of turning of for **every** language except the one I want auto-formatting on.

If that's desired behavior, it makes it harder to use it autoformatting at all, because I don't want to have it enabled for 5 out of 6 languages I interact with, and only have it for one, which is broken, so in the end I'd have 5 settings in lanugages toml and global default to `true`.

**Comment by pascalkuthe** [comment] 2023-08-19 20:03
Auto formatting is already opt in. It's just that helix ships with an extensive default config in which autoformatting was manually enabled for some languages.

The issue you are facing is that you do not like the defaults (instead of being opposed to autoformatting in principal which is what thr global setting is for). That is unfortunate but at the end of the day I don't see a good solutio as long as we have a toml config. I dont think we should start i troducing conmplex fallabacks between different config files (that would also be a nightmare to implement and maintian). The configs are currently sinply merged (with the user config taking precendence). Once we have a scheme based cobfig you could write a super simple script that sets all of these to false (for all that don't match names xy). 

Ultimately disabling autoformatting for a couple languages where you disagree with the default choice is nor a big deal.

**Comment by dead10ck** [comment] 2023-08-19 20:29
I agree, I'm sorry you don't like the defaults for your languages, but at least as much (if not far more) inconvenience would be caused by making the language config take precedence over the global config.

**Closed by dead10ck** 2023-08-19 20:29 UTC
Labels: C-enhancement

**Comment by kchibisov** [comment] 2023-08-20 21:47
Well, then auto formatting is completely useless and I just keep my local helix patched.
