### ISSUE TITLE
Change the title of the window on startup

### ISSUE THREAD

**Issue by sandalbanditten** [helix-editor/helix#6132] opened 2023-02-28 10:59 UTC
Many other terminal editors, like Neovim use CSI escape sequences 22 and 23 to change the title of the window on startup and shutdown.

It would be nice if Helix did too!

**Comment by the-mikedavis** [comment] 2023-02-28 14:27
Duplicate of https://github.com/helix-editor/helix/issues/2436

**Closed by the-mikedavis** 2023-02-28 14:27 UTC
Labels: C-enhancement
