### ISSUE TITLE
Append (insert after) doesn't respect `editor.cursor-share.insert`

### ISSUE THREAD

**Issue by casonadams** [helix-editor/helix#6025] opened 2023-02-17 06:35 UTC
### Summary

```
[editor.cursor-shape]
insert = "bar"
normal = "block"
```

Pressing `a` to enter insert mode after the char fails to convert cursor block to bar.

### Reproduction Steps

 

I tried this:

Using the following config
```
[editor.cursor-shape]
insert = "bar"
normal = "block"
```

1. press `a` to insert

I expected this to happen:

only the bar to appear

Instead, this happened:

both the bar and the block appear

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty 0.10.1

### Helix Version

helix 22.12

**Comment by sicher** [comment] 2023-02-17 10:23
Note that you will keep the selection with 'a'. If you have the same color on selection and cursor, they will blend together visually. I got the same setting as you and here's what it looks like with my theme:

![image](https://user-images.githubusercontent.com/65613/219617939-90f0429f-400d-4e68-bb56-47f34b5701bb.png)

**Comment by archseer** [comment] 2023-02-17 11:42
I can replicate the issue. Try selecting a longer word (not a single character) then press a.

**Comment by archseer** [comment] 2023-02-17 12:06
Ah sorry, this was a mistake on my end. I placed a selection like `["foo]"` so when pressing `a` the cursor is temporarily moved and the opening `"` is highlighted

**Comment by dead10ck** [comment] 2023-03-13 00:39
So is this actually a bug?

**Comment by pascalkuthe** [comment] 2023-03-13 00:50
nope I tested this and discussed with @archseer when this was first reported, this is not a bug and working as intended. Appendmode moves the cursor one to the right which can select a bracket and make it looks as tough there is a block cursor there when it's really just the bracket highlight. So this only occurs with some themes and I wouldn't even call the color choice a bug here so I am closing this issue

**Closed by pascalkuthe** 2023-03-13 00:50 UTC
Labels: C-bug
