### ISSUE TITLE
Add command to close buffer from buffer picker

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3781] opened 2022-09-10 11:03 UTC
It would be nice to be able to, when hovering over a buffer in the buffer picker have a command to close that buffer. That way it is easier to cleanup irrelevant buffers and focus on what you are working on.

**Comment by the-mikedavis** [comment] 2022-09-10 13:34
Duplicate of https://github.com/helix-editor/helix/issues/1593

**Closed by the-mikedavis** 2022-09-10 13:34 UTC
Labels: C-enhancement
