### ISSUE TITLE
Documentation Pop Up is not scrollable in insert mode

### ISSUE THREAD

**Issue by that-ambuj** [helix-editor/helix#8353] opened 2023-09-22 07:57 UTC
### Summary

The Documentation pop-up that appears when using autocomplete does not scroll using either mouse or `Ctrl-d`, The text inside the docs pop-up remains fixed when in insert mode. It is scrollable when I go out to normal mode and press `spacek` on the function/method I need docs for. It is very annoying when I need to change modes just to read a paragraph of documentation.

![image](https://github.com/helix-editor/helix/assets/97109381/a446db9e-864b-41e6-b15b-2be941ab4fbc)
_docs pop-up in insert mode, no scrollbar and fixed text_

![image](https://github.com/helix-editor/helix/assets/97109381/314dcd69-ee62-49f4-a0bd-3d70ff446990)
_pop-up is now scrollable in normal mode with `spacek`_

### Reproduction Steps

I tried this:

1. `hx`
2. Go into insert mode and type out a method name and filling it from autocomplete.
3. Try to scroll using `Ctrl-d` but does not work.
4. Try to scroll inside the small docs pop up using mouse, it rather scrolls my cursor downwards in the buffer.

I expected this to happen:

I expected the text inside the doc pop up to scroll up.

Instead, this happened:

It did not scroll but rather my cursor in the file buffer did scroll when using mouse.

### Platform

Linux

### Terminal Emulator

Kitty v0.29.2

### Helix Version

helix 23.05

**Comment by user5815** [comment] 2023-09-22 10:11
I believe this is a duplicate of https://github.com/helix-editor/helix/issues/3062, although with more details

**Comment by that-ambuj** [comment] 2023-09-22 10:13
I'm sorry, I tried searching with 'pop up' and 'documentation' but I didn't find that issue.

**Closed** 2023-09-22 10:14 UTC
Labels: C-bug
