### ISSUE TITLE
Panic "Trying to access position outside the buffer" in debug build

### ISSUE THREAD

**Issue by pathwave** [helix-editor/helix#4620] opened 2022-11-06 16:44 UTC
### Summary

This panic is only enabled in debug build, so Im unsure if its supposed to be a issue?

Line 234 in helix-tui/src/buffer.rs
```rust
    pub fn index_of(&self, x: u16, y: u16) -> usize {
        debug_assert!(
            self.in_bounds(x, y),
            "Trying to access position outside the buffer: x={}, y={}, area={:?}",
            x,
            y,
            self.area
        );
        ((y - self.area.y) as usize) * (self.area.width as usize) + ((x - self.area.x) as usize)
    }
```

thread 'main' panicked at 'Trying to access position outside the buffer: x=37, y=31, area=Rect { x: 0, y: 0, width: 35, height: 61 }', helix-tui/src/buffer.rs:235:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: helix_tui::buffer::Buffer::index_of
             at ./helix-tui/src/buffer.rs:235:9
   3: <helix_tui::buffer::Buffer as core::ops::index::IndexMut<(u16,u16)>>::index_mut
             at ./helix-tui/src/buffer.rs:616:17
   4: helix_term::ui::editor::EditorView::render_focused_view_elements
             at ./helix-term/src/ui/editor.rs:650:21
   5: helix_term::ui::editor::EditorView::render_view
             at ./helix-term/src/ui/editor.rs:164:13
   6: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::render
             at ./helix-term/src/ui/editor.rs:1477:13
   7: helix_term::compositor::Compositor::render
             at ./helix-term/src/compositor.rs:218:13
   8: helix_term::application::Application::render
             at ./helix-term/src/application.rs:265:9
   9: helix_term::application::Application::handle_terminal_events
             at ./helix-term/src/application.rs:552:13
  10: helix_term::application::Application::event_loop_until_idle::{{closure}}
             at ./helix-term/src/application.rs:297:21

### Reproduction Steps

1. Open helix (debug build) and make the width of the window pretty small (I used about ~30 character width)
2. Open a code file (I used helix-dap/src/client.rs)
3. Hold down w (move_next_word_start)
4. Panics after a while.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-11-06T17:18:19.731 helix_lsp::transport [ERROR] err <- "[ERROR project_model::workspace] cyclic deps: helix_view(CrateId(65)) -> helix_tui(CrateId(59)), alternative path: helix_tui(CrateId(59)) -> helix_view(CrateId(65))\n"
2022-11-06T17:18:20.841 helix_lsp::transport [ERROR] err <- "[ERROR project_model::workspace] cyclic deps: helix_view(CrateId(65)) -> helix_tui(CrateId(59)), alternative path: helix_tui(CrateId(59)) -> helix_view(CrateId(65))\n"

```

</details>

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

22.08.1-392-g48a3965a

**Comment by ryanfrishkorn** [comment] 2023-01-25 05:51
I can confirm the same behavior @pathwave has observed using a debug build and `buffer.rs` source file. This is as of the most recent master commit of 91dca3f667e146f93e6dca205b0a3f2a7a64b488 and the most recent tagged release of 22.12. 

I originally noticed the same panic while editing an HTML document with particularly long lines (in excess of 15k characters) using a terminal width of 213 columns. In my case, it was triggered not by moving from word to word (though I can trigger it that way also), but by opening the file and immediately using a regex search to jump to a portion of the particularly long line, then moving back just before the jump location by using the `h` key still in visual mode.

I thought the search jump scenario was peculiar enough to mention as it may give clues as to why this happens in the first place. It is interesting that the panic happens after moving exactly one character to the left of the search jump point and that the terminal width I'm using is much larger. I'll be watching this issue and am happy to offer any additionally helpful information.

**Comment by pascalkuthe** [comment] 2024-04-08 02:12
I am closing this because we fixed  quige a fer  bugs that could have caused this and basically entirely revamped text rendering (where this seemed to originate) since this issue was created. I can not rproduce this on master anymore (followed instru6ctions very closely and tried a lot). Pretty sure this has been fixed just not sure by what pr exactly

**Closed by pascalkuthe** 2024-04-08 02:12 UTC
Labels: C-bug, A-helix-term
