### ISSUE TITLE
Annotate Key Remapping

### ISSUE THREAD

**Issue by GreasySlug** [helix-editor/helix#3130] opened 2022-07-21 07:50 UTC
#### Describe your feature request

Suppose you have created a new keymap in your user settings.
e.g.
```toml
[keys.insert]
j = { j = "normal_mode", s = ":write" , C-s = [":write", ":format"] }
```

then, the infobox displays like this

+--------------------------+
| j      Enter normal mode    |
| C-s [Multiple commands]  |
| s     :write[]                        |
+--------------------------+

I want the it to be displayed like this

+-------------------------+
| j     Enter normal mode    |
| C-s write and format       |
| s     write                         |
+-------------------------+

If you don't annotate anything, it will display as before.
If annotated, override the infobox.

https://github.com/helix-editor/helix/blob/76756f0e5de2cb5e753fb49933ba47f2386c4701/helix-term/src/keymap.rs#L80-L119

https://github.com/helix-editor/helix/blob/76756f0e5de2cb5e753fb49933ba47f2386c4701/helix-term/src/commands.rs#L195

**Comment by kirawi** [comment] 2022-11-10 03:24
This seems to actually be a duplicate of #1487

**Closed** 2022-11-10 03:39 UTC
Labels: C-enhancement, A-helix-term
