### ISSUE TITLE
Document diagnostics are not reported in the buffer (but visible in the workspace picker)

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#9429] opened 2024-01-26 00:41 UTC
### Summary

It seems like one of the recent commits cause us to not be able to report the diagnostics associated with a file in the buffer on Windows.

### Reproduction Steps

I tried this:

1. `hx` in helix
2. Wait for LSP to finish initializing
3. Open `document.rs`
4. Go to line 956 where there is a cfg disabled diagnostic.

I expected this to happen:

Diagnostic is shown in the diagnostic and upper right corner as usual.

Instead, this happened:

`]d` and `[d` do not work. Going to line 956 where the error is shows nothing in the gutter nor does the error appear.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

[log.txt](https://github.com/helix-editor/helix/files/14058967/log.txt)

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal 1.18.3181.0

### Installation Method

Source

### Helix Version

2661e05b

**Comment by the-mikedavis** [comment] 2024-01-26 01:43
https://github.com/helix-editor/helix/pull/8873 was relatively recent and overhauled the way `Document`'s `diagnostics` field is handled, which powers the gutter and diagnostics rendering. It's odd that this only affects Windows though.

**Comment by pascalkuthe** [comment] 2024-01-26 13:12
Could also be #7658 maybe?

**Comment by pascalkuthe** [comment] 2024-01-26 14:33
@kirawi are you *sure* that it was one of the recetn commits. If you look trough the looks you will see that the casing of the drieletter is causing the problem. Its uppercase internally4 but RA sends a lowercase drive letter. That is exactly what https://github.com/helix-editor/helix/issues/3267 is about and #7367 would fix

**Comment by pascalkuthe** [comment] 2024-01-26 14:33
that issue has been around forever

**Comment by kirawi** [comment] 2024-01-26 16:27
Yeah that's what I thought too, but the latest commit was working on Helix a couple of weeks ago. It was reported on Matrix that 23.10 works: https://matrix.to/#/!zMuVRxoqjyxyjSEBXc:matrix.org/$BFNFaPLZCR6_4pL3RY9TDOpPrYyJ0yJeI7tJk_EfSO0?via=matrix.org&via=mozilla.org&via=envs.net

I should have checked 23.10 on Windows myself do that when I'm back on.

**Comment by kirawi** [comment] 2024-01-26 22:51
I checked and it's indeed https://github.com/helix-editor/helix/pull/8873

**Comment by pascalkuthe** [comment] 2024-01-26 22:56
Ah I see now that PR causes https://github.com/helix-editor/helix/issues/3267 to trigger more reliably. It's not a bug in that PR it just exacerbates an existing issue with an existing fix.

Closing as duplicate of https://github.com/helix-editor/helix/issues/3267

**Closed by pascalkuthe** 2024-01-26 22:56 UTC
Labels: C-bug, O-windows
