### ISSUE TITLE
Changing modes through a keybind that executes multiple commands crashes Helix

### ISSUE THREAD

**Issue by lucypero** [helix-editor/helix#2587] opened 2022-05-27 23:54 UTC
### Summary

this mapping crashes Helix:

```toml
[keys.normal]
C = ["extend_to_line_end", "change_selection"]
```

I believe the crash happens when you transition editing modes through a keymap that executes multiple commands.

Output:
```
thread 'main' panicked at 'not implemented', helix-term\src\ui\editor.rs:1292:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It crashes here in `helix-term/src/ui/editor.rs`:

```rs
self.last_insert.0 = match self.keymaps.get(mode, key) {
                            KeymapResult::Matched(command) => command,
                            // FIXME: insert mode can only be entered through single KeyCodes
                            _ => unimplemented!(),
                        };
```

Adding this line prevents the crash:

```rs
                        self.last_insert.0 = match self.keymaps.get(mode, key) {
                            KeymapResult::Matched(command) => command,
                            KeymapResult::MatchedSequence(commands) => {
                                commands.last().unwrap().clone()
                            }
                            // FIXME: insert mode can only be entered through single KeyCodes
                            _ => unimplemented!(),
                        };

```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Helix Version

22.03-258-gefae7616

**Comment by the-mikedavis** [comment] 2022-05-28 00:00
Duplicate of https://github.com/helix-editor/helix/issues/2051

**Closed by the-mikedavis** 2022-05-28 00:00 UTC
Labels: C-bug
