### ISSUE TITLE
Enhancement: Custom Snippet Support

### ISSUE THREAD

**Issue by mr-zlaam** [helix-editor/helix#11475] opened 2024-08-12 22:34 UTC
I would like to request the addition of a custom snippet feature in Helix, allowing users to create, manage, and utilize code snippets across various programming languages. This feature would greatly enhance the productivity and coding experience, especially for those transitioning from editors like VS Code that have robust snippet systems.

Custom snippets are an essential part of many developers' workflows, enabling them to quickly insert commonly used code patterns, templates, and boilerplate code. The ability to define custom snippets directly within Helix would streamline coding tasks, reduce repetitive typing, and enhance the overall efficiency of the editor.
**Enhancement**
Adding custom snippet support to Helix would be a significant enhancement, bringing it closer to the capabilities of more established editors while maintaining the lightweight and efficient nature of Helix. I believe this feature would be highly appreciated by the community and would help attract more users to the editor.

Thank you for considering this request!

**Comment by kirawi** [comment] 2024-08-12 22:41
Duplicate of https://github.com/helix-editor/helix/issues/395

**Closed by kirawi** 2024-08-12 22:41 UTC
Labels: C-enhancement
