### ISSUE TITLE
Svelte's expansion in <script> tag doesn't work properly

### ISSUE THREAD

**Issue by DoctorRyner** [helix-editor/helix#9889] opened 2024-03-15 18:12 UTC
When using selection expand / shrink inside <script> tag to select JS construction, it just selects the entire tag

**Comment by the-mikedavis** [comment] 2024-03-15 18:32
Duplicate of https://github.com/helix-editor/helix/issues/4618

**Closed by the-mikedavis** 2024-03-15 18:32 UTC
Labels: C-enhancement

**Comment by DoctorRyner** [comment] 2024-03-16 21:40
@the-mikedavis oh, 2 years without an updates on these, I'm crying T-T

**Comment by the-mikedavis** [comment] 2024-03-17 00:24
You can test drive https://github.com/helix-editor/helix/pull/5176 which should fix this for `expand_selection` / `shrink_selection`

**Comment by DoctorRyner** [comment] 2024-03-17 01:03
@the-mikedavis oh, thanks, I merged it to my fork
