### ISSUE TITLE
Tokyonight theme is not correctly rendered

### ISSUE THREAD

**Issue by prx0** [helix-editor/helix#6523] opened 2023-03-31 23:51 UTC
### Summary

Hi!

I've installed helix from the source using these commands
```sh
git clone https://github.com/helix-editor/helix
cd helix
cargo install --path helix-term --locked
ln -s $PWD/runtime ~/.config/helix/runtime
```

source: https://docs.helix-editor.com/install.html#building-from-source

Unfortunately some themes like Tokyonight are quite ugly. Does this occur because of a wrong settings ?

Here's my ~/.config/helix/config.toml
```toml
theme = "tokyonight"

[editor]
mouse = true
line-number = "absolute"
cursorline = true
auto-completion = true
auto-format = true
auto-info = true
color-modes = true
auto-pairs = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
middle-click-paste = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type", "version-control"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)
```

I'm deeply sorry if someone have already posted an issue about or if I just make a mistake during the installation process or inside the configuration file.

How can I fix it ? 

Thank you for reading.

### Reproduction Steps

 

I tried to open a rust file:

1. `hx main.rs`
2. `:theme tokyonight`

I expected this to happen:
I expect to see the tokyonight theme correctly applied

Instead, this happened:

![Screenshot_20230401_012614](https://user-images.githubusercontent.com/74690920/229250275-b789bdd2-27c9-47c5-872a-7621ea472169.png)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
2023-04-01T01:04:53.773 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:04:53.773 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:04:54.374 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:04:54.374 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:05:18.254 helix_view::theme [WARN] Theme: malformed hexcode: highlight
2023-04-01T01:05:27.662 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:05:27.662 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:05:57.616 helix_view::theme [WARN] Theme: malformed hexcode: light-black
2023-04-01T01:05:57.616 helix_view::theme [WARN] Theme: malformed hexcode: light-black
2023-04-01T01:05:57.616 helix_view::theme [WARN] Theme: malformed hexcode: purple
2023-04-01T01:06:30.158 helix_view::theme [WARN] Theme: malformed hexcode: indent
2023-04-01T01:07:12.362 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:07:12.363 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:07:12.770 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:07:12.770 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:07:36.214 helix_view::theme [WARN] Theme: malformed hexcode: highlight
2023-04-01T01:07:40.184 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:07:40.184 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:08:43.458 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:08:43.458 helix_view::theme [WARN] Theme: invalid modifier: "normal"
2023-04-01T01:11:59.092 helix_view::theme [WARN] Theme: malformed hexcode: light-black
2023-04-01T01:11:59.092 helix_view::theme [WARN] Theme: malformed hexcode: light-black
2023-04-01T01:11:59.092 helix_view::theme [WARN] Theme: malformed hexcode: purple
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty 0.11.0

### Helix Version

helix 23.03 (3cf03723)

**Comment by kirawi** [comment] 2023-04-01 01:28
Duplicate of https://github.com/helix-editor/helix/issues/3099

**Closed by kirawi** 2023-04-01 01:28 UTC
Labels: C-bug
