### ISSUE TITLE
WSL. Helix takes forever to start, if x-server is not running

### ISSUE THREAD

**Issue by Doltramir** [helix-editor/helix#6630] opened 2023-04-06 18:03 UTC
When using wsl, if you
```fish
export HOST_IP="$(ip route |awk '/^default/{print $3}')"
export DISPLAY="$HOST_IP:0"
```
but did not start x-server (VcXsrv in my case) - helix takes about a minute to start.

**Comment by the-mikedavis** [comment] 2023-04-06 19:49
If I remember correctly, where we've seen this before it was an issue with the clipboard provider. What is the output of `hx --health | head`?

**Comment by Doltramir** [comment] 2023-04-08 20:59
> What is the output of `hx --health | head`?

`Config file: /home/doltramir/.config/helix/config.toml
Language file: default
Log file: /home/doltramir/.cache/helix/helix.log
Runtime directories: /home/doltramir/.config/helix/runtime;/var/lib/helix/runtime;/usr/lib/helix/runtime
Runtime directory /home/doltramir/.config/helix/runtime is symlinked to: /mnt/d/dev/helix-editor/runtime
Runtime directory does not exist: /home/doltramir/.config/helix/runtime
Runtime directory does not exist: /usr/lib/helix/runtime
Clipboard provider: win32yank.exe
System clipboard provider: win32yank.exe`

**Comment by the-mikedavis** [comment] 2023-04-09 19:18
Ah ok, this is a duplicate of https://github.com/helix-editor/helix/issues/3655

There's a PR that should fix it by timing out when checking the clipboard provider (https://github.com/helix-editor/helix/pull/3696)

**Closed by the-mikedavis** 2023-04-09 19:18 UTC
