### ISSUE TITLE
Add word completion to search commands

### ISSUE THREAD

**Issue by taupiqueur** [helix-editor/helix#3856] opened 2022-09-16 10:09 UTC

**Comment by the-mikedavis** [comment] 2022-09-16 10:36
This would need https://github.com/helix-editor/helix/issues/1015

**Comment by the-mikedavis** [comment] 2022-12-22 22:22
Duplicate of https://github.com/helix-editor/helix/issues/2533 actually. I forgot about that issue initially

**Closed by the-mikedavis** 2022-12-22 22:22 UTC
Labels: C-enhancement, A-helix-term
