### ISSUE TITLE
no pair of ```"``` is created when typing ```"``` after the ```f``` of f-strings in python

### ISSUE THREAD

**Issue by jerabaul29** [helix-editor/helix#9441] opened 2024-01-26 20:14 UTC
### Summary

There are auto closing brackets, parenthesis, quote marks etc inserted when I edit in python. This works mostly well, except when using f-strings. See below: once I have typed ```print(f|)```, typing the ```"``` results in ```print(f"|)``` and not ```print(f"|")``` as I would expect, where ```|``` is the cursor location.

But when trying to close the ```"``` at the end, then a double quote is inserted, while I only need a single one.

### Reproduction Steps

[Screencast from 01-26-2024 09:03:33 PM.webm](https://github.com/helix-editor/helix/assets/8382834/943021c8-fde1-4e96-9ca1-bc1dc9fdb563)

### Helix log

I cannot see any relevant entries in the log file.

### Platform

Linux

### Terminal Emulator

gnome-terminal-server

### Installation Method

AppImage

### Helix Version

helix 23.10 (f6021dd0)

**Comment by the-mikedavis** [comment] 2024-01-26 20:18
Duplicate of https://github.com/helix-editor/helix/issues/4035

Also see https://github.com/helix-editor/helix/issues/4100

**Closed by the-mikedavis** 2024-01-26 20:18 UTC
Labels: C-bug
