### ISSUE TITLE
command palette is split in two panes, the right one empty

### ISSUE THREAD

**Issue by skytwosea** [helix-editor/helix#9392] opened 2024-01-20 22:11 UTC
When accessing the command palette with <space + ?> it opens with two drawn panes. Only the left is populated and searchable; the right pane is empty. This truncates the command descriptions in the left pane, and since there is no way to scroll along the description line (at least, none that I have found yet), this severely reduces the utility of the command palette.

Is there a way to configure the command palette to be drawn in only one single pane, as wide as my terminal window? Why does that right-side pane appear?

![image](https://github.com/helix-editor/helix/assets/34104395/add6f759-b55a-4af1-ba42-9bf887aa257d)

**Comment by the-mikedavis** [comment] 2024-01-20 22:17
Duplicate of https://github.com/helix-editor/helix/issues/8665

This has been fixed on master.

**Closed by the-mikedavis** 2024-01-20 22:17 UTC

**Comment by skytwosea** [comment] 2024-01-20 22:33
Oh ok, understood, and thanks. I searched for previous issues but clearly didn't search far enough.
