### ISSUE TITLE
Bad language config: invalid type: map, expected a string for key `language.file-types` 

### ISSUE THREAD

**Issue by kalidzo** [helix-editor/helix#4814] opened 2022-11-19 09:05 UTC
### Summary

I found a bug in the 1079th line.

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Arch linux

### Terminal Emulator

fish

### Helix Version

22.08.1

**Comment by archseer** [comment] 2022-11-19 09:33
You're using an older version of the editor, `languages.toml` on `master`works fine with the code on `master`.

**Comment by the-mikedavis** [comment] 2022-11-19 17:27
Duplicate of https://github.com/helix-editor/helix/issues/4516

**Closed by the-mikedavis** 2022-11-19 17:27 UTC
Labels: C-bug

**Comment by kalidzo** [comment] 2022-11-20 06:21
oh, sorry)
