### ISSUE TITLE
File search (space + f) should probably be made incremental / non-recursive (or with limited depth)

### ISSUE THREAD

**Issue by Andersama** [helix-editor/helix#6519] opened 2023-03-31 21:17 UTC
Fairly straightforward issue, I have several folders which have far too many files in it. When opening the file search prompt the file count is capped at its maximum `100000/100000`. Using the prompt in said folders it takes several seconds and prevents any other interaction, this gives the impression that helix has crashed when in fact it's just taking quite a while to list files.

If possible write the file search dialog / filter such that as files are found they are populated you can still interact with the gui, may require threading, alternatively limit the depth which file search travels while allowing folder traversal to find files. Currently up and down arrows are used to select from the list, consider using left and right to traverse folders. EG: left to expand the search to the parent folder, right to limit the search to a child folder (perhaps of the file selected).

**Comment by kirawi** [comment] 2023-04-01 02:41
Duplicate of https://github.com/helix-editor/helix/issues/1987

**Closed by kirawi** 2023-04-01 02:41 UTC
Labels: C-enhancement
