### ISSUE TITLE
Colorizer like plugin as a built-in

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#4016] opened 2022-09-28 18:47 UTC
There's a plugin https://github.com/norcalli/nvim-colorizer.lua for neovim that previews the colors.

This is quite useful in CSS files as well as TOML files for Helix's themes. 

This way users can easily create and edit themes in helix itself.

It can be restricted to certain files or toggled with a command.

**Comment by the-mikedavis** [comment] 2022-09-28 19:21
Duplicate of https://github.com/helix-editor/helix/issues/1115

Also, https://github.com/helix-editor/helix/issues/2823

**Closed by the-mikedavis** 2022-09-28 19:21 UTC
Labels: C-enhancement
