### ISSUE TITLE
Linter Information Covers Line with Cursor

### ISSUE THREAD

**Issue by ngraham20** [helix-editor/helix#4279] opened 2022-10-14 21:44 UTC
When editing a file with the LSP debugger active, the error information can cover the currently edited line, making it impossible to continue working without moving the window up and editing on the lower half of the window. Hitting escape, which closes other windows like auto-complete or code suggestions, does no hide the linter message.

The cursor is hidden behind the error, and I can't see what I'm doing.
![image](https://user-images.githubusercontent.com/22180760/195948436-d15dcf63-5b65-4375-9284-f5436f2da7ce.png)

**Comment by the-mikedavis** [comment] 2022-10-14 22:27
Duplicate of https://github.com/helix-editor/helix/issues/1462

**Closed by the-mikedavis** 2022-10-14 22:27 UTC
