### ISSUE TITLE
Crash when opening Jumplist

### ISSUE THREAD

**Issue by rnxpyke** [helix-editor/helix#4805] opened 2022-11-18 12:40 UTC
### Summary

The jumplist saves positions into the buffer.
When editing the buffer, these might point to an out of bounds location.
Opening the jumplist in this state crashes the editor.

### Reproduction Steps

 

I tried this:

1. `hx`
2. Enter two lines in the scratch buffer
3. Save location in second line in jumplist
4. Delete first line
5. Open jumplist

Minimal Setup:
`ia<ret>b<esc><C-s>ggxd`

Minimal Crashing example:
`ia<ret>b<esc><C-s>ggxd<space>j`

I expected this to happen:
The jumplist should open without crashing the editor.
Mabe remove invalid jump targets.
Ideally, update each jump target with each edit so that they point to the same line/character.

Instead, this happened:
```
thread 'main' panicked at 'Attempt to slice past the end of RopeSlice: ...', in ropey-1.5.0/src/slice.rs:645:9 
```

### Helix log

No log output.

### Platform

Linux

### Terminal Emulator

GNOME Terminal

### Helix Version

helix 22.08.1

**Comment by the-mikedavis** [comment] 2022-11-18 14:10
Duplicate of https://github.com/helix-editor/helix/issues/2489 / https://github.com/helix-editor/helix/issues/3763. This has been fixed on master.

**Closed by the-mikedavis** 2022-11-18 14:10 UTC
Labels: C-bug
