### ISSUE TITLE
gf path detection misses some edge cases

### ISSUE THREAD

**Issue by sigmaSd** [helix-editor/helix#8069] opened 2023-08-26 19:25 UTC
### Summary

If I have a string like `"hello";` and hit `gf` it goes to `hello";` instead of `hello`

If I remove the `;` it gets the correct path

vim/nvim handle this correctly 

### Reproduction Steps

- hx
- write `"hello";` 
- hit gf inside hello

expected: buffer changed to `hello`
actual: buffer chnaged to `hello";`

### Platform

linux

### Terminal Emulator

wezterm

### Helix Version

helix 23.05 (c9694f68)

**Comment by doy** [comment] 2023-08-27 15:42
looks like a duplicate of #5533?

**Closed** 2023-08-27 17:07 UTC
Labels: C-bug
