### ISSUE TITLE
Could we have a "follow system theme" option?

### ISSUE THREAD

**Issue by xcpky** [helix-editor/helix#11417] opened 2024-08-04 11:16 UTC
In some GUI code editors, there are options that follow system theme (light or dark). My thought is to let user choose each theme for light and dark mode, and switch them based on system setting.

**Comment by the-mikedavis** [comment] 2024-08-04 13:25
Duplicate of https://github.com/helix-editor/helix/discussions/10281

**Closed by the-mikedavis** 2024-08-04 13:25 UTC
Labels: C-enhancement
