### ISSUE TITLE
C-a & C-x apparently incorrectly interprets "negative" numbers

### ISSUE THREAD

**Issue by jficz** [helix-editor/helix#2517] opened 2022-05-20 11:28 UTC
### Summary

on text that looks like this
```
test-09
```
`C-a` and `C-x` behave in the opposite way

On `C-x` the number is increased.

On `C-a` the number is decreased and when it reaches zero, text is borked to
```
test00
```

and neither C-a nor C-x work anymore

It appears that Helix interprets the number as negative `-09` and when the `-` is gone, the `00` part of text `test00` is no longer recognised as an integer.

### Reproduction Steps

 

I tried this:

`i`, `test-09`, `esc`, `C-a`
`i`, `test-09`, `esc`, `C-x`

I expected this to happen:
on `C-a` increase the number to `test-10`, `test-11`, etc.
on `C-x` decrease the number to `test-08`, `test-07`, etc.

Instead, this happened:
on `C-a` the number is decreased until `test-01`, then the text is reduced to `test00` and the number isn't recognised by either `C-a` or `C-x`
on `C-x` the number is increased indefinitely

### Helix log

n/a 

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by kirawi** [comment] 2022-11-10 03:48
Duplicate of #2019

**Closed by kirawi** 2022-11-10 03:48 UTC
Labels: C-bug, A-helix-term
