### ISSUE TITLE
Show complete list of diagnostics in project

### ISSUE THREAD

**Issue by weakphish** [helix-editor/helix#2777] opened 2022-06-15 06:57 UTC
#### Describe your feature request

I think it would be helpful to have a command display a popup list of all diagnostics, similar to the file picker or symbol picker. Would make navigating problems in a project much more fluid.

**Comment by n0s4** [comment] 2022-06-15 07:34
Duplicate of #1891?

**Closed** 2022-06-15 08:24 UTC
Labels: C-enhancement
