### ISSUE TITLE
changing the language of a "scratch" buffer panics

### ISSUE THREAD

**Issue by smason** [helix-editor/helix#1995] opened 2022-04-06 17:32 UTC
### Summary

changing the language of a "scratch" buffer causes helix to panic

### Reproduction Steps

```
hx
:lang python
```

every language I've tried this with does the same, as does creating a new scratch buffer via the "Create a new scratch buffer" command.

### Helix log

<details><summary>backtrace</summary>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-view/src/editor.rs:479:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: helix_view::editor::Editor::launch_language_server
   4: helix_term::commands::typed::language
   5: helix_term::commands::typed::command_mode::{{closure}}
   6: <helix_term::ui::prompt::Prompt as helix_term::compositor::Component>::handle_event
   7: helix_term::compositor::Compositor::handle_event
   8: helix_term::application::Application::handle_terminal_events
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: tokio::park::thread::CachedParkThread::block_on
  11: tokio::runtime::thread_pool::ThreadPool::block_on
  12: tokio::runtime::Runtime::block_on
  13: hx::main
```

</details>

### Platform

linux

### Terminal Emulator

foot

### Helix Version

22.05-dev (b03421a8)

**Comment by sudormrfbin** [comment] 2022-04-06 17:33
Duplicate of #1994.

**Closed by sudormrfbin** 2022-04-06 17:33 UTC
Labels: C-bug
