### ISSUE TITLE
Comment Support in Vue / HTML files

### ISSUE THREAD

**Issue by julian-weimer** [helix-editor/helix#10525] opened 2024-04-20 09:34 UTC
When dealing with multiple languages in HTML or Vue files Helix currently uses HTML-style comments for everything:

```
<html>
<script>
  <!-- const a = "1"; -->
</script>

<style>
  body {
    <!-- color: red; -->
  }
</style>

<body>
<!-- <p>Hello World</p> -->
</body>
</html>
```

Using helix 24.3 (2cadec0b)

Is there something i need to configure?

**Comment by the-mikedavis** [comment] 2024-04-20 12:21
Duplicate of https://github.com/helix-editor/helix/issues/7364

**Closed by the-mikedavis** 2024-04-20 12:21 UTC
Labels: C-enhancement
