### ISSUE TITLE
Combine status line with command line

### ISSUE THREAD

**Issue by yerlaser** [helix-editor/helix#11045] opened 2024-06-27 07:32 UTC
I would like to create a pull request for this, but knowing that maintainers are mostly against such UI changes I wanted to first collect feedback if it's agreeable.

The separate blank command and status lines at the bottom of the editor seem to be unnecessary to me.
Especially, because when entering the command line with `:` it gives suggestions that anyway overwrite the status line.

Therefore, I suggest that the blank command line be removed and instead when pressing `:` the status line should turn into a command line.

I rarely use splits, but I tried using them and still don't see the bottom status line useful.

**Comment by archseer** [comment] 2024-06-27 08:59
Duplicate of #1662

**Closed** 2024-06-27 08:59 UTC
Labels: C-enhancement
