### ISSUE TITLE
Crash: shell_pipe + undo

### ISSUE THREAD

**Issue by helmesjo** [helix-editor/helix#2237] opened 2022-04-23 11:51 UTC
### Summary

First of all, _great_ work. (:

While playing around, I managed to trigger a crash, and found a quite simple reproducible case so figured I'd share it.

```
hread 'main' panicked at 'Position 4 is out of range for changeset len 3!', helix-core/src/transaction.rs:397:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Steps

 

I tried this:

1. Create an empty folder & cd to it.
2. `helix test.hxx`
3. Edit first and only line to the following  and save + quit:
    `./`
4. `helix test.hxx`
5. Add a new empty line (2) so that the file is modified.
6. Select the first line (`x`) & shell_pipe (`|`).
7. Write `ls` and hit enter (line should be replaced by `test.hxx`).
8. Hit undo (`u`) and it should crash.

**So from step 4 and forward:**
`A` + `enter` + `escape` + `gg` + `x` + `|` + `ls` + `enter` + `u`

I expected this to happen:
No crash.
Instead, this happened:
Crash:
```
hread 'main' panicked at 'Position 4 is out of range for changeset len 3!', helix-core/src/transaction.rs:397:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-04-23T13:44:04.653 helix_lsp::transport [ERROR] err <- "I[13:44:04.653] clangd ver
sion 13.0.1\n"
2022-04-23T13:44:04.653 helix_lsp::transport [ERROR] err <- "I[13:44:04.653] Features:
linux\n"
2022-04-23T13:44:04.653 helix_lsp::transport [ERROR] err <- "I[13:44:04.653] PID: 2074\
n"
2022-04-23T13:44:04.653 helix_lsp::transport [ERROR] err <- "I[13:44:04.653] Working di
rectory: /home/fred/git/helix-crash\n"
2022-04-23T13:44:04.653 helix_lsp::transport [ERROR] err <- "I[13:44:04.653] argv[0]: /
usr/bin/clangd\n"
2022-04-23T13:44:04.653 helix_lsp::transport [ERROR] err <- "I[13:44:04.653] Starting L
SP over stdin/stdout\n"
2022-04-23T13:44:04.653 helix_lsp::transport [ERROR] err <- "I[13:44:04.653] <-- initia
lize(0)\n"
2022-04-23T13:44:04.654 helix_lsp::transport [ERROR] err <- "I[13:44:04.654] --> reply:
initialize(0) 0 ms\n"
2022-04-23T13:44:04.654 helix_lsp::transport [ERROR] err <- "I[13:44:04.654] <-- initia
lized\n"
2022-04-23T13:44:04.654 helix_lsp::transport [ERROR] err <- "I[13:44:04.654] <-- textDo
cument/didOpen\n"
2022-04-23T13:44:04.655 helix_lsp::transport [ERROR] err <- "I[13:44:04.655] Failed to
find compilation database for /home/fred/git/helix-crash/test.hxx\n"
2022-04-23T13:44:04.655 helix_lsp::transport [ERROR] err <- "I[13:44:04.655] ASTWorker
building file /home/fred/git/helix-crash/test.hxx version 0 with command clangd fallbac
k\n"
2022-04-23T13:44:04.655 helix_lsp::transport [ERROR] err <- "[/home/fred/git/helix-cras
h]\n"
2022-04-23T13:44:04.655 helix_lsp::transport [ERROR] err <- "/usr/bin/clang -resource-d
ir=/usr/lib/clang/13.0.1 -- /home/fred/git/helix-crash/test.hxx\n"
2022-04-23T13:44:04.670 helix_lsp::transport [ERROR] err <- "I[13:44:04.670] --> textDo
cument/publishDiagnostics\n"
2022-04-23T13:44:07.133 helix_lsp::transport [ERROR] err <- "I[13:44:07.133] <-- textDo
cument/didChange\n"
2022-04-23T13:44:07.183 helix_lsp::transport [ERROR] err <- "I[13:44:07.183] Failed to
find compilation database for /home/fred/git/helix-crash/test.hxx\n"
2022-04-23T13:44:07.184 helix_lsp::transport [ERROR] err <- "I[13:44:07.184] ASTWorker
building file /home/fred/git/helix-crash/test.hxx version 1 with command clangd fallbac
k\n"
2022-04-23T13:44:07.184 helix_lsp::transport [ERROR] err <- "[/home/fred/git/helix-cras
h]\n"
2022-04-23T13:44:07.184 helix_lsp::transport [ERROR] err <- "/usr/bin/clang -resource-d
ir=/usr/lib/clang/13.0.1 -- /home/fred/git/helix-crash/test.hxx\n"
2022-04-23T13:44:07.193 helix_lsp::transport [ERROR] err <- "I[13:44:07.193] --> textDo
cument/publishDiagnostics\n"
2022-04-23T13:44:12.662 helix_lsp::transport [ERROR] err <- "I[13:44:12.662] <-- textDo
cument/didChange\n"
2022-04-23T13:44:12.713 helix_lsp::transport [ERROR] err <- "I[13:44:12.713] Failed to
find compilation database for /home/fred/git/helix-crash/test.hxx\n"
2022-04-23T13:44:12.714 helix_lsp::transport [ERROR] err <- "I[13:44:12.714] ASTWorker
building file /home/fred/git/helix-crash/test.hxx version 2 with command clangd fallbac
k\n"
2022-04-23T13:44:12.714 helix_lsp::transport [ERROR] err <- "[/home/fred/git/helix-cras
h]\n"
@@@
```

</details>

### Platform

Arch Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 22.03

**Comment by the-mikedavis** [comment] 2022-11-12 14:40
Looks like this has been fixed on master, I can't reproduce anymore

**Closed by the-mikedavis** 2022-11-12 14:40 UTC
Labels: C-bug, A-helix-term
