### ISSUE TITLE
Helix crashes when using :move

### ISSUE THREAD

**Issue by SoloJessy** [helix-editor/helix#12029] opened 2024-11-08 04:15 UTC
### Summary

`:move` command panics, crashing to terminal.

### Reproduction Steps

I tried this:

1. `hx test`
2. `:w`
3. `:move test.md`

I expected this to happen:

to add the .md extention, and initialize the md language server

Instead, this happened:

```
thread 'main' panicked at helix-lsp/src/client.rs:271:14:
language server not yet initialized!
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-11-08T04:11:16.306 globset [DEBUG] glob converted to regex: Glob { glob: "*/Dockerfile.*", re: "(?-u)^.*/Dockerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('D'), Literal('o'), Literal('c'), Literal('k'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-11-08T04:11:16.306 globset [DEBUG] glob converted to regex: Glob { glob: "*/dockerfile.*", re: "(?-u)^.*/dockerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('d'), Literal('o'), Literal('c'), Literal('k'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-11-08T04:11:16.306 globset [DEBUG] glob converted to regex: Glob { glob: "*/Containerfile.*", re: "(?-u)^.*/Containerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('C'), Literal('o'), Literal('n'), Literal('t'), Literal('a'), Literal('i'), Literal('n'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-11-08T04:11:16.306 globset [DEBUG] glob converted to regex: Glob { glob: "*/containerfile.*", re: "(?-u)^.*/containerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('c'), Literal('o'), Literal('n'), Literal('t'), Literal('a'), Literal('i'), Literal('n'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-11-08T04:11:16.306 globset [DEBUG] glob converted to regex: Glob { glob: "*/.*ignore", re: "(?-u)^.*/\\..*ignore$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('.'), ZeroOrMore, Literal('i'), Literal('g'), Literal('n'), Literal('o'), Literal('r'), Literal('e')]) }
2024-11-08T04:11:16.306 globset [DEBUG] glob converted to regex: Glob { glob: "*/BUILD.*", re: "(?-u)^.*/BUILD\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('B'), Literal('U'), Literal('I'), Literal('L'), Literal('D'), Literal('.'), ZeroOrMore]) }
2024-11-08T04:11:16.306 globset [DEBUG] glob converted to regex: Glob { glob: "*/.env.*", re: "(?-u)^.*/\\.env\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('.'), Literal('e'), Literal('n'), Literal('v'), Literal('.'), ZeroOrMore]) }
2024-11-08T04:11:16.306 globset [DEBUG] glob converted to regex: Glob { glob: "*/.envrc.*", re: "(?-u)^.*/\\.envrc\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('.'), Literal('e'), Literal('n'), Literal('v'), Literal('r'), Literal('c'), Literal('.'), ZeroOrMore]) }
2024-11-08T04:11:16.306 globset [DEBUG] glob converted to regex: Glob { glob: "*/conf/*/*.{inc,conf}", re: "(?-u)^.*/conf/.*/.*\\.(?:conf|inc)$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('c'), Literal('o'), Literal('n'), Literal('f'), Literal('/'), ZeroOrMore, Literal('/'), ZeroOrMore, Literal('.'), Alternates([Tokens([Literal('c'), Literal('o'), Literal('n'), Literal('f')]), Tokens([Literal('i'), Literal('n'), Literal('c')])])]) }
2024-11-08T04:11:16.306 globset [DEBUG] glob converted to regex: Glob { glob: "*/Jenkinsfile.*", re: "(?-u)^.*/Jenkinsfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('J'), Literal('e'), Literal('n'), Literal('k'), Literal('i'), Literal('n'), Literal('s'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-11-08T04:11:16.306 globset [DEBUG] built glob set; 1 literals, 0 basenames, 0 extensions, 0 prefixes, 129 suffixes, 9 required extensions, 10 regexes
2024-11-08T04:11:16.310 helix_view::clipboard [DEBUG] Using xclip to interact with the system and selection (primary) clipboard
2024-11-08T04:11:16.311 helix_vcs [DEBUG] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/home/jessy/Documents/writing/tv_omakes",
        },
    ),
}
2024-11-08T04:11:16.311 helix_vcs [DEBUG] failed to open diff base for /home/jessy/Documents/writing/tv_omakes/test
2024-11-08T04:11:16.311 helix_vcs [DEBUG] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/home/jessy/Documents/writing/tv_omakes",
        },
    ),
}
2024-11-08T04:11:16.311 helix_vcs [DEBUG] failed to obtain current head name for /home/jessy/Documents/writing/tv_omakes/test
2024-11-08T04:11:16.311 helix_view::editor [DEBUG] editor status: Loaded 1 file.
2024-11-08T04:11:16.314 helix_tui::backend::crossterm [DEBUG] The keyboard enhancement protocol is supported in this terminal (checked in 3.261842ms)
2024-11-08T04:11:16.314 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:16.560 helix_term::application [DEBUG] received editor event: IdleTimer
2024-11-08T04:11:17.953 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:18.203 helix_term::application [DEBUG] received editor event: IdleTimer
2024-11-08T04:11:18.218 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:19.016 helix_view::document [DEBUG] submitting save of doc 'Some("/home/jessy/Documents/writing/tv_omakes/test")'
2024-11-08T04:11:19.017 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:19.021 helix_term::application [DEBUG] received editor event: DocumentSaved(Ok(DocumentSavedEvent { revision: 0, doc_id: DocumentId(1), path: "/home/jessy/Documents/writing/tv_omakes/test", text: ["\n"] }))
2024-11-08T04:11:19.021 helix_term::application [DEBUG] document Some("/home/jessy/Documents/writing/tv_omakes/test") saved with revision 0
2024-11-08T04:11:19.021 helix_view::document [DEBUG] doc 1 revision updated 0 -> 0
2024-11-08T04:11:19.021 helix_view::editor [DEBUG] editor status: 'test' written, 2L 1B
2024-11-08T04:11:19.021 helix_lsp::file_event [DEBUG] Received file event for "/home/jessy/Documents/writing/tv_omakes/test"
2024-11-08T04:11:19.021 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:19.417 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:19.668 helix_term::application [DEBUG] received editor event: IdleTimer
2024-11-08T04:11:19.688 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:19.833 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:19.938 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:20.066 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:20.161 globset [DEBUG] glob converted to regex: Glob { glob: "projects/rust/**/target", re: "(?-u)^projects/rust(?:/|/.*/)target$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('p'), Literal('r'), Literal('o'), Literal('j'), Literal('e'), Literal('c'), Literal('t'), Literal('s'), Literal('/'), Literal('r'), Literal('u'), Literal('s'), Literal('t'), RecursiveZeroOrMore, Literal('t'), Literal('a'), Literal('r'), Literal('g'), Literal('e'), Literal('t')]) }
2024-11-08T04:11:20.161 globset [DEBUG] built glob set; 18 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required extensions, 1 regexes
2024-11-08T04:11:20.162 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:21.009 globset [DEBUG] glob converted to regex: Glob { glob: "projects/rust/**/target", re: "(?-u)^projects/rust(?:/|/.*/)target$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('p'), Literal('r'), Literal('o'), Literal('j'), Literal('e'), Literal('c'), Literal('t'), Literal('s'), Literal('/'), Literal('r'), Literal('u'), Literal('s'), Literal('t'), RecursiveZeroOrMore, Literal('t'), Literal('a'), Literal('r'), Literal('g'), Literal('e'), Literal('t')]) }
2024-11-08T04:11:21.009 globset [DEBUG] built glob set; 18 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required extensions, 1 regexes
2024-11-08T04:11:21.009 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:21.097 globset [DEBUG] glob converted to regex: Glob { glob: "projects/rust/**/target", re: "(?-u)^projects/rust(?:/|/.*/)target$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('p'), Literal('r'), Literal('o'), Literal('j'), Literal('e'), Literal('c'), Literal('t'), Literal('s'), Literal('/'), Literal('r'), Literal('u'), Literal('s'), Literal('t'), RecursiveZeroOrMore, Literal('t'), Literal('a'), Literal('r'), Literal('g'), Literal('e'), Literal('t')]) }
2024-11-08T04:11:21.097 globset [DEBUG] built glob set; 18 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required extensions, 1 regexes
2024-11-08T04:11:21.097 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:21.305 globset [DEBUG] glob converted to regex: Glob { glob: "projects/rust/**/target", re: "(?-u)^projects/rust(?:/|/.*/)target$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('p'), Literal('r'), Literal('o'), Literal('j'), Literal('e'), Literal('c'), Literal('t'), Literal('s'), Literal('/'), Literal('r'), Literal('u'), Literal('s'), Literal('t'), RecursiveZeroOrMore, Literal('t'), Literal('a'), Literal('r'), Literal('g'), Literal('e'), Literal('t')]) }
2024-11-08T04:11:21.305 globset [DEBUG] built glob set; 18 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required extensions, 1 regexes
2024-11-08T04:11:21.306 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:21.393 globset [DEBUG] glob converted to regex: Glob { glob: "projects/rust/**/target", re: "(?-u)^projects/rust(?:/|/.*/)target$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('p'), Literal('r'), Literal('o'), Literal('j'), Literal('e'), Literal('c'), Literal('t'), Literal('s'), Literal('/'), Literal('r'), Literal('u'), Literal('s'), Literal('t'), RecursiveZeroOrMore, Literal('t'), Literal('a'), Literal('r'), Literal('g'), Literal('e'), Literal('t')]) }
2024-11-08T04:11:21.393 globset [DEBUG] built glob set; 18 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required extensions, 1 regexes
2024-11-08T04:11:21.393 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:21.537 globset [DEBUG] glob converted to regex: Glob { glob: "projects/rust/**/target", re: "(?-u)^projects/rust(?:/|/.*/)target$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('p'), Literal('r'), Literal('o'), Literal('j'), Literal('e'), Literal('c'), Literal('t'), Literal('s'), Literal('/'), Literal('r'), Literal('u'), Literal('s'), Literal('t'), RecursiveZeroOrMore, Literal('t'), Literal('a'), Literal('r'), Literal('g'), Literal('e'), Literal('t')]) }
2024-11-08T04:11:21.537 globset [DEBUG] built glob set; 18 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required extensions, 1 regexes
2024-11-08T04:11:21.537 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:21.793 globset [DEBUG] glob converted to regex: Glob { glob: "projects/rust/**/target", re: "(?-u)^projects/rust(?:/|/.*/)target$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('p'), Literal('r'), Literal('o'), Literal('j'), Literal('e'), Literal('c'), Literal('t'), Literal('s'), Literal('/'), Literal('r'), Literal('u'), Literal('s'), Literal('t'), RecursiveZeroOrMore, Literal('t'), Literal('a'), Literal('r'), Literal('g'), Literal('e'), Literal('t')]) }
2024-11-08T04:11:21.793 globset [DEBUG] built glob set; 18 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required extensions, 1 regexes
2024-11-08T04:11:21.793 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:21.889 globset [DEBUG] glob converted to regex: Glob { glob: "projects/rust/**/target", re: "(?-u)^projects/rust(?:/|/.*/)target$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([Literal('p'), Literal('r'), Literal('o'), Literal('j'), Literal('e'), Literal('c'), Literal('t'), Literal('s'), Literal('/'), Literal('r'), Literal('u'), Literal('s'), Literal('t'), RecursiveZeroOrMore, Literal('t'), Literal('a'), Literal('r'), Literal('g'), Literal('e'), Literal('t')]) }
2024-11-08T04:11:21.889 globset [DEBUG] built glob set; 18 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required extensions, 1 regexes
2024-11-08T04:11:21.889 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-11-08T04:11:22.304 helix_view::editor [DEBUG] Language server not found for `source.md` markdown-oxide command 'markdown-oxide' not found: cannot find binary path
2024-11-08T04:11:22.304 helix_lsp::transport [INFO] marksman -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"positionEncodings":["utf-8","utf-32","utf-16"]},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"isPreferredSupport":true,"resolveSupport":{"properties":["edit","command"]}},"completion":{"completionItem":{"deprecatedSupport":true,"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{}},"formatting":{"dynamicRegistration":false},"hover":{"contentFormat":["markdown"]},"inlayHint":{"dynamicRegistration":false},"publishDiagnostics":{"tagSupport":{"valueSet":[1,2]},"versionSupport":true},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":true},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":false},"executeCommand":{"dynamicRegistration":false},"fileOperations":{"didRename":true,"willRename":true},"inlayHint":{"refreshSupport":false},"symbol":{"dynamicRegistration":false},"workspaceEdit":{"documentChanges":true,"failureHandling":"abort","normalizesLineEndings":false,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"helix","version":"24.7"},"processId":57704,"rootPath":"/home/jessy/Documents/writing/tv_omakes","rootUri":null,"workspaceFolders":[]},"id":0}

```

</details>

### Platform

Arch Linux

### Terminal Emulator

kitty 0.37.0

### Installation Method

pacman

### Helix Version

helix 24.7

**Comment by the-mikedavis** [comment] 2024-11-08 17:09
Duplicate of https://github.com/helix-editor/helix/issues/11384, fixed in https://github.com/helix-editor/helix/pull/11387

**Comment by saviway** [comment] 2024-11-08 17:09
> Confirmed on MacOS 15.0.1 intel.
> ### Platform
> 
> MacOS 15.0.1 intel
> ### Terminal Emulator
> 
> WezTerm
> ### Installation Method
> 
> homebrew
> ### Helix Version
> 
> 24.7 ([079f544](https://github.com/helix-editor/helix/commit/079f544260f4f5eaff08104bf07abd57bfb7b611))
> ### Helix log
> 
> Empty. (Cleared before test. No new records found after hx crash)
> ### `RUST_BACKTRACE=1`
> 
> ```
> thread 'main' panicked at helix-lsp/src/client.rs:271:14:
> language server not yet initialized!
> stack backtrace:
>    0: _rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::panicking::panic_display
>    3: core::option::expect_failed
>    4: std::sync::once::Once::call_once_force::{{closure}}
>    5: std::sys::sync::once::queue::Once::call
>    6: std::sync::once_lock::OnceLock<T>::initialize
>    7: helix_lsp::client::Client::did_rename
>    8: helix_view::editor::Editor::move_path
>    9: helix_term::commands::typed::move_buffer
>   10: helix_term::commands::typed::command_mode::{{closure}}
>   11: <helix_term::ui::prompt::Prompt as helix_term::compositor::Component>::handle_event
>   12: helix_term::compositor::Compositor::handle_event
>   13: hx::main_impl::{{closure}}
>   14: tokio::runtime::park::CachedParkThread::block_on
>   15: tokio::runtime::context::runtime::enter_runtime
>   16: tokio::runtime::runtime::Runtime::block_on
>   17: hx::main
> ```

After clone the master branch and build on local machine i cannot reproduce the crash with reproduce steps

**Closed** 2024-11-08 17:09 UTC
Labels: C-bug
