### ISSUE TITLE
Add cursor avoidance of errors and warnings

### ISSUE THREAD

**Issue by Hessesian** [helix-editor/helix#5060] opened 2022-12-08 07:57 UTC
![image](https://user-images.githubusercontent.com/7366371/206390518-82f28958-6ab5-4a18-b83f-afa3ca7a5b6e.png)

When typing in a smaller window (like scratch terminal) or in a screen with reduced width (multiple terminals on one screen) warnings and errors often hide what is being typed on top of the screen. 

I would suggest to take note of cursor position and add option to always display errors either on top or on the bottom depending on which relative position to top of the window cursor has.

**Comment by the-mikedavis** [comment] 2022-12-08 17:43
Duplicate of https://github.com/helix-editor/helix/issues/1462

**Closed by the-mikedavis** 2022-12-08 17:43 UTC
Labels: C-enhancement
