### ISSUE TITLE
Language server highlighting support

### ISSUE THREAD

**Issue by mkrueger** [helix-editor/helix#10343] opened 2024-04-11 06:29 UTC
I wrote a lsp for an old language and searched for editors which have lsp support.
Helix is awesome btw. I think I'll switch to it for my terminal editor :). 

Yeah I know I can add a grammer but the lsp can provide semantic highlighting and does the highlighting job in general. It's easier just to plug in the lsp.

**Comment by pascalkuthe** [comment] 2024-04-11 08:06
Duplicate of https://github.com/helix-editor/helix/discussions/5589

We will not support semantic tokens as the primary/only highlighting source. Only to supplement the TS grammar.

Helix is fundamentally a TS based editor. Tree sitter is used for much more than syntax highlighting.  A tree sitter grammar is the minimum requirement for supporting a language in helix.

**Closed by pascalkuthe** 2024-04-11 08:06 UTC
Labels: C-enhancement

**Comment by mkrueger** [comment] 2024-04-13 06:52
makes sense, but for me it's a deal breaker :/. Y I know how cool such O(log N) data structures are but sometimes it's about compatibilty. I've a parser for my language and I don't want to maintain one for every editor out there.
Esp. the use case I've is hard IMO - context sensitive keywords.

LSP gives authors of programming languages the toolset to bring features to every editor - all except highlighting works fine in helix and I wouldn't call the highligting I've in let's say vs code slow.   LSP parses the file in any case so there is no perf. loss requesting highlighting from the datastructure that's already there - just saying.

gl with the project - it's a very good editor but I fear now I've to look how to put an lsp into neovim :/ - seemed to complex at first glance.
