### ISSUE TITLE
save previously selected items on top of pickers

### ISSUE THREAD

**Issue by otavioschwanck** [helix-editor/helix#5821] opened 2023-02-04 11:03 UTC
Like: 
https://github.com/prochri/telescope-all-recent.nvim

**Comment by pascalkuthe** [comment] 2023-02-07 01:17
There are a bunch of issues about this already:
 #4776
 #5484
 #3812

I am going to close this as a duplicate of those.

**Closed by pascalkuthe** 2023-02-07 01:17 UTC
Labels: C-enhancement, A-helix-term
