### ISSUE TITLE
Indicators/Scroll at Bufferline when there are many open buffers.

### ISSUE THREAD

**Issue by rodrigopim** [helix-editor/helix#10510] opened 2024-04-18 20:07 UTC
Buffer line have indicators on the left and/or right if it acts on an open number of buffers exceeding the screen space. When navigating the buffers rolling the line, either right or left.

**Comment by the-mikedavis** [comment] 2024-04-18 20:46
Duplicate of https://github.com/helix-editor/helix/discussions/10199, also see https://github.com/helix-editor/helix/pull/8362

**Closed by the-mikedavis** 2024-04-18 20:46 UTC
Labels: C-enhancement
