### ISSUE TITLE
Scrolling down LSP definition in autocomplete tab

### ISSUE THREAD

**Issue by CyberFlaw** [helix-editor/helix#5691] opened 2023-01-26 18:50 UTC
Hey guys, I'm trying to scroll down the definition generated in autocomplete tab `<C+x>`. Whenever I press `Tab`, I can find a section of docs, but I'm unable to scroll or collapse the menu.

![lsp issue](https://user-images.githubusercontent.com/53346567/214923072-cc5ec0f1-d549-4472-aa41-7accbf5bfe4a.png)

How can I scroll down this documentation for a quick peek at examples? I can also use `space+k` and use `<C+d>` and `<C+u>` to scroll in docs under the cursor. But it would be nice to scroll within insert mode and quickly move on

**Comment by the-mikedavis** [comment] 2023-01-26 18:57
Duplicate of https://github.com/helix-editor/helix/issues/3062

**Closed by the-mikedavis** 2023-01-26 18:57 UTC
