### ISSUE TITLE
Make all cursors respect cursor-shape config in multi-selection

### ISSUE THREAD

**Issue by ndtoan96** [helix-editor/helix#9865] opened 2024-03-13 14:55 UTC
Currently, if I set cursor-shape to 'bar' in insert mode and use `C` to do multi-selection in normal mode then press `i` to enter insert mode, only the primary cursor has bar shape, the other non-primary cursors are still block-shape.

It would be more natural for all cursors to have the same shape.

**Comment by the-mikedavis** [comment] 2024-03-13 14:58
Duplicate of https://github.com/helix-editor/helix/issues/2744

**Closed by the-mikedavis** 2024-03-13 14:58 UTC
Labels: C-enhancement
