### ISSUE TITLE
dart not found in $PATH

### ISSUE THREAD

**Issue by ash-hashtag** [helix-editor/helix#7266] opened 2023-06-07 03:19 UTC
### Summary

```
[ash@dellg15 ~]$ helix --health dart
Configured language server: dart
Binary for language server: 'dart' not found in $PATH
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✘
Indent queries: ✓

[ash@dellg15 ~]$ which dart
/home/ash/Development/flutter/bin/dart

[ash@dellg15 ~]$ echo $PATH
/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:~/Development/flutter/bin

```

as you can see its clearly in the PATH. but helix doesn't seem to find it for some reason? Did I miss anything? I haven't changed anything in languages.toml, this is just the default behaviour. and all the other LSPs are working fine, just can't find dart

### Reproduction Steps

I just did a basic flutter installation, downloaded zip and placed it in some directory(here ~/Development) and added ~/Development/flutter/bin to $PATH in .bashrc

and everything seems to work fine, except helix. It can't find the dart executable in flutter/bin/

I tried with different terminals, made sure to source ~/.bashrc, I mean the terminal is clearly showing dart can be found. just helix can't find it.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-06-07T08:42:04.353 helix_view::editor [ERROR] Failed to initialize the LSP for `source.dart` { cannot find binary path }
```

</details>

### Platform

Linux

### Terminal Emulator

wezterm 20230408-112425-69ae8472

### Helix Version

helix 23.05

**Comment by ash-hashtag** [comment] 2023-06-09 15:02
thank you, yup that fixes it, but should I close this issue? I mean it kinda feels like a small bug, because I don't know why, it is detecting other LSPs as expected, but only with dart? or it just randomly fails to detect a LSP? Some of the other LSPs also were in path '~'. 

But also I don't think this issue is necessary because obviously using ${HOME} is recommended. Is there already an issue regarding this?

**Comment by kirawi** [comment] 2023-06-10 01:53
See https://github.com/rust-lang/rust/issues/19686
Duplicate of https://github.com/helix-editor/helix/issues/5538

**Comment by kirawi** [comment] 2023-06-10 01:56
It is possible this is an upstream bug w/ https://github.com/harryfei/which-rs

**Comment by kulothunganug** [comment] 2023-11-12 09:58
I had a same experience as the author but in neovim.
Maybe this has nothing to do with helix.

**Comment by kirawi** [comment] 2023-11-12 14:39
Closed as it was fixed upstream.

**Closed by kirawi** 2023-11-12 14:39 UTC
Labels: C-bug
