### ISSUE TITLE
missing eof newline

### ISSUE THREAD

**Issue by baffling-knee** [helix-editor/helix#4933] opened 2022-11-29 13:37 UTC
### Summary

unlike vim and neovim, helix doesnt add a eof newline at the end of file.
causes issues when submit files to github for ex and warning is show.
possible to do automatic like vim or with config option please?

### Reproduction Steps

 

I tried this:

1. `hx` edit new file
2. add content and save+quit
3. look for eof newline - is missing

I expected this to happen:

eof newline add automatic like vim

Instead, this happened:

no eof newline. have to open in vim and save to add it

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

all

### Terminal Emulator

all

### Helix Version

22.08.1

**Comment by gabydd** [comment] 2022-11-29 13:52
Lol turns out my GitHub searching was not good enough and there is a duplicate for this my bad: https://github.com/helix-editor/helix/issues/4274

**Comment by the-mikedavis** [comment] 2022-11-29 13:57
Duplicate of #4274

**Closed by the-mikedavis** 2022-11-29 13:57 UTC
Labels: C-bug
