### ISSUE TITLE
Typescript LSP formatting removes all indentation.

### ISSUE THREAD

**Issue by dimas-cyriaco** [helix-editor/helix#2349] opened 2022-04-30 17:30 UTC
### Summary

Formatting typescript code via the LSP formatter removes all indentation.

`typescript-language-server` version: 0.9.7

This works fine with neovim.

I've noticed that the `textDocument/formatting` command is sent to the lsp with the parameter `"tabSize":0`. Don't know if this could be related.

### Reproduction Steps

 

1. I added this to language.toml:

```toml
[[language]]
name = "typescript"
auto-format = true
```

2. Create a file with `.ts` extension and the following contents:

```ts
function Test() {
  console.log("test")
}
```

3. Save the file.

I expected this to happen:
Nothing.

Instead, this happened:
File changed to:

```ts
function Test() {
console.log("test")
}
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-04-30T14:27:16.664 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/formatting","params":{"options":{"insertSpaces":false,"tabSize":0},"textDocument":{"uri":"file:///Users/dimascyriaco/test.ts"}},"id":1}
2022-04-30T14:27:16.703 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":1,"result":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":2}},"newText":""}]}
2022-04-30T14:27:16.703 helix_lsp::transport [INFO] <- [{"newText":"","range":{"end":{"character":2,"line":1},"start":{"character":0,"line":1}}}]
2022-04-30T14:27:16.703 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":2,"line":1},"start":{"character":0,"line":1}},"text":""}],"textDocument":{"uri":"file:///Users/dimascyriaco/test.ts","version":4}}}
2022-04-30T14:27:16.977 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/dimascyriaco/test.ts","diagnostics":[]}}
```

</details>

### Platform

macOs

### Terminal Emulator

Alacritty

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by the-mikedavis** [comment] 2022-04-30 18:02
Duplicate of https://github.com/helix-editor/helix/issues/1884

**Closed by the-mikedavis** 2022-04-30 18:02 UTC
Labels: C-bug
