### ISSUE TITLE
Glitching when texts contain some Unicode symbols

### ISSUE THREAD

**Issue by Hapenia-Lans** [helix-editor/helix#5502] opened 2023-01-11 09:28 UTC
![bug](https://user-images.githubusercontent.com/93276898/211772287-5a53ba3f-9122-49d2-a689-595aa9db6442.gif)

the code snippet:

```rust
if ui.button("🗙").clicked() {
    self.mark_as_delete = Some(i);
}
```

**Comment by the-mikedavis** [comment] 2023-01-11 14:37
What terminal are you using? I can't reproduce this with kitty 0.26.2

**Comment by Hapenia-Lans** [comment] 2023-01-11 15:47
Microsoft Terminal in Windows 11 22H2

**Comment by kirawi** [comment] 2023-01-11 22:16
This may be a bug with Microsoft Terminal. It's notoriously been a bit buggy.

**Comment by CptPotato** [comment] 2023-01-12 11:57
This might be #4932

**Comment by kirawi** [comment] 2023-01-13 22:05
Perhaps it's related, but according to Unicode it isn't an emoji: https://util.unicode.org/UnicodeJsps/character.jsp?a=1F5D9

**Comment by pascalkuthe** [comment] 2023-02-16 00:45
Closing in favor of https://github.com/helix-editor/helix/issues/6012

**Closed by pascalkuthe** 2023-02-16 00:45 UTC
Labels: C-bug, A-helix-term
