### ISSUE TITLE
File not saved until quit, which hangs for a while

### ISSUE THREAD

**Issue by hazeycode** [helix-editor/helix#2570] opened 2022-05-25 14:16 UTC
### Summary

Fairly frequently, `:w` can fail with `Async Error: request timed out`, other times no message is observed.
The current file will not be written until the program is quit using `:q` where then the program hangs for a couple of minutes before finally writing the file and exiting.

Part of the problem appears to be that the language server I am using is failing. Helix does not deal with this situation gracefully.

### Reproduction Steps

As described.

I would expect that language server errors are reported promptly to the user and that they interfere with file writing operations minimally.

### Helix log

```
2022-05-25T15:10:47.749 helix_lsp::transport [ERROR] err: <- IO(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
2022-05-25T15:11:07.750 helix_view::document [WARN] LSP formatting failed: request timed out
2022-05-25T15:11:07.750 helix_lsp::transport [ERROR] err: <- IO(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
2022-05-25T15:11:08.252 helix_term::application [ERROR] Timed out waiting for language servers to shutdown
```

### Platform

Linux

### Terminal Emulator

kitty 0.23.1

### Helix Version

helix 0.5.0

**Comment by hazeycode** [comment] 2022-05-25 15:00
[zls](https://github.com/zigtools/zls) is the LS i'm using.

My config file, very simple:
```toml
theme = "gruvbox"

[editor]
line-number = "absolute"
auto-completion = true
true-color = true
```

As for a particular file, I've observed the issue with any .zig file.

**Comment by the-mikedavis** [comment] 2022-05-25 15:56
Similar but I think a different issue overall: https://github.com/helix-editor/helix/issues/2059

It looks like the formatting callback is timing out because the language server crashed (hence the "broken pipe"). I'm not sure there's any handling of crashing language servers at the moment.

**Comment by Xaeroxe** [comment] 2022-10-21 18:41
Reproducible with `rust-analyzer` language server too. Really breaks up the flow of using helix for dev work sadly.

**Comment by the-mikedavis** [comment] 2022-11-29 22:18
This was fixed in https://github.com/helix-editor/helix/pull/4797

**Closed by the-mikedavis** 2022-11-29 22:18 UTC
Labels: C-bug
