### ISSUE TITLE
Docstrings for custom keymappings beneath a mode

### ISSUE THREAD

**Issue by ElDifinitivo** [helix-editor/helix#3867] opened 2022-09-16 19:32 UTC
When defining new keymappings under an existing mode, the docstring will default to the description of the command, with each new keymap listed as a new entry in the pop-up.

However, when one of the new maps consist of multiple commands (e.g. `m = { l = ["extend_to_line_bounds", "trim_selections"] }`), the docstring will default to `[Multiple commands]`, which gives the user no indication as to what the keymap will do. There should be an override which would allow the user to set a custom description for the keymap. The default `Multiple commands` should probably remain as i+ commands could get increasingly unwieldy if it defaulted to the description of each individual command.

**Comment by the-mikedavis** [comment] 2022-09-16 20:18
Duplicate of https://github.com/helix-editor/helix/issues/3130

**Closed by the-mikedavis** 2022-09-16 20:18 UTC
Labels: C-enhancement
