### ISSUE TITLE
Hangs on open picker

### ISSUE THREAD

**Issue by simonsolnes** [helix-editor/helix#4076] opened 2022-10-02 19:35 UTC
### Summary

Helix hangs on open file picker. 
It should be noted that it worked earlier today. 
It has worked and failed with no `config.toml` file. 

I suspect it happened after i did 
`pip3 install python-lsp-server`, 
but that shouldn't really affect Helix in that way.

### Reproduction Steps

1. Open helix with `hx`
2. Press `<space>`,
3. Select 'Open file picker' by pressing `f`
4. Helix is now hung, and responds to nothing.

### Helix log

2022-10-02T21:23:47.550 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }

### Platform

macOS 12.6

### Terminal Emulator

iTerm 3.4.16

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by the-mikedavis** [comment] 2022-10-02 19:40
Are you opening the file picker in a directory with many files?

**Comment by simonsolnes** [comment] 2022-10-02 20:16
No. Tried to open it at `~`, `~/.config/helix` and I created an empty directory now to try it out. I'd be glad to provide more information, but there's nothing int the helix log when i have followed the steps.

**Comment by simonsolnes** [comment] 2022-10-02 20:19
Even after running with `hx -v`.

**Comment by simonsolnes** [comment] 2022-10-02 20:22
It should be noted that `<space>F` works. Not `<space>f`, which I assume should not be affected by current working directory.

**Comment by simonsolnes** [comment] 2022-10-02 20:34
<img width="328" alt="Screenshot 2022-10-02 at 22 31 57" src="https://user-images.githubusercontent.com/8342979/193475015-00326c29-c5da-41a4-a22d-827ebd985316.png">
After leaving it on for 5 minutes I get this pop-up, and it works. Helix has probably now scanned all of my files. Maybe this is not a bug, but rather a feature request to show that Helix is scanning my files. (I have an absurd amount of files.)

**Comment by simonsolnes** [comment] 2022-10-02 20:36
It still hangs. And it blocks my usage of Helix, even after it has 'loaded'. I still regard it as a bug.

**Comment by the-mikedavis** [comment] 2022-10-02 21:09
Duplicate of https://github.com/helix-editor/helix/issues/1707

**Comment by the-mikedavis** [comment] 2022-10-02 21:09
There isn't a way to cancel it so you'll need to `kill` from a separate terminal emulator session

**Closed by the-mikedavis** 2022-10-02 21:09 UTC
Labels: C-bug
