### ISSUE TITLE
Dollar $ symbol appened to imports

### ISSUE THREAD

**Issue by cemalokten** [helix-editor/helix#5785] opened 2023-02-02 15:37 UTC
### Summary

When I use the suggested imports from auto-complete, the import name is appended with a `$1`. 

### Reproduction Steps

Use import auto-complete to import (Typescript / React)

<img width="677" alt="image" src="https://user-images.githubusercontent.com/60609268/216369435-c771066c-1a93-44c4-b99b-2fc04dca6eef.png">

### Platform

MacOS

### Terminal Emulator

wezterm 20221119-145034-49b9839f

### Helix Version

helix 22.12 (79b6422d)

**Comment by the-mikedavis** [comment] 2023-02-02 15:46
What does the log say when running in verbose mode? https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file

This looks like snippet syntax which is not currently handled: #395. The language server should not be sending snippet syntax though because we tell the language server not to use them in the LSP initialization message: https://github.com/helix-editor/helix/blob/62d046fa219b927c536bf6726fcae1e825346e0e/helix-lsp/src/client.rs#L312

**Comment by pascalkuthe** [comment] 2023-02-02 15:47
> What does the log say when running in verbose mode? [helix-editor/helix/wiki/FAQ#access-the-log-file](https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file)
> 
> This looks like snippet syntax which is not currently handled: #395. The language server should not be sending snippet syntax though because we tell the language server not to use them in the LSP initialization message:
> 
> https://github.com/helix-editor/helix/blob/62d046fa219b927c536bf6726fcae1e825346e0e/helix-lsp/src/client.rs#L312

many LSPs (including tablo and RA) do so anyway so that `snippet_support` setting seems to be ignored frequently

**Comment by pascalkuthe** [comment] 2023-02-11 21:12
closing as duplicate of #395 which will soon be implemented in #5864

**Closed by pascalkuthe** 2023-02-11 21:12 UTC
Labels: C-bug, A-language-server
