### ISSUE TITLE
autopairs doesn't work with f strings in python

### ISSUE THREAD

**Issue by loyalrami** [helix-editor/helix#7815] opened 2023-08-03 10:20 UTC
Hi, I recently switched to helix and I am a python programmer. I have encountered issues with autopairs after f strings in python.

**ISSUE WITH DOUBLE QUOTES**
If I type ``` return f ``` and then type double quotes then it is typed once only. like ``` return f" ``` and after i type double quotes again then pairs work and it gets 3 double quotes. like ``` return f""" ```

**ISSUE WITH SINGLE QUOTES**
And with single quotes after f string if i type single quote then it is also typed once. like ``` return f' ``` and if I type single quote again then only 1 single quote is typed again like ``` f'' ```

**STEPS TO REPRODUCE**
1. Type f string in python and after type double quotes 2 times to see the behavior of it.
2. Type f string in python and after f type single quote 2 times to see.

**INFO**
OS: Windows 10
HELIX VERSION: 23.05 ( 7f5940be )

**Comment by dead10ck** [comment] 2023-08-03 11:21
Duplicate of #4100

**Closed** 2023-08-03 11:21 UTC
