### ISSUE TITLE
Append mode selection behavior

### ISSUE THREAD

**Issue by Carrotstrip** [helix-editor/helix#4451] opened 2022-10-24 18:32 UTC
I haven't been able to find mention of this behavior anywhere; when I enter insert mode through `a`, all of my insertion is selected as I type it. This does not happen when I enter insert mode through `i`, `I`, or even `A`. Is this expected behavior, and if so, why? I can imagine being convinced that it's beneficial to auto-select each insertion, but then this should be the behavior regardless of how I entered insert mode. I can take this on if the change is desired.

**Comment by ksandvik** [comment] 2022-10-24 18:59
Yes, verified this happening in top-of-tree.

**Comment by the-mikedavis** [comment] 2022-10-24 22:38
Duplicate of #1411

The current behavior of `a` is intentional.

Also see https://github.com/helix-editor/helix/issues/3744#issuecomment-1240726094

**Closed by the-mikedavis** 2022-10-24 22:38 UTC
