### ISSUE TITLE
Make file picker asynchronous

### ISSUE THREAD

**Issue by IvanVnucec** [helix-editor/helix#7560] opened 2023-07-07 05:50 UTC
### Discussed in https://github.com/helix-editor/helix/discussions/7489

<div type='discussions-op-text'>

<sup>Originally posted by **IvanVnucec** June 30, 2023</sup>
The problem is when File picker is opened on large mono-repos, it takes few seconds (too long) to open it. 
One solution would be to open File picker immediately and display empty window with some kind of message that the files are being loaded. When files are loaded, then we would display it.
In this way, user could open File picker and start to type immediately and the results would shown once they are loaded.
The feature is similar how the vscode does searching.

Also, this feature could be implemented also in the Global search which blocks once it has found the results. There is an issue related to this [here](https://github.com/helix-editor/helix/issues/5871).</div>

**Comment by pascalkuthe** [comment] 2023-07-07 12:38
I don't think we need yet anoteher issue to track this, closing as duplicate of https://github.com/helix-editor/helix/issues/5871

**Closed by pascalkuthe** 2023-07-07 12:38 UTC
