### ISSUE TITLE
Keybinding for ["normal_mode", ":write"] doesn't remove file-modification-indicator

### ISSUE THREAD

**Issue by rdscott-vrsk** [helix-editor/helix#6513] opened 2023-03-31 19:41 UTC
### Summary

 A keybinding like
```toml
[keys.insert]
k = { j = ["normal_mode", ":write"] }
```
Will exit insert mode and write the file, but the `file-modification-indicator` will remain in the bufferline and statusline (if configured) as if the file were not saved.

This appears to be specific to having the `:write` be a second command in a list, or when going from insert mode to normal mode. Key bindings that save when triggered in normal mode work as expected.

### Helix log

Log shows stuff like this:
```
2023-03-31T11:08:13.875 helix_view::document [DEBUG] id 9 modified - last saved: 0, current: 0
2023-03-31T11:08:13.875 helix_view::document [DEBUG] id 10 modified - last saved: 10, current: 10
2023-03-31T11:08:13.875 helix_view::document [DEBUG] id 7 modified - last saved: 0, current: 4
```

### Platform

macOS

### Terminal Emulator

wezterm 20230326-111934-3666303c

### Helix Version

helix 23.03 (3cf03723)

**Comment by Xalfer** [comment] 2023-05-24 09:54
I've looked into this and it appears that right after writing it creates a new revision. This new revision has a different id than the id of the last changed revision, which is why the `file-modification-indicator` appears.

One way I managed to fix this issue is by adding `doc.append_changes_to_history(view)` in  `helix-term::commands::typed::write_impl` and `helix-term::commands::typed::write_all_impl`. But this feels like a hack so I want to find a better solution.

**Comment by Connortsui20** [comment] 2023-08-19 01:36
I'd like to just mention here since it is not brought up anywhere else that for some file types (like `.rs`), this is not a problem, likely because of auto-formatting with rust-analyzer. Since #7226 is not done yet, maybe this could be helpful in figuring out a slick way to fix this? I can't really tell if the general solution there actually works or not

**Comment by Joe-Zer0** [comment] 2023-10-13 21:15
I am having the same issue.  When pressing C-s while in insert mode, the file does save.  But the file modification indicator remains and I must use :q! to quit.
```
[keys.insert]
C-s = ["normal_mode", ":write"]
```
Windows Terminal - 1.18.2822.0
PowerShell Core - 7.3.8
Helix - 9f6e9a15 - 2023-10-13

**Comment by Joe-Zer0** [comment] 2023-12-30 21:49
I updated my keymap to this as a temporary work around.
```
[keys.insert]
C-s = ["normal_mode", "commit_undo_checkpoint", ":write"]
```
reference - https://github.com/helix-editor/helix/issues/3501#issuecomment-1861753973

**Comment by pascalkuthe** [comment] 2024-04-06 01:53
Duplicate of  #3501

**Closed by pascalkuthe** 2024-04-06 01:53 UTC
Labels: C-bug
