### ISSUE TITLE
golang auto import fail 

### ISSUE THREAD

**Issue by fastfading** [helix-editor/helix#5980] opened 2023-02-14 08:31 UTC
### Summary

<img width="494" alt="image" src="https://user-images.githubusercontent.com/8351732/218680850-38d43ab4-47b9-4c19-a0ed-bb3015d107fd.png">

I add below configure,  did not help either

[[language]]
name = "go"
config = { goimports = true, gofumpt = true, staticcheck = true, analyses = { unusedparams = true, unreachable = true } }

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macos

### Terminal Emulator

iterm2

### Helix Version

22.12

**Comment by the-mikedavis** [comment] 2023-02-14 23:45
Could you post the log when running in verbose mode (`hx -v`) for when this happens? https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file

**Comment by fastfading** [comment] 2023-02-15 06:14
hx --health go
Configured language server: gopls
Binary for language server: /Users/xxx/go/bin/gopls
Configured debug adapter: dlv
Binary for debug adapter: /Users/xxx/go/bin/dlv
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓

**Comment by fastfading** [comment] 2023-02-15 06:14
[helix.log.zip](https://github.com/helix-editor/helix/files/10739871/helix.log.zip)

**Comment by fastfading** [comment] 2023-02-15 06:16
it is very easy to duplicate . 
write a golang program ,  remove some imports



```
package main
//import "fmt"
func main() {
    fmt.Println("hello world")
}
```

**Comment by the-mikedavis** [comment] 2023-02-15 14:49
Are you looking for the import to happen when using auto-complete of `fmt.Println` or on save? If it's on save then this is https://github.com/helix-editor/helix/issues/1565

**Comment by fastfading** [comment] 2023-02-16 01:11
> Are you looking for the import to happen when using auto-complete of `fmt.Println` or on save? If it's on save then this is #1565

yes,  this is the same issue.
most editor auto import on save
we expect this in helix too

**Comment by pascalkuthe** [comment] 2023-02-16 01:13
In that case I am closing this as a duplicate of #1565

**Closed by pascalkuthe** 2023-02-16 01:13 UTC
Labels: C-bug

**Comment by Sackbuoy** [comment] 2023-05-02 21:20
In case anyone else comes across this, a quick solution to get auto imports with go in helix is this https://bminde.com/2022/08/27/til-helix-editor.html
