### ISSUE TITLE
`:config-open <file>` to open files like "languages.toml"

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#4014] opened 2022-09-28 18:30 UTC
There's no command to open the "languages.toml" file.

Extending `:config-open` to open the "languages.toml" or any config files that might be linked to helix in the future.

This way `:config-open` alone would open "config.toml" and `:config-open languages.toml` would open the "languages.toml" file and so on....

**Comment by the-mikedavis** [comment] 2022-09-28 19:24
Duplicate of https://github.com/helix-editor/helix/issues/3495

**Closed by the-mikedavis** 2022-09-28 19:24 UTC
Labels: C-enhancement
