### ISSUE TITLE
Different behaviors of the rust-analyzer in helix and vscode

### ISSUE THREAD

**Issue by Dangerise** [helix-editor/helix#10626] opened 2024-04-29 10:02 UTC
I'm using slint crate in my rust code, my rust code has included some slint modules,

in vs code, If I edit the slint files and save them, I can get the newest auto completion from the slint when I back to the rust code, but helix didn't

**Comment by pascalkuthe** [comment] 2024-04-29 10:39
Duplicate of  #1125

**Closed by pascalkuthe** 2024-04-29 10:39 UTC

**Comment by Dangerise** [comment] 2024-04-29 11:39
@pascalkuthe reload don't make it work

**Comment by Dangerise** [comment] 2024-04-29 12:26
I compare with them a little further, maybe the problem is RA in helix is not very often to expand the macro, in vsc, every time I changed the macro and it will give me new results
