### ISSUE TITLE
Alert the user when in-view buffer gets modified externally

### ISSUE THREAD

**Issue by gyreas** [helix-editor/helix#9176] opened 2023-12-27 13:38 UTC
As the title suggests, when the current document is modified externally, the user should be alerted of this. This allows the user to take action without having to find out when attempting to save the document. This is particularly useful when editing using multiple IDE/editors eg Intellij + hx.

- A background task will monitor the modified state of the document in any editing mode, then alert accordingly.
- The alert box should be of a prominent red color, preferably outlined like Infoboxes
- Ideally, present the user with a dialog to keep their version or update the document.

I'm new to Rust, tho. Anyway, this is what I got for PoC. 
![image](https://github.com/helix-editor/helix/assets/126640223/ca520151-35ab-4a72-aa3f-97e3fbd10d4a)

**Comment by pascalkuthe** [comment] 2023-12-27 13:44
Duplicate of #1125

**Closed by pascalkuthe** 2023-12-27 13:44 UTC
Labels: C-enhancement
