### ISSUE TITLE
Editor freezes when editing specific mermaid block inside markdown

### ISSUE THREAD

**Issue by 4ndv** [helix-editor/helix#9572] opened 2024-02-08 21:04 UTC
### Summary

When I edit mermaid sequenceDiagram inside markdown file, and move cursor to specific character, entire editor just becomes unresponsive, and stops handling any inputs

### Reproduction Steps

 

Edit this markdown file (backticks are part of the file):

``````
```mermaid
sequenceDiagram
  Device -->> App: Hello
```
``````

Navigate cursor to the second "-" character and advance to ">"

I expected this to happen:

Editor reacts to that command

Instead, this happened:

Editor stops reacting to any commands

### Helix log

In the logs there is only one line around that event:

```
2024-02-09T04:00:48.708 helix_view::editor [ERROR] Failed to initialize the language servers for `source.md` - `marksman` { cannot find binary path }
```

### Platform

macOS

### Terminal Emulator

iTerm 3.4.23 / macOS Terminal

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by kirawi** [comment] 2024-02-08 21:11
Duplicate of https://github.com/helix-editor/helix/issues/8709

**Closed by kirawi** 2024-02-08 21:11 UTC
Labels: C-bug
