### ISSUE TITLE
Mouse click on bufferline

### ISSUE THREAD

**Issue by DuckDuckWhale** [helix-editor/helix#5102] opened 2022-12-10 00:00 UTC
Switching tabs with mouse is possible in Vim but not yet in Helix and would be nice to have. Currently clicking on tabs seems to do nothing.

**Comment by the-mikedavis** [comment] 2022-12-10 00:19
Duplicate of https://github.com/helix-editor/helix/issues/4942

**Closed by the-mikedavis** 2022-12-10 00:19 UTC
Labels: C-enhancement
