### ISSUE TITLE
LSP/ UI related crash (possibly for `rust analyzer` or something general) + One More

### ISSUE THREAD

**Issue by ZuixAlias** [helix-editor/helix#2588] opened 2022-05-28 02:25 UTC
### Summary

Finished building a rust project in windows terminal (in a panel alongside helix, which is a new instance of `cmd` i guess)...then went back to the rust file and pressed `.` key (it had default key binding), maybe without pressing any mouse button + was in normal mode and got a crash with this msg :

![lsp_crash](https://user-images.githubusercontent.com/96847142/170805936-df17bf9e-7323-48b1-b226-3a582acb516e.jpg)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-05-27T19:41:31.363 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 10, character: 4 }, end: Position { line: 10, character: 17 } }, severity: Some(Warning), code: Some(String("unused_imports")), code_description: None, source: Some("rustc"), message: "unused import: `nwg::NativeUi`\n`#[warn(unused_imports)]` on by default", related_information: None, tags: Some([Unnecessary]), data: None }
2022-05-27T19:44:04.267 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-05-27T19:44:04.267 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-05-27T22:32:56.797 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-05-27T22:32:56.798 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-05-27T23:16:50.712 helix_lsp::transport [ERROR] <- Server error: content modified
```

</details>

### Platform

Windows

### Terminal Emulator

Window Terminal 1.12.10983.0

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by ZuixAlias** [comment] 2022-05-28 02:42
I was typing and got another crash (log contains the same last msg as in the log posted above two more times) :

![crash2](https://user-images.githubusercontent.com/96847142/170806601-fdf3e5d4-0fd7-495f-b220-5b7d0854e934.jpg)

**Comment by archseer** [comment] 2022-05-28 05:52
Please:

- Copy paste your error rather than taking a screenshot so it's searchable
- Reproduce the trace with RUST BACKTRACE=full as the output suggests
- Open separate issues

The first issue is a duplicate of https://github.com/helix-editor/helix/issues/2051 but I'd like to see a proper backtrace of the second one.

**Comment by ZuixAlias** [comment] 2022-05-28 06:56
Oh no, i a really sorry, will make sure to copy the text next time onwards...and open issues separately too...

Btw i am unable to backtrace/ reproduce the second error, it had occurred randomly when i was typing...and from path in the error i can see that it is not related to what i was working on (could be a dependency of one of the dependencies that i was using...but i have checked and doesn't seem like it)

Having said that, i will make sure to try my best to reproduce asap and as accurately as possible if it happens again (and update here/ open an issue).

**Comment by archseer** [comment] 2022-05-31 15:51
I think the second issue is also a duplicate, we're getting a trace in https://github.com/helix-editor/helix/issues/2616#issuecomment-1142286249=

**Closed by archseer** 2022-05-31 15:51 UTC
Labels: C-bug
