### ISSUE TITLE
add option to display syntax tree path in status line or enably sticky scroll

### ISSUE THREAD

**Issue by calbaker** [helix-editor/helix#10672] opened 2024-05-03 16:30 UTC
Make it so that the `[editor.statusline]` section of config.toml could have something like `center = ["file-name", "syntax-tree-path"]` where the presence of `"syntax-tree-path"` would tell helix to display something like `crate::mymod::MyStruct::my_method` if my cursor is inside the function signature or body of `my_method`.  This would have a similar effect to VS Code's sticky scroll.  Another option would be to just implement [VSCode's sticky scroll](https://learn.microsoft.com/en-us/visualstudio/ide/editor-sticky-scroll?view=vs-2022) because it seems doable in Helix.

**Comment by calbaker** [comment] 2024-05-03 16:48
Note that maybe `syntax-tree-path` is not the semantically correct name, and it's ok to change that to something more appropriate.  I'm a mechanical engineer pretending to be a computer scientist.

**Comment by kirawi** [comment] 2024-05-04 15:13
Duplicate of https://github.com/helix-editor/helix/issues/396

**Closed by kirawi** 2024-05-04 15:13 UTC
