### ISSUE TITLE
Locale-independent keybinds

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1301] opened 2021-12-19 11:36 UTC
Current keybinds depend on your keyboard layout, e.g. `C-s=":w"` only works for latin `s`, but fails when you change keyboard layout to something else
I'd like to be able to set keybinds in a locale-independent way, for example, via a virtual key code
`C-vk53=":w"  #comment: vk53 = physical key with latin s`
(scan codes are another alternative, though they are hardware-dependent, so potentially worse?)

**Comment by archseer** [comment] 2021-12-19 14:18
Duplicate of https://github.com/helix-editor/helix/issues/133

**Closed by archseer** 2021-12-19 14:18 UTC
Labels: C-enhancement
