### ISSUE TITLE
Introduce an `auto-info-timeout` configuration parameter

### ISSUE THREAD

**Issue by novusnota** [helix-editor/helix#10556] opened 2024-04-22 18:25 UTC
This would reduce the visual noise from the helpful info boxes by making them open after some specified timeout. Otherwise they blink too much in the bottom right corner, developing some kind of "ad blindness", but in Helix — my brain learns to ignore those and after a while it's tough to read anything from them when I deliberately need and try to.

May be added into the general "editor" section of `config.toml`.

**Comment by kirawi** [comment] 2024-04-22 18:51
duplicate of https://github.com/helix-editor/helix/issues/1475

**Closed by kirawi** 2024-04-22 18:51 UTC
Labels: C-enhancement
