### ISSUE TITLE
Arrow keys unrecognized in edit mode

### ISSUE THREAD

**Issue by TH3-S4LM0N** [helix-editor/helix#3880] opened 2022-09-17 20:29 UTC
### Summary

I recently switched from `helix` to `helix-git` in the aur, and i instantly noticed that my arrow keys no longer work in edit mode. Really all there is to say.
Will send my config if neccesary.

### Reproduction Steps

`hx ~/.config/helix/config.toml`
Pressed I
Arrow keys stop working

### Helix log

[helix.log](https://github.com/helix-editor/helix/files/9592570/helix.log)

### Platform

Arch Linux, zen kernel

### Terminal Emulator

kitty (xterm-kitty)

### Helix Version

latest (cant `git describe` as helix-git install)

**Comment by the-mikedavis** [comment] 2022-09-17 20:33
Duplicate of https://github.com/helix-editor/helix/issues/3762

**Closed by the-mikedavis** 2022-09-17 20:33 UTC
Labels: C-bug
