### ISSUE TITLE
Can't remap C-/

### ISSUE THREAD

**Issue by vlabo** [helix-editor/helix#6430] opened 2023-03-24 22:17 UTC
Remapping "C-/" does not work.
Remapping just "/" works with no issue.

When I press C-/ in insert mode it types 7.
My config:
```toml
[keys.normal]
"C-/" = "toggle_comments"
```

Thanks for the great work. I tried to fix it myself but it does not look like something obvious at least for me.

**Comment by the-mikedavis** [comment] 2023-03-25 13:21
Duplicate of https://github.com/helix-editor/helix/issues/3210

This has been fixed on master for terminal emulators that support the enhanced keyboard protocol.

**Closed by the-mikedavis** 2023-03-25 13:21 UTC
