### ISSUE TITLE
Reload files changed on disk if they aren't modified in helix

### ISSUE THREAD

**Issue by leonm1** [helix-editor/helix#5647] opened 2023-01-23 16:37 UTC
vim/neovim/emacs/vscode reloads files that have changed on disk if they don't have unsaved changes in the editor. I think it would be really helpful if Helix did the same.

### Steps to reproduce:

1. Open a file in helix, say helix-editor's README.md
2. Open another terminal window, and in the terminal window:
    a. Open the file in another editor, like nvim
    b. add a line to the description of Helix, and
    c. save the file
4. Return to helix and observe the file does not contain the line added in helix. Modify the file in helix, and observe your other editor of choice update the file's contents to match (as long as there are no unsaved changes in the other editor)

### Expected behavior

I would expect the displayed file contents in Helix to match the file contents on disk, assuming and unless the buffer is not "dirty"/has unsaved changes in Helix

This is especially helpful after performing actions like  `git switch`, after which manually running `:reload-all` is required.

**Comment by kirawi** [comment] 2023-01-23 16:39
Duplicate of https://github.com/helix-editor/helix/issues/1125

**Closed by kirawi** 2023-01-23 16:39 UTC
Labels: C-enhancement

**Comment by leonm1** [comment] 2023-01-23 16:55
Thanks for finding the duplicate. I searched a few different ways but for whatever reason never found that issue 🤔 

Cheers!

**Comment by kirawi** [comment] 2023-01-23 20:51
Glad to have helped :p
