### ISSUE TITLE
Undo changes

### ISSUE THREAD

**Issue by Cosmanaute** [helix-editor/helix#7252] opened 2023-06-06 06:23 UTC
I have a recently switched over from using neovim. I really miss the feature of being able to undo changes for the session. With that, I mean still being able to undo earlier changes after quitting and reopening a file with helix. What can I do to implement this?

**Comment by CptPotato** [comment] 2023-06-06 08:57
Persistent undo was/is in the works. See #401 for related info.

**Comment by pascalkuthe** [comment] 2023-06-06 09:04
Duplicate of #401

**Closed by pascalkuthe** 2023-06-06 09:04 UTC
