### ISSUE TITLE
Crash when editing markdown

### ISSUE THREAD

**Issue by rgasper** [helix-editor/helix#9011] opened 2023-12-05 20:21 UTC
### Summary

I'm frequently encountering crashes when editing markdown files. It seems to maybe have something to do with code blocks in particular, but I'm not sure.

This seems similar to #8821

### Reproduction Steps

- Opened a markdown file `hx README.md`:
- added contents like:
  - (sorry this isn't raw text - I'm not sure how to do a markdown code block with code blocks inside...

> # Header
> some text 
> some text
> 
> ## Header2
> do a thing:
> ```python
> import pandas as pd
> df = pd.DataFrame({'a':1})
> ```
> 

It doesn't immediately crash on edit, but this is happening often. Crash has happened to me both in normal mode and in insert mode. Has occurred on markdown files approximately this short. It *seems* to occur in moments when the python syntax inside the code blocks is invalid syntax, but the syntax error is in the middle of the block (not the end).

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
I'm not clear these error messages are associated with the crash, but they happened around the same time.

```
2023-12-05T14:26:59.427 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(350)), original request likely timed out
...
2023-12-05T15:02:07.709 helix_view::editor [ERROR] Failed to initialize the language servers for `source.md` - `marksman` { cannot find binary path }
2023-12-05T15:04:02.831 helix_view::editor [ERROR] Failed to initialize the language servers for `source.md` - `marksman` { cannot find binary path }
2023-12-05T15:10:58.277 helix_view::editor [ERROR] editor error: Register [@] empty
2023-12-05T15:16:38.485 helix_view::editor [ERROR] Failed to initialize the language servers for `source.md` - `marksman` { cannot find binary path }
```

</details>

### Platform

macOS

### Terminal Emulator

kitty

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by the-mikedavis** [comment] 2023-12-05 20:56
What does the panic message say? Or by crash do you mean that Helix is hanging? This might be https://github.com/helix-editor/helix/issues/8709 if it's a hang

**Comment by rgasper** [comment] 2023-12-06 14:19
it's a hang - terminal freezes, accepts no inputs

**Comment by pascalkuthe** [comment] 2023-12-06 14:25
then its almost certainly a duplicate of https://github.com/helix-editor/helix/issues/8709. This is abug in tree-sitter not in helix. If you switch to the helix master branch the bug is fixed because we use an unreleaesd version of TS with a relevant fix.  We just can't do that in official release because package mangers can't deal with that

**Closed** 2023-12-06 14:48 UTC
Labels: C-bug

**Comment by chtenb** [comment] 2024-03-07 11:02
> then its almost certainly a duplicate of #8709. This is abug in tree-sitter not in helix. If you switch to the helix master branch the bug is fixed because we use an unreleaesd version of TS with a relevant fix. We just can't do that in official release because package mangers can't deal with that

@pascalkuthe My personal helix branch is branched off of origin/master from 5 weeks ago, but I'm still experiencing the bug. Would I need to do something special to get the TS fix other than just checking it out and recompiling?

**Comment by pascalkuthe** [comment] 2024-03-07 11:08
it should be automatically fixed, if you have a small reproduction case you can open an issue with that

**Comment by chtenb** [comment] 2024-03-07 11:09
The same reproduction as in https://github.com/helix-editor/helix/issues/8821, i.e. open a list with three nesting levels and the crash is imminent.

**Comment by pascalkuthe** [comment] 2024-03-07 11:13
That is a seperate issue and hence that issue is still open (with a way described to fix it). It has nothing to do with this issue (which is about an endless loop/freeze)

**Comment by chtenb** [comment] 2024-03-07 11:13
My apologies, I misinterpreted the comments in this thread it seems.
