### ISSUE TITLE
jdtls not starting when opening a .java file

### ISSUE THREAD

**Issue by raj23689** [helix-editor/helix#3145] opened 2022-07-22 10:35 UTC
### Summary

I have installed the `jdtls` server using `aur` and checked with `helix --health java ` to make sure it is ok.
```bash
Configured language server: jdtls
Binary for language server: /usr/bin/jdtls
Configured debug adapter: None
Highlight queries: ✔
Textobject queries: ✘
Indent queries: ✘
```

But when I open a .java  file the LSP doesn't start.

### Reproduction Steps

 

I tried this:

1. `helix add.java`

I expected this to happen: autocompletions, definitions to show up by pressing `Space + k`

Instead, this happened: `Language Server not active for the current buffer` showed up in status bar.

After this I also downloaded and extracted the latest `jdlts tar `  Below is my `languages.toml` file

```rust
[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml"]
language-server = { command = "jdtls", args =[ 
    "java", 
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=ALL",
    "-Xms1g",
    "--add-modules=ALL-SYSTEM",
    "--add-opens java.base/java.util=ALL-UNNAMED",
    "--add-opens java.base/java.lang=ALL-UNNAMED",
    "-jar  /home/zack/.cache/jdtls_install/plugins/org.eclipse.equinox.launcher_1.14.0-202207211651.jar",
    "-configuration /home/zack/.cache/jdtls_install/config_linux"
    ] }
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "java"
source = { git = "https://github.com/tree-sitter/tree-sitter-java", rev = "bd6186c24d5eb13b4623efac9d944dcc095c0dad" }

```

But still nothing happened.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-07-22T14:24:17.342 helix_lsp [ERROR] failed to initialize language server: request timed out
2022-07-22T14:34:14.774 helix_term::application [ERROR] Timed out waiting for language servers to shutdown
2022-07-22T14:34:17.043 helix_lsp::transport [ERROR] err <- "Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true\n"
2022-07-22T14:34:17.044 helix_lsp::transport [ERROR] err <- "OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.\n"
2022-07-22T14:34:17.340 helix_lsp::transport [ERROR] err <- "WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector\n"
2022-07-22T14:34:19.927 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-22T14:34:19.927 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-22T14:34:36.667 helix_lsp [ERROR] failed to initialize language server: request timed out
2022-07-22T14:38:42.188 helix_term::application [ERROR] Timed out waiting for language servers to shutdown
2022-07-22T15:35:16.316 helix_lsp::transport [ERROR] err <- "Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true\n"
2022-07-22T15:35:16.316 helix_lsp::transport [ERROR] err <- "OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.\n"
2022-07-22T15:35:16.596 helix_lsp::transport [ERROR] err <- "WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign\n"
2022-07-22T15:35:19.159 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-22T15:35:19.159 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-22T15:35:35.957 helix_lsp [ERROR] failed to initialize language server: request timed out
2022-07-22T15:48:53.379 helix_term::application [ERROR] Timed out waiting for language servers to shutdown
2022-07-22T15:57:33.776 helix_lsp::transport [ERROR] err <- "Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true\n"
2022-07-22T15:57:33.776 helix_lsp::transport [ERROR] err <- "OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.\n"
2022-07-22T15:57:34.094 helix_lsp::transport [ERROR] err <- "WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign\n"
2022-07-22T15:57:36.774 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-22T15:57:36.774 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-22T15:57:53.412 helix_lsp [ERROR] failed to initialize language server: request timed out
```

</details>

### Platform

Axyl Os(ArchLinux)

### Terminal Emulator

kitty

### Helix Version

helix 22.05

**Comment by sudormrfbin** [comment] 2022-07-22 17:35
Reading the log it seems like the LSP requests are timing out, try setting a higher timeout value:

```toml
[[language]]
name = "java"
language-server = { command = "jdtls", timeout = 60, args = [ 
    "java", 
	"...",
    ] }
```

**Comment by raj23689** [comment] 2022-07-23 14:08
> Reading the log it seems like the LSP requests are timing out, try setting a [higher timeout](https://docs.helix-editor.com/master/languages.html?highlight=timeout#language-server-configuration) value:
> 
> ```toml
> [[language]]
> name = "java"
> language-server = { command = "jdtls", timeout = 60, args = [ 
>     "java", 
> 	"...",
>     ] }
> ```

Nope still gives the same error in the log

**Comment by Vixeliz** [comment] 2022-08-18 20:03
I'm also having this issue I think the problem might be jdtls needs a data directory which should be the project root. I may be wrong but it seems helix may not be providing that. Looking at the initial pr that added jdtls as a default it doesn't look like it is passing that arg. This is from the projects homepage:

> Choose a value for -data: An absolute path to your data directory. eclipse.jdt.ls stores workspace specific information in it. This should be unique per workspace/project.

**Comment by raj23689** [comment] 2022-08-28 10:36
> I'm also having this issue I think the problem might be jdtls needs a data directory which should be the project root. I may be wrong but it seems helix may not be providing that. Looking at the initial pr that added jdtls as a default it doesn't look like it is passing that arg. This is from the projects homepage:
> 
> > Choose a value for -data: An absolute path to your data directory. eclipse.jdt.ls stores workspace specific information in it. This should be unique per workspace/project.

Were you able to find any solution to this ?

**Comment by Vixeliz** [comment] 2022-08-28 18:56
> > I'm also having this issue I think the problem might be jdtls needs a data directory which should be the project root. I may be wrong but it seems helix may not be providing that. Looking at the initial pr that added jdtls as a default it doesn't look like it is passing that arg. This is from the projects homepage:
> > 
> > > Choose a value for -data: An absolute path to your data directory. eclipse.jdt.ls stores workspace specific information in it. This should be unique per workspace/project.
> 
> Were you able to find any solution to this ?

The only thing that sometimes would work was setting an absolute data path. Helix doesn't expose any variable for the workspace root so it has to be hard-coded per workspace by creating a folder .helix in the project then a languages.toml with the corresponding changes.

**Comment by Regaez** [comment] 2022-09-06 12:00
@raj23689 I just spent some time struggling with a similar issue. Managed to get it working by creating a new args string every time there's a space. For example, `"--add-opens java.base/java.util=ALL-UNNAMED",` should be two separate strings: 

```
"--add-opens",  
"java.base/java.util=ALL-UNNAMED",
```

Therefore, [per the suggested CLI command](https://github.com/eclipse/eclipse.jdt.ls#running-from-the-command-line), in the `languages.toml` file, it should look more like this:

```
language-server = { command = "java", args = [  
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=ALL",
    "-Xms1g",
    "--add-modules=ALL-SYSTEM",
    "--add-opens",
    "java.base/java.util=ALL-UNNAMED",
    "--add-opens",
    "java.base/java.lang=ALL-UNNAMED",
    "-jar",
    "/home/zack/.cache/jdtls_install/plugins/org.eclipse.equinox.launcher_1.14.0-202207211651.jar",
    "-configuration",
    "/home/zack/.cache/jdtls_install/config_linux"
    "-data",
    "/home/zack/.cache/jdtls_data"
] }
```

---

**NOTE:** If you want to use `jdtls` as the root command, i.e. [using the wrapper script](https://github.com/eclipse/eclipse.jdt.ls#running-from-command-line-with-wrapper-script), then you only need something like the following:

```
language-server = { command = "jdtls", args = [
  "-configuration",
  "/home/zack/.cache/jdtls_install/config_linux",
  "-data",
  "/home/zack/.cache/jdtls_data"
] }
```

The downside of using `jdtls` is that if you use a dependency like [`lombok`](https://projectlombok.org/) in your project, then you'll get LSP errors and missing suggestions from the code lombok would generate, as lombok requires some configuration to come before the `-jar` line (and when you use `jdtls`, the `jar` is loaded automatically for you), e.g.

```diff
language-server = { command = "java", args = [  
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=ALL",
    "-Xms1g",
    "--add-modules=ALL-SYSTEM",
    "--add-opens",
    "java.base/java.util=ALL-UNNAMED",
    "--add-opens",
    "java.base/java.lang=ALL-UNNAMED",
+   "-javaagent:/path/to/lombok.jar",
+   "-Xbootclasspath/a:/path/to/lombok.jar",
    "-jar",
    "/home/zack/.cache/jdtls_install/plugins/org.eclipse.equinox.launcher_1.14.0-202207211651.jar",
    "-configuration",
    "/home/zack/.cache/jdtls_install/config_linux"
    "-data",
    "/home/zack/.cache/jdtls_data"
] }
```

So while more complicated to setup, it might be preferable to use the more explicit configuration if you're going to have such dependencies.

**Comment by pascualex** [comment] 2022-10-03 14:50
I've updated the [wiki](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#java-eclipse-jdt-language-server) to document how to configure jdtls in each project following the advice from @Vixeliz.

**Comment by dead10ck** [comment] 2022-10-03 18:54
If it helps, I made a wrapper script that sets the config and data directories

https://gist.github.com/dead10ck/6a516e4ff27e916c2c2c90d5b4a2a4a3

I did not need all of the many config options in newer versions, since they've switched the `jdtls` Python executable that sets many of those defaults for you.

With this, and following the instructions in the script comments, all you need in your `languages.toml` is

```toml
[[language]]
name = "java"
roots = ["pom.xml", "build.gradle"]
language-server = { command = "jdtls" }
```

**Comment by tron2346** [comment] 2022-10-06 13:53
This seems to have been fixed in latest jdtls version here:
https://github.com/eclipse/eclipse.jdt.ls/issues/2191

**Comment by pascualex** [comment] 2022-10-06 14:22
> This seems to have been fixed in latest jdtls version here: [eclipse/eclipse.jdt.ls#2191](https://github.com/eclipse/eclipse.jdt.ls/issues/2191)

I can confirm that this fixes the problem. Thanks for sharing!

I've updated the wiki.

**Closed as completed** 2022-10-06 14:40 UTC
Labels: C-bug

**Comment by yusuphgammut** [comment] 2024-06-05 01:31
Hey @Regaez @dead10ck . I'm trying to set up jdtls but I've failed miserably trying to make lombok recognize generated classes. So far I've tried adding the `javaagent` arg but the errors about generated classes not being resolved keep appearing. I was wondering if maybe you can give me some advice. I'm using a very recent Helix version on MacOs Sonoma. I've downloaded the latest `lombok.jar` from the website and `jdtls` version via Hombrew, and added a custom `.helix/languages.toml` file to my project, just as @Regaez suggests.

``` toml
[language-server.jdtls]
command = "jdtls"
args = ["--jvm-arg=-javaagent:/Users/myuser/.myconfigs/helix/dependencies/lombok-1.18.32.jar"]
```

I also have `codehaus.mojo` in the projects `pom.xml`:

``` xml
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>build-helper-maven-plugin</artifactId>
	<version>${build.helper.maven.plugin.version}</version>
	<executions>
		<execution>
			<phase>generate-sources</phase>
			<goals>
				<goal>add-source</goal>
			</goals>
			<configuration>
				<sources>
					<source>${project.build.directory}/generated-sources/swagger/src</source>
				</sources>
			</configuration>
		</execution>
	</executions>
</plugin>
```

Do you know about any other things that might affect the processing of generated classes by lombok that I should look after? Excuse my somewhat vague question. I'm getting used to the Java ecosystem and this has been a bit frustrating.
