### ISSUE TITLE
Panic when type '<' during editing the Rust code

### ISSUE THREAD

**Issue by cgfork** [helix-editor/helix#3146] opened 2022-07-22 11:12 UTC
### Summary

Panic when type '<' after `Validator` during editing the Rust code.

```rust
pub trait Validator {
    type Err;

    fn validate<I: AsRef<str>>(&self, input: I) -> Result<(), Self::Err>;
}

pub enum ValidatorKind {
    Predefined(String),
    Regex(String),
    Extend(Box<dyn Validator>),
}
```

### Reproduction Steps

see Summary

### Helix log

empty helix log

RUST_BACKTRACE:
```
thread 'main' panicked at 'byte index 23 is not a char boundary; it is inside '…' (bytes 22..25) of `trait Validator<Err = …>`', library/core/src/str/mod.rs:127:5
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::str::slice_error_fail_rt
   3: core::ops::function::FnOnce::call_once
   4: core::intrinsics::const_eval_select
   5: core::str::slice_error_fail
   6: helix_term::ui::markdown::highlighted_code_block
   7: <helix_term::ui::lsp::SignatureHelp as helix_term::compositor::Component>::render
   8: helix_term::compositor::Compositor::render
   9: helix_term::application::Application::event_loop_until_idle::{{closure}}
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: std::thread::local::LocalKey<T>::with
  12: tokio::park::thread::CachedParkThread::block_on
  13: tokio::runtime::thread_pool::ThreadPool::block_on
  14: tokio::runtime::Runtime::block_on
  15: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Platform

macOS

### Terminal Emulator

wezterm/iterm2

### Helix Version

helix 22.05 (76756f0e)

**Comment by cgfork** [comment] 2022-07-22 13:15
https://github.com/helix-editor/helix/blob/19e51c826411352c42a035cbe274d466b7cda5fe/helix-term/src/ui/markdown.rs#L83

The byte index 'end' is not a char boundary

**Comment by kirawi** [comment] 2022-07-22 14:18
Looks to be caused by the signature help.

**Comment by sudormrfbin** [comment] 2022-07-22 15:24
Duplicate of #3120.

**Closed by sudormrfbin** 2022-07-22 15:24 UTC
Labels: C-bug, A-helix-term
