### ISSUE TITLE
Implement synchronized renders (CSI 2026)

### ISSUE THREAD

**Issue by nilsherzig** [helix-editor/helix#11581] opened 2024-08-26 20:33 UTC
### the problem

Cross post from zellij (terminal multiplexer). 

https://github.com/zellij-org/zellij/issues/3368

Using helix inside Zellij results in sometimes showing partly rendered pages "screen tearing", especially noticeable during actions which affect the whole screen, like changing files or themes. The original issue has a screen recording showing the problem. 

### possible solution

The latest comment on the original issue suggests implementing something called CSI 2026. 

CSI explained, [quoted from [this gist](https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036):

> When rendering the screen of the terminal, the Emulator usually iterates through each visible grid cell and renders its current state. With applications updating the screen a at higher frequency this can cause tearing.

> This mode attempts to mitigate that.

> When the synchronization mode is enabled following render calls will keep rendering the last rendered state. The terminal Emulator keeps processing incoming text and sequences. When the synchronized update mode is disabled again the renderer may fetch the latest screen buffer state again, effectively avoiding the tearing effect by unintentionally rendering in the middle a of an application screen update.

**Comment by the-mikedavis** [comment] 2024-08-26 20:50
Duplicate of https://github.com/helix-editor/helix/issues/731

**Closed by the-mikedavis** 2024-08-26 20:50 UTC
Labels: C-enhancement

**Comment by nilsherzig** [comment] 2024-08-27 09:13
Oh, I'm sorry, I only searched for "synchronized renders" and csi.
