### ISSUE TITLE
Python LSP: auto-completion crushes

### ISSUE THREAD

**Issue by Dimonoy** [helix-editor/helix#11283] opened 2024-07-23 13:10 UTC
### Summary

Excuse my illiteracy, I am not really familiar with some terminologies.

Editing python file in Django project. When I open file and perform auto-completion <tab> on the first attempt, it works, but on the second attempt it crushes:
```
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ropey-1.6.1/src/slice.rs:656:9:
Attempt to slice past end of RopeSlice: slice end 399, RopeSlice length 398
stack backtrace:
   0:     0x56ce7ff3ea11 - <unknown>
   1:     0x56ce7f21a01c - <unknown>
   2:     0x56ce7ff3a80e - <unknown>
   3:     0x56ce7ff3e7f4 - <unknown>
   4:     0x56ce7ff40533 - <unknown>
   5:     0x56ce7ff40271 - <unknown>
   6:     0x56ce7ff40b74 - <unknown>
   7:     0x56ce7ff4091e - <unknown>
   8:     0x56ce7ff3eee6 - <unknown>
   9:     0x56ce7ff406c2 - <unknown>
  10:     0x56ce7f11b075 - <unknown>
  11:     0x56ce7f64e903 - <unknown>
  12:     0x56ce7f654bd1 - <unknown>
  13:     0x56ce7f9106b4 - <unknown>
  14:     0x56ce7f75422c - <unknown>
  15:     0x56ce7f7557b1 - <unknown>
  16:     0x56ce7fa505a7 - <unknown>
  17:     0x56ce7fa4bed2 - <unknown>
  18:     0x56ce7f75349a - <unknown>
  19:     0x56ce7fcaef39 - <unknown>
  20:     0x56ce7fcc3e8d - <unknown>
  21:     0x56ce7fd587db - <unknown>
  22:     0x56ce7fd180b3 - <unknown>
  23:     0x56ce7fd0c573 - <unknown>
  24:     0x56ce7fcfc4dd - <unknown>
  25:     0x56ce7ff323cf - <unknown>
  26:     0x56ce7fd181a5 - <unknown>
  27:     0x7ea7649e81ca - <unknown>
  28:     0x7ea7649e828b - __libc_start_main
  29:     0x56ce7f196e85 - <unknown>
  30:                0x0 - <unknown>
  ```

**Note.**
There is another strange behavior. In my case, everything is attempted on the first auto-completion. When trying to autocomplete a standalone variable/module, everything works as intended. However, when trying to autocomplete a sub-module (for example: `os.pat` $\rightarrow$ `os.path`), it turns out to select everything from the beginning of the sub-module until the 2nd letter from the end of the word (**os.pat**|h, where bold text represents selection and | represents the cursor in a typing mode).

### Reproduction Steps

 

I tried this:

1. `hx file.py`
2. Press <tab> to autocomplete (anything)
3. Press <tab> to autocomplete (anything) second time $\rightarrow$

I expected this to happen:

Helix to not crush when using LSP server auto-completion.

Instead, this happened:

Helix closes, showing the error message provided above in the Summary section.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-07-23T21:57:31.324 globset [DEBUG] glob converted to regex: Glob { glob: "*/Dockerfile.*", re: "(?-u)^.*/Dockerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('D'), Literal('o'), Literal('c'), Literal('k'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-07-23T21:57:31.324 globset [DEBUG] glob converted to regex: Glob { glob: "*/dockerfile.*", re: "(?-u)^.*/dockerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('d'), Literal('o'), Literal('c'), Literal('k'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-07-23T21:57:31.324 globset [DEBUG] glob converted to regex: Glob { glob: "*/Containerfile.*", re: "(?-u)^.*/Containerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('C'), Literal('o'), Literal('n'), Literal('t'), Literal('a'), Literal('i'), Literal('n'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-07-23T21:57:31.324 globset [DEBUG] glob converted to regex: Glob { glob: "*/containerfile.*", re: "(?-u)^.*/containerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('c'), Literal('o'), Literal('n'), Literal('t'), Literal('a'), Literal('i'), Literal('n'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-07-23T21:57:31.324 globset [DEBUG] glob converted to regex: Glob { glob: "*/.*ignore", re: "(?-u)^.*/\\..*ignore$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('.'), ZeroOrMore, Literal('i'), Literal('g'), Literal('n'), Literal('o'), Literal('r'), Literal('e')]) }
2024-07-23T21:57:31.324 globset [DEBUG] glob converted to regex: Glob { glob: "*/BUILD.*", re: "(?-u)^.*/BUILD\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('B'), Literal('U'), Literal('I'), Literal('L'), Literal('D'), Literal('.'), ZeroOrMore]) }
2024-07-23T21:57:31.324 globset [DEBUG] glob converted to regex: Glob { glob: "*/.env.*", re: "(?-u)^.*/\\.env\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('.'), Literal('e'), Literal('n'), Literal('v'), Literal('.'), ZeroOrMore]) }
2024-07-23T21:57:31.324 globset [DEBUG] glob converted to regex: Glob { glob: "*/.envrc.*", re: "(?-u)^.*/\\.envrc\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('.'), Literal('e'), Literal('n'), Literal('v'), Literal('r'), Literal('c'), Literal('.'), ZeroOrMore]) }
2024-07-23T21:57:31.325 globset [DEBUG] glob converted to regex: Glob { glob: "*/conf/*/*.{inc,conf}", re: "(?-u)^.*/conf/.*/.*\\.(?:conf|inc)$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('c'), Literal('o'), Literal('n'), Literal('f'), Literal('/'), ZeroOrMore, Literal('/'), ZeroOrMore, Literal('.'), Alternates([Tokens([Literal('c'), Literal('o'), Literal('n'), Literal('f')]), Tokens([Literal('i'), Literal('n'), Literal('c')])])]) }
2024-07-23T21:57:31.325 globset [DEBUG] built glob set; 1 literals, 0 basenames, 0 extensions, 0 prefixes, 128 suffixes, 9 required extensions, 9 regexes
2024-07-23T21:57:31.328 helix_view::clipboard [DEBUG] Using xclip to interact with the system and selection (primary) clipboard
2024-07-23T21:57:31.328 helix_tui::backend::crossterm [DEBUG] The keyboard enhancement protocol is not supported in this terminal (checked in 260.492µs)
2024-07-23T21:57:31.328 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:31.329 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:31.579 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T21:57:32.182 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:32.300 globset [DEBUG] glob converted to regex: Glob { glob: "*.{zip,gz,bz2,zst,lzo,sz,tgz,tbz2,lz,lz4,lzma,lzo,z,Z,xz,7z,rar,cab}", re: "(?-u)^[^/]*\\.(?:cab|rar|7z|xz|Z|z|lzo|lzma|lz4|lz|tbz2|tgz|sz|lzo|zst|bz2|gz|zip)$", opts: GlobOptions { case_insensitive: false, literal_separator: true, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('.'), Alternates([Tokens([Literal('c'), Literal('a'), Literal('b')]), Tokens([Literal('r'), Literal('a'), Literal('r')]), Tokens([Literal('7'), Literal('z')]), Tokens([Literal('x'), Literal('z')]), Tokens([Literal('Z')]), Tokens([Literal('z')]), Tokens([Literal('l'), Literal('z'), Literal('o')]), Tokens([Literal('l'), Literal('z'), Literal('m'), Literal('a')]), Tokens([Literal('l'), Literal('z'), Literal('4')]), Tokens([Literal('l'), Literal('z')]), Tokens([Literal('t'), Literal('b'), Literal('z'), Literal('2')]), Tokens([Literal('t'), Literal('g'), Literal('z')]), Tokens([Literal('s'), Literal('z')]), Tokens([Literal('l'), Literal('z'), Literal('o')]), Tokens([Literal('z'), Literal('s'), Literal('t')]), Tokens([Literal('b'), Literal('z'), Literal('2')]), Tokens([Literal('g'), Literal('z')]), Tokens([Literal('z'), Literal('i'), Literal('p')])])]) }
2024-07-23T21:57:32.300 globset [DEBUG] built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 1 regexes
2024-07-23T21:57:32.300 helix_term::ui [DEBUG] file_picker init 427.015µs
2024-07-23T21:57:32.301 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:32.551 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T21:57:32.551 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:32.657 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:32.738 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:32.827 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:32.902 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:33.154 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T21:57:33.154 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:33.172 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:33.376 helix_vcs [DEBUG] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/home/anythen/Projects/djapp/website",
        },
    ),
}
2024-07-23T21:57:33.376 helix_vcs [DEBUG] failed to open diff base for /home/anythen/Projects/djapp/website/manage.py
2024-07-23T21:57:33.376 helix_vcs [DEBUG] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/home/anythen/Projects/djapp/website",
        },
    ),
}
2024-07-23T21:57:33.376 helix_vcs [DEBUG] failed to obtain current head name for /home/anythen/Projects/djapp/website/manage.py
2024-07-23T21:57:33.376 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T21:57:33.376 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"positionEncodings":["utf-8","utf-32","utf-16"]},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"isPreferredSupport":true,"resolveSupport":{"properties":["edit","command"]}},"completion":{"completionItem":{"deprecatedSupport":true,"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{}},"formatting":{"dynamicRegistration":false},"hover":{"contentFormat":["markdown"]},"inlayHint":{"dynamicRegistration":false},"publishDiagnostics":{"tagSupport":{"valueSet":[1,2]},"versionSupport":true},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":true},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":false},"executeCommand":{"dynamicRegistration":false},"fileOperations":{"didRename":true,"willRename":true},"inlayHint":{"refreshSupport":false},"symbol":{"dynamicRegistration":false},"workspaceEdit":{"documentChanges":true,"failureHandling":"abort","normalizesLineEndings":false,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"helix","version":"24.7 (079f5442)"},"processId":121729,"rootPath":"/home/anythen/Projects/djapp/website","rootUri":null,"workspaceFolders":[]},"id":0}
2024-07-23T21:57:33.377 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2024-07-23T21:57:33.587 helix_lsp::transport [INFO] pylsp <- {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"documentFormattingProvider":true,"documentHighlightProvider":true,"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"definitionProvider":true,"executeCommandProvider":{"commands":[]},"hoverProvider":true,"referencesProvider":true,"renameProvider":true,"foldingRangeProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","="]},"textDocumentSync":{"change":2,"save":{"includeText":true},"openClose":true},"notebookDocumentSync":{"notebookSelector":[{"cells":[{"language":"python"}]}]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"experimental":{}},"serverInfo":{"name":"pylsp","version":"1.10.0"}}}
2024-07-23T21:57:33.587 helix_lsp::transport [INFO] pylsp <- {"capabilities":{"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":[]},"experimental":{},"foldingRangeProvider":true,"hoverProvider":true,"notebookDocumentSync":{"notebookSelector":[{"cells":[{"language":"python"}]}]},"referencesProvider":true,"renameProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","="]},"textDocumentSync":{"change":2,"openClose":true,"save":{"includeText":true}},"workspace":{"workspaceFolders":{"changeNotifications":true,"supported":true}}},"serverInfo":{"name":"pylsp","version":"1.10.0"}}
2024-07-23T21:57:33.587 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"initialized","params":{}}
2024-07-23T21:57:33.587 helix_term::application [DEBUG] received editor event: LanguageServerMessage((LanguageServerId(1v1), Notification(Notification { jsonrpc: None, method: "initialized", params: None })))
2024-07-23T21:57:33.587 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"python","text":"#!/usr/bin/env python\n\"\"\"Django's command-line utility for administrative tasks.\"\"\"\nimport os\nimport sys\n\n\ndef main():\n    \"\"\"Run administrative tasks.\"\"\"\n    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'website.settings')\n    try:\n        from django.core.management import execute_from_command_line\n    except ImportError as exc:\n        raise ImportError(\n            \"Couldn't import Django. Are you sure it's installed and \"\n            \"available on your PYTHONPATH environment variable? Did you \"\n            \"forget to activate a virtual environment?\"\n        ) from exc\n    execute_from_command_line(sys.argv)\n\n\nif __name__ == '__main__':\n    main()\n","uri":"file:///home/anythen/Projects/djapp/website/manage.py","version":0}}}
2024-07-23T21:57:33.622 helix_term::application [DEBUG] received editor event: Redraw
2024-07-23T21:57:33.622 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2024-07-23T21:57:33.627 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T21:57:33.738 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2024-07-23T21:57:33.990 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T21:57:34.082 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2024-07-23T21:57:34.088 helix_lsp::transport [INFO] pylsp <- {"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"file:\/\/\/home\/anythen\/Projects\/djapp\/website\/manage.py","diagnostics":[]}}
2024-07-23T21:57:34.088 helix_term::application [DEBUG] received editor event: LanguageServerMessage((LanguageServerId(1v1), Notification(Notification { jsonrpc: Some(V2), method: "textDocument/publishDiagnostics", params: Map({"diagnostics": Array [], "uri": String("file:///home/anythen/Projects/djapp/website/manage.py")}) })))
2024-07-23T21:57:34.123 helix_term::application [DEBUG] received editor event: Redraw
2024-07-23T21:57:34.123 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2024-07-23T21:57:34.129 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2024-07-23T21:57:34.380 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T21:57:34.540 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":10,"line":21},"start":{"character":10,"line":21}},"text":"\n    "}],"textDocument":{"uri":"file:///home/anythen/Projects/djapp/website/manage.py","version":1}}}
2024-07-23T21:57:34.541 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2024-07-23T21:57:34.662 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"textDocument/signatureHelp","params":{"position":{"character":4,"line":22},"textDocument":{"uri":"file:///home/anythen/Projects/djapp/website/manage.py"}},"id":1}
2024-07-23T21:57:34.662 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2024-07-23T21:57:34.773 helix_lsp::transport [INFO] pylsp <- {"jsonrpc":"2.0","id":1,"result":{"signatures":[]}}
2024-07-23T21:57:34.773 helix_lsp::transport [INFO] pylsp <- {"signatures":[]}
2024-07-23T21:57:34.773 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2024-07-23T21:57:34.789 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T21:57:34.852 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":4,"line":22},"start":{"character":4,"line":22}},"text":"o"}],"textDocument":{"uri":"file:///home/anythen/Projects/djapp/website/manage.py","version":2}}}
2024-07-23T21:57:34.852 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2024-07-23T21:57:34.934 helix_lsp::transport [INFO] pylsp -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":5,"line":22},"start":{"character":5,"line":22}},"text":"s"}],"textDocument":{"uri":"file:///home/anythen/Projects/djapp/website/manage.py","version":3}}}
2024-07-23T21:57:34.935 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
```

</details>

### Platform

Linux

### Terminal Emulator

GNOME Terminal 3.52.0

### Installation Method

snap 2.63+24.04 (Ubuntu 24.04 LTS)

### Helix Version

helix 24.7 (079f5442)

**Comment by kirawi** [comment] 2024-07-23 13:19
Duplicate of https://github.com/helix-editor/helix/issues/10689

**Closed by kirawi** 2024-07-23 13:19 UTC
Labels: C-bug
