### ISSUE TITLE
Autocomplete don't work with multiple cursors

### ISSUE THREAD

**Issue by IvanGoncharov** [helix-editor/helix#3498] opened 2022-08-21 18:47 UTC
### Summary

If I go into insert mode on multiple cursors, autocomplete will change only the active cursor.

### Reproduction Steps

[![asciicast](https://asciinema.org/a/8KR4afLnhlvsb4xinuKWe3UmZ.svg)](https://asciinema.org/a/8KR4afLnhlvsb4xinuKWe3UmZ)

### Helix log

Nothing was written in the log

### Platform

MacOs

### Terminal Emulator

iTerm2

### Helix Version

22.05-393-g8deaebde

**Comment by the-mikedavis** [comment] 2022-08-21 20:26
Duplicate of https://github.com/helix-editor/helix/issues/2016

**Closed by the-mikedavis** 2022-08-21 20:26 UTC
Labels: C-bug
