### ISSUE TITLE
Greek symbols, mathematics unicode and emojies

### ISSUE THREAD

**Issue by henrysheehy** [helix-editor/helix#9506] opened 2024-02-03 00:16 UTC
Great editor!

I'd like to ask if it's possible to implement Greek symbols, mathematics unicode and emojies? If not, I will do so at at the level of the keyboard input, but I would prefer Helix, for its autocompletion and hints.

Thanks!

**Comment by pascalkuthe** [comment] 2024-02-03 01:09
Duplicate of #1438 I personally do think this is better solved at the keyboard level or potentially snippets/abnreviations in the future

**Closed by pascalkuthe** 2024-02-03 01:09 UTC
Labels: C-enhancement
