### ISSUE TITLE
Deleting the directory of a file that is currently opened in Helix causes a panic

### ISSUE THREAD

**Issue by Endode** [helix-editor/helix#5311] opened 2022-12-27 02:30 UTC
### Summary

Running ```rm v_test/ -rf``` externally (another terminal) whilst Helix had a file open from that directory.

I was messing with the V programming language, I had a directory called "v_test" that contained a file called "main.v".
Helix had the "main.v" file open, I deleted the "v_test" directory using another terminal.
Helix panicked
```
thread 'main' panicked at 'couldn't determine current directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', helix-core/src/path.rs:86:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Steps

I tried this:

Running ```rm v_test/ -rf``` from another terminal whilst Helix had a file open from that directory

I expected this to happen:

No panic, maybe an error message saying that the file or directory doesn't exist anymore. Maybe an option for Helix to create that directory and/or file for you.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-12-26T21:13:32.002 helix_lsp::transport [ERROR] Discarding Language Server response without a request (id=Num(38)) Ok(Null)
2022-12-26T21:13:39.098 helix_lsp::transport [ERROR] Discarding Language Server response without a request (id=Num(42)) Ok(Null)
2022-12-26T21:15:12.120 helix_lsp::transport [ERROR] err: <- Other(failed to send a message to server

Caused by:
    channel closed)
2022-12-26T21:15:12.120 helix_lsp::transport [ERROR] err: <- StreamClosed

```

</details>

### Platform

Linux

### Terminal Emulator

alacritty

### Helix Version

helix 22.12

**Comment by the-mikedavis** [comment] 2022-12-27 14:48
Duplicate of https://github.com/helix-editor/helix/issues/2527

**Closed by the-mikedavis** 2022-12-27 14:48 UTC
Labels: C-bug
