### ISSUE TITLE
Highlight all searches

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#3834] opened 2022-09-13 12:14 UTC
I tried to search for a similar issue but could not find one.

When a search is done for any word only the first occurence is highlighted. On
pressing `n` the next word will be highlighted.

The idea is to highlight all the matches but highlighting current one with with
a different bg color. This is very helpful, especially while using regex.

**Comment by kirawi** [comment] 2022-09-13 14:01
This looks like a duplicate of https://github.com/helix-editor/helix/issues/1733 :P

It can be hard to sift through the issues, so no worries.

**Closed by kirawi** 2022-09-13 14:01 UTC
Labels: C-enhancement

**Comment by zim0369** [comment] 2022-09-13 15:50
> This looks like a duplicate of https://github.com/helix-editor/helix/issues/1733 :P
> 
> It can be hard to sift through the issues, so no worries.

That title is almost same. I should've found it quite easily but didn't... Idk why.
