### ISSUE TITLE
Add documentation to nested keymaps

### ISSUE THREAD

**Issue by adrian-budau-ogreai** [helix-editor/helix#4230] opened 2022-10-12 16:29 UTC
Currently only the original keymaps have documentation added to them. It would be useful though if we could do something like the following:

```
[keys.normal.space.c]
doc = "Custom space"
a = "some_command_here" 

# Extra
[keys.normal.space.c.b]
doc = "Special command nested in others"
command = "some_other_command_here"
```

The toml parsing already supports all this so it's just a little bit of code added in keymap parsing, which I'm happy to contribute assuming this sounds like something that is useful?

The extra case where you can have both doc and command is assuming you don't have other nested fields (it's a leaf command) and is probably less useful much useful than non-leaf docs, though it would be nice for when you share keymaps with people not yet knowing what all commands do.

**Comment by the-mikedavis** [comment] 2022-10-12 16:33
Duplicate of https://github.com/helix-editor/helix/issues/1752

**Closed by the-mikedavis** 2022-10-12 16:33 UTC
Labels: C-enhancement
