### ISSUE TITLE
what wrong with rust nightly 

### ISSUE THREAD

**Issue by djemilbakhti** [helix-editor/helix#12234] opened 2024-12-10 15:58 UTC
[Screencast_20241210_165226.webm](https://github.com/user-attachments/assets/fd870eba-d2bd-4423-8716-efaedf946e79)

**Comment by pascalkuthe** [comment] 2024-12-10 16:00
Duplicate of #12119 

This is being fixed on the RA side (updating your nightly to yesterday's build should be enough)

**Closed by pascalkuthe** 2024-12-10 16:00 UTC
