### ISSUE TITLE
buildin helix-gpt etc code assistant 

### ISSUE THREAD

**Issue by fastfading** [helix-editor/helix#10488] opened 2024-04-17 02:16 UTC
https://github.com/leona/helix-gpt

code assistant is essential these days  .
please build in this tool or any other gpt tools.
or at least provide a convinient way or guide to install it .

**Comment by kirawi** [comment] 2024-04-17 02:46
Duplicate of https://github.com/helix-editor/helix/issues/1927

**Closed by kirawi** 2024-04-17 02:46 UTC
Labels: C-enhancement
