### ISSUE TITLE
Add paragraph + indenation text object/motion

### ISSUE THREAD

**Issue by wurosh** [helix-editor/helix#1580] opened 2022-01-26 03:07 UTC
These are very simple to define (by whitespace) and often reflect logical groupings that are not part of a programming language's grammar (not Treesitter's domain).

I tend to put lines of code that are related together, and I do my best to indent things semantically. I think this applies to most programmers across all filetypes so it makes sense as language-agnostic functionality.

**Comment by archseer** [comment] 2022-01-26 03:15
> very simple to define

Actually, there was quite a bit of work to get it working properly: https://github.com/helix-editor/helix/pull/784

@pickfire is going to do another pass at it.

Partly duplicate of https://github.com/helix-editor/helix/issues/753

**Comment by wurosh** [comment] 2022-01-26 06:52
@archseer my mistake, I didn't mean that it would be easy from an implementation standpoint. What I meant to say was that it is very easy to unambiguously define across languages, i.e.:
- a paragraph is all text between two consecutive newlines
- an "indentation" is a contiguous portion of text (possibly separated by newlines) preceded by an identical sequence of non-newline whitespace characters.

**Comment by pickfire** [comment] 2022-01-26 14:16
Yes, the first implementation I want it to be in a behavior that I would like to use, but it end up being more complicated that I thought, so I guess I am just gonna port kakoune's implementation over.

But lately I am busy, I really like this feature too so I guess I need to speed on this since someone is requesting it too.

**Comment by wurosh** [comment] 2022-01-27 02:03
@pickfire kakoune's implementation sounds great to me. Which differences did you originally plan to implement?

Honestly, the absence of this and [searching with an interactive prompt](https://github.com/helix-editor/helix/issues/196#issuecomment-968193504) are the only things that still have me occasionally opening Vim, and I'd say that's pretty impressive for an editor this young. Keep up the good work!

**Comment by pickfire** [comment] 2022-01-31 09:57
> @pickfire kakoune's implementation sounds great to me. Which differences did you originally plan to implement?

When you select paragraph from the end of the file, it will select the last paragraph with previous whitespace, kakoune does not do that but vim do that.

**Closed** 2022-04-02 15:46 UTC
Labels: C-enhancement, A-tree-sitter
