### ISSUE TITLE
Close buffer from buffer picker

### ISSUE THREAD

**Issue by Ha5hBr0wn** [helix-editor/helix#7259] opened 2023-06-06 16:05 UTC
Don't know if there is a way to do this or not already, but I would like to be able to close a buffer from the buffer picker rather than having to use :bc or :bc!

**Comment by the-mikedavis** [comment] 2023-06-06 16:14
Duplicate of https://github.com/helix-editor/helix/issues/1593

**Closed by the-mikedavis** 2023-06-06 16:14 UTC
Labels: C-enhancement
