### ISSUE TITLE
In select mode, remapped movement key binds act as in normal mode

### ISSUE THREAD

**Issue by rdvdev2** [helix-editor/helix#4711] opened 2022-11-11 10:12 UTC
### Summary

Remapping the movement keys (h/k/j/l) in selection mode makes them act as in normal mode (i.e. the selection isn't sticky, and the cursor just moves). With the standard mappings, this doesn't happen.

Note: Arrow keys work as intended.

### Reproduction Steps

I tried this:

1. `hx`
2. `:config-open`
3. Use this configuration:
```toml
[keys.normal]
h = "move_char_left"
n = "move_char_right"
l = "move_line_up"
k = "move_line_down"
"ret" = "search_next"
"backspace" = "search_prev"

[keys.select]
h = "move_char_left"
n = "move_char_right"
l = "move_line_up"
k = "move_line_down"
"ret" = "search_next"
"backspace" = "search_prev"
```
3. `:config-reload`
4. `vnnnnnn`

I expected this to happen: 7 characters should be selected

Instead, this happened: 1 character is selected

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-11-11T11:09:45.592 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
```

</details>

### Platform

Linux (Arch)

### Terminal Emulator

alacritty 0.11.0 (8dbaa0bb)

### Helix Version

helix 22.08.1

**Comment by the-mikedavis** [comment] 2022-11-11 13:18
Duplicate of https://github.com/helix-editor/helix/issues/2200

See the definition for hjkl in select mode here: https://github.com/helix-editor/helix/blob/7367abd6c6f764b45802613ca9c46e921b4394e6/helix-term/src/keymap/default.rs#L317-L320

The commands should be `extend_` instead of `move_`

**Closed by the-mikedavis** 2022-11-11 13:18 UTC
Labels: C-bug

**Comment by rdvdev2** [comment] 2022-11-11 16:45
Oh I see. I think the online docs don't mention this, maybe that's the real issue. Thank you!
