### ISSUE TITLE
Use LSP Semantic Syntax Highlighting

### ISSUE THREAD

**Issue by Lohann** [helix-editor/helix#8438] opened 2023-10-01 15:58 UTC
tree-sitter is great, but only LSP can enable consistent highlighting, example using rust:

## Helix:
Issues:
- **U256** is a struct (blue), but when imported is wrongly highlighted as a `constant` (purple).
- Methods when imported are highlighted as a `module` (white) instead `method` (green).

<img width="787" alt="Screenshot 2023-10-01 at 12 46 06" src="https://github.com/helix-editor/helix/assets/4323004/8a2b7fb4-893e-4ae2-90f7-e1e5f325082e">

## VSCode
The same code is correctly highlighted in VSCode and RustRover
<img width="742" alt="Screenshot 2023-10-01 at 12 52 31" src="https://github.com/helix-editor/helix/assets/4323004/9960ce24-8af0-4b37-bb8b-b729a730686c">

## Feature Request
Use rust-analyzer semantic syntax highlighting:
https://github.com/rust-lang/rust-analyzer/blob/2023-09-25/crates/ide/src/syntax_highlighting.rs#L65-L182

**Comment by kirawi** [comment] 2023-10-01 16:08
Duplicate of https://github.com/helix-editor/helix/discussions/5589

**Closed by kirawi** 2023-10-01 16:08 UTC
Labels: C-enhancement
