### ISSUE TITLE
LSP Message Covers Written Text

### ISSUE THREAD

**Issue by faisaal99** [helix-editor/helix#11886] opened 2024-10-14 15:47 UTC
System: Linux Arch (ver. 6.11.3-arch1-1)
Terminal Shell: bash 5.2.37

Whenever the LSP of a language outputs a warning/error message, the message covers the text that you're currently working on. Inspect image below:

![image](https://github.com/user-attachments/assets/9d73204b-bac5-46eb-b34b-65ab58e54f1d)

Personally, I don't mind this if I'm not actively working on that piece of text. But, like in the screenshot, if I am, it's really annoying. I'd like it if the LSP message would disappear while I am in INSERT mode, and re-appear when I enter NORMAL.

**Comment by the-mikedavis** [comment] 2024-10-14 16:03
Duplicate of #1462

If you build from source you can enable inline diagnostics now, also see #6417

**Closed by the-mikedavis** 2024-10-14 16:03 UTC
Labels: C-enhancement
