### ISSUE TITLE
Terminal caret settings not reset after closing helix

### ISSUE THREAD

**Issue by Tubbles** [helix-editor/helix#5364] opened 2023-01-02 09:32 UTC
### Summary

Helix does not restore the terminal caret style upon exit

Might be a good idea to also double check if there are any other terminal settings that get changed that should be reverted?

### Reproduction Steps

I tried this:

1. Change terminal caret style to eg. I-bar `printf '\033[6 q'`
2. Start helix `hx`/`helix`
3. Exit helix `:q`

I expected this to happen:

- Caret style is I-bar

Instead, this happened:

- Caret style is block

### Helix log

Log file did not catch anything (empty)

### Platform

Linux

### Terminal Emulator

st

### Helix Version

helix 22.12

**Comment by the-mikedavis** [comment] 2023-01-02 12:40
Duplicate of https://github.com/helix-editor/helix/issues/2684

**Closed by the-mikedavis** 2023-01-02 12:40 UTC
Labels: C-bug
