### ISSUE TITLE
Current state of the Plugin System

### ISSUE THREAD

**Issue by trueegorletov** [helix-editor/helix#5194] opened 2022-12-17 15:01 UTC
Hello!

I love Helix project and that's really amazing to watch how the editor grows day by day, but with current circumstances it is very difficult to completely move to Helix for all everyday tasks due to total lack of any sort of pluginning support.

As far as I know, this is a pretty long story, but I (and more other people) would like to know, what is current state of the Plugin System? Since the approach to implement it was chosen there is no any information about progress in making it real (and getting it for a non-contributor turns difficult).

Is there any roadmap in plans, that could give us at least very and very approximate terms it can come in sight?

Thanks.

**Comment by archseer** [comment] 2022-12-17 15:10
Duplicate of https://github.com/helix-editor/helix/discussions/3806

No public road map since we're all volunteers with varying amounts of free time. I'm doing some prototyping over the holidays but I can't promise any timelines.

**Closed** 2022-12-17 15:31 UTC
