### ISSUE TITLE
panic when rename reference with LSP (jdtls) two windows open

### ISSUE THREAD

**Issue by rodrigopim** [helix-editor/helix#9911] opened 2024-03-17 19:08 UTC
### Summary

thread 'main' panicked at helix-core/src/transaction.rs:461:9:
Positions [(3100, After), (3101, Before)] are out of range for changeset len 2389!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Reproduction Steps

I tried rename reference (space + r) on java project when using two windows, various buffers open. This works well, but this time a dont know whats happen. In other pane, other helix instance, with angular project it stay works.

### Helix log

Last 200 lines

```
2024-03-14T16:57:46.316 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T16:57:46.335 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registra
tion is not enabled. Please report this upstream to the language server
2024-03-14T16:57:46.335 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T20:35:14.307 helix_lsp::client [WARN] language server failed to terminate gracefully - server closed the stream
2024-03-14T20:35:14.307 helix_lsp::transport [ERROR] vscode-html-language-server err: <- IO(Os { code: 32, kind: BrokenPipe, message: "
Broken pipe" })
2024-03-14T20:35:14.308 helix_lsp::transport [ERROR] vscode-html-language-server err: <- StreamClosed
2024-03-14T20:35:14.315 helix_lsp::client [WARN] language server failed to terminate gracefully - failed to parse: invalid type: map, e
xpected unit
2024-03-14T20:35:14.321 helix_lsp::transport [ERROR] vscode-json-language-server err: <- StreamClosed
2024-03-14T20:35:14.322 helix_lsp::client [WARN] language server failed to terminate gracefully - server closed the stream
2024-03-14T20:35:14.322 helix_lsp::transport [ERROR] vscode-json-language-server err: <- IO(Os { code: 32, kind: BrokenPipe, message: "
Broken pipe" })
2024-03-14T20:35:14.326 helix_lsp::transport [ERROR] typescript-language-server err: <- StreamClosed
2024-03-14T20:35:14.328 helix_lsp::client [WARN] language server failed to terminate gracefully - server closed the stream
2024-03-14T20:35:14.333 helix_lsp::transport [ERROR] vscode-html-language-server err: <- StreamClosed
2024-03-14T20:35:14.333 helix_lsp::client [WARN] language server failed to terminate gracefully - server closed the stream
2024-03-14T20:35:14.337 helix_lsp::transport [ERROR] vscode-html-language-server err: <- IO(Os { code: 32, kind: BrokenPipe, message: "
Broken pipe" })
2024-03-14T21:25:59.303 helix_lsp::transport [ERROR] jdtls err <- "WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubato
r.foreign\n"
2024-03-14T21:26:00.332 helix_lsp::transport [ERROR] jdtls err <- "Mar 14, 2024 9:26:00 PM org.apache.aries.spifly.BaseActivator log\n"
2024-03-14T21:26:00.332 helix_lsp::transport [ERROR] jdtls err <- "INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServ
letContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic\n"
2024-03-14T21:26:00.336 helix_lsp::transport [ERROR] jdtls err <- "Mar 14, 2024 9:26:00 PM org.apache.aries.spifly.BaseActivator log\n"
2024-03-14T21:26:00.336 helix_lsp::transport [ERROR] jdtls err <- "INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceP
rovider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic\n"
2024-03-14T21:26:04.275 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:04.276 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:06.376 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:06.576 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:10.853 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:11.460 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:16.411 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:16.975 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:16.979 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:16.979 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:16.981 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:16.998 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:17.038 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registra
2024-03-14T21:26:17.038 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:26:40.356 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T21:50:03.145 helix_view::editor [ERROR] Failed to initialize the language servers for `source.toml` - `taplo` { cannot find
2024-03-14T22:04:57.170 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registra
2024-03-14T22:09:05.241 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-14T22:10:28.943 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registra
2024-03-15T09:41:00.309 helix_lsp::client [WARN] language server failed to terminate gracefully - failed to parse: invalid type: map, expected unit
2024-03-15T10:26:27.421 helix_lsp::transport [ERROR] pylsp err <- "Traceback (most recent call last):\n"
2024-03-15T10:26:27.421 helix_lsp::transport [ERROR] pylsp err <- "  File \"/home/rodrigopim/.local/bin/pylsp\", line 5, in <module>\n"
2024-03-15T10:26:27.421 helix_lsp::transport [ERROR] pylsp err <- "    from pylsp.__main__ import main\n"
2024-03-15T10:26:27.421 helix_lsp::transport [ERROR] pylsp err <- "ModuleNotFoundError: No module named 'pylsp'\n"
2024-03-15T10:26:27.434 helix_lsp [ERROR] failed to initialize language server: server closed the stream
2024-03-15T10:26:27.434 helix_lsp::transport [ERROR] pylsp err: <- StreamClosed
2024-03-15T19:20:47.907 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-15T19:21:17.715 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
2024-03-15T22:02:41.211 helix_lsp::transport [ERROR] jdtls err <- "WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign\n"
2024-03-15T22:02:41.998 helix_lsp::transport [ERROR] jdtls err <- "Mar 15, 2024 10:02:41 PM org.apache.aries.spifly.BaseActivator log\n"
2024-03-15T22:02:41.998 helix_lsp::transport [ERROR] jdtls err <- "INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic\n"
2024-03-15T22:02:42.002 helix_lsp::transport [ERROR] jdtls err <- "Mar 15, 2024 10:02:42 PM org.apache.aries.spifly.BaseActivator log\n"
2024-03-15T22:02:42.002 helix_lsp::transport [ERROR] jdtls err <- "INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic\n"
2024-03-15T22:02:44.452 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-15T22:02:44.454 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-15T22:02:46.028 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-15T22:02:46.635 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-15T22:02:46.937 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-15T22:02:46.938 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-15T22:02:46.940 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-15T22:02:46.977 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-15T22:02:47.002 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
2024-03-15T22:02:47.003 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-16T11:54:09.325 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:54:29.864 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:54:41.526 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:56:06.578 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:56:21.984 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:56:31.746 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:56:44.843 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:56:53.274 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:57:01.339 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:57:07.135 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:57:16.168 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:58:12.743 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:58:21.750 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:58:34.748 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T11:58:41.798 helix_view::editor [ERROR] editor error: Surround pair not found around all cursors
2024-03-16T18:55:42.012 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(188)), original request likely timed out
2024-03-16T18:57:15.856 helix_core::syntax [ERROR] TS parser failed, disabling TS for the current buffer: Err(Cancelled)
2024-03-16T19:31:47.116 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-16T19:31:47.118 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-16T19:31:55.179 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(118)), original request likely timed out
2024-03-16T19:33:34.394 helix_view::editor [ERROR] Failed to initialize the language servers for `source.toml` - `taplo` { cannot find binary path }
2024-03-16T19:40:01.363 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["src/main/java/...."]
2024-03-16T19:48:53.716 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(263)), original request likely timed out
2024-03-16T19:51:54.872 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["src/main/java/...."]
2024-03-16T20:20:02.796 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-16T22:10:00.073 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(568)), original request likely timed out
2024-03-16T22:18:20.401 helix_view::editor [ERROR] editor error: Register [@] empty
2024-03-17T12:15:13.382 helix_view::editor [ERROR] editor error: No definition found.
2024-03-17T12:22:25.601 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(1195)), original request likely timed out
2024-03-17T13:08:37.788 helix_view::editor [ERROR] editor error: No definition found.
2024-03-17T13:16:08.924 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(1352)), original request likely timed out
2024-03-17T13:37:58.879 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2024-03-17T15:01:06.856 helix_view::document [ERROR] TS parser failed, disabling TS for the current buffer: Err(Cancelled)
2024-03-17T15:07:46.975 helix_lsp::util [WARN] LSP position Position { line: 61, character: 10 } out of range assuming EOF
2024-03-17T15:07:46.975 helix_lsp::util [WARN] LSP position Position { line: 61, character: 14 } out of range assuming EOF
2024-03-17T15:09:54.101 helix_view::editor [ERROR] editor error: No definition found.
2024-03-17T15:09:54.194 helix_view::editor [ERROR] editor error: Invalid regex: *nfIf
```

### Platform

Linux

### Terminal Emulator

Alacritty -> zellij session -> tab -> pane -> helix

### Installation Method

Fodora COPR varlad repo

### Helix Version

helix 23.10 (f6021dd0)

**Comment by pascalkuthe** [comment] 2024-03-17 23:45
likely fixed by #9173, try reproducing on latest master. If you can't reproduce on master then I will close this

**Comment by rodrigopim** [comment] 2024-03-18 11:28
building of master branch (head revision) and trying to reproduce the error, and it seems fixed. Thanks!!
Other thing is that binary hx has 474mb when the current installation has 16mb. A lot of features? Or how can I custom the build and update my current installation. Thanks again!

**Comment by the-mikedavis** [comment] 2024-03-18 12:15
By default cargo builds in the debug profile which contains a lot more symbol information so the binary size is much bigger. You can use `cargo build --release` or `cargo run --release` to build in the same profile that package managers use. We will cut a new release fairly soon (hopefully by the end of the month) that the COPR package could update to. In the meantime you can switch to a from-source build following: https://docs.helix-editor.com/master/install.html#building-from-source

**Closed by the-mikedavis** 2024-03-18 12:15 UTC
Labels: C-bug, S-waiting-on-author
