### ISSUE TITLE
[Feature] Install with `cargo install`

### ISSUE THREAD

**Issue by BobH-Official** [helix-editor/helix#3045] opened 2022-07-12 06:43 UTC
Can we have a easier, universal install option, other than using the system package manager or building from GitHub source, that simply using `cargo install` and building from crates.io source?

**Comment by the-mikedavis** [comment] 2022-07-12 15:22
Duplicate of https://github.com/helix-editor/helix/issues/42

**Closed by the-mikedavis** 2022-07-12 15:22 UTC
Labels: C-enhancement
