### ISSUE TITLE
Helix autocomplete for rust is broken

### ISSUE THREAD

**Issue by hazelwiss** [helix-editor/helix#12261] opened 2024-12-15 19:05 UTC
### Summary

Whenever I try to use the autocomplete feature with Rust (using rust-analyzer 1.85.0-nightly (33c245b 2024-12-10)) it just keeps replacing suggestions with random other alternatives. Such that, if I wanted to write `MyType` and I write like `MyT` then try to autocomplete, it might just replace that suggestion last second with `SomeOtherType` without that type even being suggested first. This happens for not just types, it happens for everything.

I have attached a video of it happening here:
https://github.com/user-attachments/assets/21c6f1ca-cda8-4303-9373-f1b079233ddd

### Reproduction Steps

I don't know what is causing me to have this bug, but for me to reproduce it is very easy as it happens literally all the time I try to use autocomplete.

### Helix log

This is the log from what I did in the video.

[helix.log](https://github.com/user-attachments/files/18141623/helix.log)

### Platform

Linux

### Terminal Emulator

alacritty

### Installation Method

yay

### Helix Version

helix 24.7

**Comment by twvd** [comment] 2024-12-15 19:09
I have the exact same issue, also on Linux, 24.7.

**Comment by pascalkuthe** [comment] 2024-12-15 19:55
Duplicate of  #12119, this has been fixed in rust-analyzer

**Closed by pascalkuthe** 2024-12-15 19:55 UTC
Labels: C-bug
