### ISSUE TITLE
[discuss] place runtime folder in `~/.local/helix` or `~/.cache/helix` instead of `~/.config/helix`

### ISSUE THREAD

**Issue by hh9527** [helix-editor/helix#4498] opened 2022-10-28 03:48 UTC
My `~/.config` in under git control, I have to configure `.gitignore` to avoid upload/download tree-sitter sources and `*.so`.

I think the more reasonale approach is

- only keep `config.toml` `languages.toml` inside `~/.config/helix`
- make all other files into `~/.local/helix`

and one more step, for one who need to workspace-level customize (for example: tree-sitter grammar developer)

we can config addtional runtime path in `$workspace/.helix/config`

```toml
# merged into runtime file lookup path with high priority
additional-runtime-path = ["./workspace-level-runtime-folder"]
```

finally behaviour:

helix **merge** `config.toml` & `languages.toml` in the following order:

- workspace-level: `$workspace/.helix/`
- user-level: `~/.config/helix/`
- system-level: `/etc/helix/`
- distribution-level (always readonly) : `/usr/local/helix/`

and **lookup** runtime files in the following order:

- workspace-level: following values of `additional-runtime-path` in **merged** `config.toml`
- user-level: `~/.local/helix/runtime/`
- distribution-level: `/usr/local/helix/runtime/`

**alternative**: use `.cache` instead `.local`
*reason*: `runtime` somehow could be seen as a build-cache of `languages.toml`

**Comment by the-mikedavis** [comment] 2022-10-28 13:08
Duplicate of https://github.com/helix-editor/helix/issues/584

**Closed by the-mikedavis** 2022-10-28 13:08 UTC
Labels: C-enhancement
