### ISSUE TITLE
Indent guide renders outside of the scope of function or class

### ISSUE THREAD

**Issue by d33kshant** [helix-editor/helix#9462] opened 2024-01-29 05:09 UTC
### Summary

While working with identation based programming language like python, The indentation guides are being rednered outside of the scope of any function, class, loop etc.
![Annotation 2024-01-29 103223](https://github.com/helix-editor/helix/assets/68581632/744920e8-564f-41da-8b26-c0d5aca6dd1b)
(Helix)

In the above image the indendation guide is visible till the next non empty line

![Annotation 2024-01-29 103320](https://github.com/helix-editor/helix/assets/68581632/dc44e8d5-cd3e-48db-8963-0dde61ea1598)
(VS Code)

Expected behaviour is that the indentation guide should stop to next empty line.

### Reproduction Steps

1. Open a new file in hx, eg. `main.py`
2. Enable indent-guide with command `:set indent-guides.render true`
3. Write some indented code with multiple new lines, eg. 
```
def foo():
  for i in range(3):
    c = 2
    while True:
      if c == 2:
        break
      c -= 1
      print(c)


foo()
```

### Platform

Ubuntu on WSL

### Terminal Emulator

windows terminal

### Installation Method

apt

### Helix Version

helix 23.10 (f6021dd0)

**Comment by kirawi** [comment] 2024-01-29 13:43
Duplicate of https://github.com/helix-editor/helix/issues/8487

**Closed by kirawi** 2024-01-29 13:43 UTC
Labels: C-bug
