### ISSUE TITLE
incorrect indentation with if..elif..else statements in python

### ISSUE THREAD

**Issue by loyalrami** [helix-editor/helix#7816] opened 2023-08-03 10:28 UTC
Hi, The indentation with if..elif..else statements if python doesn't work.
Here is the issue and reproduction steps in image.
![IMG20230803152535](https://github.com/helix-editor/helix/assets/132257626/a4939e6f-144b-4fc3-a78e-be3640899e22)
**VERSION**
helix 23.05 (7f5940be)
OS windows 10

**Comment by loyalrami** [comment] 2023-08-03 11:46
> Hi, this doesn't really tell us what you did to reproduce the issue. Can you give more details? What did you do and what did you expect to happen?

Hi, Just start and if..elif..else statement in python.

**Comment by dead10ck** [comment] 2023-08-03 12:09
That's still not enough information. What are you expecting to happen? Are you expecting helix to automatically unindent the `elif` for you?

**Comment by loyalrami** [comment] 2023-08-03 12:11
> That's still not enough information. What are you expecting to happen? Are you expecting helix to automatically unindent the `elif` for you?

yes helix does not unindent the else and elif statements  , I have to do it manually

**Comment by pascalkuthe** [comment] 2023-08-03 12:18
@Triton171  mentioned retroactive dedent somewhere I think but I cant find it. The current indent system only effects where your cursor is placed in a new line and not past lines so this is not a bug and working as intended.

**Comment by pascalkuthe** [comment] 2023-08-04 12:24
Ah found it: duplicate of #6044

**Closed by pascalkuthe** 2023-08-04 12:24 UTC
Labels: C-enhancement, A-indent
