### ISSUE TITLE
Helix freezes when selecting Markdown text in certain situations 

### ISSUE THREAD

**Issue by weiying-chen** [helix-editor/helix#9321] opened 2024-01-12 01:19 UTC
### Summary

I think this issue is solved when you build from source? And we have to wait for the next release to see it fixed for, say, `apt-get install helix`?

### Reproduction Steps

 

I tried this:

1. `hx README.md`
2. I selected this text: `npx eslint "src/**/*.{ts,vue}"`

I expected this to happen: Helix to select the line

Instead, this happened: Helix froze

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-01-12T09:03:26.558 helix_lsp::transport [ERROR] marksman err <- "[09:03:26 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
```

</details>

### Platform

Linux

### Terminal Emulator

wezterm 20230712-072601-f4abf8fd

### Installation Method

nixpkgs

### Helix Version

helix 23.10 (f6021dd0)

**Comment by kirawi** [comment] 2024-01-12 01:45
Dupe of https://github.com/helix-editor/helix/issues/8709

**Closed by kirawi** 2024-01-12 01:45 UTC
Labels: C-bug
