### ISSUE TITLE
Set a default tab width across all languages

### ISSUE THREAD

**Issue by gamma-delta** [helix-editor/helix#8504] opened 2023-10-10 01:03 UTC
Hello,

Every time I start working in a new language I have to go into the languages file and set `indent = { tab-width = 2, unit = "  " }`. (At a font size I can read easily, I can just barely fit 3 80-char columns across my laptop, so every byte counts!)

It would be nice if I could set this across all languages at once. It doesn't look like there's a way to configure it in the `editor` settings.

**Comment by kirawi** [comment] 2023-10-10 03:38
Duplicate of https://github.com/helix-editor/helix/issues/3159

**Closed by kirawi** 2023-10-10 03:38 UTC
Labels: C-enhancement
