### ISSUE TITLE
Changing two adjacent selection causes them to collapse into one.

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3632] opened 2022-09-01 10:31 UTC
### Summary

When you have to adjacent selections and attempt to change both of them (with `c` command), they collapse into a single one.

### Reproduction Steps

 

I tried this:

1. `hx`
2. type "hihi"
3. select all with `%`
4. select regex with `s` `select:hi`
5. change with `c` to "hello"

I expected this to happen:
Text is "hellohello"

Instead, this happened:
Text is "hello"

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
Empty
</details>

### Platform

Linux

### Terminal Emulator

Gnome console

### Helix Version

22.08-3-g5c2b77b41

**Comment by A-Walrus** [comment] 2022-09-01 12:57
The issue is that `change` works by deleting and putting you into insert mode. When the two selections are right after each other, deleting them will put both cursors on top of each other.

**Comment by noobyogi0010** [comment] 2022-09-02 18:07
@A-Walrus 
Can I work on this issue?

**Comment by A-Walrus** [comment] 2022-09-02 18:30
Go ahead!

**Comment by archseer** [comment] 2022-09-03 02:47
I think it's a problem with the selection merging if they overlap: https://github.com/helix-editor/helix/blob/e917a8e0be29aa3f8aaa537e0aa88e6df8ce974e/helix-core/src/selection.rs#L498

Could be an issue with https://github.com/helix-editor/helix/blob/e917a8e0be29aa3f8aaa537e0aa88e6df8ce974e/helix-core/src/selection.rs#L136

**Comment by eburghar** [comment] 2022-11-06 19:04
Duplicate of #2298 ?

**Closed** 2022-11-06 21:55 UTC
Labels: C-bug, A-helix-term
