### ISSUE TITLE
Enhancement request: Vi Mode

### ISSUE THREAD

**Issue by Ktoks** [helix-editor/helix#4735] opened 2022-11-14 04:40 UTC
Request for another 'mode' be added to allow easy transition to Helix for Vi users who cannot always use Helix commands in their editors.

Vi is installed on most servers and it's unrealistic to expect Helix to be available on each system a tech professional could be asked to make changes on.

Adding a 'Vi mode' with its own keybindings that match Vi would make Helix more welcoming to such users.

Zellij added a 'Tmux mode' recently for the very same reason and is the inspiration for this enhancement request.

**Comment by kirawi** [comment] 2022-11-14 05:28
Duplicate of https://github.com/helix-editor/helix/issues/3623

**Closed by kirawi** 2022-11-14 05:28 UTC
Labels: C-enhancement
