### ISSUE TITLE
Editor freezes while scrolling the markdown file

### ISSUE THREAD

**Issue by monochromeParasol** [helix-editor/helix#8881] opened 2023-11-22 11:32 UTC
### Summary

Helix editor freezes completely during an attempt to scroll through a markdown file. It happens across separate configurations:
- Alacritty + zellij + zsh
- Alacritty + zsh
- iTerm2 + zsh

When helix is frozen, it doesn't allow me either to quit or suspend.

### Reproduction Steps

 

I tried this:

1. `hx README.md`
2. Scroll with mouse/touchpad to the end of the file

I expected this to happen:
I am at the end of the file and can proceed with work

Instead, this happened:
Editor freezes up

Workaround:
It looks like using C-f and C-b to scroll doesn't freeze the editor

Below I attached a sample markdown file with which it is possible to reproduce the behaviour (taken from exercism.org)
[README.md](https://github.com/helix-editor/helix/files/13438706/README.md)

### Helix log

```
2023-11-22T13:20:26.072 helix_vcs [INFO] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "<some_path>",
        },
    ),
}
2023-11-22T13:20:26.072 helix_vcs [INFO] failed to open diff base for <some_path>/README.md
2023-11-22T13:20:26.072 helix_vcs [INFO] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "<some_path>",
        },
    ),
}
2023-11-22T13:20:26.072 helix_vcs [INFO] failed to obtain current head name for <some_path>/README.md
2023-11-22T13:20:26.072 helix_view::editor [ERROR] Failed to initialize the language servers for `source.md` - `marksman` { cannot find binary path }
2023-11-22T13:20:26.072 helix_view::editor [DEBUG] editor status: Loaded 1 file.
2023-11-22T13:20:26.072 helix_tui::backend::crossterm [DEBUG] The keyboard enhancement protocol is not supported in this terminal (checked in 132µs)
2023-11-22T13:20:26.074 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.081 helix_term::application [DEBUG] received editor event: IdleTimer
2023-11-22T13:20:26.859 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.864 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.872 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.875 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.878 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.881 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.884 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.887 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.890 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.892 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.894 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.896 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.898 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.900 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.902 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.904 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.905 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.907 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.909 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.911 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.912 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.920 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.922 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.924 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.925 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.927 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.929 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.930 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.932 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.933 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.935 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.937 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.938 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.940 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.941 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.943 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.944 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.946 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.947 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.949 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.950 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.952 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.954 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.955 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.957 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T13:20:26.959 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0

```

### Platform

macOS

### Terminal Emulator

Alacritty 0.13.0-dev (1) | iTerm2 3.4.22

### Installation Method

source 

### Helix Version

helix 23.10 (f6021dd0)

**Comment by monochromeParasol** [comment] 2023-11-22 12:59
I've also noted that installation of `marksman` LSP server (via homebrew `brew install marksman`) doesn't fix the issue. from extended logs with rust backtrace and `-vv`, the only difference in logs I see is the addition of :

```
2023-11-22T14:54:20.219 helix_vcs [INFO] failed to obtain current head name for <some_path>/README.md
2023-11-22T14:54:20.221 helix_view::editor [DEBUG] editor status: Loaded 1 file.
2023-11-22T14:54:20.221 helix_lsp::transport [INFO] marksman -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"positionEncodings":["utf-8","utf-32","utf-16"]},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"isPreferredSupport":true,"resolveSupport":{"properties":["edit","command"]}},"completion":{"completionItem":{"deprecatedSupport":true,"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"inlayHint":{"dynamicRegistration":false},"publishDiagnostics":{"versionSupport":true},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":true},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":false},"executeCommand":{"dynamicRegistration":false},"inlayHint":{"refreshSupport":false},"symbol":{"dynamicRegistration":false},"workspaceEdit":{"documentChanges":true,"failureHandling":"abort","normalizesLineEndings":false,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"helix","version":"23.10 (f6021dd0)"},"processId":41934,"rootPath":"<some_path>","rootUri":null,"workspaceFolders":[]},"id":0}
2023-11-22T14:54:20.221 helix_tui::backend::crossterm [DEBUG] The keyboard enhancement protocol is not supported in this terminal (checked in 183.5µs)
2023-11-22T14:54:20.223 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:20.229 helix_term::application [DEBUG] received editor event: IdleTimer
2023-11-22T14:54:20.939 helix_lsp::transport [ERROR] marksman err <- "[14:54:20 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
2023-11-22T14:54:21.187 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.190 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.193 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.204 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.206 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.221 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.223 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.225 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.227 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.229 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.231 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.233 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.236 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.245 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.247 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.248 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.250 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.252 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.254 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.256 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.258 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.275 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.277 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.279 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.280 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.282 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.286 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.288 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.289 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.291 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.293 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.295 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.296 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.298 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.299 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.301 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.303 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.305 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.306 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.308 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.309 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.311 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.313 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.314 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.316 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.318 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-11-22T14:54:21.333 helix_lsp::transport [INFO] marksman <- {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":1},"hoverProvider":true,"completionProvider":{"triggerCharacters":["[","#","("]},"definitionProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":{"resolveProvider":false},"renameProvider":{"prepareProvider":true},"semanticTokensProvider":{"legend":{"tokenTypes":["class","class","enumMember"],"tokenModifiers":[]},"range":true,"full":{"delta":false}},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true},"fileOperations":{"didCreate":{"filters":[{"pattern":{"glob":"**/*.{}","matches":"file","options":{"ignoreCase":true}}}]},"didDelete":{"filters":[{"pattern":{"glob":"**/*.{}","matches":"file","options":{"ignoreCase":true}}}]}}}}}}
2023-11-22T14:54:21.333 helix_lsp::transport [INFO] marksman <- {"capabilities":{"codeActionProvider":{"resolveProvider":false},"completionProvider":{"triggerCharacters":["[","#","("]},"definitionProvider":true,"documentSymbolProvider":true,"hoverProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"semanticTokensProvider":{"full":{"delta":false},"legend":{"tokenModifiers":[],"tokenTypes":["class","class","enumMember"]},"range":true},"textDocumentSync":{"change":1,"openClose":true},"workspace":{"fileOperations":{"didCreate":{"filters":[{"pattern":{"glob":"**/*.{}","matches":"file","options":{"ignoreCase":true}}}]},"didDelete":{"filters":[{"pattern":{"glob":"**/*.{}","matches":"file","options":{"ignoreCase":true}}}]}},"workspaceFolders":{"changeNotifications":true,"supported":true}},"workspaceSymbolProvider":true}}
2023-11-22T14:54:21.334 helix_lsp::transport [INFO] marksman -> {"jsonrpc":"2.0","method":"initialized","params":{}}

```

**Comment by pascalkuthe** [comment] 2023-11-22 14:51
duplicate of #8709

this is fixed on master, we had to revert the TS update before the release because we can't depend on specific git commits of dependencies (packaging issues). If you build from source this is not an issue

**Closed by pascalkuthe** 2023-11-22 14:51 UTC
Labels: C-bug

**Comment by monochromeParasol** [comment] 2023-11-22 15:20
@pascalkuthe thanks for the link. I will try building from master and report here if it is working as expected or not

**Comment by monochromeParasol** [comment] 2023-11-22 15:31
@pascalkuthe works great with the latest `hx -V` == `helix 23.10 (f6021dd0)`
