### ISSUE TITLE
Mouse mode enabled prevents copying selection to clipboard on remote system

### ISSUE THREAD

**Issue by groovy9** [helix-editor/helix#2207] opened 2022-04-21 01:09 UTC
### Summary

I'm using Windows terminal, ssh to remote linux server, running Helix there.  Mouse mode works fine, doesn't select the line numbers, and middle-button pasting works into Helix, all of which is great.  But it prevents me from copying any text to the clipboard.  With mouse mode off, I can select text, control-c to copy to windows clipboard and then paste into anything.

With mouse mode on, I have no apparent way to copy text from Helix to anything else.

Same thing happens with the Alacritty terminal, which uses control-shift-c to copy.  Works with mouse mode off, doesn't with it on.

### Reproduction Steps

- add ':set mouse true' to [editor] section of config.toml
- start Helix
- Open a text file
- select text with mouse
- control-c
- control-v into other tool

### Platform

Linux

### Terminal Emulator

Windows terminal

### Helix Version

22.05-dev (5247d3ae)

**Comment by kirawi** [comment] 2022-04-21 21:23
I think this might be a duplicate of https://github.com/helix-editor/helix/issues/1901

**Comment by kirawi** [comment] 2022-11-10 03:44
Closing in favor of #2615

**Closed by kirawi** 2022-11-10 03:44 UTC
Labels: C-bug

**Comment by AviKav** [comment] 2022-12-08 07:42
@groovy9 You can use Shift to do the selection in Windows Terminal itself and prevent mouse events being intercepted/sent to the underlying application. You can also do Shift + Alt to do rectangular selections to avoid copying the line numbers.
