### ISSUE TITLE
Workspace symbol picker not showing all symbols clangd

### ISSUE THREAD

**Issue by creikey** [helix-editor/helix#4907] opened 2022-11-27 01:52 UTC
### Summary

Workspace symbol picker not showing all symbols clangd. This is on fairly small C project.

### Reproduction Steps

The workspace symbol picker:
![image](https://user-images.githubusercontent.com/28424206/204115643-b3c2b50e-5f37-4d89-8529-8c65590baf56.png)

![image](https://user-images.githubusercontent.com/28424206/204115648-67d6b560-954c-431d-95f6-6123959adba1.png)

The same query in the workspace symbol picker in file in workspace

### Helix log

```
2022-11-26T17:50:06.251 helix_lsp::transport [ERROR] err <- "I[17:50:06.251] <-- workspace/symbol(1179)\r\n"
2022-11-26T17:50:06.258 helix_lsp::transport [ERROR] err <- "I[17:50:06.258] --> reply:workspace/symbol(1179) 6 ms\r\n"
2022-11-26T17:51:15.491 helix_lsp::transport [ERROR] err <- "I[17:51:15.491] <-- textDocument/documentSymbol(1180)\r\n"
2022-11-26T17:51:15.497 helix_lsp::transport [ERROR] err <- "I[17:51:15.497] --> reply:textDocument/documentSymbol(1180) 5 ms\r\n"
```

### Platform

Windows 11

### Terminal Emulator

Windows Terminal

### Helix Version

7e99087fa36fd49b350311ebdbc3b9338794746b

**Comment by kirawi** [comment] 2022-11-27 02:00
Duplicate of https://github.com/helix-editor/helix/issues/1437

**Closed by kirawi** 2022-11-27 02:00 UTC
Labels: C-bug
