### ISSUE TITLE
Add _Select inside quoted textobject_ `miq` command

### ISSUE THREAD

**Issue by getreu** [helix-editor/helix#5917] opened 2023-02-11 12:25 UTC
Idea:

A new command `miq` could act like `mi"`, `mi<backtic>` or  `mi'`, whatever comes first.

**Comment by gabydd** [comment] 2023-02-11 15:09
Duplicate of https://github.com/helix-editor/helix/issues/5262

**Closed** 2023-02-11 15:17 UTC
Labels: C-enhancement
