### ISSUE TITLE
Cannot backspace on full-width space character

### ISSUE THREAD

**Issue by s0LA1337** [helix-editor/helix#2842] opened 2022-06-20 22:02 UTC
### Summary

The idiographic space cannot be deleted on insert mode via Backspace.
If 'Delete' is hit (in front of the idiographic space) the character is deleted.

This test has been performed with:
Google IME in IME mode as well as alphanumeric mode

Tried on WSL2 (on NixOS)

### Reproduction Steps

I tried this:

1. `hx`
2. Enter a idiographic space in insert mode "　" (U+3000)
3. Try to backspace delete the character (in insert mode)

I expected this to happen:
The character will be deleted.

Instead, this happened:
Nothing, it cannot delete the character in insert mode.

### Helix log

N/A

### Platform

Windows 11

### Terminal Emulator

Windows-Terminal

### Helix Version

helix-term 22.05 (27609f50)

**Comment by the-mikedavis** [comment] 2022-06-20 23:18
Curiously, `delete_char_forward` (<kbd>Delete</kbd> in insert mode) and `delete_selection` (<kbd>d</kbd> in normal mode) can delete it but not `delete_char_backward` (<kbd>Backspace</kbd> or `C-h` in insert mode)

**Comment by kirawi** [comment] 2022-06-21 00:28
What I noticed is that if there is a character before it, you can delete it using backspace.

**Comment by kirawi** [comment] 2022-06-21 21:07
I think the problem is these lines:
https://github.com/helix-editor/helix/blob/5b3b6ffc9e9b34fbbb39ad33cd29c8dec78ac231/helix-term/src/commands.rs#L2981-L2987

It assumes that any other whitespace characters are regular spaces, and so it will `break` upon reaching the full-width character. A fix for this would probably be to limit indentation to just spaces or tabs, instead of checking for whitespace.

**Comment by kirawi** [comment] 2022-06-21 22:41
Sure

**Closed** 2022-07-01 09:08 UTC
Labels: C-bug, A-helix-term
