### ISSUE TITLE
Rulers are invisible in some themes

### ISSUE THREAD

**Issue by sourproton** [helix-editor/helix#6554] opened 2023-04-02 10:40 UTC
### Summary

The following themes don't show their rulers:

- adwaita-dark
- bogster
- default
- flatwhite
- all github themes
- hex_lavender
- mellow
- monokai
- monlai_aqua
- rasmus
- rose_pine_dawn
- solarized_dark
- solarized_light
- spacebones_light
- zenburn

### Reproduction Steps

1. setup rulers in the config file
2. choose one of the themes above
3. launch Helix and confirm the ruler is the same color as the background

### Platform

Linux

### Terminal Emulator

alacritty

### Helix Version

23.03

**Comment by the-mikedavis** [comment] 2023-04-02 14:23
Duplicate of https://github.com/helix-editor/helix/issues/5721

**Closed by the-mikedavis** 2023-04-02 14:23 UTC
Labels: C-bug
