### ISSUE TITLE
Auto Complete with multiple cursors only adds it to one of the cursors

### ISSUE THREAD

**Issue by EriKWDev** [helix-editor/helix#3995] opened 2022-09-27 16:45 UTC
### Summary

When using multiple cursors and getting an autocomplete suggestion, if you select that completion it only writes it to one of the cursors messing the editing up for the other cursors. I've only tried with rust. I would expect it to put the completion on all the cursors.

...or is there a different key than "enter" that would apply it to all?

### Reproduction Steps

shift + c, shift + c, write until auto complete pops up, press tab until correct completion and then enter, only one of cursors get completion
see GIF:

[Screencast from 09-27-2022 06:40:32 PM.webm](https://user-images.githubusercontent.com/19771356/192586039-d2eb80c9-adeb-4209-b182-edf75f4cd1f6.webm)

with larger context around:
[Screencast from 09-27-2022 06:41:05 PM.webm](https://user-images.githubusercontent.com/19771356/192586087-dd027a2b-c925-435e-b95c-93f885b58de1.webm)

### Platform

Linux, Fedora

### Terminal Emulator

alacritty 0.12.0-dev (c5ae05e8

### Helix Version

helix 22.08.1 (bdc7b352)

**Comment by sudormrfbin** [comment] 2022-09-27 18:02
Duplicate of https://github.com/helix-editor/helix/issues/2016

**Closed by sudormrfbin** 2022-09-27 18:02 UTC
Labels: C-bug
