### ISSUE TITLE
Enhancement: add keyboard shortcut to close buffer from buffer picker

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4730] opened 2022-11-13 15:15 UTC
When there are multiple buffers open, if you type `space b` you are shown a list of buffers. From this window, it would be nice to have a keyboard shortcut to close a buffer. 

Currently you have to open the buffer and type `:bc` and then `space b` again

**Comment by the-mikedavis** [comment] 2022-11-13 15:45
Duplicate of https://github.com/helix-editor/helix/issues/1593

**Closed by the-mikedavis** 2022-11-13 15:45 UTC
Labels: C-enhancement
