### ISSUE TITLE
Performance problems on large diff files

### ISSUE THREAD

**Issue by hansfbaier** [helix-editor/helix#5684] opened 2023-01-26 00:31 UTC
The editor becomes unuseable when loading large diff files.
Example attached.
[diff.patch.xz.gz](https://github.com/helix-editor/helix/files/10504857/diff.patch.xz.gz)

**Comment by kirawi** [comment] 2023-01-26 02:55
Duplicate of https://github.com/helix-editor/helix/issues/1865

**Closed by kirawi** 2023-01-26 02:55 UTC
Labels: C-enhancement
