### ISSUE TITLE
Syntax highlighting in file picker

### ISSUE THREAD

**Issue by fraunos** [helix-editor/helix#1615] opened 2022-02-02 13:32 UTC
I took a quick search and haven't seen this reported earlier.

#### Describe your feature request
Syntax highlighting starts working only on files loaded into the buffer - so when scrolling through the list in file picker the files don't have syntax highlighting.
I'm using version 0.6.0-1.

**Comment by kirawi** [comment] 2022-02-02 14:22
Duplicate of #609

**Closed by kirawi** 2022-02-02 14:22 UTC
Labels: C-enhancement
