### ISSUE TITLE
Append after selection combines selections, when insert before selection doesn't

### ISSUE THREAD

**Issue by kanashimia** [helix-editor/helix#10861] opened 2024-05-31 14:18 UTC
When you have multiple selections next to one another then they are combined when you press `a` but not when you press `i`, append shouldn't combine selections.
Example, assuming you have a buffer with a word `foo` in it:
By executing `%s.<enter>a.` your buffer will contain: `foo.`
By executing `%s.<enter>i.` your buffer will contain: `.f.o.o`

› hx --version
helix 24.3 (2cadec0b)

**Comment by kirawi** [comment] 2024-05-31 15:58
dupe of https://github.com/helix-editor/helix/issues/2298

**Closed by kirawi** 2024-05-31 15:58 UTC
