### ISSUE TITLE
filename autocompletion doesnt work right with filenames containing a space

### ISSUE THREAD

**Issue by ZWRh3** [helix-editor/helix#4499] opened 2022-10-28 07:00 UTC
### Summary

autocompletion of filenames containing a space makes it get read as 2 or more arguments

### Reproduction Steps

 

I tried this:
create a file named `lorem ipsum.txt`
1. `hx`
2. :open (just enter the command in dont run it)
3. then try to use autocompletion for the file `lorem ipsum.txt`
I expected this to happen:
being properly autocompleted
Instead, this happened:
autocompletion didnt account for the space and causes it to get treated as 2 different args `lorem` and `ipsum.txt`

### Helix log

N/A this bug doesnt even touch the the log

### Platform

windows

### Terminal Emulator

cmd

### Helix Version

helix 22.08 (ee94031f)

**Comment by Ordoviz** [comment] 2022-10-28 08:38
duplicate of #4266?

**Comment by the-mikedavis** [comment] 2022-10-28 13:14
Duplicate of https://github.com/helix-editor/helix/issues/4266

**Closed by the-mikedavis** 2022-10-28 13:14 UTC
Labels: C-bug
