### ISSUE TITLE
duplicated words when diagnostic messages are on screen

### ISSUE THREAD

**Issue by JakeHL** [helix-editor/helix#2881] opened 2022-06-26 12:22 UTC
### Summary

![image](https://user-images.githubusercontent.com/9119973/175813735-59826b4e-b96b-46ff-a3cc-dc7e2134e08d.png)

When trying to type on a line above or inline with a diagnostic message, the screen seems to render spurious duplicate words. `esbuild"esbuild"` in the screenshot.

Those words don't actually exist in the document, moving the cursor a few lines away makes it go away.

### Reproduction Steps

using a language with LSP enabled, cause an error on the first line and then type some more things on that line.

### Platform

macos m1

### Terminal Emulator

wezterm

### Helix Version

helix 22.05 (ad15e7b5)

**Comment by the-mikedavis** [comment] 2022-06-26 17:06
Duplicate of https://github.com/helix-editor/helix/issues/2248

**Closed by the-mikedavis** 2022-06-26 17:06 UTC
Labels: C-bug, A-helix-term
