### ISSUE TITLE
Running command/script with sudo inside `:sh`

### ISSUE THREAD

**Issue by mfirhas** [helix-editor/helix#11008] opened 2024-06-21 16:25 UTC
### Summary

So I need to run a script inside helix with sudo inside, password prompt suddenly appear at the cursor location but seems broken. I tried to insert the password, after pressing enter it freeze, and keep lagging. Tried inserting another command, but helix became unresponsive, not only that, the UI was broken. After sometime it got responsive I just quit and restart helix.

<img width="245" alt="Screenshot 2024-06-21 at 23 09 33" src="https://github.com/helix-editor/helix/assets/11944811/bbf32e8c-3031-48a7-bf46-ddef13505ab0">

### Reproduction Steps

 

I tried this:

1. `:sh some-script-or-command-with-sudo`

I expected this to happen:
prompt password(masked) and enter, and everything executed normally.

Instead, this happened:
Freeze, unresponsive, UI broken.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-06-21T23:05:04.928 helix_term::commands [ERROR] Shell error: sudo: 3 incorrect password attempts
```

</details>

### Platform

macOS

### Terminal Emulator

wezterm 20240203-110809-5046fc22

### Installation Method

brew

### Helix Version

helix 24.3 (2cadec0b)

**Comment by kirawi** [comment] 2024-06-21 20:21
Duplicate of https://github.com/helix-editor/helix/issues/1976

**Closed by kirawi** 2024-06-21 20:21 UTC
Labels: C-bug
