### ISSUE TITLE
reproducible panic while typing

### ISSUE THREAD

**Issue by odama626** [helix-editor/helix#7655] opened 2023-07-16 21:40 UTC
### Summary

I have seen this issue quite a few times before, but this time I was able to reproduce it 3 times in a row so I got the steps down

### Reproduction Steps

 

I tried this:

1. edit file 
```
<script lang="ts">
	import { goto } from '$app/navigation';
	import { currentProject } from '$lib/storage';

	$: {
		// if ($currentProject) goto(`/projects/${$currentProject}`);
	}
</script>
```

2. click end of 3rd line
3. o
4. enter
5. enter
6. type `$: projects = liveQuery`

I expected this to happen:
typed input to show up

Instead, this happened:

```
thread 'main' panicked at 'byte_slice(): Byte range out of bounds: byte range 197..212, Rope/RopeSlice byte length 211', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.6.0/src/slice.rs:703:2
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

tmux in alacritty 0.12.2 (9d9982df)

### Helix Version

Helix 23.05

**Comment by pascalkuthe** [comment] 2023-07-16 21:43
this is likely fixed by #7621, please try building from that branch and reproducing the panic

**Comment by pascalkuthe** [comment] 2023-07-16 21:44
likely duplicate of #7621 too

**Comment by gabydd** [comment] 2023-07-17 19:47
I can confirm this is also fixed by https://github.com/helix-editor/helix/pull/7621

**Closed by gabydd** 2023-07-17 19:47 UTC
Labels: C-bug, S-waiting-on-author
