### ISSUE TITLE
:sh cargo run freezes

### ISSUE THREAD

**Issue by ArikRahman** [helix-editor/helix#4155] opened 2022-10-09 03:26 UTC
### Summary

Howdy! When I start to get user input, the helix editor freezes and I'm unable to do anything, ctrl-c doesn't work and I end up having to kill the terminal.

### Reproduction Steps

 

I tried this:

fn main() {
    let mut line = String::new();
    println!("Enter your name :");
    let b1 = std::io::stdin().read_line(&mut line).unwrap();
    println!("Hello , {}", line);
    println!("no of bytes read , {}", b1);
}

:sh cargo run

I expected this to happen:
Runs and asks for user input

Instead, this happened:
Freezes until killed

### Platform

Linux Fedora

### Terminal Emulator

Gnome Default Terminal

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by kirawi** [comment] 2022-10-09 03:33
`:sh` is meant for one-off commands and will freeze until the command is completed. You're looking for something like https://github.com/helix-editor/helix/issues/1976

**Comment by the-mikedavis** [comment] 2022-10-09 19:05
Duplicate of https://github.com/helix-editor/helix/issues/3950 and https://github.com/helix-editor/helix/issues/3524

**Closed by the-mikedavis** 2022-10-09 19:05 UTC
Labels: C-bug
