### ISSUE TITLE
Panic when pressing space in the command prompt

### ISSUE THREAD

**Issue by Itay123TheKing** [helix-editor/helix#4684] opened 2022-11-09 19:20 UTC
### Backtrace

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-term/src/commands/typed.rs:2206:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   3: helix_term::commands::typed::command_mode::{{closure}}
   4: helix_term::ui::prompt::Prompt::insert_char
   5: <helix_term::ui::prompt::Prompt as helix_term::compositor::Component>::handle_event
   6: helix_term::compositor::Compositor::handle_event
   7: helix_term::application::Application::handle_terminal_events
   8: hx::main_impl::{{closure}}
   9: std::thread::local::LocalKey<T>::with
  10: tokio::park::thread::CachedParkThread::block_on
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  12: tokio::runtime::Runtime::block_on
  13: hx::main
```

### Reproduction Steps

```
$ hx
:<space>
```

### Helix Version

helix 22.08.1 (4ec2a21c)

**Comment by the-mikedavis** [comment] 2022-11-09 20:40
Duplicate of https://github.com/helix-editor/helix/issues/4586

This was fixed on master in #4587

**Closed by the-mikedavis** 2022-11-09 20:40 UTC
Labels: C-bug
