### ISSUE TITLE
More granular undo/redo

### ISSUE THREAD

**Issue by FedericoCeratto** [helix-editor/helix#9931] opened 2024-03-19 09:09 UTC
Hello and thanks for developing Helix.

In most editors undo/redo has a whole-file granularity. Often I want to undo/redo changes on the chunk of code currently show on screen rather than the whole file.

Would it be possible to limit undo to selections, or tab/pane, or even at functions/structs?

Thanks!

**Comment by kirawi** [comment] 2024-03-19 15:07
Related https://github.com/helix-editor/helix/discussions/1588

**Comment by willhansen** [comment] 2024-03-19 15:27
I've often wanted this.  Especially with those markers in the margin indicating the line has been changed, but there's no way for me to directly get that change without looking in git.  They're just sitting there, mocking me.

![image](https://github.com/helix-editor/helix/assets/2918280/cab8bcd3-349e-442c-9446-88c8335ba60b)

**Comment by kirawi** [comment] 2024-03-19 15:39
In that instance, you can select and do `:reset-change`

**Comment by the-mikedavis** [comment] 2024-03-19 16:05
Duplicate of https://github.com/helix-editor/helix/issues/3364

**Closed by the-mikedavis** 2024-03-19 16:05 UTC
Labels: C-enhancement
