### ISSUE TITLE
Jumpy Navigation

### ISSUE THREAD

**Issue by rgasper** [helix-editor/helix#4782] opened 2022-11-17 01:01 UTC
As implemented in [Atom](https://atom.io/packages/jumpy) and a [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=wmaurer.vscode-jumpy).

**Comment by kirawi** [comment] 2022-11-17 01:34
Duplicate of https://github.com/helix-editor/helix/issues/274

**Closed by kirawi** 2022-11-17 01:34 UTC
Labels: C-enhancement
