### ISSUE TITLE
Scrolling with multiple cursors unselects cursors

### ISSUE THREAD

**Issue by Daeraxa** [helix-editor/helix#3921] opened 2022-09-21 11:56 UTC
### Summary

I was editing a large markdown table (too big to fit on one screen) and needed to make a new column. I extended the cursor down then scrolled back up (with the mousewheel) to check where it needed to end.
I noticed that where the blinking cursor fell during the scroll, Helix would "unselect" that cursor leaving gaps.

### Reproduction Steps

Mostly default config except:
```
[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"
```
- Open `hx` and create a single column of data that extends beyond the length of the window (i.e. so you have to scroll)
- Starting at line 1, press <kbd>shift</kbd> + <kbd>c</kbd> to extend the cursor downwards to the end of the file
- Press <kbd>i</kbd> to enter insert mode
   - Note that all the cursors except the primary one are `block` and the primary is `bar`.
- Use mouse wheel to scroll up
   - Note that wherever the primary cursor "stops" it clears the block cursors
- Type something, it will only type on the lines where the cursor is still present

![image](https://user-images.githubusercontent.com/58074586/191496501-7eeebcba-bafc-4063-9bf2-9f852083878d.png)

### Helix log

Nothing in log at timestamp

[helixlog.txt](https://github.com/helix-editor/helix/files/9616263/helixlog.txt)

### Platform

Linux (Linux Mint 20.03)

### Terminal Emulator

kitty 0.24.1

### Helix Version

22.03-15-g924462ed

**Comment by the-mikedavis** [comment] 2022-09-21 12:39
Duplicate of https://github.com/helix-editor/helix/issues/2520

**Closed by the-mikedavis** 2022-09-21 12:39 UTC
Labels: C-bug
