### ISSUE TITLE
Char index out of bounds error

### ISSUE THREAD

**Issue by 95th** [helix-editor/helix#4911] opened 2022-11-27 19:22 UTC
### Summary

Got following panic while editing:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 5751, Rope/RopeSlice char length 1201', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/ropey-1.5.0/src/slice.rs:349:41

### Reproduction Steps

 

I tried this:

1. `hx`
2. I think I was trying to copy paste content like I am used to in VS code.

I expected this to happen:
Not panic
Instead, this happened:
panic

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
</details>

Nothing relevant in helix.log

### Platform

macOS

### Terminal Emulator

iterm2

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by the-mikedavis** [comment] 2022-11-27 19:45
Duplicate of https://github.com/helix-editor/helix/issues/2489

This has been fixed on master.

**Closed by the-mikedavis** 2022-11-27 19:45 UTC
Labels: C-bug
