### ISSUE TITLE
Can't unbind `.`

### ISSUE THREAD

**Issue by uAliFurkanY** [helix-editor/helix#6775] opened 2023-04-16 15:02 UTC
### Summary

you can't change the keymap binding for `.` or unbind it

### Reproduction Steps

 

I tried this:

1. add `"." = "no_op"` to the config, save and reload the config

I expected this to happen:

`.` would be unbound

Instead, this happened:

`.` was not unbound

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-16T17:59:14.682 helix_vcs [ERROR] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/home/afy/.config/helix",
        },
    ),
}
2023-04-16T17:59:14.682 helix_vcs [ERROR] failed to open diff base for /home/afy/.config/helix/config.toml
2023-04-16T17:59:14.682 helix_vcs [ERROR] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/home/afy/.config/helix",
        },
    ),
}
2023-04-16T17:59:14.682 helix_vcs [ERROR] failed to obtain current head name for /home/afy/.config/helix/config.toml
2023-04-16T17:59:14.682 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty 0.12.0 (5a728195)

### Helix Version

helix 23.03

**Comment by the-mikedavis** [comment] 2023-04-16 15:20
Duplicate of https://github.com/helix-editor/helix/issues/1488

**Closed by the-mikedavis** 2023-04-16 15:20 UTC
Labels: C-bug
