### ISSUE TITLE
Error: Timed out waiting for language servers to shutdown

### ISSUE THREAD

**Issue by geometryolife** [helix-editor/helix#4551] opened 2022-11-01 01:00 UTC
### Summary

This bug was introduced in the commit d706194 or later.
It caused the following two problems:

**First**: Open the `.toml` file, the time to use the `:q` to exit becomes very long, it takes about 3 seconds
**Second**: After exiting helix, `Error: Timed out waiting for language servers to shutdown` is output on *stdout*

### Reproduction Steps

 

I tried this:

1. `hx languages.toml`

I expected this to happen:

Exit normally, no error output

Instead, this happened: as mentioned above

![image](https://user-images.githubusercontent.com/54882546/199136226-42ee0287-eb84-4360-af09-7e549559977e.png)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-11-01T08:48:47.549 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"initialize\"\n"
2022-11-01T08:48:47.549 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"textDocument/foldingRange\"\n"
2022-11-01T08:48:47.549 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"textDocument/documentSymbol\"\n"
2022-11-01T08:48:47.549 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"textDocument/formatting\"\n"
2022-11-01T08:48:47.549 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"textDocument/completion\"\n"
2022-11-01T08:48:47.549 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"textDocument/hover\"\n"
2022-11-01T08:48:47.549 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"textDocument/documentLink\"\n"
2022-11-01T08:48:47.549 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"textDocument/semanticTokens/full\"\n"
2022-11-01T08:48:47.549 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"textDocument/prepareRename\"\n"
2022-11-01T08:48:47.549 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"textDocument/rename\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered notification handler method=\"textDocument/didOpen\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered notification handler method=\"textDocument/didChange\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered notification handler method=\"textDocument/didSave\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered notification handler method=\"textDocument/didClose\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered notification handler method=\"workspace/didChangeConfiguration\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered notification handler method=\"workspace/didChangeWorkspaceFolders\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"taplo/convertToJson\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"taplo/convertToToml\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"taplo/listSchemas\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered request handler method=\"taplo/associatedSchema\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered notification handler method=\"taplo/associateSchema\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: registered notification handler method=\"initialized\"\n"
2022-11-01T08:48:47.550 helix_lsp::transport [ERROR] err <- " INFO taplo: LSP server listening transport=\"stdio\"\n"
2022-11-01T08:48:56.475 helix_term::application [ERROR] Timed out waiting for language servers to shutdown
2022-11-01T08:52:48.296 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["helix.log"]

```

</details>

### Platform

WSL2 of Ubuntu

### Terminal Emulator

windows-terminal

### Helix Version

helix 22.08.1 (756253b4)

**Comment by archseer** [comment] 2022-11-01 02:58
This is essentially a duplicate of https://github.com/helix-editor/helix/issues/4468

**Closed** 2022-11-01 14:15 UTC
Labels: C-bug

**Comment by Itay123TheKing** [comment] 2022-11-01 14:30
I'm also facing this; happens on pretty much any language, quite annoying indeed
