### ISSUE TITLE
Display number of search results in buffer when searching

### ISSUE THREAD

**Issue by godalming123** [helix-editor/helix#6737] opened 2023-04-13 10:33 UTC
When you are searching with in a buffer I think their should be a indicator as to how many results their are in the document and what result you are focused on this would help a lot when working with big code bases

**Comment by gabydd** [comment] 2023-04-13 16:22
duplicate of https://github.com/helix-editor/helix/issues/2811

**Closed** 2023-04-13 16:22 UTC
Labels: C-enhancement
