### ISSUE TITLE
Allow manually setting file type at runtime

### ISSUE THREAD

**Issue by cinerea0** [helix-editor/helix#2042] opened 2022-04-09 01:42 UTC
#### Describe your feature request

It would be useful to be able to set the file type that helix treats a file as at runtime. An example use case would be for setting the syntax highlighting for a file as bash even if the file doesn't have the markers helix looks for. This is possible in vim/neovim using the `set ft=bash` command.

**Comment by the-mikedavis** [comment] 2022-04-09 01:44
Duplicate of https://github.com/helix-editor/helix/issues/1794

This was merged a few days ago which implements it: https://github.com/helix-editor/helix/pull/1866

**Closed by the-mikedavis** 2022-04-09 01:44 UTC
Labels: C-enhancement
