### ISSUE TITLE
Autocompletion only works on first line of multi selection

### ISSUE THREAD

**Issue by trskare** [helix-editor/helix#4130] opened 2022-10-06 19:21 UTC
### Summary

Autocompletion will only complete on the first line in a multi selection

### Reproduction Steps

I have 2 lines with "int". I select both lines with "x" key, then press "s" and type "int", for selecting int on both lines. Then press "c" and starts to type str, (autocompletion shows up and suggest "string", then i press TAB or CTRL-N or Arrow Down and only the first selected line will fill out with with the word "string", second line only will get "str".

### Platform

macOS

### Terminal Emulator

kitty

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by dead10ck** [comment] 2022-10-06 19:22
Duplicate of #2016

**Closed by dead10ck** 2022-10-06 19:23 UTC
Labels: C-bug
