### ISSUE TITLE
The highlighting *doesn't* go away either after going into insert mode OR append mode.

### ISSUE THREAD

**Issue by wmstack** [helix-editor/helix#2501] opened 2022-05-18 20:47 UTC
The highlighting *doesn't* go away either after going into insert mode OR append mode. 
Before append/insert:
![image](https://user-images.githubusercontent.com/58462210/169152121-c287579f-aa61-4f2c-9eb9-ba1fe68c8206.png)
After append:
![image](https://user-images.githubusercontent.com/58462210/169152220-7348719a-0482-455f-a62d-d6040dbe0c97.png)
After insert:
![image](https://user-images.githubusercontent.com/58462210/169152317-0f8a9f09-5a11-45a1-9393-8c643d8f9f2e.png)

As you can see, the selection is still there. Definitely surprising behaviour. One more thing I want to mention. Suppose you say well, "let me collapse the selection before `append`, that should fix it right". Well, no!

After collapsing selection
![image](https://user-images.githubusercontent.com/58462210/169152598-2f3b4336-3adf-4d39-a96b-d6c194222c37.png)

Appending after collapsing the selection!
![image](https://user-images.githubusercontent.com/58462210/169152663-6e0c84f4-8232-4754-a8be-4d727d0cfe75.png)
Still doesn't get rid of the highlight.

_Originally posted by @wmstack in https://github.com/helix-editor/helix/issues/1377#issuecomment-1130521457_

Suppose you are editing a file. Now you want to skip one word. You do <kbd> esc </kbd> <kbd> e </kbd> <kbd> a </kbd> thinking now you have surmounted the obstacle! Little did you know that the selection is still there.

**Comment by the-mikedavis** [comment] 2022-05-18 21:13
This is the intended behavior and is an important part of helix's multi-cursor support and select-then-act paradigm. It can be a bit distracting visually until you get used to it but there's a lot of utility in keeping selections when switching between modes (insert/normal/select). As for the collapsing example, that's also intended behavior: cursors are actually single-width selections.

**Comment by wmstack** [comment] 2022-05-18 21:18
Even if it is the intended behaviour, their ought to be a command to *append* to the end of selection, but unselect everything. Same for *insert*.

**Comment by wmstack** [comment] 2022-05-18 21:36
Would it be alright if I personally implement some extra editing primitive commands into helix that make configuring the keymap to act as close as possible to vim possible? I want to see how far the configuration can allow the user to choose his own style of modal editing.

**Comment by the-mikedavis** [comment] 2022-05-18 22:16
There has been some discussion about "evil mode" bindings in Helix - a vim keymap - but the issue with it is that it's entirely different from the select-then-act paradigm. Implementing it would most likely take very large changes. See https://github.com/helix-editor/helix/discussions/1511#discussioncomment-2517661

Of course you're welcome to hack around in a fork but I expect that PRs that add vim-paradigm commands will not be merged - it would be problematic to maintain competing paradigms.

I would encourage you to try to abandon your vim muscle memory and use the default keymap for a while and see if you can adjust. After adjusting you might end up preferring select-then-act.

**Comment by Zoybean** [comment] 2022-05-19 03:27
I hated the behaviour of `i` and `a` at first but have grown to rely on it. In any situation where you want to remove the selection, you can use `;`.
E.g. if you select every occurrence of a word to append to it, use `a`, if you want to append after the first character, use `;a`

**Comment by the-mikedavis** [comment] 2022-08-05 17:34
Closing this as it is by design and we have no intention of changing it. You can use `;` to collapse selections and you can rebind keys to include the `collapse_selection` in order to do this general. I wouldn't encourage it though - the selection retaining behavior of `i` and `a` is by design and is useful.

**Closed by the-mikedavis** 2022-08-05 17:34 UTC
