### ISSUE TITLE
Explanation + completer for set-option options

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3189] opened 2022-07-25 15:00 UTC
#### Describe your feature request

When using `:set-option some-option` you have no way of knowing what values are valid for this option. It would be nice to have 
- The explanation for the option appear above the completions (like it does in `:indent-style`, for example)
- Completions when applicable. For example `:set-option line-number` should suggest the completions `absolute` and `relative`

Currently after typing `:set-option some-option <space>` the suggested completions are other options, which is not useful, and could be confusing.

**Comment by the-mikedavis** [comment] 2022-07-26 04:13
Duplicate of https://github.com/helix-editor/helix/issues/2772

**Closed** 2022-07-26 04:13 UTC
Labels: C-enhancement
