### ISSUE TITLE
Suspending helix leaves state in terminal

### ISSUE THREAD

**Issue by rcorre** [helix-editor/helix#6154] opened 2023-03-02 02:28 UTC
### Summary

When I suspend helix with `ctrl+z`, it leaves a bunch of UI elements in the terminal, such as line numbers and sometimes the bottom-right keyhint dialog. I also see control sequences like `^[[?6c`.
`ctrl+z` also takes several seconds to exit the application, and `fg` takes several seconds to restore.

### Reproduction Steps

 

I tried this:

1. `hx`
2. `ctrl+z`

I expected this to happen:

I see what what previously in my terminal

Instead, this happened:

```
[rco3re@midgar agos]$ fg
hx s2enes/Spell.gd
    1        (             )
   12   
[1]+  Stopped                 hx scenes/Spell.gd
[rcorre@midgar agos]$ 
    3
    4
    5
    6
    7
    8
    9
    0
    1
    2
    3
    4
    5
    6
    7
    8
   19
    0
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>
[helix.log](https://github.com/helix-editor/helix/files/10867014/helix.log)

### Platform

Linux

### Terminal Emulator

st 0.8.5

### Helix Version

22.12-313-gac75cdec (bad)
22.12-294-g6494fc1d (good)

**Comment by rcorre** [comment] 2023-03-02 02:52
The culprit appears to be `Enable the enhanced keyboard protocol if supported`

**Comment by the-mikedavis** [comment] 2023-03-02 16:04
Duplicate of https://github.com/helix-editor/helix/issues/6149

**Closed by the-mikedavis** 2023-03-02 16:04 UTC
Labels: C-bug
