### ISSUE TITLE
Add automatic horizontal scroll to bufferline to follow current buffer

### ISSUE THREAD

**Issue by benmuth** [helix-editor/helix#10868] opened 2024-06-02 16:37 UTC
When there are too many open buffers to display at once in the bufferline, the names of the buffers just run off the screen to the right and aren't visible. This makes the bufferline and commands like `goto_next_buffer` less useful, because you often can't see the currently viewed or adjacent buffers.

I think it would be better if the view of the bufferline automatically moved to keep the name of the currently viewed buffer on screen.

You could indicate the presence of buffers that are currently offscreen with simple `<` and `>` characters at the start and end of the bufferline.

This would be especially helpful for smaller displays like laptops.

**Comment by kirawi** [comment] 2024-06-02 20:45
Duplicate of https://github.com/helix-editor/helix/discussions/10199
See https://github.com/helix-editor/helix/pull/8362

**Closed by kirawi** 2024-06-02 20:45 UTC
Labels: C-enhancement
