### ISSUE TITLE
Order buffer selection by last visitation time

### ISSUE THREAD

**Issue by otavioschwanck** [helix-editor/helix#5172] opened 2022-12-15 18:18 UTC
Buffer is ordered by opening order.  The ideal is the buffer to be ordererd by last visitation time, to quickly go to previous buffers.

**Comment by gabydd** [comment] 2022-12-15 18:51
Duplicate of https://github.com/helix-editor/helix/issues/4776

**Closed** 2022-12-15 18:51 UTC
Labels: C-enhancement
