### ISSUE TITLE
Helix crashes on Windows with "Attempt to index past end of Rope:"

### ISSUE THREAD

**Issue by rpherman** [helix-editor/helix#5077] opened 2022-12-08 22:43 UTC
I have installed HX with chocolatey on my Windows 11 notebook, and it opens.

When I open a text file with 5224 lines and I hit '5301 g' it crashes with a "Attempt to index past end of Rope: line index 5301, Rope line length 5224"

It shouldn't crash and end the program. It should go to the last line.

**Comment by pascalkuthe** [comment] 2022-12-08 23:51
Just a small note for the future: Please use the bug issue template when reporting a bug, that would have avoided some of my questions.

I can not reproduce this with the latest helix version. I admittedly did not test on windows but that should have no effect. The only difference I could think of would be crlf related but even with line-endings set to crlf I can not reproduce this.

 A couple questions to help us pin down the bug:
 
 * What version are you using (a stable release? Otherwise the commit you compiled from)
 * please provide the full back-trace and not just the panic message (ideally with `RUST_BACKTRACE=1`)
 * can you provide a reproducible example (so files, exact keysequence to reproduce the issue)

**Comment by CptPotato** [comment] 2022-12-09 07:55
I cannot reproduce either using current master on Windows 10.

I think this might be an outdated version. Every time I checked, the chocolatey version was one or two versions behind.

**Comment by pascalkuthe** [comment] 2022-12-09 11:44
> I cannot reproduce either using current master on Windows 10.
> 
> I think this might be an outdated version. Every time I checked, the chocolatey package was one or two versions behind.

Thank youbfor confirming that, I also guessed an outdated version. With 22.12 a ton of bugs that could cause this were squadhed so I suspect it's already fixed. I will close this for now as its unactionable. If you are using the latest version 22.12 @rpherman feel free to reopen

**Closed by pascalkuthe** 2022-12-09 11:44 UTC
Labels: C-bug

**Comment by rpherman** [comment] 2022-12-12 09:27
I built Helix from source and the error is gone. Thank you.
