### ISSUE TITLE
Add PowerShell Language Support

### ISSUE THREAD

**Issue by LucasWagler** [helix-editor/helix#9434] opened 2024-01-26 15:49 UTC
Add PowerShell language support.

- [Tree-sitter grammar](https://github.com/airbus-cert/tree-sitter-powershell) (as linked on the [TS website](https://tree-sitter.github.io/tree-sitter/))
- Bonus points: [PowerShell Editor Services LSP](https://github.com/PowerShell/PowerShellEditorServices)

**Comment by the-mikedavis** [comment] 2024-01-26 15:59
Duplicate of https://github.com/helix-editor/helix/issues/3123

**Closed by the-mikedavis** 2024-01-26 15:59 UTC
Labels: C-enhancement
