### ISSUE TITLE
Global search v2 cannot filter by path

### ISSUE THREAD

**Issue by woojiq** [helix-editor/helix#11240] opened 2024-07-19 15:48 UTC
My previous workflow
1. Global search by a phrase.
2. The picker will open and I can filter the results by path. So if I type `.nix` in the open picker, I will only see patterns in certain files. This is actually very useful. `<explanation goes here if you wonder>`.

After updating to the latest version I can no longer do this(

I know it will be a nightmare to maintain, but I don't see a good solution for this other than returning the previous version of the picker too (we will have two choices of how we want to search).

**Comment by the-mikedavis** [comment] 2024-07-19 15:50
Duplicate of https://github.com/helix-editor/helix/issues/11212

You can use `searchterm %p .nix` to filter on nix files for example

**Comment by the-mikedavis** [comment] 2024-07-19 15:51
(Documentation is being worked on in https://github.com/helix-editor/helix/pull/11218)

**Closed by the-mikedavis** 2024-07-19 15:50 UTC

**Comment by woojiq** [comment] 2024-07-19 15:54
Oops, I didn't see the open issue and thought I was the first) Sorry and thanks for your work❤️
