### ISSUE TITLE
Undocumented commands for configs

### ISSUE THREAD

**Issue by AceofSpades5757** [helix-editor/helix#5614] opened 2023-01-20 22:50 UTC
There are some undocumented commands that could be used for user configs. It looks like these aren't documented because they aren't bound to any keys.

### Example

Link to docs: <https://docs.helix-editor.com/keymap.html?highlight=extend_line_#selection-manipulation>
Reddit Post on Issue: <https://www.reddit.com/r/HelixEditor/comments/10h7fzw/how_to_reverse_x/>

`extend_line_above` is undocumented in the documentation, even though it is a valid configuration command available to users. These commands should be documented somewhere. Below is an image of how I think they should be seen, either without anything in the `Key` column or something like `UNBOUND`.

![image](https://user-images.githubusercontent.com/10341888/213818571-443ea9c1-e89d-4272-a4cf-ec0021f78c78.png)

### Related

These looked related, but weren't solely targeted at this issue. The pull request does say "Added missing information..." but I didn't look that far into it.

Discussion #5428 issues with Helix documentation
Pull Request #5534 on Helix documentation refactor

**Comment by gabydd** [comment] 2023-01-20 23:18
Duplicate of https://github.com/helix-editor/helix/issues/3705

**Closed** 2023-01-21 01:59 UTC
