### ISSUE TITLE
Search stops working when match jumps over an Unicode symbols

### ISSUE THREAD

**Issue by kevinsjoberg** [helix-editor/helix#88] opened 2021-06-03 11:53 UTC
When searching using `/`, going to the next match using `n` stops working when you've passed the character `⽆`.

**Environment**
- hx v0.0.9
- helix-term 0.1.0

**Steps to reproduce**

Given the following file:

```
test:
key
⽆
key
key
```

1. Put your cursor at the first line `test:`. Search for `key` using `/key`
2. Press `n` for next match
3. Press `n` for next match (does not work)

**Comment by archseer** [comment] 2021-06-05 03:50
Fixed by #121

**Comment by kevinsjoberg** [comment] 2021-06-07 19:02
Got bitten by this today again, while searching in my `kitty.conf` file. I managed deduce the offending line:

```
#: ירושלים, selecting the character that on the screen appears to be ם
```

**Comment by kirawi** [comment] 2021-06-08 02:14
One clue I found is here in `helix-term/src/commands.rs`:
`let head = end - 1;`

If it's offset by the number of bytes in each unicode character, it works just fine for that number of unicode characters. No idea what it is caused by though.

**Closed** 2021-06-08 04:20 UTC
