### ISSUE TITLE
syntax highlighting breaks on cursor move

### ISSUE THREAD

**Issue by mahmoud-eltahawy** [helix-editor/helix#11282] opened 2024-07-23 02:46 UTC
### Summary

https://github.com/user-attachments/assets/571658f7-4158-4173-a4f4-d8295fe6ac84

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

archlinux

### Terminal Emulator

alacritty

### Installation Method

paru 

### Helix Version

24.07

**Comment by the-mikedavis** [comment] 2024-07-23 04:31
Duplicate of #1151

Rather than the cursor it's the viewport

**Closed by the-mikedavis** 2024-07-23 04:31 UTC
Labels: C-bug
