### ISSUE TITLE
Support system wide configuration

### ISSUE THREAD

**Issue by c0rydoras** [helix-editor/helix#8416] opened 2023-09-28 13:11 UTC
It would be nice if a system wide configuration would be supported

1. check in `$XDG_CONFIG_HOME`
2. check in `.config`
3. check in system_wide config (e.g. `/etc/xdg/`)

**Comment by kirawi** [comment] 2023-09-28 16:43
Duplicate of https://github.com/helix-editor/helix/issues/584

**Closed by kirawi** 2023-09-28 16:43 UTC
Labels: C-enhancement
