### ISSUE TITLE
"x" should not select next line when cursor is on empty line

### ISSUE THREAD

**Issue by funny-falcon** [helix-editor/helix#11901] opened 2024-10-16 12:18 UTC
When cursor is at the end of non empty line, `x` selects this line only.
When cursor is at the beginning of non empty line, `x` selects this line only.

When cursor is on empty line, it is both at the beginning and at the end of the same line. Both positions intends to selection of this line only. But currently it select next line as well.

It is quite inconvenient, since finger-pattern to delete line is "xd", and it is quite annoying to see, how next line after current is disappearing when I try to delete empty line.

**Comment by the-mikedavis** [comment] 2024-10-16 13:28
Duplicate of https://github.com/helix-editor/helix/issues/3077

**Closed by the-mikedavis** 2024-10-16 13:28 UTC
