### ISSUE TITLE
<C-i> doesn't do jump_forward

### ISSUE THREAD

**Issue by gyreas** [helix-editor/helix#6184] opened 2023-03-04 17:04 UTC
C-i doesn't behave as intended. When "tab" is mapped to "command_mode", C-i then does "command_mode". It doesn't do anything when "tab" is not mapped as such. 
I tried changing keymaps/defaults.rs as such:
`- "C-i" | "tab" => "command_mode",`
`+ "C-i" => "command_mode",`

And recompiling helix-term. Got the same result: it behaves the same way.

Is this an isolated event?

**Terminal:**
Kitty
**Platform:**
Fedora 37
**hx -v:**
22.12

**Comment by nuid32** [comment] 2023-03-04 17:44
It is caused by #4961

**Comment by the-mikedavis** [comment] 2023-03-04 17:54
Are you running helix from master or a pre-built release from a package manager?

By default, when you hit C-i, the terminal sends the same escape sequences as if you had hit tab to Helix. With #4939 being merged, it's now possible to tell C-i and tab apart if you're using a terminal that supports the enhanced keyboard protocol like Kitty.

**Comment by gyreas** [comment] 2023-03-04 18:45
> Are you running helix from master or a pre-built release from a package manager?
> 
> By default, when you hit C-i, the terminal sends the same escape sequences as if you had hit tab to Helix. With #4939 being merged, it's now possible to tell C-i and tab apart if you're using a terminal that supports the enhanced keyboard protocol like Kitty.

I'm using the master branch, and that's because I couldn't get Ada lsp to work with it. I'm using Kitty too

**Comment by the-mikedavis** [comment] 2023-03-04 18:53
What does the log say when opening the editor when running in verbose mode (`hx -vv`)? https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file

There should be a line that says "The enhanced keyboard protocol is supported on this terminal" if we're enabling the enhanced keyboard protocol.

**Comment by gyreas** [comment] 2023-03-04 19:12
> What does the log say when opening the editor when running in verbose mode (`hx -vv`)? https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file

Running `tail -f ~/.cache/helix/helix.log | grep enhanced` showed nothing even tho `hx -vv` was used

> There should be a line that says "The enhanced keyboard protocol is supported on this terminal" if we're enabling the enhanced keyboard protocol.

Do I enable it myself or it's core to helix?

**Comment by the-mikedavis** [comment] 2023-03-04 19:26
Ah ok, I think you are using a build that is older than the merge commit for #4939 then. Can you try pulling master and re-installing from source? `cargo install --path helix-term --locked`

**Comment by gyreas** [comment] 2023-03-04 19:28
Oh, okay. I try that now. Thanks

**Comment by gyreas** [comment] 2023-03-04 21:00
Yup, works like magic OTTB. We can close now. Thanks.

**Closed** 2023-03-04 21:29 UTC
