### ISSUE TITLE
An auto-complete selection from the popup does not update all of the cursor position text.

### ISSUE THREAD

**Issue by grv07** [helix-editor/helix#2973] opened 2022-07-05 07:20 UTC
Ex: I have a line of text `hello there is some issue with your hello`  I select the line with `x` then s to select the hello and `enter` that split it into two cursors, now if I change first `hello` from auto-complete suggestion to `hello_var` it will update the current cursor but will not update the text for other cursors.

Pls, feel free to update :)

**Comment by sudormrfbin** [comment] 2022-07-05 08:25
Duplicate of #2016.

**Closed by sudormrfbin** 2022-07-05 08:25 UTC
