### ISSUE TITLE
Cannot edit a file if the file is named `justfile`

### ISSUE THREAD

**Issue by drzymalanet** [helix-editor/helix#9703] opened 2024-02-22 23:57 UTC
### Summary

My edits to the justfile are overwritten. If I change the name, it works. If i create a brand new file named justfile with helix, I can put the file contents into the file, but after reopening and saving, file changes are not saved.

### Reproduction Steps

 

I tried this:

```
mkdir -p /tmp/test
cd /tmp/test
hx justfile
# Create file contents, then `:wq`
hx justfile
# Change anything and then `:wq`
cat justfile
# Observe that the file did not change.
```

Repeat the same with a differently named file and it will work. It seems to me that the `justfile` syntax highlighter is causing the problem but I don't know.

### Helix log

When creating the file named `justfile`:
```
2024-02-23T00:46:11.334 helix_view::document [ERROR] Formatter error: error: Unknown start of token:
 ——▶ justfile:1:8
  │
1 │ bbbbbbb;
  │        ^
```

The bbbbb is not what I was adding to the file. It seems that the formatter is in a different dimension.

### Platform

Linux

### Terminal Emulator

GNOME Terminal 3.28.3

### Installation Method

nixpkgs

### Helix Version

helix 23.10

**Comment by the-mikedavis** [comment] 2024-02-23 00:12
This would be caused by the external formatter rather than the tree-sitter parser: https://github.com/helix-editor/helix/blob/98ebeeebd8c7462409f82d34ff4ac0a7ae9116c7/languages.toml#L2833

I can't reproduce this but we should remove that line anyways: `just --dump` doesn't format stdin, it reads `justfile`. External formatters should take input from stdin and print the formatted output to stdout

**Comment by drzymalanet** [comment] 2024-02-23 00:38
@the-mikedavis I have copied the `languages.toml` file you've mentioned into my helix config dir:
- Removing that line did not help
- Setting `auto-format = false` did fix the issue.

**Comment by kirawi** [comment] 2024-02-23 01:27
The configs are merged, so you'd have to unset it to "" rather than delete it.

**Comment by drzymalanet** [comment] 2024-02-23 11:29
@kirawi Yes I figured that out. 

@the-mikedavis @kirawi Can we revert commit https://github.com/helix-editor/helix/commit/0eec518ff68072071d595b4a297080add11738e3 ?

**Comment by the-mikedavis** [comment] 2024-02-23 14:23
Yep please send a PR

**Comment by drzymalanet** [comment] 2024-03-01 19:11
@the-mikedavis @kirawi @rokf @kpbaks @archseer @rokf
Hello, https://github.com/helix-editor/helix/pull/9778 is ready.

**Closed** 2024-03-02 02:05 UTC
Labels: C-bug, A-language-support
