### ISSUE TITLE
allow configuring the default register

### ISSUE THREAD

**Issue by jyn514** [helix-editor/helix#11398] opened 2024-08-01 16:29 UTC
i like to share a clipboard across all my applications. helix allows me to select the register to use for the clipboard (`"`), including the system clipboard (`"+`), but it does not allow me to choose the *default* clipboard, so every yank breaks my muscle memory and requires 3x as many strokes. it would be nice to make this configurable with an option. currently it's hard-coded to `"`, e.g. https://github.com/helix-editor/helix/blob/cfe80acb6f8893e20dc04ff9a99c4551c3129624/helix-term/src/commands.rs#L2656

**Comment by the-mikedavis** [comment] 2024-08-08 19:42
Duplicate of https://github.com/helix-editor/helix/issues/2038, see https://github.com/helix-editor/helix/issues/2038#issuecomment-1658847967 in particular. My comment there about multi selection yank and paste is out of date actually - that works now when yanking & pasting within the same Helix session.

**Closed by the-mikedavis** 2024-08-08 19:42 UTC
Labels: C-enhancement
