### ISSUE TITLE
Bug: Helix crashes when 17 vertical splits are made

### ISSUE THREAD

**Issue by LoadingBG** [helix-editor/helix#2534] opened 2022-05-22 18:25 UTC
### Summary

When spliting 17 times the editor crashes with the following error:
```
thread 'main' panicked at 'index out of bounds: the len is 10340 but the index is 65535', helix-term\src\ui\editor.rs:139:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Running with `RUST_BACKTRACE = "full"` gives this:
```
thread 'main' panicked at 'index out of bounds: the len is 10340 but the index is 65535', helix-term\src\ui\editor.rs:139:17
stack backtrace:
   0:     0x7ff71263da04 - <unknown>
   1:     0x7ff711ec83ea - <unknown>
   2:     0x7ff7126350b7 - <unknown>
   3:     0x7ff71264132b - <unknown>
   4:     0x7ff712640ed2 - <unknown>
   5:     0x7ff712504b6e - <unknown>
   6:     0x7ff7126418dd - <unknown>
   7:     0x7ff7126416f5 - <unknown>
   8:     0x7ff71263ebf7 - <unknown>
   9:     0x7ff7126413cf - <unknown>
  10:     0x7ff7126ce4e0 - <unknown>
  11:     0x7ff7126ce4a7 - <unknown>
  12:     0x7ff7121eb254 - <unknown>
  13:     0x7ff7121f43e6 - <unknown>
  14:     0x7ff712210e63 - <unknown>
  15:     0x7ff7121db5f2 - <unknown>
  16:     0x7ff7124fe762 - <unknown>
  17:     0x7ff7124dc81b - <unknown>
  18:     0x7ff7124cad95 - <unknown>
  19:     0x7ff7124f6182 - <unknown>
  20:     0x7ff7124d0d66 - <unknown>
  21:     0x7ff7124dd4a6 - <unknown>
  22:     0x7ff7124e31fa - <unknown>
  23:     0x7ff71263d2a3 - <unknown>
  24:     0x7ff7124d5dd7 - <unknown>
  25:     0x7ff7126c930c - <unknown>
  26:     0x7ffc54d57034 - BaseThreadInitThunk
  27:     0x7ffc56a22651 - RtlUserThreadStart
```

### Reproduction Steps

`$ hx config.toml` (works with any file)
`:vs config.toml` 16 times in a row

### Helix log

After deleting the previous logs and crashing the editor again this was inside:
```
2022-05-22T21:21:36.804 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
```

### Platform

Microsoft Windows 10 Pro 10.0.19044 Build 19044

### Terminal Emulator

Powershell inside Windows Terminal

### Helix Version

helix-term 22.03 (d4e45fd4)

**Comment by the-mikedavis** [comment] 2022-05-22 20:13
Duplicate of https://github.com/helix-editor/helix/issues/1083

**Closed by the-mikedavis** 2022-05-22 20:13 UTC
Labels: C-bug
