### ISSUE TITLE
Weird diagnostics rendering issue

### ISSUE THREAD

**Issue by winged** [helix-editor/helix#4677] opened 2022-11-09 14:10 UTC
### Summary

I'm getting weird rendering issues when getting language server diagnostics on the last line of a file. Parts of the line are duplicated, sometimes on the same line, sometimes below. Swapping out the terminal (I've tried xfce4-terminal and alacritty) didn't change the result either, changing the theme also didn't help.

I'm using the following:

* python-lsp-server 1.6.0-1
* helix (archlinux build) 22.08.1-1

My config only contains theme, ruler, and indent-guides as well as some unrelated keymaps.

### Reproduction Steps

[![asciicast](https://asciinema.org/a/mwq8NJdkqZZNnLQhbK0uDu8K6.svg)](https://asciinema.org/a/mwq8NJdkqZZNnLQhbK0uDu8K6)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
The helix log contains a bunch of messages like the following (not from the exact same test run as the recording above, but they looked the same):

```
2022-11-09T15:03:11.127 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1, character: 39 }, end: Position { line: 1, character: 78 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "expected ':'", related_information: None, tags: None, data: None }
2022-11-09T15:03:20.577 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1, character: 38 }, end: Position { line: 1, character: 91 } }, severity: Some(Error), code: None, code_description: None, source: Some("pyflakes"), message: "non-default argument follows default argument", related_information: None, tags: None, data: None }
```

</details>

### Platform

Arch Linux

### Terminal Emulator

xfce4-terminal, but it happens with others too

### Helix Version

helix 22.08.1

**Comment by the-mikedavis** [comment] 2022-11-09 15:20
Duplicate of https://github.com/helix-editor/helix/issues/2248

This has been fixed on master

**Closed by the-mikedavis** 2022-11-09 15:20 UTC
Labels: C-bug
