### ISSUE TITLE
`:wa` often panics after "LSP rename variable"

### ISSUE THREAD

**Issue by getreu** [helix-editor/helix#4304] opened 2022-10-16 06:28 UTC
Unfortunately, I can not reproduce it reliably, but it often happens when I use the language server's "rename variable" followed by `:wa`.

```
thread 'main' panicked at 'no entry found for key', helix-view/src/document.rs:1032:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by archseer** [comment] 2022-10-16 08:58
Duplicate of https://github.com/helix-editor/helix/issues/3459

**Closed by archseer** 2022-10-16 08:58 UTC
