### ISSUE TITLE
ALT and ALTGR modifiers conflicts in normal mode

### ISSUE THREAD

**Issue by Nlight91** [helix-editor/helix#9195] opened 2024-01-01 19:28 UTC
### Summary

I use a custom os keyoard layout (derived from a French azerty board). That layout make an extensive use of the AltGr (Ctrl+Alt) modifier to output nearly all symbols like ":" or "&" for example.

While it does work no problem in insert mode, in normal mode it does not at all.
From the various related issues I have seen on the tracker, it seems like Helix is remapping the Alt modifier, mapping that takes place at a lower level than the one where the OS send the key codes corresponding to this or that scancodes combinations.

While I may be wrong this is how it seems to behave :

OS keyboard Inputs (scancodes HID report) -> Helix Normal Mode -> OS translates scancodes into keycodes -> Helix Insert Mode

### Reproduction Steps

 

I tried this:

1. AltGr + f (this normaly ouputs a colon ":")

I expected this to happen:

helix to enter command mode

Instead, this happened:

nothing

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows10

### Terminal Emulator

all of them

### Installation Method

chocolatey

### Helix Version

helix 23.10 (f6021dd0)

**Comment by pascalkuthe** [comment] 2024-01-01 20:07
Helix doesn't do anything in that regard, this is simply how windows is sending these input Events. There are multiple hacls for working around the subpar windows api in that regard but the upstream library we use does not implement them currently. This can't be solved on our end. Duplicate of #7129

**Closed by pascalkuthe** 2024-01-01 20:07 UTC
Labels: C-bug

**Comment by Nlight91** [comment] 2024-01-01 20:34
Upstream library, ok, noted. Thanx :)
