### ISSUE TITLE
Windows (MinGW / Git Bash) looks for runtime in an unusual location

### ISSUE THREAD

**Issue by tgross35** [helix-editor/helix#7959] opened 2023-08-16 03:59 UTC
### Summary

On Windows (MinGW), Helix seems to look for the runtime directory in a binary directory (`C:\Users\MyUser\.local\bin\runtime`) rather than a configuration directory (`C:\Users\MyUser\.config\helix\runtime`), which doesn't seem to match up with the other operating systems.

### Reproduction Steps

 

I tried this:

1. `hx --health` 

I expected this to happen: find runtime directory at `~/.config/helix/runtime`

Instead, this happened: 

```
Runtime directories: C:\Users\MyUser\AppData\Roaming\helix\runtime;\\?\C:\Users\MyUser\.local\bin\runtime
Runtime directory does not exist: C:\Users\MyUser\AppData\Roaming\helix\runtime
Runtime directory does not exist: \\?\C:\Users\MyUser\.local\bin\runtime
```

### Helix log

Nothing relevant

### Platform

Windows (MinGW)

### Terminal Emulator

Git Bash

### Helix Version

helix 23.05 (7f5940be)

**Comment by pascalkuthe** [comment] 2023-08-16 09:32
C:\Users\MyUser\AppData\Roaming\helix\runtime is the windows equivalent of `~/.config/helix` on unix. Windows does usually not have a convention to place files in the home directory the way that Unix does (specifically they don't follow XDG). Somtimes these directories exist/are used anyway for programs with unix emulation. Adding that kind of behavior to helix additionally, see #6747 


The second path is indeed where the binary is installed but that's on purpose and also the case on other operating systems..

Closing as this is the intended behavior and the only changes we would be willing to considers are already tracked in #6747.

**Closed by pascalkuthe** 2023-08-16 09:32 UTC
Labels: C-bug

**Comment by tgross35** [comment] 2023-08-16 20:57
Thank you for the clarification on binary location, and for pointing me to the other issue!
