### ISSUE TITLE
Using Tab on files in `open` on window causes panik

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [helix-editor/helix#2004] opened 2022-04-07 08:02 UTC
### Summary

thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\alloc\src\string.rs:1718:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Reproduction Steps

 

I tried this:

1. `hx`
2. :open <Tab> a few times

### Helix log

No log was written

### Platform

Windows 10

### Terminal Emulator

windows terminal 1.13.220202006-release1.13

### Helix Version

22.05-dev (d37369c1)

**Comment by archseer** [comment] 2022-04-07 08:12
Duplicate of https://github.com/helix-editor/helix/issues/1888, if you can produce a full backtrace let us know in that issue

**Closed by archseer** 2022-04-07 08:12 UTC
Labels: C-bug

**Comment by sschneider-ihre-pvs** [comment] 2022-04-07 08:21
``
   0: std::panicking::begin_panic_handler
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\panicking.rs:116
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\panicking.rs:48
   3: alloc::string::String::replace_range
   4: helix_term::ui::prompt::Prompt::change_completion_selection
   5: <helix_term::ui::prompt::Prompt as helix_term::compositor::Component>::handle_event
   6: helix_term::compositor::Compositor::handle_event
   7: helix_term::application::Application::handle_terminal_events
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: tokio::park::thread::CachedParkThread::block_on
  10: tokio::runtime::thread_pool::ThreadPool::block_on
  11: tokio::runtime::Runtime::block_on
  12: hx::setup_logging
```

**Comment by sschneider-ihre-pvs** [comment] 2022-04-07 08:22
```
0:     0x7ff7f1b7cd34 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7f1b7cd34 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7f1b7cd34 - std::sys_common::backtrace::_print_fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff7f1b7cd34 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff7f13f83ea - core::fmt::write
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\fmt\mod.rs:1168
   5:     0x7ff7f1b743e7 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\io\mod.rs:1660
   6:     0x7ff7f1b8071b - std::sys_common::backtrace::_print
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff7f1b8071b - std::sys_common::backtrace::print
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff7f1b8071b - std::panicking::default_hook::closure$1
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:211
   9:     0x7ff7f1b802c2 - std::panicking::default_hook
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:228
  10:     0x7ff7f1a33818 - core::ptr::drop_in_place<jsonrpc_core::types::request::Notification>::h3cfc9094128f712a
  11:     0x7ff7f1b80ccd - std::panicking::rust_panic_with_hook
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:610
  12:     0x7ff7f1b80ac3 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:500
  13:     0x7ff7f1b7df27 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:139
  14:     0x7ff7f1b807bf - std::panicking::begin_panic_handler
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:498
  15:     0x7ff7f1c0d9f0 - core::panicking::panic_fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\panicking.rs:116
  16:     0x7ff7f1c0d93c - core::panicking::panic
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\panicking.rs:48
  17:     0x7ff7f17c1ca5 - alloc::string::String::replace_range::h74ce854b2b66f046
  18:     0x7ff7f1894d91 - helix_term::ui::prompt::Prompt::change_completion_selection::h9c88515c99cb354d
  19:     0x7ff7f1895a95 - <helix_term::ui::prompt::Prompt as helix_term::compositor::Component>::handle_event::hd91098f78aa66a5d
  20:     0x7ff7f177fdc6 - helix_term::compositor::Compositor::handle_event::h487772922ee8d354
  21:     0x7ff7f174d08c - helix_term::application::Application::handle_terminal_events::h010f12b058a7f98c
  22:     0x7ff7f1a4de36 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf1e113bcb715a21c
  23:     0x7ff7f1a17dfb - tokio::park::thread::CachedParkThread::block_on::h70084b04f6099996
  24:     0x7ff7f1a18b05 - tokio::runtime::thread_pool::ThreadPool::block_on::h34f1192fbb46421e
  25:     0x7ff7f1a46ce2 - tokio::runtime::Runtime::block_on::hda9c16b2a53cc5f5
  26:     0x7ff7f1a15c36 - hx::setup_logging::hf62efd2c054303db
  27:     0x7ff7f1a1cdb6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb1f096ac490e1ddb
  28:     0x7ff7f1a22a1a - std::rt::lang_start::{{closure}}::hf11e8096ed728982
  29:     0x7ff7f1b7c5d3 - core::ops::function::impls::impl$2::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\ops\function.rs:259
  30:     0x7ff7f1b7c5d3 - std::panicking::try::do_call
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:406
  31:     0x7ff7f1b7c5d3 - std::panicking::try
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:370
  32:     0x7ff7f1b7c5d3 - std::panic::catch_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panic.rs:133
  33:     0x7ff7f1b7c5d3 - std::rt::lang_start_internal::closure$2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\rt.rs:128
  34:     0x7ff7f1b7c5d3 - std::panicking::try::do_call
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:406
  35:     0x7ff7f1b7c5d3 - std::panicking::try
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:370
  36:     0x7ff7f1b7c5d3 - std::panic::catch_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panic.rs:133
  37:     0x7ff7f1b7c5d3 - std::rt::lang_start_internal
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\rt.rs:128
  38:     0x7ff7f1a199d7 - main
  39:     0x7ff7f1c0881c - invoke_main
                               at d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  40:     0x7ff7f1c0881c - __scrt_common_main_seh
                               at d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  41:     0x7ffd4e477034 - BaseThreadInitThunk
  42:     0x7ffd4eb42651 - RtlUserThreadStart
```
