### ISSUE TITLE
Display the load spinner when the LSP takes time to respond

### ISSUE THREAD

**Issue by magopian** [helix-editor/helix#6150] opened 2023-03-01 09:42 UTC
Sometimes the LSP takes time to respond, but there's no indication it's doing anything. It would be nice to display the load spinner in the status line (on the left by default).

See the following small screen capture for an idea of the current situation when asking to select symbol references (default keymap: `<Space>-h`).

https://user-images.githubusercontent.com/167767/222101049-b538bd75-5a94-4c52-b862-e08c35ecb4e0.mov

**Comment by the-mikedavis** [comment] 2023-03-02 15:33
Duplicate of https://github.com/helix-editor/helix/issues/1060

**Closed by the-mikedavis** 2023-03-02 15:33 UTC
Labels: C-enhancement
