### ISSUE TITLE
evil-mode: extensible vi layer for helix?

### ISSUE THREAD

**Issue by Dentrax** [helix-editor/helix#4867] opened 2022-11-23 17:22 UTC
Hey there, as a fresh user of helix, I should admit that I really like this! You're doing awesome, keep going!

---

I was really struggling to learn helix keymaps in the first place, and it'd be great to have "extensible vi layer" for helix. Simply looking for: like evil-mode for emacs; but for helix. Or are there any configuration for this? I took a look at repo and issues and couldn't find much. (I'm already aware of [Migrating from Vim](https://github.com/helix-editor/helix/wiki/Migrating-from-Vim) doc, but it's not what I'm saying.)

My motivation and use case here is that I'm too lazy to learn a completely new key bind mapping. I'd like to prefer to choose any keybinding template from the helix console (or config): helix-bindings, vim-bindigs, etc.

**Comment by the-mikedavis** [comment] 2022-11-23 17:24
Duplicate of https://github.com/helix-editor/helix/issues/3623

**Closed by the-mikedavis** 2022-11-23 17:24 UTC

**Comment by Dentrax** [comment] 2022-11-23 17:28
Thanks @the-mikedavis, but I'm not so sure if this issue is duplicate of #3623. You want from me to use https://raw.githubusercontent.com/LGUG2Z/helix-vim/master/config.toml config? What's your closing thoughts? Could you please clarify and enlighten my way? _(I'm pretty sure that some new folks will eventually hit this from the search engines.)_

**Comment by the-mikedavis** [comment] 2022-11-23 17:48
Yeah I suppose we don't have a good point issue on this. There was https://github.com/helix-editor/helix/issues/4735 but it also points at #3623.

Vi uses a different paradigm than Helix. Helix follows select-then-act where you create selections and then act on those selections. Vi's commands follow a verb-object paradigm: you act on some object. The canonical example is `wd` (select a word and then delete the selection) vs Vi's `dw` (delete the next word object).

Supporting Vi's paradigm would take significant changes to Helix's codebase. (For example, to accomodate verb-object, you need a sort of "pending" mode where you have an action pending and waiting for an object.) We aren't interested in maintaining competing paradigms and we're committed to select-then-act (see the [vision doc](https://github.com/helix-editor/helix/blob/590a628460c8fa8a4e101541d67289fa2fac95b5/docs/vision.md?plain=1#L18)), so there will not be a Vi emulation mode or an option to switch to pure Vi keybindings.

I would urge you to try Helix without changing the keymap at all for a while and see if you like it after your muscle memory adjusts. I would not recommend the `LGUG2Z/helix-vim` keymap: you will miss out on bindings that are important for select-then-act like `C`. IMO if you try to shoehorn the verb-object paradigm into Helix, you will end up with neither paradigm and it will be a worse experience overall.

**Comment by Dentrax** [comment] 2022-11-23 17:58
Ohhh, thank you so much for taking your time to write a great explanation. Maybe I should check first differences between paradigms: select-then-act vs verb-object to 100% understand of the vision. I'll follow your advices. 👍
