### ISSUE TITLE
Rotating main selection between cursors is only visible in select mode

### ISSUE THREAD

**Issue by ndtoan96** [helix-editor/helix#7913] opened 2023-08-11 16:15 UTC
### Summary

When using `(` or `)` to rotate between cursors, the main cursor is only visible in select mode, i.e there's no indication of main cursor in normal mode.

Note: I use Helix on Windows terminal, don't know if this also happen in Linux and Mac.

### Reproduction Steps

 

I tried this:

1. `hx --tutor`
2. Put the cursor at the "Wellcome" below INTRODUCTION
3. `10x` to select the paragraph
4. `s` and then `it`, then `enter` to create multiple cursors with `it` selected
5. Use `)` to cycle through selections

I expected this to happen: The main cursor moves from one selection to another and it's visible.

Instead, this happened: The main cursor does move, but it's not visible at all (it will show only if I press `v` to change to select mode).

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
This issue is simple enough that I don't think a log is needed
```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Helix Version

helix 23.05 (7f5940be)

**Comment by pascalkuthe** [comment] 2023-08-11 16:19
This depends on your theme. Some themes don't have highlighting for the primary cursor yet.

Duplicate of #3842

**Closed by pascalkuthe** 2023-08-11 16:19 UTC
Labels: C-bug
