### ISSUE TITLE
Python indent not working

### ISSUE THREAD

**Issue by crides** [helix-editor/helix#2651] opened 2022-06-02 20:04 UTC
Hi, I'm very new to helix. I just set up the tree sitter grammars and the python lsp (through `pylsp`), but indentation is not working. If I create a new blank python file, and enter:

```python
def f():
```

and press enter at the end of the line, the cursor stays on the first column. `hx --health python` returns: 

```
Configured language server: pylsp
Binary for language server: /usr/bin/pylsp
Configured debug adapter: None
Highlight queries: ✔
Textobject queries: ✔
Indent queries: ✔
```

version is 22.05 installed from Arch repo. Can anyone help me figure out the issue? Thanks!

**Comment by the-mikedavis** [comment] 2022-06-02 20:10
Duplicate of https://github.com/helix-editor/helix/issues/763

**Closed by the-mikedavis** 2022-06-02 20:10 UTC
