### ISSUE TITLE
Improve Matching Behavior on Quotation Marks

### ISSUE THREAD

**Issue by rban123** [helix-editor/helix#8253] opened 2023-09-12 01:18 UTC
# Improve Matching Behavior on Quotation Marks

This enhancement is related to behavior experienced when matching quotation marks in strings that contain escaped quotation marks, IE:

<img width="249" alt="Screenshot 2023-09-11 at 7 53 19 PM" src="https://github.com/helix-editor/helix/assets/41516125/46064f50-20ef-4204-8dfb-0e6e1c364dcc">

in the above example, my cursor is at the first level of nesting within this string, if I type `mi f` I would expect it to select the entire string, or visually I would expect the result of that command to look like:

<img width="249" alt="Screenshot 2023-09-11 at 8 04 12 PM" src="https://github.com/helix-editor/helix/assets/41516125/cd4cb04a-618b-4587-a26c-5ddba5e0e243">

However, the actual behavior results in this:

<img width="249" alt="Screenshot 2023-09-11 at 8 05 54 PM" src="https://github.com/helix-editor/helix/assets/41516125/294998f4-ff09-41cf-a9a3-12ca57910e4e">

It is only selecting to the next `"` character, it is unaware of any nesting. 

This is notably NOT the same behavior when performing this same operation with other characters such as `)`, where applying `mi )` on

<img width="249" alt="Screenshot 2023-09-11 at 8 09 15 PM" src="https://github.com/helix-editor/helix/assets/41516125/c8d0376f-4674-477a-bb86-0d8082d9812c">

results in:

<img width="249" alt="Screenshot 2023-09-11 at 8 09 43 PM" src="https://github.com/helix-editor/helix/assets/41516125/59ecc0f8-3e2e-460f-99ec-d39d66ddb557">
 
as would be expected.

Clearly, given the examples above, the matching behavior for `"` behaves differently, and therefore unexpectedly, compared to other characters. This enhancement proposes that this same matching behavior should apply to quotation marks as well.

**Comment by pascalkuthe** [comment] 2023-09-12 01:27
`mi<char>` is a textual match only. That means with you do `mi)` it will search for a pair of brackets. This usually endup correctly because brackets are almost always praised. But for example uaing mi( on `x` will match the second and third bracket: `( "("  x) ` 
This is just more obvious with quotes because they are symmetrical so false positives like this are much more common. There are multiple open issue about this. Ultimately the only way to solve this is using tree sitter for matching. That will however always ignore the inner whitespace (since it's just text and notnoart of the syntax). Potentially we could switch `mi<char>` to use TS too (with plaintext matching inside nodes).

**Comment by xavier-gl71** [comment] 2023-09-13 12:29
Maybe related: `mam` and `mim` skip quotes (double or single).

Simple example :
```
printf( "a = %d", a );
```
If you type `mam` when the cursor is in the string the text between the parenthesis is selected.

Weird example :
```
case '[': a = "foo";
case ']': a = "bar";
```
If you type `mim` when the cursor is on `foo` the text between [ and ] is selected.

Not so related : selection/move undo would be great.

**Comment by pascalkuthe** [comment] 2024-04-14 01:32
closing as duplicate of https://github.com/helix-editor/helix/issues/7012

**Closed by pascalkuthe** 2024-04-14 01:32 UTC
Labels: C-enhancement
