### ISSUE TITLE
Commenting code within JSX blocks uses incorrect comment format

### ISSUE THREAD

**Issue by TheAndrewJackson** [helix-editor/helix#7731] opened 2023-07-24 23:50 UTC
### Summary

The normal typescript and javascript comment syntax (`//`) is correctly applied in standard ts/js. JSX markup inside ts/js files requires block comments within curly braces (`{/* */}`). `<C-c>` is applying the normal syntax (`//`) inside JSX blocks.

### Reproduction Steps

https://github.com/helix-editor/helix/assets/17103888/499ff27b-0a06-4d15-b8d4-fe3d8ccd449d

I tried this:

1. `hx file-with-jsx-markup.tsx` 
2. create a react component with a minimal render function
3. try commenting out some text within the JSX markup `<C-c>`

I expected this to happen:
4. the code is commented out with the block syntax `{/* */}`

Instead, this happened:
4. the code is commented out with the standard syntax `//`

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
The log file was empty
```

</details>

### Platform

macOS

### Terminal Emulator

kitty 0.25.0

### Helix Version

helix 23.05 (7f5940be)

**Comment by the-mikedavis** [comment] 2023-07-24 23:53
Duplicate of #1505

See https://github.com/helix-editor/helix/issues/6832

**Closed by the-mikedavis** 2023-07-24 23:53 UTC
Labels: C-bug
