### ISSUE TITLE
:write-quit on Elm files takes a long time

### ISSUE THREAD

**Issue by brendantang** [helix-editor/helix#3700] opened 2022-09-05 02:09 UTC
### Summary

Hi, thanks for all your work! Helix is really nice.

I'm finding that the `:write-quit` command takes a long time, but only on Elm files. It looks like Helix is waiting for auto-format to complete, but the request times out. The `:write` command on its own invokes `elm-format` with no issue, and `:quit` on its own closes the file without delay.

### Reproduction Steps

 

I tried this:

1. Use `hx` to edit a file `src/Example.elm` with the following contents:
```elm
import Html exposing (text)


main =
  text "Hello!"
```
2. `:wq` and observe that it takes a long time to close the file.
3. Check the logs and see that "request timeout" message

### Helix log

```
2022-09-04T21:54:18.188 helix_view::document [WARN] LSP formatting failed: request timed out
```

### Platform

macOS

### Terminal Emulator

Alacritty 

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by antoyo** [comment] 2022-09-05 12:46
Seems like a duplicate of #1639.

**Closed** 2022-09-05 13:11 UTC
Labels: C-bug

**Comment by brendantang** [comment] 2022-09-05 13:15
@antoyo I’m happy to close the issue if 1639 would solve it! But I don’t know why this happens when issuing the :wq command, but not when issuing :w or :q alone.

**Comment by brendantang** [comment] 2022-09-05 13:17
I see it’s already closed, no problem!

**Comment by brendantang** [comment] 2022-09-05 17:49
Got it, thanks!
