### ISSUE TITLE
Crash triggered by tabbing in LSP suggestions

### ISSUE THREAD

**Issue by statushub-piotr** [helix-editor/helix#11329] opened 2024-07-26 08:57 UTC
### Summary

Backtrace:
```
thread 'main' panicked at helix-core/src/transaction.rs:483:9:
Positions [(16, Before)] are out of range for changeset len 0!
stack backtrace:
   0:        0x1014cc308 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4bff038afc05d0ab
   1:        0x100907b50 - core::fmt::write::he9fa43146d420946
   2:        0x1014c8188 - std::io::Write::write_fmt::hf4fd30c8192b15d9
   3:        0x1014cc148 - std::sys_common::backtrace::print::h5d71f7b09493fc9b
   4:        0x1014cdd18 - std::panicking::default_hook::{{closure}}::hb75620628e95e648
   5:        0x1014cda5c - std::panicking::default_hook::h4ac4acc64d21c4ad
   6:        0x1014ce30c - std::panicking::rust_panic_with_hook::h81dc715fa5de32cf
   7:        0x1014ce0e4 - std::panicking::begin_panic_handler::{{closure}}::h26c73eb75670321f
   8:        0x1014cc75c - std::sys_common::backtrace::__rust_end_short_backtrace::hef4773cf0f80485b
   9:        0x1014cde98 - _rust_begin_unwind
  10:        0x101590054 - core::panicking::panic_fmt::h10bd3bfe5bb30d67
  11:        0x100b1f280 - helix_core::transaction::ChangeSet::map_pos::h2c942f74b4393301
  12:        0x10125d760 - helix_view::document::Document::apply_impl::ha71d331c6e157ee2
  13:        0x10125e3ac - helix_view::document::Document::apply_inner::hf04eb7e3746b4364
  14:        0x10125f17c - helix_view::document::Document::restore::h3c5adea3596ae818
  15:        0x100df22e4 - helix_term::ui::completion::Completion::new::{{closure}}::h377e81054fcf0fa9
  16:        0x100df3120 - <helix_term::ui::menu::Menu<T> as helix_term::compositor::Component>::handle_event::h3888717065a611be
  17:        0x100fd76a8 - <helix_term::ui::popup::Popup<T> as helix_term::compositor::Component>::handle_event::h3b7dd18a34ccfbf4
  18:        0x100fd2700 - <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event::h8b10755d9430c77b
  19:        0x100eeca08 - helix_term::compositor::Compositor::handle_event::h617b4b09186d1237
  20:        0x101285e18 - helix_term::application::Application::run::{{closure}}::h7237ff732ce488e0
  21:        0x1012980b0 - tokio::runtime::park::CachedParkThread::block_on::h93485e27ebf2c46c
  22:        0x1012e3a60 - tokio::runtime::runtime::Runtime::block_on::hb665565c677b58a6
  23:        0x1012f9eec - hx::main::hee2975600bce82fb
  24:        0x1012d7a80 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb59f15430a8158a2
  25:        0x1013181d0 - std::rt::lang_start::{{closure}}::h1c6a9f72ad228f3a
  26:        0x1014c1984 - std::rt::lang_start_internal::haeade8bb0e866fa6
  27:        0x1012f9fe8 - _main
```

### Reproduction Steps

It not happens always. So far I wasn't able to trigger it reliably but it happens under 30 min of coding session.
It happens when tabbing through LSP auto-completion suggestions.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-07-26T10:30:05.913 helix_lsp::transport [ERROR] golangci-lint-lsp err: <- StreamClosed
2024-07-26T10:30:05.914 helix_lsp::transport [ERROR] err: <- Other(failed to send a message to server

Caused by:
    channel closed

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: helix_lsp::transport::Transport::process_server_message::{{closure}}
   2: helix_lsp::transport::Transport::recv::{{closure}}
   3: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   4: tokio::runtime::task::harness::Harness<T,S>::poll
   5: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   6: tokio::runtime::scheduler::multi_thread::worker::Context::run
   7: tokio::runtime::context::runtime::enter_runtime
   8: tokio::runtime::scheduler::multi_thread::worker::run
   9: tokio::runtime::task::core::Core<T,S>::poll
  10: tokio::runtime::task::harness::Harness<T,S>::poll
  11: tokio::runtime::blocking::pool::Inner::run
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: std::sys::unix::thread::Thread::new::thread_start
  15: __pthread_joiner_wake)
2024-07-26T10:33:22.799 helix_core::syntax [ERROR] Could not parse queries for language "bash". Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'. This query could not be parsed: QueryError { row: 3, column: 3, offset: 31, message: "ansi_c_string", kind: NodeType }
2024-07-26T10:33:26.151 helix_lsp::transport [ERROR] golangci-lint-lsp err <- "golangci-lint-langserver: connections opened\n"
2024-07-26T10:52:38.325 helix_lsp::transport [ERROR] err: <- Other(failed to send a message to server

Caused by:
    channel closed)
2024-07-26T10:52:38.325 helix_lsp::transport [ERROR] golangci-lint-lsp err: <- StreamClosed

```

</details>

### Platform

macOS

### Terminal Emulator

wezterm 20240203-110809-5046fc22

### Installation Method

source

### Helix Version

helix 24.7 (9b65448f)

**Comment by pascalkuthe** [comment] 2024-07-26 12:01
duplicate of #11291

this was fixed by https://github.com/helix-editor/helix/pull/11304

**Closed by pascalkuthe** 2024-07-26 12:01 UTC
Labels: C-bug
