### ISSUE TITLE
Helix failing to map `keep_primary_selection` on `"."` key

### ISSUE THREAD

**Issue by sumit-modak** [helix-editor/helix#7651] opened 2023-07-16 17:23 UTC
### Summary

Helix failing to map `keep_primary_selection` on `"."` key. It is doing the default operation which is `repeat_last_insert` and also at the same time there is no way to map `repeat_last_insert`

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

kitty

### Helix Version

helix 23.05

**Comment by gabydd** [comment] 2023-07-16 18:19
Duplicate of https://github.com/helix-editor/helix/issues/1488 ``.`` isn't currently remappable

**Closed** 2023-07-16 18:19 UTC
Labels: C-bug
