### ISSUE TITLE
In selection, using / to search and extend selection

### ISSUE THREAD

**Issue by tahir-hassan** [helix-editor/helix#6964] opened 2023-05-04 11:23 UTC
Hello, 

When using NeoVim, if I am in Visual Mode, and I press '/' to search, I can extend the selection to the search result. Is there anything similar in Helix? 

In Helix, when I try to do this, It *changes* the selection to the searched-for text., rather than *extending* it.  

The only "workaround" I have found is to use fX and then repeatedly use Alt-. until it selects the right character.

**Comment by the-mikedavis** [comment] 2023-05-04 17:16
Duplicate of https://github.com/helix-editor/helix/issues/5672

**Closed by the-mikedavis** 2023-05-04 17:16 UTC
Labels: C-enhancement, A-helix-term
