### ISSUE TITLE
Add support for extending themes

### ISSUE THREAD

**Issue by DCsunset** [helix-editor/helix#1469] opened 2022-01-09 22:14 UTC
#### Describe your feature request

Currently, we can create custom themes from scratch but can't extend an existing theme.
It would be useful to support extending an existing theme if we only want to customize a specific part of it.

Thanks!

**Comment by the-mikedavis** [comment] 2022-07-30 12:45
I didn't recognize it at the time but it looks like https://github.com/helix-editor/helix/issues/2454 is a duplicate of this. Let's close this in favor of https://github.com/helix-editor/helix/issues/2454 since it has more discussion and now a linked PR

**Closed by the-mikedavis** 2022-07-30 12:45 UTC
Labels: C-enhancement, A-helix-term
