### ISSUE TITLE
Panic when snapping Helix to right side of screen

### ISSUE THREAD

**Issue by Chickenkeeper** [helix-editor/helix#4086] opened 2022-10-03 16:41 UTC
### Summary

A panic will be triggered if maximised helix is snapped to the right side with `windows key + right arrow`. A workaround is to restore the windows with `windows key + down arrow` arrow before snapping it to the right.

### Reproduction Steps

I tried this:

1. Open terminal and run Helix with `hx` (with or without extra args)
2. Maximise terminal window
3. Press `windows key + right arrow`

I expected this to happen:
- Window gets snapped to the right

Instead, this happened:
- Helix exits and terminal prints the following:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', helix-tui\src\buffer.rs:458:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Helix log

Log doesn't print anything

### Platform

Windows 10

### Terminal Emulator

powershell, command prompt, and git bash

### Helix Version

helix 22.08.1

**Comment by CptPotato** [comment] 2022-10-04 06:40
I can reproduce this. Seems to be something weird with Window's CMD as I can only reproduce it there, not in wezterm. I guess the window size is 0 for a split moment or something.

Here's a stack trace:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', helix-tui\src\buffer.rs:458:17
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
   2: core::panicking::panic_bounds_check
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:84
   3: helix_term::ui::editor::EditorView::render_gutter
   4: helix_term::ui::editor::EditorView::render_view
   5: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::render
   6: helix_term::compositor::Compositor::render
   7: helix_term::application::Application::handle_terminal_events
   8: alloc::raw_vec::RawVec<T,A>::reserve_for_push
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: tokio::park::thread::CachedParkThread::block_on
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  12: tokio::runtime::Runtime::block_on
  13: hx::setup_logging
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Chickenkeeper** [comment] 2022-10-04 19:53
I can't reproduce the issue with Alacritty either. Both wezterm and Alacritty are GPU accelerated, so maybe their windows are handled differently as a result. Either way it's a nasty bug to hit in the wrong situations.

I wonder if it's just caused by a lack of bounds checking, in which case some carefully placed if's might do the trick?

**Comment by rsteube** [comment] 2022-12-19 11:24
I got a similar panic at a different position but it seems to be related to this. Can't say exactly what caused it but i was pasting sth. and resizing the window (switching between fullscreen and tiled in sway).
 
`helix 22.08.1 (af532147)`
```rust
thread 'main' panicked at 'index out of bounds: the len is 1825 but the index is 2774', helix-tui/src/buffer.rs:513:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:84:5
   3: helix_tui::buffer::Buffer::clear_with
   4: <helix_term::ui::popup::Popup<T> as helix_term::compositor::Component>::render
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: helix_term::application::Application::run::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: tokio::runtime::park::CachedParkThread::block_on
   9: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  10: tokio::runtime::runtime::Runtime::block_on
  11: hx::main
```

**Comment by pascalkuthe** [comment] 2024-04-04 02:21
I think this was likely fixed by a PR I can't find right now (we fixed a bug in number clear). This bug report is pretty old so I am closing it. If you reliably reproduce on latest master please open a new issue

**Closed by pascalkuthe** 2024-04-04 02:21 UTC
Labels: C-bug, A-helix-term
