### ISSUE TITLE
Symbol picker : Display module hierarchy

### ISSUE THREAD

**Issue by Marsevil** [helix-editor/helix#10692] opened 2024-05-05 17:04 UTC
Tightly linked with [5446](https://github.com/helix-editor/helix/issues/5446) but I think that in addition of type, symbol picker could display the module tree of the symbol, Zed do that very beautifully.
We can also think about `/` or `::` separated module names.

![2024-05-05_19-05-1714928422](https://github.com/helix-editor/helix/assets/55738609/3ddc8f1d-16ba-44e4-9fdd-0f1f73318419)

**Comment by kirawi** [comment] 2024-05-05 21:22
Duplicate of https://github.com/helix-editor/helix/issues/2425

**Closed by kirawi** 2024-05-05 21:22 UTC
Labels: C-enhancement
