### ISSUE TITLE
Enhancement: add an option to keep statusbar visible when entering commands

### ISSUE THREAD

**Issue by ravsii** [helix-editor/helix#7087] opened 2023-05-20 10:52 UTC
Currently, when you start entering commands,  the statusbar is becomes hidden.

| before | after |
| :-: | :-: |
| ![image](https://github.com/helix-editor/helix/assets/5007271/893ec1e2-f27a-413d-94b6-f425a0be5c4b) | ![image](https://github.com/helix-editor/helix/assets/5007271/f422df8c-2d53-4c2d-945f-08807841d74b) |

One possible use case of this is: There's no way to view the path of the currently opened file/buffer, except in the statusbar. This could be helpful in big projects when creating new files from helix with `:w`.

Possible solutions (maybe even all three with another configurable option, but the first one looks better to me):

![image](https://github.com/helix-editor/helix/assets/5007271/2d679ee6-4693-404f-84a4-f5b8109cab97)
![image](https://github.com/helix-editor/helix/assets/5007271/33f644d2-c9c0-4411-83d6-c9eff1d8a8d5)
![image](https://github.com/helix-editor/helix/assets/5007271/b42d088b-de28-4c28-b558-c93771e632e6)

**Comment by the-mikedavis** [comment] 2023-05-20 11:33
Duplicate of #5758

**Closed** 2023-05-20 11:33 UTC
Labels: C-enhancement
