### ISSUE TITLE
Manually specify position of Multi cursors

### ISSUE THREAD

**Issue by lsl00** [helix-editor/helix#9898] opened 2024-03-16 17:21 UTC
Is there  a way to do the follow thing:
1. Enter a special mode
2. Go to a position and mark this postion
3. Go to another position and mark it.
4. ......
5. Quit this special mode and begin multi-cursors editing in those marked positions

**Comment by kirawi** [comment] 2024-03-16 18:44
Duplicate of https://github.com/helix-editor/helix/issues/703

**Closed by kirawi** 2024-03-16 18:44 UTC
