### ISSUE TITLE
Soft wrap jump to relative line numbers.

### ISSUE THREAD

**Issue by hakan-demirli** [helix-editor/helix#8202] opened 2023-09-07 17:49 UTC
### Summary

In normal mode when I type `2j` I expect it to move to the line that has a relative position of 2 (bbb...). But instead it goes to the line that has soft-wrap of 1st line (aaa...).

![image](https://github.com/helix-editor/helix/assets/78746991/55fd3758-7a59-479d-8c81-98aa24e08931)

### Reproduction Steps

```toml
[editor]
line-number = "relative"
mouse = false
bufferline = "always"
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.file-picker]
hidden = true

[editor.soft-wrap]
enable = true
```

### Platform

Linux

### Terminal Emulator

kitty

### Helix Version

23.05

**Comment by the-mikedavis** [comment] 2023-09-07 17:52
Duplicate of https://github.com/helix-editor/helix/issues/6819

**Closed by the-mikedavis** 2023-09-07 17:52 UTC
Labels: C-bug

**Comment by pascalkuthe** [comment] 2023-09-07 17:57
its event mentioned in the FAQ: https://github.com/helix-editor/helix/wiki/FAQ#can-the-jk-bindings-be-changed-to-ignore-soft-wrapping-when-using-a-count-like-3j

**Comment by hakan-demirli** [comment] 2023-09-08 06:12
Thank you for the link.
