### ISSUE TITLE
Primary selection not visible

### ISSUE THREAD

**Issue by jonmon6691** [helix-editor/helix#11602] opened 2024-08-30 05:18 UTC
### Summary

While I was working through the tutor in section 10, I was not able to see which of the selections was the primary selection while cycling through them with the '(' and ')' keys.

I can see the numbers in the ruler on the button right updating, so I know it's working, but there's no visual feedback.

I am using the default theme and have no custom configuration in place.

![image](https://github.com/user-attachments/assets/00bb31dd-3fc0-4fd5-8d73-d5b8df87d0a3)

### Reproduction Steps

In normal mode, I made multiple disjoint selections by using the 's' command and searching for text in my current visual selection.

I then pressed the open paren key, '(' aka Shift+9 repeatedly.

I expected some sort of visual indication to cycle between each selection to indicate which was the primary selection. Maybe a change in hue/value or type weight.

What happened was that there was no change in the appearance of any of the selections.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
[helix.log](https://github.com/user-attachments/files/16812046/helix.log)

</details>

### Platform

Linux

### Terminal Emulator

foot version: 1.18.1 +pgo +ime +graphemes -assertions

### Installation Method

source

### Helix Version

24.07-150-g1b5295a3

**Comment by jonmon6691** [comment] 2024-08-30 05:53
After experimenting with this swapping through the included themes, it seems the maybe less than half have a usable amount of contrast for this feature.

Dracula has really good contrast for this feature:
![image](https://github.com/user-attachments/assets/52a056ff-bbc6-4894-b62a-09ec621f7fe0)


I'd be interested in tinkering with this but I can't figure out where the default theme is stored. I don't see a `default.toml` in the `runtime/themes/` folder. And `find . -name "default.toml"` didn't turn anything up in the source repo.

**Comment by kirawi** [comment] 2024-08-30 12:06
duplicate of https://github.com/helix-editor/helix/issues/3842#issue-comment-box

**Closed by kirawi** 2024-08-30 12:06 UTC
Labels: C-bug
