### ISSUE TITLE
Optionally display variable type in front of it.

### ISSUE THREAD

**Issue by hirohido** [helix-editor/helix#4471] opened 2022-10-26 01:28 UTC
I would love to be able to see what type a variable has displayed in front of it. this helps to understand what a block of code is doing at one glance and improves code readability.

**Comment by the-mikedavis** [comment] 2022-10-26 01:33
Duplicate of https://github.com/helix-editor/helix/issues/2070

**Closed by the-mikedavis** 2022-10-26 01:33 UTC
Labels: C-enhancement
