### ISSUE TITLE
`assertion failed: original_doc.len_chars() == self.len` when using a keybinding to discard autocompletion menu

### ISSUE THREAD

**Issue by MaxVerevkin** [helix-editor/helix#8131] opened 2023-08-31 15:19 UTC
### Summary

Helix crashes with

```
thread 'main' panicked at 'assertion failed: original_doc.len_chars() == self.len', helix-core/src/transaction.rs:269:9
```

Config:

```toml
[keys.insert]
C-x = ["normal_mode", "undo", "insert_mode"]
```

### Reproduction Steps

1. Create the keybinding mentioned above.
2. Open a file with active lang server.
3. Type something, trigger autocompletion, press tab to select something.
4. Trigger the keybinding mentioned above.

### Helix log

Github said it is too long. Let me know if the log would actually be useful.

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 23.05 (48373d4a)

**Comment by MaxVerevkin** [comment] 2023-08-31 16:08
> You should use `C-c` to cancel the completion

Thanks, that's exactly what I needed.

**Comment by pascalkuthe** [comment] 2023-08-31 17:04
It's kown issues that executing normal-mode commands (like undo) in insert-mode cab lead to crashes like this (especially with undo). The mdoe switch doesn't finish until after the entire command sequence has been finished. 

Pretty sure there is an existing issue for that

**Comment by pascalkuthe** [comment] 2023-10-19 14:54
Duplicate of #3501

**Closed by pascalkuthe** 2023-10-19 14:54 UTC
Labels: C-bug
